### ISSUE TITLE
Make it possible to remove CLI flags from non-dev binaries

### ISSUE THREAD

**Issue by johnbellessa** [onsi/ginkgo#1007]
As far as I can tell, there's no way to use ginkgo without it polluting our binary's CLI flags because the top-level `init()` method adds everything to the flagset. But, we really don't need (or want) the ginkgo flags in production builds. Am I missing something?

**Comment by onsi** [comment]
correct, there's currently no way to remove the CLI flags from the generated test binary.  if you are simply running invoking the test binary with zero additional cli configuration then it could be plausible to remove them - however if you are invoking them via the ginkgo cli (e.g. to parallelize the suite - a la `ginkgo -p binary.test`) then they will need to stay as the CLI flags are how the ginkgo cli configures the binary.

So... we _could_ make it possible to remove the flags but the resulting binary would behave differently from other ginkgo binaries which would be confusing.  Moreover, `go test` injects it's own flags into the binary as well - so while we could make the various `--ginkgo.*` flags go away all those `--test.*` flags remain.

Stepping back, perhaps I should ask: what is the underlying problem you are trying to solve?  The issue title says "non-dev" binaries which makes me wonder if these are test suites you are shipping to customers/end-users?

**Comment by johnbellessa** [comment]
Apologies, the problem is that we have a non-`_test.go` file importing ginkgo. 🤦‍♂️

Removing that addresses our problem.

**Comment by onsi** [comment]
No worries!  Glad you were able to sort it :)
