### ISSUE TITLE
t.Failed status not propagating with GinkgoT() interface after test failure

### ISSUE THREAD

**Issue by qmilangowin** [onsi/ginkgo#1008]
I'm pretty new to Ginkgo, however, I've a need to be able to pass `*t.Testing` to a helper function that will produce failure reports. 
My status function does implement the `GinkgoTInterface` interface, however the results are iffy at best. 
`t.Failed()` does show the status, however if the test case fails, the test-run exits. `t.Failed()` only is executed if the tests have passed. Seems that when tests fail (either when using testify or Gomega), the failure is not captured by `t.Failed()`.

**Comment by onsi** [comment]
hey @qmilangowin I suspect this is a lifecycle issue.  Ordinarily when a test fail Ginkgo immediately halts execution of the test and then runs any cleanup nodes (e.g. [`AfterEach`](https://onsi.github.io/ginkgo/#spec-cleanup-aftereach-and-defercleanup)) and any reporting nodes (e.g. [`ReportAfterEach`](https://onsi.github.io/ginkgo/#reporting-nodes---reportaftereach-and-reportbeforeeach)).

When are you calling the helper function.  Your use-case sounds like an example of [custom reporting](https://onsi.github.io/ginkgo/#generating-reports-programmatically) and I would expect the helper function to be called in a `ReportAfterEach` - doing so would ensure it is called after the test has run and the various reporting functions (including `t.Failed()`) should then be accurately capturing the state of the test.

If you can point me at some code and/or any libraries you are using I can try to help debug this further. Also, the documentation pieces I've linked to above could help too.

**Comment by qmilangowin** [comment]
Hi @onsi that seemed to have solved it when using with `AfterEach`. Since the framework I wrote has to be decoupled from any test frameworks I couldn't really just rely on the Ginkgo reporting functionality but above is a nice work-around. 
I'll close this issue now. 

Thanks for the help.
