### ISSUE TITLE
Any way to check spec status during cleanup?

### ISSUE THREAD

**Issue by aharbis** [onsi/ginkgo#1016]
We are using `ginkgo` (and `gomega`) to build e2e tests which run against a Kubernetes cluster. Succinctly, my goal is to have a way to gather and dump pod logs from Kubernetes when a test failure occurs. However, it's unclear to me how I can catch this error state during cleanup code.

My initial thinking is to use a `DeferCleanup` node which would be responsible for gathering logs from the cluster and writing them to `GinkgoWriter` - however, I'd like to do this if and only if the spec **failed**.

```go

Describe("some e2e test", func() {

    It("some spec that fails", func() {

		DeferCleanup(func() {
			// some check for spec failure
			if specFailed() {
				// would write to GinkgoWriter
				gatherPodLogs()
			}
		})

		// test assertions
    })

})
```

Is there any way to check the status of a spec from a cleanup node?

**Comment by onsi** [comment]
Take a look here:

https://onsi.github.io/ginkgo/#separating-diagnostics-collection-and-teardown-justaftereach

(not so much the justaftereach - more the CurrentSpecReport() bit)

**Comment by aharbis** [comment]
This is perfect, thank you! Admittedly I did search through the docs before opening this, but somehow missed this. Thanks for the quick response, and as always excellent documentation.

**Comment by aharbis** [comment]
Re-opening for a related query, then happy to close again.

It does not appear that `JustAfterEach` is usable from the context of `BeforeSuite` or `AfterSuite`, so what is the recommended way to handle failures during suite setup / tear-down?

I could forego using Gomega assertions in the suite setup nodes, and write typical error handling, but it would be more succinct if we could register a single `JustAfterEach`.

```go
var _ = BeforeSuite(func() {

	Expect(someComplexSetup()).To(Succeed())
	// how could we catch a failure here and run diagnostics?

})
```

**Comment by onsi** [comment]
hey - probably the best way to do this is via something like: 
```
var _ = BeforeSuite(func() {
	Expect(someComplexSetup()).To(Succeed())
})

var _ = ReportAfterSuite("cleanup in case of failure", func(report Report) {
    beforeSuiteReport := report.SpecReports.WithLeafNodeType(types.NodeTypeBeforeSuite)[0]
    if (beforeSuiteReport.Failed()) {
        //run diagnostics
    }
})
```


It's a tiny bit of a hack to use `ReportAfterSuite` this way but there is no way for `AfterSuite` to get the failure/success state of `BeforeSuite`.

Actually - that's not entirely true - you could try something like this as well:

```go
var allGood = false

var _ = BeforeSuite(func() {
	Expect(someComplexSetup()).To(Succeed())
	allGood = true //only runs if the above succeeds
})

var _ = AfterSuite(func() {
     if (!allGood) {
        // run diagnostics
    } 
})
```
