### ISSUE TITLE
specs before the focused specs in Ordered container should also be auto focused and run

### ISSUE THREAD

**Issue by JiaYongfei** [onsi/ginkgo#1018]
Sample code: 

`
var _ = Describe("Books", Ordered, func() {

	var str string

	It("test1", Label("id_1"), func() {
		str = "123"
	})

	It("test2", Label("id_2"), func() {
		gomega.Ω(str).Should(gomega.Equal("123"))
	})

	It("test3", Label("id_3"), func() {

	})

})
`

Run with:
`ginkgo --label-filter=id_2`

Actual: test1 didn't run
`Ran 1 of 3 Specs in 0.000 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 2 Skipped
`

Expected: test1 should be somehow be focused and run

You might curious why we only specify the second specs. The reason is only the second spec **failed** the first time we run them all.  The first spec **succeed** and The third spec was **skipped**. 

For ordered specs, each case is always coupled with the one before it. If one of the ordered cases was focused and run, the cases before it won't run with current design. The case will fail again.

So I think we may need to focus all the specs in ordered container, take them as one complex case each time we focused one of the specs in the ordered container. 

One way to do this is redesigning the related code in Ginkgo testing framework to auto focus the whole ordered container.

Another way is running ginkgo command with all those ordered specs, like `ginkgo --label-filter=id_1,id_2,id_3`, but the problem is how could we know the other specs in the same ordered container. For example, we have one failed spec id - id_2, how could we figure out the other specs - id_1 and id_3? Any suggestions? Thanks in advance.

**Comment by onsi** [comment]
hey - sorry for never getting back to you.  I agree that the interplay of focusing and filtering with `Ordered` is unintuitive.  in this case my best solution is to propose putting a label on the `"Books"` container and focusing _that_.

Am going to close this for now, feel free to reopen it if need be.
