### ISSUE TITLE
Update Ginkgo's installation instruction to match Go 1.18+

### ISSUE THREAD

**Issue by thediveo** [onsi/ginkgo#1026]
At this time, Ginkgo's documentation instructs users to install Ginkgo using

```bash
go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
```

Now I'm not sure if there are intended side effects of using `mod=mod`, but if there aren't any, then please update the instructions to follow Go 1.18+ practice:

```bash
go install github.com/onsi/ginkgo/v2/ginkgo@latest
```

**Comment by onsi** [comment]
the change to add `-mod=mod` was added by @bdshroyer in [this commit](https://github.com/onsi/ginkgo/commit/0ededb2a81495b2fd201b7970f88a3fe9255dc64) 

The commit is labeled "Update docs to reflect Go v1.18 installation" and is from this PR: https://github.com/onsi/ginkgo/issues/950

which  indicates that this is the issue:

> Specifically, the -mod flag is set to readonly by default when the Go version in go.mod is below 1.14 (GInkgo's is 1.12).  

Ginkgo's go.mod now lists 1.18 so I suspect we can go back to just `go install` sans `-mod=mod`.  I'll update the docs but feel free to chime in if you disagree @bdshroyer - you dug into this pretty deeply and I still find that go's various module related flags are opaque to me!

**Comment by bdshroyer** [comment]
I tried dropping the `-mod=mod` flag from my installation command in Github Actions and got the same errors that prompted #950. I think the current issue stems from the current backup defaults in the [Go Build flags](https://go.dev/ref/mod#build-commands):

```
By default, if the [go version](https://go.dev/ref/mod#go-mod-file-go) in go.mod is 1.14 or higher and a vendor directory is present, the go command acts as if -mod=vendor were used. Otherwise, the go command acts as if -mod=readonly were used.
```

I'm not using any vendoring, so `go install` so unless you set the `-mod` flag Go currently defaults to readonly mode again and fails (I checked this by setting `-mod=readonly` and getting the same error, and then setting `-mod=vendor` and getting a completely different one that I hadn't seen).
