### ISSUE TITLE
DescribeTable with no entries should fail

### ISSUE THREAD

**Issue by Airblader** [onsi/ginkgo#1029]
In our project we just ran into the following human error situation:

```
var _ = Describe("Some API", func() {
	DescribeTable("for some context", func() {
		DescribeTable("does something", func(someArg bool) {
			// ...
		},
			Entry("", true),
			Entry("", false),
		)
	})
})
```

These tests will never execute. Why? Because the outer `DescribeTable` should be a `Describe` instead. As-is, this will silently pass and never execute anything.

Thus, the question becomes: should `DescribeTable` with no test cases perhaps fail?

**Comment by eriknyk** [comment]
you have nested `DescribeTable ` and since the first `DescribeTable` have not any valid `Entry` sentence it doesn't nothing.
Maybe a Warning from ginkgo could help.

**Comment by onsi** [comment]
hey @Airblader this makes sense.  The only minor drawback I see is that users who are in the middle of developing their specs and have a placeholder `DescribeTable` in place that they haven't fleshed out yet will get a failure until they do...

...but honestly that's a small price to pay given the irritation and costliness of this particular silently-passing-without-running-anything failure mode.

I'll add it to the backlog and will try to get to it soon.

**Comment by Airblader** [comment]
Thanks, @onsi! I'd probably argue that the case you're describing is even more reason to fail in this case. 😄 

There's always `XDescribeTable` to temporarily disable the test, too. Perhaps the error message when failing could point to that so users have a way forward (I know from my team that the X variants weren't actually known to everyone).

**Comment by onsi** [comment]
Yep that makes sense!
