### ISSUE TITLE
How to get Spec Name and Status in JustAfterEach (Ginkgo v1)

### ISSUE THREAD

**Issue by coreyperkins** [onsi/ginkgo#1030]
I am currently stuck on GinkgoV1 because the project I am assisting on has a hard requirement of golang 1.17.x. It appears GinkgoV2 requires golang 1.18.x so I cannot upgrade yet.

Is there a way, even if it is a bit of a hack, to get just the spec name and status inside JustAfterEach in v1?

Thanks!

Corey

**Comment by onsi** [comment]
yes `CurrentGinkgoTestDescription()` should give you what you need :)

**Comment by coreyperkins** [comment]
@onsi thank you for your comment! It works well for what I need, but V2 looks awesome and I can't wait to use it! Here is my code just for the next person who might be in my position.

`var _ = JustAfterEach(func() {
	gtd := CurrentGinkgoTestDescription()

	fmt.Fprintf(os.Stdout, "\nGinkgo Test Status! %s\n", strconv.FormatBool(gtd.Failed))
	fmt.Fprintf(os.Stdout, "Ginkgo Test FileName! %s\n", gtd.FileName)
	fmt.Fprintf(os.Stdout, "Ginkgo Test TestText! %s\n", gtd.TestText)
	fmt.Fprintf(os.Stdout, "Ginkgo Test TestTextFullTestText! %s\n", gtd.FullTestText)
})
`

Thanks so much!
