### ISSUE TITLE
How to let Entry from DescribeTable mutate config prior to JustBeforeEach

### ISSUE THREAD

**Issue by aharbis** [onsi/ginkgo#1035]
We're trying to use two Ginkgo features together, `JustBeforeEach` <sup>1</sup> and `DescribeTable` <sup>2</sup>, but struggling to come up with a way to make it work. At a high-level, the goal is to let the value(s) passed into the `Entry` drive the configuration that's used in `JustBeforeEach`. However, the timing doesn't seem to allow this.

This is a bit of a rudimentary example, but about as brief as I can think to make it while trying to portray our use case.

```go
type Resource struct {
	Name string
}

var _ = Describe("some tests", func() {

	var foo *Resource
	var err error

	JustBeforeEach(func() {
		err = createResource(foo)
	})

	BeforeEach(func() {
		foo = &Resource{
			Name: // input from Entry
		}
	})

	DescribeTable("resource name",
		func(name string) {
			res, err := getResource(name)
			// assert res and err
		},
		Entry(nil, "John"),
		Entry(nil, "Bob"),
		Entry(nil, "Carl"),
	)
})
```

[1] - https://onsi.github.io/ginkgo/#separating-creation-and-configuration-justbeforeeach
[2] - https://onsi.github.io/ginkgo/#table-specs

**Comment by aharbis** [comment]
I did come across https://github.com/onsi/ginkgo/issues/378 but it's sort an opposite use-case, where the solution was to inject a closure into the `Entry`. I don't think this works for us, because we need to lift the value from `Entry` up the stack to the `BeforeEach`.

**Comment by onsi** [comment]
Hey - there is currently no way to do this.  I usually put the case-specific initialization code into the body of the function passed to `DescribeTable` and any outer `Before`s are just setting up common state.

**Comment by EronWright** [comment]
It would be great if an `Entry` could somehow produce a `BeforeEach` block, in addition to an `It` block.  This would allow the entry to do some configuration before creation occurs in a `JustBeforeEach` block.
