### ISSUE TITLE
[FAIL] Flags Specs [It] should run the race detector when told to [slow]

### ISSUE THREAD

**Issue by abhishekdighePersIbm1** [onsi/ginkgo#1036]
Hi Team,

I am trying to build the onsi/ginkgo package on the power/ppc64le architecture. I am doubtful when I am trying to execute the go test -v ./... command one test case is failing as follows

• [FAILED] [20.013 seconds]
Flags Specs
/ginkgo/integration/flags_test.go:12
 [It] should run the race detector when told to [slow]
 /ginkgo/integration/flags_test.go:51
 Begin Captured GinkgoWriter Output >>
   FATAL: ThreadSanitizer CHECK failed: ./gotsan.cpp:14506 "((personality(old_personality | ADDR_NO_RANDOMIZE))) != ((-1))" (0xffffffffffffffff, 0xffffffffffffffff)
   Ginkgo ran 1 suite in 19.993896808s
   Test Suite Passed
 << End Captured GinkgoWriter Output
 No future change is possible. Bailing out early after 20.012s.
 Expected
     <int>: 0
 to match exit code:
     <int>: 197
 In [It] at: /ginkgo/integration/flags_test.go:56
------------------------------
•••••••••••••••••••••••••••••••••
Summarizing 1 Failure:
 [FAIL] Flags Specs [It] should run the race detector when told to [slow]
 /ginkgo/integration/flags_test.go:56
Ran 153 of 153 Specs in 331.540 seconds
FAIL! -- 152 Passed | 1 Failed | 0 Pending | 0 Skipped

And after giving the race flag (go test -race ./...) getting following output

?   	github.com/onsi/ginkgo/v2	[no test files]
?   	github.com/onsi/ginkgo/v2/config	[no test files]
ok  	github.com/onsi/ginkgo/v2/docs	0.005s
ok  	github.com/onsi/ginkgo/v2/dsl	0.020s
?   	github.com/onsi/ginkgo/v2/dsl/core	[no test files]
?   	github.com/onsi/ginkgo/v2/dsl/decorators	[no test files]
?   	github.com/onsi/ginkgo/v2/dsl/reporting	[no test files]
?   	github.com/onsi/ginkgo/v2/dsl/table	[no test files]
ok  	github.com/onsi/ginkgo/v2/extensions/globals	0.010s
?   	github.com/onsi/ginkgo/v2/extensions/table	[no test files]
ok  	github.com/onsi/ginkgo/v2/formatter	0.022s
ok  	github.com/onsi/ginkgo/v2/ginkgo	0.003s
?   	github.com/onsi/ginkgo/v2/ginkgo/build	[no test files]
ok  	github.com/onsi/ginkgo/v2/ginkgo/command	0.021s
?   	github.com/onsi/ginkgo/v2/ginkgo/generators	[no test files]
ok  	github.com/onsi/ginkgo/v2/ginkgo/internal	0.005s
?   	github.com/onsi/ginkgo/v2/ginkgo/labels	[no test files]
ok  	github.com/onsi/ginkgo/v2/ginkgo/outline	0.004s
ok  	github.com/onsi/ginkgo/v2/ginkgo/performance	0.003s
?   	github.com/onsi/ginkgo/v2/ginkgo/run	[no test files]
?   	github.com/onsi/ginkgo/v2/ginkgo/unfocus	[no test files]
?   	github.com/onsi/ginkgo/v2/ginkgo/watch	[no test files]
ok  	github.com/onsi/ginkgo/v2/integration	0.004s
ok  	github.com/onsi/ginkgo/v2/internal	0.003s
?   	github.com/onsi/ginkgo/v2/internal/global	[no test files]
ok  	github.com/onsi/ginkgo/v2/internal/internal_integration	0.003s
ok  	github.com/onsi/ginkgo/v2/internal/interrupt_handler	0.006s
ok  	github.com/onsi/ginkgo/v2/internal/parallel_support	0.012s
?   	github.com/onsi/ginkgo/v2/internal/test_helpers	[no test files]
ok  	github.com/onsi/ginkgo/v2/internal/testingtproxy	0.034s
ok  	github.com/onsi/ginkgo/v2/reporters	0.008s
ok  	github.com/onsi/ginkgo/v2/types	0.004s

which is the right way and does the -race flag impacts/suppress the test cases for the package

**Comment by onsi** [comment]
hey there - I don't think Go's race detector supports power/ppc64.  If you're just consuming/using Ginkgo this shouldn't be a problem.  If you're trying to run the Ginkgo tests then, yes, this integration test which checks that Ginkgo is correctly running the race detector will fail.  You could skip that test with `ginkgo --skip="race detector"`
