### ISSUE TITLE
Enable describing the actions of the BeforeEach and AfterEach nodes

### ISSUE THREAD

**Issue by felipe88alves** [onsi/ginkgo#1037]
Perhaps this is a question as much as it is a request for improvement.

Is there a strong reason for not adding the \<description\> parameter to the BeforeEach and AfterEach nodes?
I find that it would really increase the readability of the code.

I.e:
```
Describe("Begin testing custom controller", func() {
	BeforeEach("Create Fake CR and adjacent resources for testing", func() {
	Context("The CR exists", func() {
		AfterEach("Cleanup of CR and managed resources", func() {
			....
```

**Comment by onsi** [comment]
hey @felipe88alves - no strong reason.  I've generally found the text in the contexts/describes/Its is enough to help understand what a `BeforeEach` is doing.  And if there is need for additional documentation most users throw in a `By`.  We could add descriptions to setup nodes - I'm not opposed; but it's gonna be a bit of a lower priority vs the other enhancements currently inflight.

**Comment by felipe88alves** [comment]
Thanks for the reply, would it be ok for me to implement this change?

**Comment by felipe88alves** [comment]
I take my suggestion back since Go doesn't support function overloading.
This means that I can't add a new BeforeEach function with a different set of parameters (`BeforeEach(text string, args ...interface{})`) and adding a new  parameter to the existing BeforeEach function would break backwards compatibility, which is an obvious no.

I'll close off this thread.
Cheers!
