### ISSUE TITLE
`--dry-run` seems to run BeforeSuite and AfterSuite functions

### ISSUE THREAD

**Issue by KevinJCross** [onsi/ginkgo#1042]
Hi,
We have some complex tests that we wish to add labels to partition the tests into groups but when we want to find out which tests the run command would exectute I would have though that the `--dry-run` option would fit the bill.

The actuall command was `ginkgo run --dry-run  --label-filter "smoke" ./...`

From my naive view I would have expected the `--dry-run` would not run any test code but `list` the tests it would run with the command. This is problematic because our tests set up a lot of stuff in the BeforeEach BeforeSuites and will cause issues when we actually want a `dry run`.

Im not sure if this is the correct assumption ?

**Comment by onsi** [comment]
yeah it should definitely not do that! let me take a look this morning and get back to you...

**Comment by onsi** [comment]
Odd - I just tried this and it worked as expected (`--dry-run` does not run `BeforeSuite` or `AfterSuite`).

Now, `ginkgo run --dry-run -v --label-filter "smoke" ./...` (note the `-v`, you could also do `-vv` to see what's skipped) will print out what will/won't run.  When it does that it will show things like

```
------------------------------
[BeforeSuite]
/Users/onsi/code/ginkgo/foo/foo_suite_test.go:16
------------------------------
[BeforeSuite] PASSED [0.000 seconds]
[BeforeSuite]
/Users/onsi/code/ginkgo/foo/foo_suite_test.go:16
------------------------------
```

That doesn't mean the `BeforeSuite` callback is invoked or running.  Just that `--dry-run` is showing that the `BeforeSuite` will run before everything (in my case, I have a `fmt.Println` statement in my `BeforeSuite` that doesn't run when `--dry-run` is enabled).

**Comment by KevinJCross** [comment]
OK great ... let me investigate more why my setup is been run and come back on that.

**Comment by KevinJCross** [comment]
Uuug 🤦 ..... it turns out to be in the Test(t) hook. Some old convoluted tests Ill close this now ... thanks for the quick response and sorry to waste your time.
