### ISSUE TITLE
Compilation takes longer than 10 minutes to start testing

### ISSUE THREAD

**Issue by weikaipan** [onsi/ginkgo#1049]
After running `Running: ginkgo -v -tags ... `

it took more than 10 minutes for ginkgo to compile before it starts to run tests. Does the team suggest any ways to profile/find the bottlenecks?

Thanks.

**Comment by onsi** [comment]
Under the hood ginkgo is just running `go test -c` - do you know if there's one package in particular that is taking time?  can you try compiling it with `go test -c`?  Is this on a local computer or some sort of CI environment?  Sometimes in CI environments ginkgo incorrectly calculates the number of compilation processes to run in  parallel - you can try `ginkgo -compilers=N` to specify a more limited number of concurrent compilers and see if that helps.

**Comment by weikaipan** [comment]
Thank you. I will give them a try.
