### ISSUE TITLE
Undefined Flag `-ginkgo.grace-period`

### ISSUE THREAD

**Issue by Roosterfish** [onsi/ginkgo#1054]
Hello,

With the latest release `v2.3.0` I am hitting the following error when trying to run `ginkgo`:

```
flag provided but not defined: -ginkgo.grace-period
```

The command I am using worked fine until `v2.2.0`:

```
ginkgo -r --race --randomize-all --randomize-suites --cover --output-dir="coverage" --coverprofile="profile.cov"
```

From the changes I saw `grace-period` was introduced with the latest release so I assume something is off there.
Do you have any ideas?

**Comment by yokaze** [comment]
We have the same problem on our CI.

**Comment by Roosterfish** [comment]
That's it! Thank you @onsi, issue closed.
