### ISSUE TITLE
Implement logr.LogSink for GingkoWriter

### ISSUE THREAD

**Issue by Nuckal777** [onsi/ginkgo#1063]
Hey :wave:,

I use [logr](https://github.com/go-logr/logr) in some projects and use Ginkgo for testing. GingkoWriter offers the option to record some output of failing test. Implementing `LogSink` allows failing Ginkgo tests to outright record what is to be logged anyway, which helps investigating the cause. Adding the glue code would be convenient.

Instead of implementing `LogSink` directly, the implementation could be wrapped in an other struct. As I have a basic implementation around, I may work on this.

**Comment by onsi** [comment]
I think I'm following.  Would the idea be to provide a struct that wraps `GinkgoWriter` but implements `LogSink` so that code under test that expects a `LogSink` will have one?

**Comment by Nuckal777** [comment]
Yes, some `GinkgoLogr` struct, which implements `LogSink` and writes to the global `GinkgoWriter`, would be great. So we can do things in tests like:
```go
// next, err := op.Transition(plugin.Parameters{Log: logr.Discard()}, &Data{})
next, err := op.Transition(plugin.Parameters{Log: GinkgoLogr{}}, &Data{})
```

**Comment by onsi** [comment]
ah ok, got it - and you'd want it in Ginkgo proper so you could avoid having to pass in `GinkgoWriter` every time on construction?   Do you, generally, always pass in a new struct/instance when adopting `logr`?  Or can you have one shared `logs` that you pass in everywhere?

**Comment by onsi** [comment]
👍 if you're up for working on a PR I'd be happy to pull something in.
