### ISSUE TITLE
Minimum required go version for v2

### ISSUE THREAD

**Issue by piksel** [onsi/ginkgo#1073]
Hello!

For version 2.3.1, the minimum required go version for using ginkgo was v1.16, so we restricted our library to v1.16+ to be able to use v2 of Ginkgo.
Now with v2.4.0 the minimum version was bumped to v1.17, due to #1065 which adds dependency on [`unsafe.Slice`](https://pkg.go.dev/unsafe#Slice) (through x/sys v0.1).

I couldn't find anything about what versions of Go V2 was supposed to support, but if it is v1.18+ only, perhaps that should be noted on the migration guide?

**Comment by onsi** [comment]
hey @piksel thanks for calling this out - it seems that when I rewrote the docs for V2 I accidentally dropped the "Support Policy" section.

The intent is for both Ginkgo and Gomega both have the same support policy, so I'll be adding this to the Ginkgo docs:

> ~Gomega~ Ginkgo provides support for versions of Go that are noted by the Go release policy i.e. N and N-1 major versions.

Ideally I'd bump the minimum version when relevant with each release (though, in practice, I don't often remember to do that!)
