### ISSUE TITLE
Streaming machine readable output

### ISSUE THREAD

**Issue by TaylorOno** [onsi/ginkgo#1085]
Is there a way to stream the machine readable output? I was previously relying on Ginkgo console output to provide real time feedback on the state of the running tests but seems like that is no longer maintainable.

**Comment by onsi** [comment]
this is something i'd like to do someday (along with better ide integration) but there isn't anything formal yet.

if you want to set something up yourself you could add a top-level `ReportAfterEach` and `ReportAfterSuite` node and send json-encoded versions of the passed-in reports to a server.  Can share more detail if you're interested.

**Comment by TaylorOno** [comment]
Thanks for the quick response but seems like I'll need to keep relying on console output for real time updates. 

If you ever want to take over https://github.com/IdeaGinkgo/Intellij-Ginkgo let me know.

**Comment by onsi** [comment]
ah! sorry @TaylorOno i replied so quickly i didn't pause to think _who_ i was replying to!

ginkgo needs a streaming machine readable output format that's a stable extension point.  i don't mean to imply that i wanna take on all the ide integrations - just to better enable them!

is parsing json off of stdout a better integration point? or would it be better for ginkgo to take an endpoint that it can send updates to?

**Comment by TaylorOno** [comment]
I think reading structured messaged that are streamed to the console is the most straight forward integration point, but it also doesn't seem like too much of a hassle to subscribe to a file and listen for updates if you can flush updates to that file as they finish. I wouldn't mind if at some point you added a flag  I would need to investigate if I can have a create a endpoint to listen for updates.
