### ISSUE TITLE
[Question] Does ginkgo v2 support flag passthrough?

### ISSUE THREAD

**Issue by pbxqdown** [onsi/ginkgo#1093]
Tried to use command like `ginkgo <flags> <packages> -- <pass-throughs>` but it seems to fail

**Comment by pbxqdown** [comment]
Thank you, I will try. I think custom flag has to start with two dashes?

**Comment by onsi** [comment]
you do need the `--` separator between flags and arguments intended for `ginkgo` and flags and arguments intended for your test, yes.

**Comment by pbxqdown** [comment]
This is the command I'm using: ` ginkgo -v --mod=vendor  --cover  --junit-report=out.xml ./tests -- --HOST_SELECTION_LABEL=abc`. ginkgo parsed as its own flag: `flag provided but not defined: -HOST_SELECTION_LABEL` Guess it is because some flag-parsing problem. Maybe I will just use ENV variable instead

**Comment by onsi** [comment]
You can use an env variable of course, but the docs do show how to set up flag parsing in a ginkgo spec and i just tried it again to make sure it continues to work.  if you'd like you can share your flag parsing code to me and i can help you figure out what's going wrong.  it may be that you're not registering the flag early enough.

**Comment by pbxqdown** [comment]
ENV solution works very well, I will stick with it :)  just curious what will be ginkgo's behavior if custom flag is not parsed in code.

**Comment by onsi** [comment]
yes environment variables work well.  Ginkgo is using go's flag library to parse the flags passed in on the command line.  it will have the same behavior as go flags.  The documentation explains how to wire things up so that you can capture custom flags.  If you don't set up the custom flag correctly Go's flag library will panic by default.

**Comment by pbxqdown** [comment]
make sense, maybe the flag parsing logic is not correctly set causing the problem. Thank you for detailed explanation.
