### ISSUE TITLE
reflection-based function calls: pointer vs. value

### ISSUE THREAD

**Issue by pohly** [onsi/ginkgo#1094]
Suppose you have:
```
s := someStruct{}
cleanup := func(s *someStruct) {}
defer cleanup(s)
```

The compiler will determine that it needs to pass `s` as pointer.

Now convert to `DeferCleanup`:
```
s := someStruct{}
cleanup := func(s *someStruct) {}
ginkgo.DeferCleanup(cleanup, s)
```

This leads to:
```
I1212 15:28:59.391]   There were additional failures detected after the initial failure:
I1212 15:28:59.391]     [PANICKED]
I1212 15:28:59.391]     Test Panicked
I1212 15:28:59.391]     In [DeferCleanup (Each)] at: /usr/local/go/src/reflect/value.go:440
I1212 15:28:59.391] 
I1212 15:28:59.391]     reflect: Call using testsuites.topologyTest as type *testsuites.topologyTest
I1212 15:28:59.391] 
```

It would be nice if Ginkgo did the value -> pointer conversion automatically. In the meantime, doing it manually should solve the problem.

This is from https://github.com/kubernetes/kubernetes/pull/114425.

**Comment by onsi** [comment]
fascinating - i somehow wasn't aware the compiler made that transformation for you.  seems very un-go-like as it can be potentially confusing to read the code ("how did this struct mutate, i passed it in by value")

in any event i believe Ginkgo will receive a value and there's no way to convert that to the original pointer as it will be a fresh copy of the struct intended for that function call.

i might be wrong though and can try it out.

**Comment by pohly** [comment]
I might be wrong - let me check the original defer call to see why it compiled...

It did indeed have a call with a pointer, and not in a simple `defer`. I messed up the translation to `DeferCleanup`. Let's pretend this issue never got reported...

**Comment by onsi** [comment]
no worries!  glad we were able to figure it out.
