### ISSUE TITLE
Error while using custom gomega instance inside a goroutine

### ISSUE THREAD

**Issue by deepankarm** [onsi/ginkgo#1096]
Hello, Thanks for the great work with ginkgo! 

I'm struggling with a use-case where I want to combine `Eventually` with a non-global `Gomega` instance & a goroutine using that gomega instance inside the function Eventually uses. Here's a simpler version of what I'm trying to achieve.

<table>
<tr>
<td> <center><b>No Goroutine</b></center> </td> <td><b><center>Goroutine</center></b></td>
</tr>
<tr>
<td>

```go
var count = 0

func some_externalfunc() bool {
	count++
	fmt.Println("count", count)
	return count >= 3
}

var _ = Describe("Some tests", func() {
	Describe("some tests", func() {
		It("should work", func() {
			testfunc := func(g Gomega) {
				somefunc := func() {

					for {
						is_done := some_externalfunc()
						fmt.Println("\nis_done:", is_done)
						g.Expect(is_done).To(BeTrue()) // this will fail for some time
						if is_done {
							break
						}
					}
				}

				fmt.Println("some work")
                                // no goroutine
				somefunc()
				fmt.Println("some more work")
				time.Sleep(2 * time.Second)
				fmt.Println("work completed")
			}

			Eventually(testfunc, 100*time.Second, 10*time.Second).Should(Succeed())
		})
	})
})
```

</td>
<td>

```go
var count = 0

func some_externalfunc() bool {
	count++
	fmt.Println("count", count)
	return count >= 3
}

var _ = Describe("Some tests", func() {
	Describe("some tests", func() {
		It("should work", func() {
			testfunc := func(g Gomega) {
				somefunc := func() {
					defer GinkgoRecover()
					for {
						is_done := some_externalfunc()
						fmt.Println("\nis_done:", is_done)
						g.Expect(is_done).To(BeTrue()) // this will fail for some time
						if is_done {
							break
						}
					}
				}

				fmt.Println("some work")
                                // goroutine
				go somefunc()
				fmt.Println("some more work")
				time.Sleep(2 * time.Second)
				fmt.Println("work completed")
			}

			Eventually(testfunc, 100*time.Second, 10*time.Second).Should(Succeed())
		})
	})
})
```

</td>
</tr>

<tr>
<td>

### Output

```text
some work
count 1

is_done: false
some work
count 2

is_done: false
some work
count 3

is_done: false
some work
count 4

is_done: false
some work
count 5

is_done: true
some more work
work completed

...
Test Suite Passed
```

</td>

<td>

### Output

```text
some work
some more work
count 1

is_done: false
work completed
some work
some more work
count 2

is_done: false
work completed
some work
some more work
count 3

is_done: true
work completed

------------------------------
• [PANICKED] [14.008 seconds]
Some tests some tests [It] should work
/home/deepankar/repos/jina-operator/api/test/e2e/basic_http_test.go:179

  [PANICKED] Test Panicked
  In [It] at: /usr/local/go/src/runtime/panic.go:838 @ 12/14/22 14:00:32.402

  stop execution

  Full Stack Trace
    panic({0x1892860, 0x1e96bb0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
    github.com/onsi/gomega/internal.(*AsyncAssertion).buildActualPoller.func2({0xc001026090, 0x25}, {0xc0016868e0?, 0xc001026090?, 0xc0000c20c0?})
        /home/deepankar/go/pkg/mod/github.com/onsi/gomega@v1.24.1/internal/async_assertion.go:232 +0x105
    github.com/onsi/gomega/internal.(*Assertion).match(0xc000fc0280, {0x1ea6d30, 0x2d2a598}, 0x1, {0x0, 0x0, 0x0})
        /home/deepankar/go/pkg/mod/github.com/onsi/gomega@v1.24.1/internal/assertion.go:106 +0x1f0
    github.com/onsi/gomega/internal.(*Assertion).To(0xc000fc0280, {0x1ea6d30, 0x2d2a598}, {0x0, 0x0, 0x0})
        /home/deepankar/go/pkg/mod/github.com/onsi/gomega@v1.24.1/internal/assertion.go:62 +0xb5
    github.com/jina-ai/jina-operator/api/test/e2e.glob..func7.1.1.1.1()
        /home/deepankar/repos/jina-operator/api/test/e2e/basic_http_test.go:186 +0x10d
    created by github.com/jina-ai/jina-operator/api/test/e2e.glob..func7.1.1.1
        /home/deepankar/repos/jina-operator/api/test/e2e/basic_http_test.go:194 +0xbe
------------------------------

...
Test Suite Failed
```
</td>
</tr>
</table>

Any hints about something I am doing wrong here?

**Comment by blgm** [comment]
I'm not sure, but here are some observations:
- GitHub is not rendering the table very well - you have to scroll to the right to understand the issue
- The way that `Eventually()` works is to run a function **many times** until it matches the expected result (or times out). `testfunc` will be run 10 times per second, but the function itself takes at least 2 seconds to run because of the sleep. I doubt this was the intention. Maybe you want something more like:
```go
It("works", func() {
  result := false
  go runSomethingThatWillMayChangeResult()
  
  Eventually(result).Should(BeTrue())
})
```
The difference here being that the "work" only gets run once, but the check it run many times.

**Comment by deepankarm** [comment]
@blgm Thanks for responding. 

> testfunc will be run 10 times per second

```go
Eventually(testfunc, 100*time.Second, 10*time.Second).Should(Succeed())
```
Doesn't this mean, every 10s `testfunc` is run until a timeout of 100s is reached (and not 10 times per sec)?

---

The timeouts, intervals & sleeps used are just to show an example of what my other larger function does. The intention here is to run `Eventually()` once every T seconds with timeout and make sure there are no errors in `testfunc`. There's no return value to assert here.

My question here was, the RHS output says that `is_done: true` - which means the goroutine is successfully completed - which means that `g.Expect(...)` is also successful. I'd expect the `Eventually` to also succeed, which is not the case in RHS.

**Comment by onsi** [comment]
Hey there @deepankarm 

So one of the issues with this:

```go
testfunc := func(g Gomega) {
	somefunc := func() {
		defer GinkgoRecover()
		for {
			is_done := some_externalfunc()
			fmt.Println("\nis_done:", is_done)
			g.Expect(is_done).To(BeTrue()) // this will fail for some time
			if is_done {
				break
			}
		}
	}

	fmt.Println("some work")
					// goroutine
	go somefunc()
	fmt.Println("some more work")
	time.Sleep(2 * time.Second)
	fmt.Println("work completed")
}

Eventually(testfunc, 100*time.Second, 10*time.Second).Should(Succeed())
```

is that `g.Expect(is_done).To(BeTrue())` panics to abort execution - which (a) drops you out of the `for` loop and (b) registers a panic failure with Ginkgo's fail handler (that's what `defer GinkgoRecover()` does).  The `Eventually` will retry your `testfunc` and so the `for` loop will be tried again later however the panic captured by `defer GinkgoRecover()` will forever be associated with the spec.  This is an unfortunate interplay between using `Eventually`'s `g Gomega` and Ginkgo's `defer GinkgoRecover()` and it's something I can improve on.

But there are a few other potential issues with the code you've shared: one is sleeping to wait for the goroutine to return vs using a channel to communicate.  What happens if the goroutine doesn't complete before `time.Sleep(2*time.Second)` expires?  Also, there's a fair bit of complexity here with lots of functions wrapping other functions.  I imagine that might be complexity that's part of your code that doesn't translate well to your simplified example (e.g. why spin up a goroutine here?)

Here's an alternative approach that uses `Eventually` to do the looping for you:

```go
testfunc := func(g Gomega) {
	fmt.Println("some work")
        Eventually(some_externalfunc).Should(BeTrue()) // this replaces your goroutine + for loop but has the same intent of "after I do some work this external function should eventually succeed"
	fmt.Println("some more work")
	fmt.Println("work completed")
}

Eventually(testfunc, 100*time.Second, 10*time.Second).Should(Succeed())
```

If you _must_ use a goroutine for some reason then I'd rewrite it like this:

```go
testfunc := func(g Gomega) {
        c := make(chan interface{}) 
	somefunc := func() {
		for {
			if some_externalfunc() {
                                  close(c)
			}
		}
	}

	fmt.Println("some work")
	go somefunc()
	fmt.Println("some more work")
        <-c // or Eventually(c).WithTimeout(2*time.Second).Should(BeClosed())
	fmt.Println("work completed")
}

Eventually(testfunc, 100*time.Second, 10*time.Second).Should(Succeed())
```

**Comment by onsi** [comment]
Would also be happy to look at the original code if it's open source.  I can imagine how the actual complexity makes some of these proposals unworkable.

**Comment by deepankarm** [comment]
Thanks for responding @onsi.

> might be complexity that's part of your code that doesn't translate well to your simplified example (e.g. why spin up a goroutine here?)

This is exactly right. There are a few complexities in some other dependencies, where `somefunc` is always run in goroutines. While I write what is inside `somefunc`, it'd always be run inside a goroutine. 

> Would also be happy to look at the original code if it's open source.

Unfortunately, this is part of a private repo for now. Thanks anyways :) 

Since I can't really avoid goroutines, I'd look at the 2nd recommendation. Working with a channel sounds like a good idea, but it still doesn't allow me to use `Expect`s (or `g.Expect`) and I have a bunch of them. I'll try with `if actual != expected { close(c) }` for all these Excepts tomorrow, and let you know how it goes. Thanks!

**Comment by onsi** [comment]
ok.  as a said there is something i can do on my end to allow you to use Expect with the gomega passed in to your function by Eventually.  My only concern is that you are getting into some really deep complexity and i suspect there's a way to clean up your spec to avoid some of that complexity.

**Comment by onsi** [comment]
i'll try to work on this today and give you a version of gomega + ginkgo that can work for your usecase.

**Comment by blgm** [comment]
@deepankarm, regarding https://github.com/onsi/ginkgo/issues/1096#issuecomment-1351218534 you're quite correct - my math was wrong!

The observation I meant to make was that tests with `Eventually()` are much simpler to reason about when there is clear separation between the _work_ and the _check_. The _work_ might well start something in another library that runs Goroutines. But potentially the check can run without Goroutines. For example:
```go
	It("works", func() {
		// -----------------------------------------
		// Data - could be atomics, channels, etc...
		// -----------------------------------------
		var (
			finished atomic.Bool
			data     atomic.Int32
		)

		// --------------------
		// Start the work going
		// --------------------
		work := func() {
			time.Sleep(5 * time.Second)
			data.Store(42) // result of calculation
			finished.Store(true)
		}

		go work()

		// ---------------------------
		// Wait for the work to finish
		// ---------------------------
		checker := func() bool {
			return finished.Load()
		}
		Eventually(checker).WithPolling(time.Second).WithTimeout(time.Minute).Should(BeTrue())

		//---------------------------------
		// Make assertions about the result
		//---------------------------------
		Expect(data.Load()).To(BeNumerically("==", 42))
	})
```
The example is meant to show separation of concerns between the work and the check; and between the work and the assertions. But maybe this doesn't work in your situation.

**Comment by onsi** [comment]
+1 to @blgm 's separation of concerns.  Agreed that it is much easier to reason about things if you can separate them in this way.

In practice it's not always possible, and gomega does support polling functions that take an embedded `g Gomega`.  While this conflates work and checking it's just proven to be necessary in some contexts.

I'm going to work on a fix that should get support for using that `g Gomega` in a goroutine with `defer GinkgoRecover()` though.

**Comment by onsi** [comment]
alrighty if you upgrade to Ginkgo v2.6.1 **and** Gomega v1.24.2 your code should now work as written.  I do think you should try to simplify things if possible at all - but `defer GinkgoRecover()` in the goroutine will now handle the panic generated by the assertion failure correctly.

Note that your `for` loop is still somewhat meaningless as the assertion failure halts execution.  And you do still run the risk of leaking a goroutine with the `time.Sleep` approach (so a channel would be better here).  But this was a bug/hole in Ginkgo + Gomega as well which should be fixed now.

**Comment by deepankarm** [comment]
> if you upgrade to Ginkgo v2.6.1 and Gomega v1.24.2 your code should now work as written

Perfect. I can confirm that this resolves the original issue. `defer GinkgoRecover()` in the goroutine does handle the panic generated by the assertion failure correctly.

> Note that your `for` loop is still somewhat meaningless as the assertion failure halts execution. And you do still run the risk of leaking a goroutine with the `time.Sleep` approach (so a channel would be better here).

I think, I just gave a bad example while trying to convey the original issue with `Eventually` & `GinkgoRecover`. 

Thank you for the help & the quick fix. I'll close the issue now.
