### ISSUE TITLE
Update issue from 2.1.4 to 2.6.1

### ISSUE THREAD

**Issue by DblK** [onsi/ginkgo#1099]
Hi,

Until now, I was launching my test with the following command: `ginkgo -r --randomize-all --randomize-suites --trace -cover`.
However it display now a warning as following:
![Screenshot 2022-12-15 at 18 59 22](https://user-images.githubusercontent.com/832617/207933916-43c3c74e-107b-40fa-9cb7-6e310d9aa7bf.png)

I did not use any of the parameter listed.
What should I fix to get rid of this warning (of course without using the ENV var)?

thx

**Comment by onsi** [comment]
hey - please make sure you've updated the ginkgo cli as well.  what's the output of `ginkgo version`?

**Comment by DblK** [comment]
Good catch! `ginkgo version` returned 2.1.4. I updated it and warning disappear.
Thx!

**Comment by onsi** [comment]
Great!  Going forward the ginkgo cli will notify you if it detects a version mismatch like this.  that's a relatively new feature.
