### ISSUE TITLE
How to run ginkgo CLI with precompiled tests.

### ISSUE THREAD

**Issue by ezh** [onsi/ginkgo#1106]
Hi. My test case is to run E2E tests in a container.
I like to build a static binary and create a root-less container with only the necessary components.
I did `ginkgo build -gcflags="all=-N -l" .`
And `./e2e.test --ginkgo.v --ginkgo.parallel.process=10 --ginkgo.parallel.total=10 --ginkgo.parallel.host=127.0.0.1`
Unfortunately, I got
```
Could not reach ginkgo.parallel.host:127.0.0.1
  It looks like you are trying to run specs in parallel with go test.
  This is unsupported and you should use the ginkgo CLI instead.

  Learn more at: http://onsi.github.io/ginkgo/#spec-parallelization
```
How to use ginkgo CLI with pre-compiled binary? I like to pack ginkgo CLI static binary to the container as well.

My tests contain heavyweight `SynchronizedBeforeSuite` I don't want to compile a group of binaries because I lost all benefits.

**Comment by onsi** [comment]
if you include the ginkgo cli then you can just run 

```
ginkgo -prove=10 e2e.test
```

(ie you can point it at the precompiled binary)
