### ISSUE TITLE
Support for retrieving labels and displaying them in ginko outline

### ISSUE THREAD

**Issue by Dannyb48** [onsi/ginkgo#1109]
We have a use case where we want to use the text from the containers to generate test cases in our tcms. Our TCMS has the concept of tags and we are looking to map ginkgo labels to those tags. The ginkgo outline command gets us most of what we need except labels. 

If this you're ok with adding this functionality. I have some working code locally that I can contribute to extract this information and include it as part of the outline output in a separate column.

**Comment by onsi** [comment]
hey sorry for the delay - have been out of town on vacation.  sure please do submit a PR!

**Comment by Dannyb48** [comment]
ack, @onsi thanks I'm cleaning up the code now but I just noticed that I am in the same area of code for issue #955 and I feel like I can easily address that issue as well. Would you be ok if I also included the fix for that issue in my PR or would you prefer that as a separate PR?

**Comment by onsi** [comment]
one PR would be great thanks!
