### ISSUE TITLE
Option in Eventually for requiring multiple successes before Accepting

### ISSUE THREAD

**Issue by lahabana** [onsi/ginkgo#1116]
Currently with Eventually it succeeds as soon as 1 occurence succeeds.

In [kumahq/kuma](https://github.com/kumahq/kuma) we have a use case where we want to make sure that something eventually happens reliably.

What we do is:

```go
func myCheck(g Gomega) {
  // ...
}

Eventually(myCheck).Should(Succeed)
Consistently(myCheck).Should(Succeed)
```

This doesn't exactly work in the following case:

- Things succeed by default 50% of the case
- After a while things succeed 100% of the cases

The code above will pass sometimes.

I think what we could introduce is a `WithOccurrence(int)` option so that Eventually will retry X times before actually succeeding

**Comment by onsi** [comment]
hey @lahabana this makes sense to me.  ginkgo has a similar feature in the `MustPassRepeatedly` decorator which applies to entire specs.

We could add a similar thing to Gomega:

```
Eventually(X).MustPassRepeatedly(N).Should(Y)
```

would require `X` to eventually satisfy `Y` `N` times in a row.

Do you have time/interest in writing a pull request for this?  I can point you at the right places and we can flesh out the behavior a bit more if you'd like.

**Comment by lahabana** [comment]
Yes I'd like to contribute from a quick look it seems like the meat should be somewhere around there: 

https://github.com/onsi/gomega/blob/9351dda0b6156f5e0087fa6429b40d1631a1ee7a/internal/async_assertion.go#L414-L423

Is this correct?

Also just noticed I've opened this on the wrong repo feel free to transfer the issue to Gomega

**Comment by onsi** [comment]
Yep somewhere in there works.  I’d say we should simply ignore MustPassRepeatedly for Consistently as it only really makes sense for Eventually.On Jan 13, 2023, at 6:26 AM, Charly Molter ***@***.***> wrote:﻿
Yes I'd like to contribute from a quick look it seems like the meat should be somewhere around there:
https://github.com/onsi/gomega/blob/9351dda0b6156f5e0087fa6429b40d1631a1ee7a/internal/async_assertion.go#L414-L423
Is this correct?
Also just noticed I've opened this on the wrong repo feel free to transfer the issue to Gomega

**Comment by lahabana** [comment]
Duplicate of https://github.com/onsi/gomega/issues/618
