### ISSUE TITLE
Unable to "go mod tidy" after upgrading to 2.x

### ISSUE THREAD

**Issue by BiggerNoise** [onsi/ginkgo#1117]
I have upgraded to ginkgo 2.x and am able to run tests, however, I am now unable to run go mod tidy. It keeps attempting to satisfy the v2 dependency in a 1.16 library.

```
parsely git:(master) ✗ go mod tidy
go: finding module for package github.com/onsi/ginkgo/ginkgo/v2
github.com/koanhealth/parsely/tools imports
	github.com/onsi/ginkgo/ginkgo/v2: module github.com/onsi/ginkgo@latest found (v1.16.5), but does not contain package github.com/onsi/ginkgo/ginkgo/v2
➜  parsely git:(master) ✗
```

It looks like my module graph is clean:

```
➜  parsely git:(master) ✗ go mod graph | grep ginkgo
github.com/koanhealth/parsely github.com/onsi/ginkgo/v2@v2.7.0
github.com/koanhealth/gotools@v1.0.19 github.com/onsi/ginkgo/v2@v2.7.0
github.com/onsi/ginkgo/v2@v2.7.0 github.com/go-logr/logr@v1.2.3
github.com/onsi/ginkgo/v2@v2.7.0 github.com/go-task/slim-sprig@v0.0.0-20210107165309-348f09dbbbc0
github.com/onsi/ginkgo/v2@v2.7.0 github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38
github.com/onsi/ginkgo/v2@v2.7.0 github.com/onsi/gomega@v1.24.1
github.com/onsi/ginkgo/v2@v2.7.0 golang.org/x/sys@v0.3.0
github.com/onsi/ginkgo/v2@v2.7.0 golang.org/x/tools@v0.4.0
github.com/onsi/ginkgo/v2@v2.7.0 github.com/golang/protobuf@v1.5.2
github.com/onsi/ginkgo/v2@v2.7.0 github.com/google/go-cmp@v0.5.9
github.com/onsi/ginkgo/v2@v2.7.0 golang.org/x/net@v0.3.0
github.com/onsi/ginkgo/v2@v2.7.0 golang.org/x/text@v0.5.0
github.com/onsi/ginkgo/v2@v2.7.0 google.golang.org/protobuf@v1.28.0
github.com/onsi/ginkgo/v2@v2.7.0 gopkg.in/yaml.v2@v2.4.0
github.com/onsi/ginkgo/v2@v2.7.0 gopkg.in/yaml.v3@v3.0.1
github.com/onsi/gomega@v1.24.2 github.com/onsi/ginkgo/v2@v2.6.1
```

I didn't see any additional clean up that I needed to do in the migration instructions and my Google-fu isn't yielding anything. Ideas?

**Comment by blgm** [comment]
Hi @BiggerNoise,

Sometimes I have seen errors a bit like this where the v1 import path `github.com/onsi/ginkgo` still exists somewhere. It's worth double-checking for that - although the error message doesn't quite fit that scenario. Some other questions that spring to mind are:

- Which version of Go are you using?
- Are you using a Go module proxy that's different from `proxy.golang.org`?
- Are you using any replace directives in the `go.mod` file?

If I can think of anything else later then I'll add it.

**Comment by BiggerNoise** [comment]
Appreciate the reply.

I am on Go 1.19 (ARM on MacOS).
I am not using a different proxy
I do not have any replace directives in my go.mod

I found v1 caches in both ~/go/pkg/mod/cache/download/github.com/onsi/ginkgo and ~/go/pkg/mod/github.com/onsi

I deleted the @v & v1.16.5 directories and tried doing a mod tidy again. The go mod command re-downloads the v1.16.5 version (and then again complains that it can't find v2 in v1.16.5).

I suspect that something is being cached elsewhere that is causing it to try and and find v2 in the wrong place, but I'm not sure where else to look.

**Comment by blgm** [comment]
Maybe something like `go ​clean -modcache` might help?

**Comment by BiggerNoise** [comment]
Thanks, I did just try that. Then go mod tidy gives:

```
go: finding module for package github.com/onsi/ginkgo/ginkgo/v2
go: downloading github.com/onsi/ginkgo v1.16.5
github.com/koanhealth/parsely/tools imports
	github.com/onsi/ginkgo/ginkgo/v2: module github.com/onsi/ginkgo@latest found (v1.16.5), but does not contain package github.com/onsi/ginkgo/ginkgo/v2
```

Strangely, all of the other modules just have a ```go: downloading ...``` but ginkgo/v2 has a ```go: finding...```, so I'm going to look and see if that's where the wheels are falling off the cart.

**Comment by onsi** [comment]
weird - sorry you're running into this.  I don't have much additional insight to add other than to ask: have you recursively grepped for `"github.com/onsi/ginkgo"` to confirm that nothing anywhere is importing v1?

**Comment by BiggerNoise** [comment]
Good grief. So, I was importing "github.com/onsi/ginkgo/ginkgo/v2" instead of "github.com/onsi/ginkgo/v2" in one file.

I appreciate all the support and suggestions.

**Comment by onsi** [comment]
❤️

computers.  gotta love 'em!
