### ISSUE TITLE
EmitSpecProgress: removal is causing compile issues

### ISSUE THREAD

**Issue by pohly** [onsi/ginkgo#1122]
Seen when trying to update [dependencies of external-provisioner](https://github.com/kubernetes-csi/external-provisioner/pull/832#discussion_r1088579719):

```
### test-go:
go test  `go list  ./... | grep -v -e 'vendor' -e '/test/e2e$' ` 
# k8s.io/kubernetes/test/e2e/framework
vendor/k8s.io/kubernetes/test/e2e/framework/test_context.go:362:14: suiteConfig.EmitSpecProgress undefined (type "github.com/onsi/ginkgo/v2/types".SuiteConfig has no field or method EmitSpecProgress)
```

This happens when combining Kubernetes 1.26 (which still uses EmitSpecProgress in Ginkgo 2.4.0) with sigs.k8s.io/controller-runtime v0.14.1 (which depends on Ginkgo v2.6.0).

I think we should bring back the method with an empty implementation and mark it as deprecated?

cc @RaunakShah

**Comment by onsi** [comment]
this is fixed in 2.7.1
