### ISSUE TITLE
Race condition introduced in By in v2.5.0

### ISSUE THREAD

**Issue by JoelSpeed** [onsi/ginkgo#1134]
I believe https://github.com/onsi/ginkgo/commit/db83f33f1142f246e6984eb82751ddefa2a94594 has introduced a race condition in the `By` utility in the core DSL.

In version 2.4.0, `By` was implemented directly into [core_dsl.go](https://github.com/onsi/ginkgo/blob/9299761f1714a2a9057916ef0ecdd86011c5ced2/core_dsl.go#L515) and used [AddReportEntry](https://github.com/onsi/ginkgo/blob/9299761f1714a2a9057916ef0ecdd86011c5ced2/core_dsl.go#L531) (which adds report untries [under lock](https://github.com/onsi/ginkgo/blob/9299761f1714a2a9057916ef0ecdd86011c5ced2/internal/suite.go#L266-L267)) and then [GinkgoWriter.Println](https://github.com/onsi/ginkgo/blob/9299761f1714a2a9057916ef0ecdd86011c5ced2/core_dsl.go#L533) (which writes to the output [under lock](https://github.com/onsi/ginkgo/blob/9299761f1714a2a9057916ef0ecdd86011c5ced2/internal/writer.go#L53-L54)) to add the report entry and then write the output.

This meant that you could use the `By` utility within go routines within a test suite, if for example, you wanted to use a waitgroup to wait for multiple conditions in tandem.

In version 2.5.0, running tests with the ginkgo binary those same tests now report a [data race](https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/159#issuecomment-1422372057) because the `By` reporter is now writing events not under lock.

`By` is now implemented in [suite.go](https://github.com/onsi/ginkgo/blob/fdb6c47b1e9f8b9ca8ab479dde7a4bf2a49c45e2/internal/suite.go#L272) and calls `suite.handleSpecEvent` which appends the [event for the report entry under lock](https://github.com/onsi/ginkgo/blob/fdb6c47b1e9f8b9ca8ab479dde7a4bf2a49c45e2/internal/suite.go#L254-L256) but then calls the `reporter.EmitSpecEvent` which in the [DefaultReporter](https://github.com/onsi/ginkgo/blob/fdb6c47b1e9f8b9ca8ab479dde7a4bf2a49c45e2/reporters/default_reporter.go#L537) is causing a race when not used under lock.

Digging in, I believe the issue is because [emit](https://github.com/onsi/ginkgo/blob/fdb6c47b1e9f8b9ca8ab479dde7a4bf2a49c45e2/reporters/default_reporter.go#L621-L627) is writing changes to the `DefaultReporter` not under lock.

So either we need to adjust the `handleSpecEvent` to use the suite selective lock to emit the event to the reported under lock or we need to fix the `DefaultReporter` so that it isn't racy here

**Comment by onsi** [comment]
Welp!  thanks for the detailed deep dive @JoelSpeed - I'll take a look!

**Comment by onsi** [comment]
this is now fixed in 2.8.1
