### ISSUE TITLE
Add new option to JunitReportConfig

### ISSUE THREAD

**Issue by liornoy** [onsi/ginkgo#1145]
My suggestion is to add to the JunitReportConfig a new option: "OmitSetupNodes"
that when is set to true, the Junit report won't create <testcase>s for setup nodes such as BeforSuite and AfterSuite.
for example: 
`<testcase name="[BeforeSuite]" classname="CNF Features e2e integration tests" status="passed" time="0"></testcase>`

This feature could be helpful for me because in [this](https://github.com/openshift-kni/cnf-features-deploy/tree/master) repo, we have a script that takes the output of the JUnit XML, and convert it to an MD file with all the tests cases, where we want to omit the Before/After suites. 

Currently, I see there is the "OmitLeafNodeType" option but it just leaves me with an empty test case like this one:
`<testcase name="" classname="CNF Features e2e integration tests" status="passed" time="0"></testcase>`

**Comment by onsi** [comment]
I think it should be `OmitSuiteSetupNodes` and I'm happy to pull it in if you could submit a PR.

**Comment by liornoy** [comment]
Sure, will do! thanks!

**Comment by myzhan** [comment]
Excuse me, can I use this feature via ginkgo cli?

**Comment by liornoy** [comment]
I think it's not supported. at least I didn't add this option to my implementation.

**Comment by myzhan** [comment]
@liornoy Thanks, but how can I use this option? Should I use GenerateJUnitReportWithConfig() directly?

**Comment by liornoy** [comment]
Yes. 
Here is a an example taken from my work:
```
var _ = ReportAfterSuite("e2esuite", func(report types.Report) {
	if *junitPath != "" {
		junitFile := path.Join(*junitPath, "metallb_operator_e2e_junit.xml")
		reporters.GenerateJUnitReportWithConfig(report, junitFile, reporters.JunitReportConfig{
			OmitTimelinesForSpecState: types.SpecStatePassed | types.SpecStateSkipped,
			OmitLeafNodeType:          true,
			OmitSuiteSetupNodes:       true,
		})
	}
})
```

**Comment by myzhan** [comment]
@liornoy Thanks, I prefer to use it via ginkgo cli. Because I use ginkgo -r to run many suites.

**Comment by onsi** [comment]
it’s not in the cli yet.  i hope to implement a cli-based workflow eventually but don’t have a timeline for it yet

**Comment by liornoy** [comment]
what do you mean by "cli-based workflow"?
Isn't it just adding the flags and piping together with the junit configurations?

**Comment by onsi** [comment]
> Isn't it just adding the flags and piping together with the junit configurations?

i _can_ do it that way - but the number of cli flags will continue to explode in size!

i’m wanting to step back and consider the problem of configuration based on usecases i’m seeing.  for example sometimes `ginkgo -r` is hampered by the reality that you need to configure one package a bit differently than another (eg “allow more parallel processes for this package - but not for this other package”)

so i want to introduce the notion of json-based configuration which can live in the repo and support different profiles (eg “when running on CI” vs “when running on my machine” vs “when developing” vs “pre-commit”) - the idea is to make most ginkgo configuration adjustable in these files and to allow you to specify things hierarchically.  this would then  be a good place to add the more detailed junit report configuration.  a single configuration file at the root of your repo would then govern all your packages.

**Comment by myzhan** [comment]
> a single configuration file at the root of your repo would then govern all your packages.

I would love to see that happen. Before that, I can fork ginkgo to add some dirty hack, and wait for your new feature.

**Comment by liornoy** [comment]
> > Isn't it just adding the flags and piping together with the junit configurations?
> 
> i _can_ do it that way - but the number of cli flags will continue to explode in size!
> 
> i’m wanting to step back and consider the problem of configuration based on usecases i’m seeing. for example sometimes `ginkgo -r` is hampered by the reality that you need to configure one package a bit differently than another (eg “allow more parallel processes for this package - but not for this other package”)
> 
> so i want to introduce the notion of json-based configuration which can live in the repo and support different profiles (eg “when running on CI” vs “when running on my machine” vs “when developing” vs “pre-commit”) - the idea is to make most ginkgo configuration adjustable in these files and to allow you to specify things hierarchically. this would then be a good place to add the more detailed junit report configuration. a single configuration file at the root of your repo would then govern all your packages.

Sounds like a really big sub-project for ginkgo, which can be useful to a lot of users.
