### ISSUE TITLE
Bumping the version of Ginkgo gives go conflicting package error

### ISSUE THREAD

**Issue by Ankitasw** [onsi/ginkgo#1149]
We are currently using ginkgo version 2.8.1 in the [Cluster API Provider for AWS](https://github.com/kubernetes-sigs/cluster-api-provider-aws) project, but tried bumping the version to 2.8.3 and got the below error
```
"Running error: context loading failed: failed to load packages: failed to load with go/packages: internal error: go list gives conflicting information for package sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2 [sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2.test]"
```
Surprisingly this error comes only when we try to bump the version. Otherwise we never get this error in our codebase.
Refer [this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4087) PR for more details.

I see no dependencies changed recently for ginkgo. Has anyone else come across this issue?
Or maybe it's a golang issue?

**Comment by Ankitasw** [comment]
We are also getting similar error when bumping Gingko to v2.8.3 in Cluster API project. https://github.com/kubernetes-sigs/cluster-api/pull/8143

**Comment by onsi** [comment]
hey @Ankitasw - can you try bumping to 2.8.2 to see if the same issue occurs?  2.8.2 introduced a `tools.go` file to force go to also fetch ginkgo's cli dependencies.  2.8.3 then bumped some other dependencies - i'd like to figure out which change is potentially causing this.

**Comment by Ankitasw** [comment]
Thanks for the quick response @onsi 
I tried with 2.8.2, and getting same error. We add ginkgo dependency in our own repo's tools.go but with this bump I even tried to remove it, but still getting the same error.

**Comment by onsi** [comment]
weird ☹️ - my mental model for go modules is not very strong so i'm not sure why this is happening t.  i can try to reproduce this over the weekend to debug it.

for now, some things to explore:

- can you run go mod tidy after updating to 2.8.2 and remind ginkgo from your tools.go file? can you share the go.mod and go.sum before you bump to 2.8.2/fix tools and after?
- is there more to the error you can share?
- does go mod list show anything interesting?

**Comment by Ankitasw** [comment]
> weird ☹️ - my mental model for go modules is not very strong so i'm not sure why this is happening.

I understand, even I don't understand much around it.

> i can try to reproduce this over the weekend to debug it.

Thankyou so much 🙇‍♀️ 

So there are two go.mod file in our repo. One is at the base project level, and another one at /hack/tools where tools.go recide.

> can you run go mod tidy after updating to 2.8.2 and remind ginkgo from your tools.go file? can you share the go.mod and go.sum before you bump to 2.8.2/fix tools and after?

This is the main [go.mod and go.sum](https://gist.github.com/Ankitasw/40e9376b68e84a7171fda3515d55d585) files with v2.8.1. This is the [go.mod and go.sum](https://gist.github.com/Ankitasw/6362e7eb5199b9635e9f48dfb7b46e1b) for tools.go. 
This is the main [go.mod and go.sum](https://gist.github.com/Ankitasw/91dcf1a091fdf12acef62cd1bd877060) files with v2.8.2. This is the [go.mod and go.sum](https://gist.github.com/Ankitasw/5e355ca1207bc9c0f3f79a48d83fcd60) for tools.go after removing ginkgo from tools.go.
I did run go mod tidy on both levels.

> is there more to the error you can share?

There is no more to the error unfortunately 😞 but this error if thrown by golangci-lint only, and not while build.

> does go mod list show anything interesting?

Uhmm.. do you mean go list to check the deps? It gave [this](https://gist.github.com/Ankitasw/9497be3a743ac3df3b218226fee17521) output from which I am not able to make out anything 😕 

Please let me know if you need any other info.

**Comment by Skarlso** [comment]
It's ginkgo's new way of being imported. It messed up the `tools` package chain. An "easy" fix is for golangci-lint not to lint tools. So remove the `tools` build tag.

**Comment by Skarlso** [comment]
Oh, I see, I'm tired so I thought this is the cluster-api issue

Okay, so ginkgo folks, the move to `tools` magic broke the link chain in tools. Maybe it's okay, and we just remove the `tools` build tag from golangci-lint to not lint stuff. But since this is a breaking change in downward products, we would prefer it to happen in a major version instead of a patch version. :)

**Comment by onsi** [comment]
is there anything i can do on my end to unbreak it? i'd sooner roll this back than bump to 3.0!

or to put it differently: do you understand (and can you explain) why this is breaking?

is it because i'm using a `tools` build tag?  if i renamed it to something else (say... `cheesecake`) would this magically work?

**Comment by onsi** [comment]
(which i'd be happy to do if you're up for bumping to a sha so we can see if it helps)

**Comment by onsi** [comment]
in case y'all want to try this - i've dropped the `tools` build tag in favor of `ginkgoclidependencies`

this is on the latest sha:
a8bb39ac52d7e6ec0db819546388a2efaf7cf0dd

please give it at ry and let me know if it fixes this weird linter issue...

**Comment by Skarlso** [comment]
Sorry @onsi it was super late so I went to bad. Most likely the break comes from a circular dependency appearing if both things use the same build tag somehow. I'm not a 100% sure yet why but I suspect it's a combination of things. It would be enough if you dropped it or used a different tag. Something like `#ginkgo` which is more specific to this library. However it's also a question if we should lint tools at all maybe.

I have to figure out some more approaches. Also I'm super thankful for your support! :)

**Comment by onsi** [comment]
no worries and happy to help!

the latest commit sha uses `ginkgoclidependencies` instead of `tools` - if y'all can give it a try next week and confirm that it works i'll cut a new release

**Comment by Skarlso** [comment]
Thanks, great! Will do that!

**Comment by Ankitasw** [comment]
@onsi The changes works fine with above commit sha.
cc @Skarlso

**Comment by Skarlso** [comment]
Fantastic! :)

**Comment by Ankitasw** [comment]
Thanks for pointing in right direction @Skarlso 🙂

**Comment by Skarlso** [comment]
My pleasure. 😊 and thanks @onsi for the rapid responses on this issue. 🙂

**Comment by Ankitasw** [comment]
@onsi Thanks for the quick look at this issue, so could there be a possibility to make a new release with this change by this week?

**Comment by sbueringer** [comment]
Thx folks for investigating this issue!

**Comment by onsi** [comment]
😮‍💨 glad that worked!  should cut a release at some point today.

**Comment by onsi** [comment]
2.8.4 is out now - please take a look and let me know if y'all are set :)

**Comment by Ankitasw** [comment]
Thanks for being so proactive @onsi 🙂

**Comment by sbueringer** [comment]
Look good: https://github.com/kubernetes-sigs/cluster-api/pull/8143

Thx for the quick fix!

**Comment by onsi** [comment]
woot! 🎉
