### ISSUE TITLE
Ginkgo logs Tree Error when infact tested code has paniced.

### ISSUE THREAD

**Issue by Lehp** [onsi/ginkgo#1157]
Hey @onsi 

Somehow when the executed test of my test panics i get the Error as shown in the image.
It shows me the line of the Describe-block in which the panic occured but it does not describe the line of my code which actually failed. 

Is it possible to fix this? I am actually willing to invest time into this. 

![image](https://user-images.githubusercontent.com/40690143/223074965-1a603e3b-895f-4997-9712-8fb95726fe9e.png)

**Comment by onsi** [comment]
hey can you share the source code for the test that is causing this. or pull together a reproducer?

**Comment by Lehp** [comment]
Hey Onsi. I forgore It statement. Sorry for wasting time. Completely overlooked it

**Comment by onsi** [comment]
hey no worries - glad you figured it out!
