### ISSUE TITLE
Merge multiple coverprofile outputs

### ISSUE THREAD

**Issue by segator** [onsi/ginkgo#1160]
I Have some tests that I run in a separate execution with go test and another set of tests with ginkgo I need to merge them so I can import them to sonarQ together.
Is there any option to append instead of override converprofile file?

Thanks!

**Comment by onsi** [comment]
hey @segator - is this still an open issue for you - or was it resolved by the other issue?  in case it's still an issue:

https://github.com/wadey/gocovmerge

is a tool that can merge coverage files for you.

**Comment by segator** [comment]
Thanks!!
