### ISSUE TITLE
Document order of execution for setup nodes on the same level

### ISSUE THREAD

**Issue by Airblader** [onsi/ginkgo#1172]
There currently is documentation for the order of execution of something like

```
Describe("", func() {
	BeforeEach(beforeEach1)

	Describe("", func() {
		BeforeEach(beforeEach2)
	})
})
```

However, I couldn't find any documentation on whether the execution order is defined for nodes on the same level:

```
Describe("", func() {
	BeforeEach(beforeEach1)
	BeforeEach(beforeEach2)
})
```

It would be nice to explicitly document whether Ginkgo makes any guarantees here (and if so, which).

**Comment by onsi** [comment]
hey @Airblader - yes good point.  I'll add updating the docs on this point to my todo list.  There _is_ a guaranteed order - nodes in outer containers always run before inner containers and nodes within the same container **always run in the order in which they are called**.
