### ISSUE TITLE
Confusion about Measure() deprecation.

### ISSUE THREAD

**Issue by geofffranks** [onsi/ginkgo#1176]
We have tests that are emitting `Measure is deprecated and will be removed in Ginkgo V2.  Please migrate to gomega/gmeasure` after upgrading to V2.

However, according to [the v2 docs](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-measure), the functionality was removed and tests aren't even run.

Since v2 was a breaking change from v1, shouldn't `Measure()` instead just cause failures, similar to how other calls to deprecated functionality do? If not, can the message at least be changed from `will be removed in Ginkgo V2` to `has been removed as of Ginkgo V2 and these tests are not being run` or something similar?

**Comment by onsi** [comment]
hey - thanks.  it should say `has been removed as of Ginkgo V2 and these tests are not being run`.  I'll fix that.

I'd like to keep the "deprecation" behavior  in place however, as opposed to failing the test,  as it provides a gentler onramp for folks migrating from V1.

**Comment by onsi** [comment]
i've updated this now.  it'll get released when the next version of Ginkgo gets cut.
