### ISSUE TITLE
Gingko test parallelization: cache sync failure 

### ISSUE THREAD

**Issue by aman98** [onsi/ginkgo#1186]
Hi I am running 3 ginkgo test specs in parallel using `ginkgo -p` command and this is the only error I am getting. There are no other error logs so I am having a hard time debugging this issue. How can I get more information from the logs? 
```
 [FAILED] Unexpected error:
      <*fmt.wrapError | 0xc0010158e0>: 
      failed to wait for caches to sync: timed out waiting for cache to be synced
      {
          msg: "failed to wait for caches to sync: timed out waiting for cache to be synced",
          err: <*errors.errorString | 0xc001034d50>{
              s: "timed out waiting for cache to be synced",
          },
      }
```

**Comment by onsi** [comment]
hey @aman98 - i replied on slack.  i'm going to close this issue in favor of figuring this out on slack as i'm going to need more information to help you and slack might give us a more efficient back and forth.  feel free to reopen with replies to my slack questions if you'd rather have the conversation here.
