### ISSUE TITLE
Junit report in v2.9.2 doesn't generate <system-out> and put all into <system-err>

### ISSUE THREAD

**Issue by cheels** [onsi/ginkgo#1188]
**STR:**

- Try to Run the tests with --junit-report=report.xml
- Check the tests with status="passed" in report.xml and <system-out> tag

**Actual result:**
The output of execution is in `<system-err>` tag, and it causes some tools don't recognize the steps inside because they are located in error tags.

**Expected result:**
The output of execution should be in `<system-out>` tag if it's not the error as it was at least in **v2.1.6**

**Comment by onsi** [comment]
hey there @cheels - unfortunately there isn't a standard JUnit XML format or even widely agreed upon conventions for how to take rich testing data/metadata and shove it into the JUnit format.

we've arrived at Ginkgo's format somewhat organically via feedback from the community (particularly folks in the kubernetes sig-testing community) over time.  while i'm open to some degree of configuration/customization i think it's also fair to say that tooling that doesn't display `system-err` in addition to `system-out` is missing a key part of the JUnit format puzzle.  I'd suggest opening an issue on the tooling you're using to ensure they support `system-err`

**Comment by cheels** [comment]
Hi @onsi, thanks for the answer, but let me explain. The problem is not with the tool we use to parse the report. The issue is that the latest Ginkgo (v2.9.2) put all By("") steps into `<system err>` tag instead of `<system out>`. And I want to say that it's just steps, not an error. The output has 0 relations with errors. The new JUnit report contains ONLY `<system err>` and `<system out>` no longer produces. 

For example, below, you can see the same test but in a different JUnit report generated by different Ginkgo versions.

**Before (v2.1.6):**
 
`        <testcase name="[It] should create Cache Config with correct default values [cache, fast]" classname="Suite OS" status="passed" time="126.683581238">
              <system-out>2023/04/19 18:06:20 INFO : trying to connect to cluster: dev&#xA;2023/04/19 18:06:20 DEBUG: Started the schema invoker&#xA;2023/04/19 18:06:20 DEBUG: authenticate: cluster name: dev; local: [::1]:42238; remote: [::1]:8001; addr: localhost:8001&#xA;2023/04/19 18:06:20 DEBUG: authentication correlation ID: 1&#xA;2023/04/19 18:06:20 DEBUG: cluster.ConnectionManager: checking the cluster: 758ed734-2ac9-413f-a4df-496a6abe09f4, current cluster: &lt;nil&gt;&#xA;2023/04/19 18:06:20 DEBUG: opened connection to: 10.244.2.4:5701&#xA;2023/04/19 18:06:20 INFO : connected to cluster: dev&#xA;2023/04/19 18:06:20 DEBUG: cluster.ConnectionManager.start: waiting for the initial member list&#xA;2023/04/19 18:06:20 DEBUG: 1: members updated: [10.244.1.4:5701:c7560325-f05b-4b62-b2ba-64bf34168327 10.244.2.4:5701:b632b2a2-c536-418e-901e-ebe5b621d633 10.244.3.4:5701:9707a76c-7fc5-4963-9cb3-8f443fb2ca91]&#xA;2023/04/19 18:06:20 INFO : &#xA;&#xA;Members {size:3, ver:3} [&#xA;&#x9;Member 10.244.1.4:5701 - c7560325-f05b-4b62-b2ba-64bf34168327&#xA;&#x9;Member 10.244.2.4:5701 - b632b2a2-c536-418e-901e-ebe5b621d633&#xA;&#x9;Member 10.244.3.4:5701 - 9707a76c-7fc5-4963-9cb3-8f443fb2ca91&#xA;]&#xA;&#xA;2023/04/19 18:06:20 DEBUG: cluster.ConnectionManager.start: received the initial member list&#xA;2023/04/19 18:06:20 DEBUG: invocation.Service: enabled non-urgent invocations&#xA;2023/04/19 18:06:20 DEBUG: Stopped the schema invoker&#xA;&#xA;Report Entries:&#xA;By Step&#xA;/home/runner/work/operator/operator/test/e2e/custom_resource_test.go:57&#xA;2023-04-19T18:04:15.78196317Z&#xA;&amp;{Text:setting the label and CR with name &#39;hch-2-k3k7x7&#39; Duration:0s}&#xA;--&#xA;CR_ID:hch-2-k3k7x7&#xA;/home/runner/work/operator/operator/test/e2e/custom_resource_test.go:76&#xA;2023-04-19T18:04:15.782287075Z&#xA;--&#xA;By Step&#xA;/home/runner/work/operator/operator/test/e2e/helpers_test.go:113&#xA;2023-04-19T18:04:15.782290475Z&#xA;&amp;{Text:creating H CR Duration:43.283833ms}&#xA;--&#xA;By Step&#xA;/home/runner/work/operator/operator/test/e2e/helpers_test.go:118&#xA;2023-04-19T18:04:15.825575208Z&#xA;&amp;{Text:checking H CR running Duration:1m55.682954905s}&#xA;--&#xA;By Step&#xA;/home/runner/work/operator/operator/test/e2e/H_cache_test.go:55&#xA;2023-04-19T18:06:11.508531313Z&#xA;&amp;{Text:creating the default cache config Duration:0s}&#xA;--&#xA;By Step&#xA;/home/runner/work/operator/operator/test/e2e/helpers_test.go:787&#xA;2023-04-19T18:06:11.597779746Z&#xA;&amp;{Text:waiting for  CR status Duration:9.006581472s}&#xA;--&#xA;By Step&#xA;/home/runner/work/operator/operator/test/e2e/H_cache_test.go:60&#xA;2023-04-19T18:06:20.604362418Z&#xA;&amp;{Text:checking if the cache config is created correctly Duration:0s}&#xA;--&#xA;By Step&#xA;/home/runner/work/operator/operator/test/e2e/client_port_forward_test.go:73&#xA;2023-04-19T18:06:20.604469119Z&#xA;&amp;{Text:Getting the member config with lookup name &#39;hch-2-k3k7x7&#39; Duration:243.962211ms}&#xA;--&#xA;By Step&#xA;/home/runner/work/operator/operator/test/e2e/helpers_test.go:565&#xA;2023-04-19T18:06:20.623570986Z&#xA;&amp;{Text:creating H client using address &#39;localhost:8001&#39; Duration:12.075469ms}&#xA;</system-out>
              <system-err>�[1mSTEP:�[0m setting the label and CR with name &#39;hch-2-k3k7x7&#39; �[38;5;243m04/19/23 18:04:15.781�[0m&#xA;�[1mSTEP:�[0m creating H CR �[38;5;243m04/19/23 18:04:15.782�[0m&#xA;�[1mSTEP:�[0m checking H CR running �[38;5;243m04/19/23 18:04:15.825�[0m&#xA;�[1mSTEP:�[0m creating the default cache config �[38;5;243m04/19/23 18:06:11.508�[0m&#xA;�[1mSTEP:�[0m waiting for  CR status �[38;5;243m04/19/23 18:06:11.597�[0m&#xA;�[1mSTEP:�[0m checking if the cache config is created correctly �[38;5;243m04/19/23 18:06:20.604�[0m&#xA;�[1mSTEP:�[0m Getting the member config with lookup name &#39;hch-2-k3k7x7&#39; �[38;5;243m04/19/23 18:06:20.604�[0m&#xA;�[1mSTEP:�[0m creating H client using address &#39;localhost:8001&#39; �[38;5;243m04/19/23 18:06:20.623�[0m&#xA;Aftereach start time is 2023-04-19 18:06:20.849300242 +0000 UTC m=+162.004178066&#xA;Aftereach end time is 2023-04-19 18:06:22.465495708 +0000 UTC m=+163.620373532&#xA;</system-err>
          </testcase>`
          
**After (v2.9.2):**
`                <testcase name="[It] should create Cache Config with correct default values [cache, fast]" classname="Suite OS" status="passed" time="42.212259831">
              <system-err>&gt; Enter [BeforeEach] H Cache Config - /home/runner/work/operator/operator/test/e2e/H_cache_test.go:19 @ 04/18/23 21:48:54.115&#xA;&lt; Exit [BeforeEach] H Cache Config - /home/runner/work/operator/operator/test/e2e/H_cache_test.go:19 @ 04/18/23 21:48:54.115 (0s)&#xA;&gt; Enter [It] should create Cache Config with correct default values - /home/runner/work/operator/operator/test/e2e/H_cache_test.go:50 @ 04/18/23 21:48:54.115&#xA;STEP: setting the label and CR with name &#39;hch-2-yorvxl&#39; - /home/runner/work/operator/operator/test/e2e/custom_resource_test.go:57 @ 04/18/23 21:48:54.115&#xA;CR_ID:hch-2-yorvxl - /home/runner/work/operator/operator/test/e2e/custom_resource_test.go:76 @ 04/18/23 21:48:54.115&#xA;STEP: creating H CR - /home/runner/work/operator/operator/test/e2e/helpers_test.go:113 @ 04/18/23 21:48:54.115&#xA;END STEP: creating H CR - /home/runner/work/operator/operator/test/e2e/helpers_test.go:113 @ 04/18/23 21:48:54.124 (9ms)&#xA;STEP: checking H CR running - /home/runner/work/operator/operator/test/e2e/helpers_test.go:118 @ 04/18/23 21:48:54.124&#xA;END STEP: checking H CR running - /home/runner/work/operator/operator/test/e2e/helpers_test.go:118 @ 04/18/23 21:49:30.077 (35.953s)&#xA;STEP: creating the default cache config - /home/runner/work/operator/operator/test/e2e/H_cache_test.go:55 @ 04/18/23 21:49:30.077&#xA;STEP: waiting for  CR status - /home/runner/work/operator/operator/test/e2e/helpers_test.go:787 @ 04/18/23 21:49:30.084&#xA;END STEP: waiting for  CR status - /home/runner/work/operator/operator/test/e2e/helpers_test.go:787 @ 04/18/23 21:49:34.494 (4.41s)&#xA;STEP: checking if the cache config is created correctly - /home/runner/work/operator/operator/test/e2e/H_cache_test.go:60 @ 04/18/23 21:49:34.494&#xA;STEP: Getting the member config with lookup name &#39;hch-2-yorvxl&#39; - /home/runner/work/operator/operator/test/e2e/client_port_forward_test.go:73 @ 04/18/23 21:49:34.494&#xA;STEP: creating H client using address &#39;localhost:8003&#39; - /home/runner/work/operator/operator/test/e2e/helpers_test.go:565 @ 04/18/23 21:49:34.511&#xA;END STEP: creating H client using address &#39;localhost:8003&#39; - /home/runner/work/operator/operator/test/e2e/helpers_test.go:565 @ 04/18/23 21:49:34.523 (12ms)&#xA;END STEP: Getting the member config with lookup name &#39;hch-2-yorvxl&#39; - /home/runner/work/operator/operator/test/e2e/client_port_forward_test.go:73 @ 04/18/23 21:49:34.679 (184ms)&#xA;&lt; Exit [It] should create Cache Config with correct default values - /home/runner/work/operator/operator/test/e2e/H_cache_test.go:50 @ 04/18/23 21:49:34.68 (40.564s)&#xA;&gt; Enter [AfterEach] H Cache Config - /home/runner/work/operator/operator/test/e2e/H_cache_test.go:28 @ 04/18/23 21:49:34.68&#xA;Aftereach start time is 2023-04-18 21:49:34.680462594 +0000 UTC m=+170.935156528&#xA;Aftereach end time is 2023-04-18 21:49:36.32814228 +0000 UTC m=+172.582836114&#xA;&lt; Exit [AfterEach] H Cache Config - /home/runner/work/operator/operator/test/e2e/H_cache_test.go:28 @ 04/18/23 21:49:36.328 (1.648s)&#xA;</system-err>
          </testcase>`
          
As you can see, all steps are in `<system err>`, but the test passed, and no reason to put the data into error and no reason to don't create a system out tags.
Is it expected behavior?

**Comment by onsi** [comment]
hi, yes - this is the expected behavior.  as i mentioned, there isn't really a structured way to capture arbitrary metadata information in the JUnit format.  The latest versions of Ginkgo generate a _timeline_ of behavior for the spec that includes all By steps in addition to other useful pieces of information.  There isn't a natural place to put this in the JUnit format so I went with <system err> - the idea being that this was more detailed  _debug_ information.  Whether the spec passes or not has no bearing on where the data goes.
