### ISSUE TITLE
Apply `ContinueOnFailure` to nested `Ordered` test containers

### ISSUE THREAD

**Issue by Kavinjsir** [onsi/ginkgo#1201]
We are having an `Ordered` test context which is wrapped in another `Ordered` test context. For instance:

```go

var _ = Describe("Books", func() {
	Context("Buy books", Ordered, func() {
		It("Should have available book items", func() {
			Expect(1).To(BeTrue())
		})

		It("Should have books in cart", func() {
			Expect(1).To(BeTrue())
		})

		Context("Should be able to run the buy flow", Ordered, ContinueOnFailure, func() {
			It("Should be able to add book to cart", func() {
				Expect(1).To(BeTrue())
			})
			It("Should be able to update book in cart", func() {
				Expect(1).To(BeTrue())
			})
			It("Should be able to delete book in cart", func() {
				Expect(1).To(BeTrue())
			})
		})
	})
})
```

In the inner context, we'd like to introduce `ContinueOnFailure` since the test specs inside are individual.
However, such usage is not allowed since `ContinueOnFailure` only applies to the outmost ordered context.

So to sum up my scenario: we'd run a series of tests that are restrictedly ordered, while there are some nested ones inside that are logically ordered but can be executed individually.
Wondering if it is possible to achieve that?

**Comment by onsi** [comment]
hey @Kavinjsir - sorry that isn't possible right now and it's not something I'm super eager to add as the `Ordered` code is getting super complex.

It's a bit of a hack but you can do something like this for now, instead:

```go
var _ = Describe("Books", func() {
	Context("Buy books", Ordered, func() {
                var setupComplete bool
		It("Should have available book items", func() {
			Expect(1).To(BeTrue())
		})

		It("Should have books in cart", func() {
			Expect(1).To(BeTrue())
                        setupComplete = true
		})

		Context("Should be able to run the buy flow", Ordered, ContinueOnFailure, func() {
                        BeforeEach(func() {
                             Expect(setupComplete).To(BeTrue(), "setup failed - failing the remaining tests")
                        })
			It("Should be able to add book to cart", func() {
				Expect(1).To(BeTrue())
			})
			It("Should be able to update book in cart", func() {
				Expect(1).To(BeTrue())
			})
			It("Should be able to delete book in cart", func() {
				Expect(1).To(BeTrue())
			})
		})
	})
})
```

**Comment by Kavinjsir** [comment]
Hey, @onsi Thx for the prompt reply! I can totally understand this might be a minor case and imagine the complicated logic for implementation.

And I'd appreciate you providing such a pattern to help with my case!

(don't have to say 'sry', really appreciate your contribution to bringing such an amazing testing framework!)

**Comment by onsi** [comment]
❤️ thanks @Kavinjsir !
