### ISSUE TITLE
ginkgo CLI parsing error when empty string given in bash script.

### ISSUE THREAD

**Issue by dschveninger** [onsi/ginkgo#1205]
When running the following ginkgo CLI in a bash script
```
#!/bin/bash
set -eux
set -Eo pipefail
# This will allow local runner to set values lie --v, --vv, --show-node-events, or --succinct
# This does not support null or nil value since it will cause issues if the value is ""
GINKGO_VERBOSITY=$1

ginkgo \
  --json-report dummy.json \
  --junit-report dummy.xml \
  "${GINKGO_VERBOSITY}" \
  --no-color \
  --timeout "30m" \
  .
```
The following execution ``` ./issue_test.sh ""``` fails to parse and drops the 
```
 --no-color \
  --timeout "30m" \
```
But ```./issue_test.sh "--v"``` works.

Running ginkgo 2.9.5

**Comment by dschveninger** [comment]
FYI this works
```
#!/bin/bash
set -eux
set -Eo pipefail
# This will allow local runner to set values lie --v, --vv, --show-node-events, or --succinct
# This does not support null or nil value since it will cause issues if the value is ""
GINKGO_VERBOSITY=$1

# GINKGO_TIMEOUT is the overall timeout needed for execution of ginkgo for all the suites.
# Currently calculating this timeout based on "COLLECT_TIMEOUT" because the upgrade mode
# implementation is tightly coupled with "COLLECT_TIMEOUT".
# COLLECT_TIMEOUT by default is 20 minutes. Adding 150 minutes so both HAKS and VM Scenario
# can run appropriately, ideally we should never hit "GINKGO_TIMEOUT" as timeouts are baked in
# different places of execution so we would want to keep the "GINKGO_TIMEOUT" high.
# DEPLOY - Run the setup and inject suites
ginkgo \
  --json-report dummy.json \
  "${GINKGO_VERBOSITY}" \
  --junit-report dummy.xml \
  --no-color \
  --timeout "30m" \
  .```

**Comment by onsi** [comment]
hey @dschveninger I think this is a bash issue?  `./issue_test.sh ""` passes in an empty argument which causes Go's standard flag parsing library (which Ginkgo uses) to stop parsing flags and interpret `""` as the first non-flag argument (in Ginkgo's case, this is interpreted as the path to the suite you'd like to test).  i'm not sure why the second example would work and not the first... `json-report` and `junit-report` are basically interpreted identically.

I think the fix will look like changing the script - but my bash isn't strong enough to be able to tell you how 😞

**Comment by dschveninger** [comment]
I was just about to post that my second post was wrong, or delete it, sorry for that.
the bash script end up trying to execute
```
ginkgo --json-report dummy.json '' --junit-report dummy.xml --no-color --timeout 30m .
```
and you are right that the ginkgo code see ```''``` as the end of the flags and ignores the rest of the flags.

I was trying to figure out how to add this as a test case.

Our issue is we have a script that run many different suites and we default --vv in the script for our pipelines.  But when we run locally we want to turn off all of the output and we are trying to replace the default --vv with ''

**Comment by dschveninger** [comment]
I will handle this in bash
