### ISSUE TITLE
Error Installing Ginkgo CLI

### ISSUE THREAD

**Issue by rodlemus** [onsi/ginkgo#1209]
go version 1.20
OS: "Ubuntu 22.04.2 LTS"

go install github.com/onsi/ginkgo/v2/ginkgo@v2.9.5
go get github.com/onsi/gomega/...

terminal output: 
```
go: downloading github.com/onsi/ginkgo/v2 v2.9.5
go: downloading golang.org/x/tools v0.9.1
go: downloading github.com/go-task/slim-sprig v0.0.0-20230315185526-52ccab3ef572
go: downloading github.com/google/pprof v0.0.0-20210407192527-94a9f03dee38
\# github.com/onsi/ginkgo/v2/ginkgo
IBAo8dA#ov`Q@i9=}U      3: dwarf: type name doesn't start with "type:"
sym 72513: relocation target go:info.func() (uint32, error) not defined
go: downloading github.com/onsi/gomega v1.27.7
go: downloading github.com/golang/protobuf v1.5.3
go: downloading github.com/google/go-cmp v0.5.9
go: downloading golang.org/x/net v0.10.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading google.golang.org/protobuf v1.28.1
go: downloading golang.org/x/text v0.9.0
```

terminal command: ginkgo version
`
zsh: command not found: ginkgo`

my .zshrc
```

export PATH=$PATH:/usr/bin
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$GOBIN

```

I Don't have problems when i code, i can import Describe, BeforeEach, etc. The problem is that i can't not* run my tests.

**Comment by onsi** [comment]
Hey there @rodlemus 

I suspect there's some sort of path issue here.  Here are some thoughts on how to proceed/debug this:

First, I've never seen this error before:

```
\# github.com/onsi/ginkgo/v2/ginkgo
IBAo8dA#ov`Q@i9=}U      3: dwarf: type name doesn't start with "type:"
sym 72513: relocation target go:info.func() (uint32, error) not defined
```

to make sure things are actually compiling can you try `go run github.com/onsi/ginkgo/v2/ginkgo` this should compile and run the cli and should not be susceptible to any path issues.

Assuming that works my best guess is there's something awry with your path setup.  If you create your own go package with a `main.go` and then run `go install` where does go put your executable?  Are you then able to invoke it by name (i.e. is it on your path)?

**Comment by rodlemus** [comment]
Sorry I read it too late, I uninstalled and reinstalled golang and after that, it worked without errors
