### ISSUE TITLE
Ginkgo 2.0 Migration cannot install ginkgo cli

### ISSUE THREAD

**Issue by jackmbuda** [onsi/ginkgo#1228]
I am trying to migrate a repo to use v2 and I cannot get cli to install on my mac. This is my go version `go version go1.18.10 darwin/arm64` and running ginkgo version outputs `zsh: command not found: ginkgo` Could I get some advice or guidance? TY in advance.

**Comment by onsi** [comment]
how are you installing the cli?  in general if you have `go.mod` file then `go install github.com/onsi/ginkgo/v2/ginkgo`  should succesfully install Ginkgo in `$GOBIN` which you should ensure is on your `$PATH`

**Comment by jackmbuda** [comment]
Thanks that was my issue. My $PATH lacked my $GOPATH. I will be closing this issue.
