### ISSUE TITLE
ginkgo v2 ignores flags when using TestMain

### ISSUE THREAD

**Issue by johnnycxm** [onsi/ginkgo#1233]
I have a project like this:
test\\
    e2e.go
    e2e_test.go
    case1.go
    case2.go
    ....
when I trying to run tests by cli: ginkgo --label-filter=XXX --focus=XXX. Any flags I passing after ginkgo command not working, it seems just ignored. Almost every flags of ginkgo cli I'v tried, even -vv is not working
here is code in e2e_test.go:
```go
package test
import (
	"flag"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	flag.StringVar(&MyFlag, "myflag", "default",
		"myflag arg")
        flag.Parse()
	os.Exit(m.Run())
}

func TestE2E(t *testing.T) {
	RunE2ETests(t)
}
```

and code in e2e.go

```go
package test

import (
	"testing"

	"github.com/onsi/ginkgo/v2"
	"github.com/onsi/gomega"
)

func RunE2ETests(t *testing.T) {
	gomega.RegisterFailHandler(ginkgo.Fail)
	ginkgo.RunSpecs(t, "e2e suite")
}
```

**Comment by onsi** [comment]
hey there - first I'd encourage you to put all the test fils in the test package by giving them a name that ends in `_test.go` - what you're doing works but it can get a bit confusing.

As for flags - please follow the pattern established here:

https://onsi.github.io/ginkgo/#supporting-custom-configuration-custom-command-line-flags

I don't generally use `TestMain` and the pattern outlined above is the tested and supported pattern for passing custom flags into a Ginkgo suite.

**Comment by onsi** [comment]
hey - try it without calling flag.Parse

**Comment by johnnycxm** [comment]
> 

@onsi Thank you, this works for me!

**Comment by tnozicka** [comment]
I've had a similar issue using `TestMain` calling flag.Parse - took a while to figure out I needed to add a dummy include on ginkgo to fix the init order so ginkgo flags are initialize early. My custom flags are parsed using `github.com/spf13/cobra`.

```golang
include (
    _ "github.com/onsi/ginkgo/v2" // ginkgo flags need to be registered before the first flag.Parse (otherwise it silently passes with default values)
)
```

Kubernetes also uses a similar pattern
https://github.com/kubernetes/kubernetes/blob/bae4122f56fa3bd2738baa33fd9f46e5dd9cee4d/test/e2e/e2e_test.go#L80
https://github.com/kubernetes/kubernetes/blob/bae4122f56fa3bd2738baa33fd9f46e5dd9cee4d/test/e2e/e2e_test.go#L89
(It actually needs a few functions like `ginkgo.ReportAfterEach` so it naturally has that import.)

Maybe this helps someone stumbling into this issue.
