### ISSUE TITLE
GinkgoT doenst behave like expected

### ISSUE THREAD

**Issue by c0ffee** [onsi/ginkgo#1261]
I am trying to get Ginkgo running in co,bination with some other testhelpers. According to the documentation I would expect the following should work:
```
package main

import (
	"testing"

	. "github.com/onsi/ginkgo/v2"
)

func main() {
	blub(GinkgoT())
}

func blub(t *testing.T) {

}
```

`./prog.go:12:7: cannot use GinkgoT() (value of type ginkgo.FullGinkgoTInterface) as *testing.T value in argument to blub`

Am I missing something?
Thanks in advance!

**Comment by c0ffee** [comment]
onsi thank you for your reply, yeh i digged deeper into it and realized i was way to naiv :s

I adapted my own functions to use an interface but at the end I have to call
https://github.com/hashicorp/vault/blob/5374b3b046d13d3e7a9f6833efcaeff0e49fddc4/sdk/helper/testcluster/docker/environment.go#L398

and they are not using an interface either. so this fails at the end too

**Comment by onsi** [comment]
yep you’ll have to open an issue there.  i’ve seen the hasicorp/vault team be fairly responsive to this exact request in the past though so hopefully it won’t be too tricky to get worked on!

**Comment by c0ffee** [comment]
ok lets close this here then, but for sure the next one who will stumple over it will find at least the issue ;)
