### ISSUE TITLE
Does the eventually matcher support this usage?

### ISSUE THREAD

**Issue by myzhan** [onsi/ginkgo#1274]
I write a testcase like this, and expect it to pass. But it's not.

```go
a := false
go func() {
	a = true
}()
Eventually(a).Should(BeTrue())
```

Until I rewrite it like this.

```go
a := int32(0)
go func() {
	atomic.StoreInt32(&callbackCalled, 1)
}()
Eventually(func() int32 { return atomic.LoadInt32(&a) }).Should(BeEquivalentTo(1))
```

**Comment by onsi** [comment]
in the first example you are passing `a` by value so a copy of its contents is made.  in the second example the function closure captures `a`.  you could replace `a` with a pointer in the first example but you shouldn’t do that as it will trigger the race detector.  your second example is the way to go (alternatively you can use channels)

**Comment by myzhan** [comment]
Ah, now I see, thanks.
