### ISSUE TITLE
How do I specify the build path when I use `ginkgo build` ?

### ISSUE THREAD

**Issue by zc2638** [onsi/ginkgo#1288]
Run `ginkgo build test/e2e`

Actual:
will be generated at `test/e2e/e2e.test`

Expect:
I can specify the build path

**Comment by onsi** [comment]
hey there,

you can't specify a different output path.  you can use `go test -c` with `-o` if you'd like to specify the output path - ginkgo build simply uses that under the hood.

**Comment by zc2638** [comment]
Thanks, I got what I expected using `go test -c <Package Path> -o <Output Path>`
