### ISSUE TITLE
Multiple suites in one package? 

### ISSUE THREAD

**Issue by t3hmrman** [onsi/ginkgo#130]
Is this possible? 

I may just be mistaken on how I should be structuring my Go, but I have a project that looks like this

a/
|------a.go
|------a_suite_test.go
|------a_test.go
|------b.go

I'd lke to have a suite that ONLY tests the functionality in B (and requires different setup/teardown from tests in A)

Is this possible? I've read the docs up and down and it seems like multiple suites are possible, but I have no idea the axiomatic ginkgo way to do it. Maybe it's really obvious and I just missed it.

**Comment by timothysc** [comment]
@onsi 
So this would be a nice RFE, b/c if you have testing infra libraries across multiple repos this behavior would be useful for extensiblity. 

/cc @jayunit100

**Comment by nabbas-ca** [comment]
I want to write k8s controller/operator tests within 2 suites, one with envtest controlller manager initialized and listening, and one without. So I can have finegrained negative path testing. For example, I want to to be able to setup a mock k8s api with bad CRs(before the webhook is alive or registered), and see how my controller reacts to correct it , as unit tests. 

This way, I can setup a set of suites, within the same package like this:

1- clean controller, no CRs preloaded
2- preloaded good CRs, setup controller after the CRs are created
3- preloaded bad CRs, setup controller after the CRs are created
.....

Is that possible? remember that envTest is expensive to start. making a BeforeEach at top level of tests that includes manager start, could be possiblle, but it means starting and stopping manager for every test.

**Comment by onsi** [comment]
hey @nabbas-ca I've opened a new issue [here](#1108) to track this.
