### ISSUE TITLE
[Bug] File Handler Leak

### ISSUE THREAD

**Issue by stasos24** [onsi/ginkgo#1308]
In case of error at line:
https://github.com/onsi/ginkgo/blob/3b2a2a7e74069d66b0f64922afd3426a6167dd3c/reporters/json_report.go#L23
Handler:
https://github.com/onsi/ginkgo/blob/3b2a2a7e74069d66b0f64922afd3426a6167dd3c/reporters/json_report.go#L17
won't be freed on
https://github.com/onsi/ginkgo/blob/3b2a2a7e74069d66b0f64922afd3426a6167dd3c/reporters/json_report.go#L27
Solution: 
Replace -  return f.Close() with return 0
Add defer f.Close at line 20

**Comment by stasos24** [comment]
In case of error at:
https://github.com/onsi/ginkgo/blob/3b2a2a7e74069d66b0f64922afd3426a6167dd3c/reporters/json_report.go#L62
Handler:
https://github.com/onsi/ginkgo/blob/3b2a2a7e74069d66b0f64922afd3426a6167dd3c/reporters/json_report.go#L56
won't be freed on:
https://github.com/onsi/ginkgo/blob/3b2a2a7e74069d66b0f64922afd3426a6167dd3c/reporters/json_report.go#L64

**Comment by onsi** [comment]
hey there - thanks for catching for this.  can you submit a PR?
