### ISSUE TITLE
Feature request:  `BeforeGroup`/`AfterGroup`

### ISSUE THREAD

**Issue by tsaleh** [onsi/ginkgo#133]
I'd like to have `Foo` run *once*, before all of the tests in a single Describe group.  Unlike with `BeforeSuite`, I *don't* want `Foo` to run if I'm not running any examples in that particular group.

For example:

```
var _ = Describe("Global", func() {
	BeforeSuite(func() { Foo() })

	Describe("Group 1", func() {
		It("one")
	})

	Describe("Group 2", func() {
		It("two")
	})
})
```

Works fine, until you focus on "two" - `Foo` is still executed.  I'd like something like:

```
var _ = Describe("Global", func() {
	Describe("Group 1", func() {
		BeforeSuite(func() { Foo() })

		It("one")
	})

	Describe("Group 2", func() {
		It("two")
	})
})
```

...where `Foo` is only executed if an example inside "Group 1" is being run.  `Foo` won't be executed if I focus on example "two".

**Comment by onsi** [comment]
This has come up before:
https://github.com/onsi/ginkgo/issues/70

And I've shared my thoughts on that thread.  tl;dr this kind of shared state smells like test pollution and isn't something I want to make easy.

You could always do:

```
var BeforeGroup = func(body func(), timeout ...float64) bool {
    once := &sync.Once{}
    BeforeEach(func() {
        once.Do(body)
    }, timeout...)
}
```

and ditto for `AfterGroup`.
