### ISSUE TITLE
GinkoT().Error[f]: record error instead of aborting the test

### ISSUE THREAD

**Issue by pohly** [onsi/ginkgo#1331]
Ginkgo is built around the assumption that all failed assertions are fatal, i.e. testing must stop. This has the effect that `GinkgoT().Error` and `GinkgoT().Errorf` behave like `GinkgoT().Fatal[f]`.

It would be nice to support the normal `testing.T` semantic and not abort the test.

Alternatively (or perhaps as a interim solution) this limitation should at least get documented.

**Comment by onsi** [comment]
I'll document it - but don't have plans to change the behavior of `Fail()`.

**Comment by pohly** [comment]
`Fail` shouldn't change. It's `GinkgoT().Error` error which is currently a bit odd. But not changing it is fine.
