### ISSUE TITLE
Cannot use cgo

### ISSUE THREAD

**Issue by glyn** [onsi/ginkgo#135]
It appears that we can't use cgo in a test package with Ginkgo. The failure is as follows:
```
$ ginkgo .
Failed to compile cgo_ginkgo:

can't load package: package github.com/cloudfoundry-incubator/garden-linux/cgo_ginkgo: use of cgo in test /Users/gnormington/go/src/github.com/cloudfoundry-incubator/garden-linux/cgo_ginkgo/use_cgo_test.go not supported

Ginkgo ran 1 suite in 50.57228ms
Test Suite Failed
```

If cgo is not supported, please could this be mentioned in the documentation. Better still, can it be supported? :-)

**Comment by glyn** [comment]
Testcase is in [this gist](https://gist.github.com/glyn/33fd0e9759d047002008).

**Comment by onsi** [comment]
Hmm this is likely a go test issue.  Perhaps there's a flag to go test that
I need to expose. Will take a look.

**Comment by onsi** [comment]
Looks like golang doesn't support importing "C" in _test files:
https://github.com/golang/go/issues/4030

**Comment by glyn** [comment]
Wow! Thanks Onsi.
