### ISSUE TITLE
Get coverage from ginkgo

### ISSUE THREAD

**Issue by fabulias** [onsi/ginkgo#1356]
I have a suit of tests which run fine if I run 

`go test ./app/tests/...`

usually when I've used `go test` is straightforward to get the coverage of my tests but I'm trying to get the coverage now using `ginkgo` and I can't no matter what.

could you help to get the coverage of my folder `./app/tests` using `go test` instead of the `ginkgo` binary?

just to clarify, I have my tests made with `ginkgo`, and if I run `go test ./app/tests/...` tests run fine, but when I try to get the coverage my problem is born.

**Comment by djbeaumont** [comment]
@fabulias did you find how to get coverage reports for ginkgo tests when invoking using `go test -coverprofile=...`?
