### ISSUE TITLE
Feature Request: Log method to suppliment By

### ISSUE THREAD

**Issue by rrati** [onsi/ginkgo#138]
Ginkgo provides the By method to separate specs into steps, and it prefaces of all strings sent to the By method with STEP in the output.  There are times when you want to provide output on a progress of a step and you want that output to go through the GinkgoWriter.  You can use By for all logging, but that makes figuring out what was happening in a step cumbersome as everything is logged as a step.  For example:

STEP: Waiting for a to change to state z
a is in state x
a changed to y
a changed to z

In such a case it is helpful to know not only what step the test is in when it fails, but also where in the step it failed.

**Comment by onsi** [comment]
You could just

```
fmt.Fprintln(GinkgoWriter, "...")
```

I'd rather not add `Log` to the top level namespace and I think the GinkgoWriter gives you enough flexibility around this usecase.

**Comment by rrati** [comment]
fmt.Fprintln(GinkgoWriter, "...") doesn't feel very clean to me and isn't all the obvious.  What's the issue with adding a Log method to the top level namespace?

**Comment by onsi** [comment]
Since Ginkgo is imported into the global namespace I need to be very careful when I add new methods.  `Log` is very generic and is likely to collide with something somewhere.

But, really, the whole point of `GinkgoWriter` is that it's an `io.Writer` that you can use all over the place.  You can easily define your own `Log` method in the suite setup file, or you could use Golang's  [log library](http://golang.org/pkg/log/#New) and pass it in the `GinkgoWriter`.

**Comment by rrati** [comment]
I wasn't intending that the method specifically be called Log because that is definitely too generic. :)

It's certainly possible to define a log method in the test suite as you suggest, but at some point if that is common practice for using ginkgo then it would make sense to have a high level api call for that type of functionality.  I can see a lot of use for a native log function in Ginkgo, but I can also see that a test suite would want to roll their own on top of GinkgoWriter.

Having a wrapper at a test suite level kind of hides the native Ginkgo methods.  That can be good or bad depending on your point of view.  It also creates a non-standard API for people familiar with Ginkgo.  Project A has a wrapper called Y, Project B has a wrapper called Z, Project C has no wrapper.  While that is somewhat a project specific issue an argument can be made that such a fundamental part of the suite, logging, should be constant.

**Comment by rrati** [comment]
@onsi Any update on this?  The request came from the kubernetes project.  We've implemented a wrapper to do this functionality using the GinkgoWriter but a 1st class supported method would be better

**Comment by onsi** [comment]
I think implementing a wrapper is the right approach here.  The `GinkgoWriter` gives you a flexible abstraction and I'd really rather avoid adding more to the top-level namespace than is strictly necessary (in fact, I'm not even convinced that `By` is strictly necessary...).

But it sounds like y'all would really like this -- can we think of a better name than `Log`?

**Comment by onsi** [comment]
What did y'all call the helper you wrote?

**Comment by rrati** [comment]
We called the wrapper Logf:

func Logf(format string, a ...interface{}) {
        fmt.Fprintf(GinkgoWriter, "INFO: "+format+"\n", a...)
}

We have a similar one called Failf that wraps Fail with an embedded fmt.Sprintf so we can provide sprintf-like strings and variables for a Fail invocation.  Having Fail and By accept and sprintf-like strings would be a nice enhancement as well, but that's a different request. :)

**Comment by robdimsdale** [comment]
@rrati it's been a while since the last comment in this conversation. How are you getting on with your `Logf` function? Is it something you want to submit a PR for?

**Comment by onsi** [comment]
Closing this out for now.  Please open it up again if you'd like to discuss.
