### ISSUE TITLE
Add cli flag to fail when no tests were run

### ISSUE THREAD

**Issue by grosser** [onsi/ginkgo#1394]
Problem: we run our tests with user-defined labels, but if the user typos then no tests run
Solution: add a `--fail-when-no-tests` or similar command that fails when no test was run
Workaround: we do some grep hackery which is not great

**Comment by onsi** [comment]
makes sense, i can add this to the backlog.  not sure when i'll get to it but let me know if you're interested in working on a PR and I can point you at the right places to make changes.
