### ISSUE TITLE
Feature request: HTML reporter

### ISSUE THREAD

**Issue by abourget** [onsi/ginkgo#141]
It would be very handy to have a simple HTML reporter.  Anyone wrote one somewhere ?

thanks!

**Comment by onsi** [comment]
Not that I'm aware of, no.  Should be fairly easy though I think more useful would be a generic JSON output format that one could build tooling on top of for visualization.

**Comment by Pushplaybang** [comment]
@abourget you should be able to use goconvey

**Comment by Br3nda** [comment]
for those that land here and want to get a HTML report from your ginkgo tests, the magic command is:

```
go test ./... -json | go-test-report
```

you'll need to install https://github.com/vakenbolt/go-test-report

**Comment by aasasi** [comment]
Hi @Br3nda ,
Have you had success using go-test-report  for GINKGO tests? Can `| go-test-report` be used with the `ginkgo` command?
I tried using this as you mentioned above, but it does not seem to recognize each spec. Any guidance on this is greatly appreciated.

**Comment by Br3nda** [comment]
@[aasasi](https://github.com/aasasi) alas no. it sees each package as one test - it doesn't see each spec as it's own test.

however, this issue claims we can get json out put from ginkgo V2.
https://github.com/onsi/ginkgo/issues/639

**Comment by onsi** [comment]
building out an html reporter for ginkgo would be super fun.  it hasn't been a priority for a while but with the new json format it wouldn't be too hard to implement something fairly feature rich.

it's a project i'd like to take on at some point.  i generally just use the console so this is a nice-to-have for me but i'd love to hear what kinds of usecases folks have in mind.  the most compelling one to me would be to be able to visualize and explore a failed CI test run in a browser after-the-fact.  but curious what others think.  i'd love to wrap my head around questions like enabling real-time browser updates vs a static page after the test runs (kinda how the pprof toolchain works).  is there value in running specs from the browser?  watching specs (ie `ginkgo watch`) from the browser?

**Comment by onsi** [comment]
and one more clarification - the json format i'm reporting to is Ginkgo's own json format, not the go test json format.

**Comment by aasasi** [comment]
Thanks @onsi ! As you mentioned, I would like to be able to visualize a summary of the test run and be able to drill down to the steps of each test for debugging . I have always loved the karate/cucumber test report , and I believe that something of that sort would be super helpful. With the current test logs, it is not super easy for folks who are not working on the tests to actually debug.

**Comment by Mo0rBy** [comment]
I see this issue is closed but I would like to +1 it.
Other GO html reporters that work with the `go test` command see each package as a test rather than the individual Ginkgo specs, so they are unusable with Ginkgo (I've only looked at `go-test-report` and `goconvey` so far)
