### ISSUE TITLE
Shared example patterns

### ISSUE THREAD

**Issue by binarylogic** [onsi/ginkgo#145]
This probably isn't a real issue and might be a noob question, but I can't for the life of me dot import the parent package as described in the [shared examples](http://onsi.github.io/ginkgo/#shared-example-patterns) section of the docs. I get a package not found error. It works find in the test file under the main package. I did place the `sharedexamples` package in it's own folder. Am I missing something basic here? Thanks for your help.

**Comment by onsi** [comment]
can you share some code?

it's posible you placed the `sharedexamples` package in a `_test` package:

`package sharedexamples_test`

if you did, in fact do this, then any definitions in the package will actually not be exported (as they are in the magical `_test` package)

**Comment by binarylogic** [comment]
Sure

    package sharedbehaviors

    import (
      . "github.com/onsi/ginkgo"
      . "github.com/onsi/gomega"
      . "github.com/binarylogic/myapp" // <===== this import fails
    )

    type ImmutableInputs struct {
      Model interface{}
      Config *Config
    }

    func SharedImmutableBehavior(inputs *ImmutableInputs) {                
      It("should fail", func() {
        Expect(true).To(BeFalse())
      })
    }

The package is `github.com/binarylogic/myapp/sharedbehaviors`. I can not figure out how to import `main` basically.

**Comment by onsi** [comment]
Oh.  I see.  You can't import main.

Pull out what you need to share into a separate package and then import
*that* into both main and your shared behavior.

**Comment by binarylogic** [comment]
Awesome, that was it. Thank you!
