### ISSUE TITLE
[Question]: Retrying a failed ordered integration test using description based filtering 

### ISSUE THREAD

**Issue by Dannyb48** [onsi/ginkgo#1468]
Hey, 

I would like to do an out of out of process retry rather than using ginkgo's retry mechanisms. 

1. Run my usual ginkgo command
2. process the output file for failed tests
3. Run the ginkgo command against tests that failed using the `--focus` argument. 

If I have an integration spec file layed out like so. And that `Describe` block has the `Ordered`

``` 
Describe: Gitlab with status reporting of Integration tests in the assosiated merge request
    When: a new Component with specified custom branch is created @custom-branch
      It: triggers a Build PipelineRun
      It: does not contain an annotation with a Snapshot Name
      It: should lead to build PipelineRun finishing successfully
      It: should have a related PaC init MR is created
      It: eventually leads to the build PipelineRun's status reported at MR notes
    When: the PaC build pipelineRun run succeeded
      It: checks if the BuildPipelineRun have the annotation of chains signed
      It: checks if the Snapshot is created
      It: checks if the Build PipelineRun got annotated with Snapshot name
```
Say ` It: checks if the BuildPipelineRun have the annotation of chains signed` failed and I tell ginkgo `ginkgo run --output-interceptor-mode=none --timeout=90m --focus="checks if the BuildPipelineRun have the annotation of chains signed" ./cmd` 

Does ginkgo re-run all the prior container nodes and subject nodes because they are all nested under an ordered container node?

**Comment by Dannyb48** [comment]
so I was able to create a quick expirement with a following spec file
```
var _ = framework.BookSuiteDescribe("Book service E2E tests", Ordered, func() {
	defer GinkgoRecover()
	var err error
	BeforeAll(func() {
		// Initialize the tests controllers
		f, err = framework.NewFramework()
		Expect(err).NotTo(HaveOccurred())
	})

	// Generated specs:

	Describe("Categorizing book length ", Label("book"), func() {
		// Declare variables here.

		When("the book has more than 300 pages ", Label("slow"), func() {

			It("should be a novel", func() {
				// Implement test and assertions here
				Expect("foo").To(Equal("foo"))

			})

		})

		When("the book has fewer than 300 pages ", Label("fast"), func() {

			It("should be a short story", func() {
				// Implement test and assertions here
				Expect("bar").To(Equal("foo"))

			})

		})

	})

})
```

 Confirmed that when I use --focus to to specify the last spec without trying the other first When, It combo. Which makes sense  but at the same time Ordered is meant to imply that there is an interdependence between specs. So that means I would need to re-try the whole root level `Describe` to make sure I do everything properly

**Comment by onsi** [comment]
hey @Dannyb48 - sorry for the delay.  Correct, you would need to retry the describe and there isn't great support for what you're trying to do (namely - retry the parent of the It that matches this line).  One (lame, but better than nothing) option would be to use --focus-file and pass in the filename that contains the `It` that failed.  This would run any other specs in the file as well but _would_ run the entire ordered Describe block.

**Comment by Dannyb48** [comment]
@onsi thank you! We can close out the issue!
