### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by jmtuley** [onsi/ginkgo#148]
We're not entirely sure that this is an issue with Ginkgo itself – but our error comes from within it, so it seems like a good starting place to look.

In the [logs](https://s3.amazonaws.com/archive.travis-ci.org/jobs/57065605/log.txt) from a [Travis build of loggregatorlib](https://travis-ci.org/cloudfoundry/loggregatorlib/jobs/57065605) against Go tip, we get a very interesting error message:

```
# github.com/onsi/ginkgo/internal/leafnodes
../../onsi/ginkgo/internal/leafnodes/benchmarker.go:91: internal compiler error: racewalk: unknown node type O-153
```

It looks like the race detector is trying to insert some code that's no longer supported in the future version of Go. We think that might be related to Ginkgo – or maybe not?

**Comment by onsi** [comment]
Hmm sounds like a bug on Go tip to me.... we could open an issue there and point to this issue.

**Comment by jmtuley** [comment]
That does seem reasonable. It may be difficult to build a minimal runnable example, but we can take a stab.

**Comment by onsi** [comment]
gonna close this out... for now...

**Comment by jmtuley** [comment]
Sure; we're also not seeing it anymore. Sorry for leaving it open forever.
