### ISSUE TITLE
Running ginkgo with --focus for 'when' function

### ISSUE THREAD

**Issue by iamralch** [onsi/ginkgo#1486]
Presently, `ginkgo` is not consistent when you want to run tests that are using `when` instead of `context`.

Let's have the following suite:

```golang
package example_api_test

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Example", func() {
	Context("when the numbers are positive", func() {
		It("returns the sum", func() {
			Expect(10 + 15).To(Equal(25))
		})
	})

	When("the numbers are negative", func() {
		It("returns the sum", func() {
			Expect(-10 + 15).To(Equal(5))
		})
	})
})
```

If you want to run the first test, you should run the following command:

```bash
ginkgo --focus '\bExample when the numbers are positive\b'
```

If you want to run the second test, you should run:

```bash
ginkgo --focus '\bExample when the numbers are negative\b'
```

The second test requires `when` prefix when you create the regexp. It's not obvious and consistent with the first call.

https://github.com/nvim-contrib/nvim-ginkgo/issues/3

**Comment by onsi** [comment]
Indeed it is not obvious, but it has been the behavior for several years and changing it may break existing user's scripts. I'm not sure what the best course of action is.

**Comment by iamralch** [comment]
@onsi appreciate your quick response. I think I have a clue on how to overcome that behaviour. I will close the issue for now.
