### ISSUE TITLE
Feature request: also handle interrupts from SIGTERM

### ISSUE THREAD

**Issue by ixdy** [onsi/ginkgo#149]
When aborting a run (for example, due to a timeout), CI systems like Jenkins send test processes a SIGTERM rather than a SIGINT. As a result, all completed test result data is lost, since Ginkgo only prints its summary (and runs reporters like the JUnit reporter) on a completed run or SIGINT.

In GoogleCloudPlatform/kubernetes#6388 I hacked around this issue by catching SIGTERM and emitting a SIGINT, but this workaround seems a bit hacky. Even if Ginkgo didn't handle SIGTERMs by default, it'd be nice to have an option for it to do so.

**Comment by onsi** [comment]
Just pushed a fix to master -- lemme know if this solves your Jenkins woes.

**Comment by onsi** [comment]
Closing this out -- lemme know if it's still an issue for you

**Comment by ixdy** [comment]
Thanks! I tested this locally and it seems to work; just opened GoogleCloudPlatform/kubernetes#6944 to update our version of Ginkgo and revert my hack.
