### ISSUE TITLE
Optimizing Struct Field Alignment

### ISSUE THREAD

**Issue by ZuhairORZaki** [onsi/ginkgo#1494]
# Overview

In file: [config.go](https://github.com/onsi/ginkgo/blob/master/types/config.go#L235), the fields of the `deprecatedConfig` struct are organized in a way that takes more memory. The fields of the struct can be sorted in a way that takes less memory than the initial alignment.

```go
type deprecatedConfig struct {
	DebugParallel                   bool
	NoisySkippings                  bool
	NoisyPendings                   bool
	RegexScansFilePath              bool
	SlowSpecThresholdWithFLoatUnits float64
	Stream                          bool
	Notify                          bool
	EmitSpecProgress                bool
	SlowSpecThreshold               time.Duration
	AlwaysEmitGinkgoWriter          bool
}
```

For the above alignment, the size of the struct is 40 bytes (for 64-bit systems). It can be reduced to 24 bytes by aligning the fields as follows:

```go
type deprecatedConfig struct {
	SlowSpecThresholdWithFLoatUnits float64
	SlowSpecThreshold               time.Duration
	DebugParallel                   bool
	NoisySkippings                  bool
	NoisyPendings                   bool
	RegexScansFilePath              bool
	Stream                          bool
	Notify                          bool
	EmitSpecProgress                bool
	AlwaysEmitGinkgoWriter          bool
}
```

### Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed - to improve global software supply chain security.

The bug is found by running the iCR tool by [OpenRefactory, Inc.](https://openrefactory.com/) and then manually triaging the results.

**Comment by onsi** [comment]
hey there, this is a very odd issue to open:

1. the layout of this structure is not a security concern.
2. the memory usage for a minimally used configuration struct has no meaningful impact on this open source project.
3. the configuration struct in question is actually deprecated.

I'll be closing this issue.  I appreciate efforts to help make OSS more secure.  If you do find actual security issues in this... um.. _testing framework_ please let me know.

**Comment by ZuhairORZaki** [comment]
@onsi  Yes it isn't a security bug so we just filed a normal issue. This was done because we are also obligated to report other issues in addition to security vulnerabilities.

Thank you for your feedback. We didn't have prior knowledge on the scope of usage of the struct, so our policy in such cases is to bring such cases to developers' attention and let them decide if it is something worthwhile to fix.

Sorry for any inconvenience.
