### ISSUE TITLE
Feature request: add flag that prints test name before execution

### ISSUE THREAD

**Issue by vmihailenco** [onsi/ginkgo#155]
This greatly helps when tests are stucked and you have to find which test caused deadlock.

**Comment by onsi** [comment]
this already exists

ginkgo -v

I'd also recommend

ginkgo -v -progress

Which will emit output just before each block of code (BeforeEach, It,
AfterEach, etc..) runs

**Comment by vmihailenco** [comment]
I added to the tests:

```
		ch := make(chan struct{})
		<-ch
```

and run

```
go test gopkg.in/redis.v2 -ginkgo.v -ginkgo.progress
```

and I don't get any output.  What I am doing wrong?

**Comment by onsi** [comment]
in general i recommend using the `ginkgo` cli as it smooths over some rough edges around `go test` (and allows you to run your suite in parallel)

you're running into one of those rough edges.  when `go test` is explicitly pointed at a package (like you are doing: `go test gopkg.in/redis.v2` it suppresses all output from the test.  you want:

```
go test gopkg.in/redis.v2 -test.v -ginkgo.v -ginkgo.progress
```

or

```
cd gopkg.in/redis.v2
go test -ginkgo.v -ginkgo.progress
```

FWIW `ginkgo` is just calling `go test` under the hood and can run existing non-ginkgo test suites.  alll the above becomes

```
ginkgo -v -progress gopkg.in/redis.v2
```

or even better, to run all test suites recursively

```
ginkgo -v -progress -r
```

**Comment by vmihailenco** [comment]
Thanks, `-test.v` worked for me.
