### ISSUE TITLE
Ginkgo does not work with go <=1.3

### ISSUE THREAD

**Issue by wwwdata** [onsi/ginkgo#156]
Hi,

we are using ginkgo for a long time now and it always worked fine. But it seems that the newest version does not work correctly with go 1.3 and 1.2. It works all fine with 1.4

The tests are working when executed with `go test`. But it is not possible to run them with the ginkgo command line tool. But we'd like to do that for additional options for our CI builds.

Output:
```bash
root@19a97b3d9245:/gopath/src/github.com/manyminds/api2go# go version
go version go1.3 linux/amd64
root@19a97b3d9245:/gopath/src/github.com/manyminds/api2go# ginkgo
Failed to run test suite!
	fork/exec /tmp/ginkgo721761102/api2go.test: no such file or directory
Ginkgo ran 1 suite in 942.915467ms
Test Suite Failed
root@19a97b3d9245:/gopath/src/github.com/manyminds/api2go# go test
Running Suite: Api2go Suite
===========================
Random Seed: 1430747014
Will run 56 of 56 specs

••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 56 of 56 Specs in 0.020 seconds
SUCCESS! -- 56 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
ok  	github.com/manyminds/api2go	0.110s
```

Here is a travis build https://travis-ci.org/manyminds/api2go/builds/61144609

**Comment by wwwdata** [comment]
Hm, just saw in the Readme go version 1.4+

Does that mean older versions are not supported anymore?

**Comment by onsi** [comment]
Hey @wwwdata - yes I introduced a change that requires go 1.4.  I'm using go test -c -o which is only available in go 1.4.

If this is very painful for you/others I can fairly easily add a fallback that will work with older versions.  Was trying to avoid that if possible.

**Comment by wwwdata** [comment]
alright, thanks for your reply, i will close the ticket

**Comment by fgrosse** [comment]
I would like to have the fallback if it is easily possible. I love ginko but not all my systems do have go 1.4 yet and I would like to support go 1.3 a little longer. Until then I will now stick with an older version of ginkgo

**Comment by mwf** [comment]
Hi!
The same thing for me - I'd like to have the fallback. Debian stable repos provide go 1.3, that's why it's still widely used.

**Comment by onsi** [comment]
It's not hard to do but I'm pretty busy these days :/

Is anyone up for a PR?  I'd be happy to point you in the right direction.

**Comment by fgrosse** [comment]
I would be happy to help :)

**Comment by onsi** [comment]
Sweet - thanks @fgrosse  :) 

So basically:
https://github.com/onsi/ginkgo/blob/master/ginkgo/testrunner/test_runner.go#L66-L106

Compiles with `go test -c -i -o <PATH>` to place a binary at the location specified by `<PATH>`.  If you're on go `< 1.4` this will fail as the `-o` flag is new.  If that failure occurs, `CompileTo` could retry without `-o` and, upon success, move the file produced by `go test` (which is typically `filepath.Join(t.Suite.Path, t.Suite. PackageName+".test")` to the requested `<PATH>`.

**Comment by onsi** [comment]
Thanks to @fgrosse this should now be resolved!
