### ISSUE TITLE
How to run spec in a specific order?

### ISSUE THREAD

**Issue by nvcnvn** [onsi/ginkgo#158]
I'm using Agouti with Gomega to write some test, including:
1. User registration.
2. User purchasing an item.
3. User playing with that item.

I think each of them should live in each own "Describe" block and on different file.
And 1 must run before 2 and then 3.
I don't know how to do that, so I repeat a test before other test (and this make the test take longer to finish) like this:
```go
Describe("UserRegistration", fuction() {
  email := "test@example.com"
  SharedSuccessUserRegistration(email)
})
```
###
```go
Describe("UserPurchasing", fuction() {
  email := "test@example.com"
  SharedSuccessUserRegistration(email)
  item := Item{ID:123}
  SharedSuccessUserPurchasing(email, item)
})
```
###
```go
Describe("UserPlaying", fuction() {
  email := "test@example.com"
  SharedSuccessUserRegistration(email)
  item := Item{ID:123}
  SharedSuccessUserPurchasing(email, item)
  SharedSuccessUserPlaying(email, item)
})
```

I have som more test but not realted and need to run them in parallel with these 3 test (just for faster)

**Comment by onsi** [comment]
HI @nvcnvn - sorry for the delay in getting back to you.  Ginkgo is *built* for running tests in parallel so I think you'll find it will suit your needs quite well once you learn how to leverage its feature set.

Based on your code snippets, however, I'd recommend that you spend some time reading the [documentation](http://onsi.github.io/ginkgo/).  You must not place assertions inside `Describe` blocks - they must occur in `It` blocks.

In your particular case, you are testing a user-flow.  You could break this up into 3 separate tests but often times, with a flow like this, it actually is more efficient and makes more sense to just have one test:

```
Describe("Items", func() {
  Context("with a logged-in user", func() {
    var item Item
    var email string
    
   BeforeEach(func{
       email = "test@example.com"
       item = Item{ID:123}
       Expect(RegisterUser(email)).To(Succeed())
    }) 
  
    It("allows a logged in user to purchase and play with an item", func() {
     By("purchasing the item")
     Expect(UserPurchasing(email, item)).To(Succeed())
     By("playing with the item")
     Expect(UserPlaying(email, item)).To(Succeed())
    })
  })
})
```

If you run `ginkgo -p` this test will run in parallel with any other `It`s in your test suite.
