### ISSUE TITLE
Feature request: Allow AfterEach functions to tell if the test has failed

### ISSUE THREAD

**Issue by lavalamp** [onsi/ginkgo#163]
That way, they can print extra debugging information etc.

**Comment by onsi** [comment]
It's a mouthful but:

```go
AfterEach(func() {
    if (CurrentGinkgoTestDescription().Failed) {
        fmt.Printf("oops... %s failed\n", CurrentGinkgoTestDescription().FullTestText)
    }
})
```

does what you're asking for.

In case you aren't aware of it, the `GinkgoWriter` is also a way to communicate additional information when a test fails.  Everything written to the `GinkgoWriter` is stored off in an in-memory buffer.  If the current test fails, the contents of this buffer are emitted to stdout.  This is super helpful when you are running, say, an external process and want to emit its output if the test fails.  For example:

```go
It("should encabulate and exit succesfully", func() {
    cmd := exec.Command("encabulate", "things")
    cmd.Stdout = GinkgoWriter
    cmd.Stderr = GinkgoWriter
    Expect(cmd.Run()).To(Succeed())
})
```

Now, if `cmd` exits succesfully the test will pass and nothing will be emitted to stdout (except for a pretty green dot).

If `cmd` exits unsuccesfully, the test will fail and any output emitted by the command will appear on stdout.

Last thing: if you *are* testing external commands like this, I highly recommend checking out Gomega's [gexec](http://onsi.github.io/gomega/#gexec-testing-external-processes) package.

**Comment by lavalamp** [comment]
Thank you very much!
