### ISSUE TITLE
bad --trace performance in go 1.5beta3

### ISSUE THREAD

**Issue by sharpner** [onsi/ginkgo#172]
I don't know if it is a bug or not, but maybe you can provide some useful information or at least want to know :-)

Testresults on Travis-CI: 

1.4.2 Performance: 
```ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
Ginkgo ran 3 suites in 5.807183567s```

1.5b3 Performance:
```Ginkgo ran 3 suites in 1m6.652172561s```

1.5b3 without --trace:
```Ginkgo ran 3 suites in 8.825528334s```

Any hints? I know that 1.5 will be slower than 1.4 but one minute more seems excessive. 
I could reproduce these build times locally as well.

**Comment by onsi** [comment]
Hey @sharpner thanks for letting me know, absolutely.  I haven't had a chance to play with 1.5 yet.

This is really odd. `--trace` is just a simple boolean that makes its way down to ginkgo's test output printer.  It doesn't modify anything substantial other than to emit additional information (information that is already always being captured) when a failure occurs.

Weird.. I'll try to dig out some time to look into it.  Are you seeing it happen consistently and (forgive the irritating question) are you sure the only difference between your test runs is `--trace`?

**Comment by onsi** [comment]
lol, could it be this:

http://tip.golang.org/doc/go1.5#trace_command

`ginkgo` takes pains to namespace its flags so that `ginkgo --trace` eventually gets turned into `go test --ginkgo.trace` to avoid collisions.  But maybe that isn't happening correctly?

**Comment by onsi** [comment]
Actually, I just confirmed that `--trace` does get namespaced correctly.  Guess I'll have to just install the beta and try it out myself.

**Comment by sharpner** [comment]
Nice :) Let me know if I can help!

**Comment by sharpner** [comment]
any news on this?

**Comment by onsi** [comment]
hey nino, sorry -- but no one I'm aware of has managed to reproduce this.  do you have a repo you could point me to?

**Comment by sharpner** [comment]
hey! I think you can close this. I just wanted to look up the repository and saw that the problem seems to be fixed. Sorry to bother you! :-)
