### ISSUE TITLE
How can I distinguish between various type of test case ?

### ISSUE THREAD

**Issue by egarle** [onsi/ginkgo#174]
Hello Onsi: I want to run part of test cases, so I want to distinguish of them, How can I do ?

**Comment by onsi** [comment]
I'm going to need a bit more detail than that to help.  What problem are you trying to solve?  Can you give me some concrete examples or point me at code?

**Comment by egarle** [comment]
I have two type of test in a testsuite: Unit test and Performance test. When running Unit Test, there's no need to run Performance test. The question is, who can I do that, thx.

**Comment by onsi** [comment]
One approach I take is something like:

Describe("[PERF] some perf stuff", func() {
...
})

Then you can

ginkgo -skip=PERF

or

ginkgo -focus=PERF

**Comment by robdimsdale** [comment]
A concrete example of what is described above is can be found at: https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/crashing_test.go#L28 with the constant defined in https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/init_test.go#L22

@egarle does this and the above comment answer your question?

**Comment by robdimsdale** [comment]
@egarle I'm going to close this issue. Feel free to open another one if you have further comments or questions.
