### ISSUE TITLE
Question:any plan to support table driven test?

### ISSUE THREAD

**Issue by AlexLuya** [onsi/ginkgo#175]
Hello,
     It will reduce lot of duplications,so any play to support it?

**Comment by onsi** [comment]
IMO there's really nothing to support.  Table driven testing is a technique that works just fine in Ginkgo.  I've used tables to generate Contexts, tables to generate Its and sometimes tables that simply generate assertions in a single It.

Am wondering if you have thoughts around what more formal support for table-driven tests might look like.


Curious to hear what table driven test support might look like.

**Comment by AlexLuya** [comment]
just like:
https://dzone.com/articles/spock-data-driven-testing#!

**Comment by onsi** [comment]
I'm not sure that first-class support for this is particularly necessary though I'm open to the idea.  In fact, it could be a new library distinct from Ginkgo/Gomega that gives you a DSL you can use within an `It`

To get concrete, though.  The following example from your link:

```ruby
class Math extends Specification {
    def "maximum of two numbers"(int a, int b, int c) {
        expect:
        Math.max(a, b) == c

        where:
        a | b | c
        1 | 3 | 3
        7 | 4 | 4
        0 | 0 | 0
    }
}
```

Could be (note all the `context` and `description` stuff is sugar, not necessary but helpful IMO):

```go
Describe("math.Max", func() {
    table := []struct{
        a int
        b int
        c int
        context string
        outcome string
    }{
        {1, 3, 3, "when a < b", "chooses b"},
        {7, 4, 7, "when a > b", "chooses a"},
        {0, 0, 0, "when a = b", "chooses either"},
    }

    for _, entry := range table {
        entry := entry //gotcha!
        Context(entry.context, func() {
            It(entry.outcome, func() {
                Ω(math.Min(entry.a, entry.b)).Should(Equal(entry.c))
            })
        })
    }
})
```

Obviously, this is just a loop.  You can do it within an `It` but I like the documentation you get if you do it this way.  Also, with individual `It`s like this you can get test parallelization for free with `ginkgo -p`.

**Comment by onsi** [comment]
hey @AlexLuya - on second thought, I experimented with a DSL for supporting this.

It's documented here: http://onsi.github.io/ginkgo/#table-driven-tests

And on master now!  Note that it's not part of the Ginkgo core but, rather, an extension under `extensions/table`.  Give it a whirl :)

**Comment by carldunham** [comment]
> entry := entry //gotcha!

That's the little nugget that cost me a couple of hours. 😸

**Comment by pprasanthi** [comment]
> > entry := entry //gotcha!
> 
> That's the little nugget that cost me a couple of hours. 😸

I dont understand why we use this `entry := entry //gotcha!` step?

**Comment by carldunham** [comment]
And when you do, you will be one step closer to realizing what a truly awful language Go is. 

Carl

**Comment by blacksails** [comment]
@carldunham can you link to some explanation of the `entry := entry` madness?

**Comment by johanbrandhorst** [comment]
This is another flavour of https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables. The variable that is closed over will change before the function is called. More explanation here: https://blog.cloudflare.com/a-go-gotcha-when-closures-and-goroutines-collide/.
