### ISSUE TITLE
Run goroutines synchronous

### ISSUE THREAD

**Issue by jplethier** [onsi/ginkgo#177]
Is there a way to set goroutines to run synchronous when I am running the tests with ginkgo?

**Comment by onsi** [comment]
Nope.  Not possible in go.  What problem are you trying to solve, maybe I can help.

**Comment by jplethier** [comment]
I would like to do a config where I do not need to worry with goroutines in
tests, so I could test the result of goroutines and could have sure that I
am erasing all data from database after each test.

For example, I have a goroutine that updates something in database and, for
the rest of the code, does not matter if the update was successfull or not,
so, I do not need channel or anything else with this goroutine. How can I
test those update on TDD?

Em 20/08/2015 20:12, "Onsi Fakhouri" <notifications@github.com> escreveu:

Nope. Not possible in go. What problem are you trying to solve, maybe I can
help.

—
Reply to this email directly or view it on GitHub
<https://github.com/onsi/ginkgo/issues/177#issuecomment-133208344>.

**Comment by onsi** [comment]
@jplethier yep, there's no way to force go to run your goroutines synchronously.  there are whole classes of things that simply would not work if that were the case.

For your particular case, I'd recommend looking at Gomega's [`Eventually`](http://onsi.github.io/gomega/#making-asynchronous-assertions)

Here's a simple example (obviously this is made up):
```
BeforeEach(func() {
    db.Insert("foo") //does it async
    Eventually(db.List).Should(ContainElement("foo")) //blocks until "foo" is in the database
})

AfterEach(func() {
    db.CleanUp() //does it async
    Eventually(db.List).Should(BeEmpty())
})

It("does something", func() {
  ...
})
```

**Comment by jplethier** [comment]
Thanks, I will try this eventually
Em 20/08/2015 20:50, "Onsi Fakhouri" <notifications@github.com> escreveu:

**Comment by onsi** [comment]
Marking this closed.  Reopen if you'd like!

**Comment by jplethier** [comment]
Eventually works great, thanks
Em 30/08/2015 17:22, "Onsi Fakhouri" <notifications@github.com> escreveu:
