### ISSUE TITLE
support vendoring

### ISSUE THREAD

**Issue by tve** [onsi/ginkgo#187]
Would it make sense to add minimal support for vendoring into ginkgo? In the sense of not running tests recursively on vendored packages. Right now I using the `skipPackage` option but that turns out to be very verbose:
```
ginkgo -r -skipPackage vendor --randomizeAllSpecs --randomizeSuites --failOnPending
Will skip:
  ./vendor/github.com/alecthomas/template
  ./vendor/github.com/alecthomas/template/parse
  ./vendor/github.com/alecthomas/units
  ./vendor/github.com/gorilla/websocket
  ./vendor/github.com/rightscale/gojiutil
  ./vendor/github.com/rightscale/wstunnel
  ./vendor/github.com/rightscale/wstunnel/tunnel
  ./vendor/github.com/zenazn/goji/graceful
  ./vendor/github.com/zenazn/goji/graceful/listener
  ./vendor/github.com/zenazn/goji/web
  ./vendor/github.com/zenazn/goji/web/middleware
  ./vendor/gopkg.in/alecthomas/kingpin.v2
  ./vendor/gopkg.in/inconshreveable/log15.v2
  ./vendor/gopkg.in/inconshreveable/log15.v2/ext
  ./vendor/gopkg.in/inconshreveable/log15.v2/stack
[1443467249] Demo - 4/4 specs •••• SUCCESS! 7.422851ms PASS
[1443467249] MAIN - 0/0 specs  SUCCESS! 59.089µs PASS
```
Maybe there's another option I'm missing?

**Comment by onsi** [comment]
I haven't been keeping up with the Jonses on the vendoring adventures that Golang is going through.

There's this:
https://github.com/onsi/ginkgo/blob/master/ginkgo/testsuite/test_suite.go#L60-L65

which uses a regexp to ignore hidden directories (anything beginning with a `.`) and Godeps style vendoring (anything beginning with a `_`).

If you're up for a PR to support skipping `/vender/` - that would be the code to modify...  Hilariously the CLI has no unit tests so I'd ask that you add an integration test if you're up for it.

**Comment by xeger** [comment]
I wasn't courageous enough to add unit tests to the CLI, but by my reckoning, the vendor-skipping behavior should be conditional on the GO15VENDOREXPERIMENT env variable anyhow, so it can be nicely encapsulated  side FindTestSuites). I opened a PR, with unit tests, to skip vendored tests (and skip recursing into vendor); see #204
