### ISSUE TITLE
Copy compiled file if move fails

### ISSUE THREAD

**Issue by robdimsdale** [onsi/ginkgo#189]
When running on golang < 1.4, there is no `-o` option so ginkgo attempts to compile the file and move it (see [test_runner.go](https://github.com/onsi/ginkgo/blob/462326b1628e124b23f42e87a8f2750e3c4e2d24/ginkgo/testrunner/test_runner.go#L108))

This fails if `/tmp` is on a different partition. It should be possible to copy the file across partitions instead.

I appreciate this is an edge-case as not many people will be running tests on golang 1.2 and 1.3, but I'm supporting a library on all versions of golang, and currently ginkgo is failing.

How do you feel about adding a `io.Copy` if `os.Rename` fails? I'm willing to submit a PR for this, but I'm a little concerned about how to drive this out with a test, as forcing `os.Rename` to fail could be tricky.

**Comment by onsi** [comment]
@robdimsdale that would be great.  I agree that driving it out with a test will be tricky.  Since this is supporting an edge case with old versions of Go I'm ok doing this without a test.  If you can confirm that it works in your environment that'll have to do.

**Comment by robdimsdale** [comment]
Great, thanks. I will figure something out and submit a PR soon, probably without a test.
