### ISSUE TITLE
Context() could take an argument for the BeforeEach()

### ISSUE THREAD

**Issue by vito** [onsi/ginkgo#192]
Instead of...:

```go
Context("when foo is true", func() {
  BeforeEach(func() {
    foo = true
  })

  It("wibbles the wobble", func() {
  })
})
```

...wouldn't it be neato if you could write...:

```go
Context("when foo is true", func() {
  foo = true
}, func() {
  It("wibbles the wobble", func() {
  })
})
```

...?

**Comment by abourget** [comment]
not sure about this one :) the former seems more readable, more explicit.. it _is_ two lines more.. but it's a lot easier to read for the newcomer, don't you think ?

**Comment by robdimsdale** [comment]
I like the elegance of this @vito, but I tend to agree with @abourget - readability is really important, and one of the attractive aspects of the go programming language is that anything written in golang tends to look similar. I'd like to see ginkgo adhere to that mindset as much as possible. I value both readability and elegance, but if I can only have one I prefer readability.

**Comment by vito** [comment]
It's not really about saving lines, it's more about encouraging that `Context` implies `BeforeEach`. It also saves indentation, making it easier to distinguish between setup code vs. example code (which currently have the same level of indentation). Which imo makes it more readable.

Hard to see without a larger example though, and it does have one concrete drawback: there's nowhere to put declarations.

**Comment by robdimsdale** [comment]
Right, you're describing something like:

```
Context("some thing", func(){
    var foo FooType

    BeforeEach(func(){
        foo = NewFoo()
    })

    It("behaves as it should", func(){
        Expect(foo.Bar()).Should(Equal("bar"))
    })
})
```

which wouldn't work with your suggestion.

The other points are interesting though; being more explicit about the connection between `Context` and setup, and the indentation point is fair too.

Given this proposal doesn't work with declarations, I'm not inclined to explore it further. If you have more to add, great, otherwise I'll close this issue.

**Comment by robdimsdale** [comment]
@vito I'm going to close this issue. Feel free to open another one if you have further thoughts or questions.
