### ISSUE TITLE
Seeing compilation failure when using -race

### ISSUE THREAD

**Issue by Zteve** [onsi/ginkgo#193]
```
ginkgo -r -failOnPending -randomizeAllSpecs -skipMeasurements=true -race

Failed to compile integration:

go install runtime: mkdir /opt/local/lib/go/pkg/darwin_amd64_race/: permission denied

Ginkgo ran 1 suite in 7.234788563s
Test Suite Failed
```
It works fine when running with `-race=false`. Is this a Go problem?

Go version 1.5.1; Here are the ginkgo and gomega versions:
```
"Deps": [
		{
			"ImportPath": "github.com/onsi/ginkgo",
			"Comment": "v1.2.0-22-g39d2c24",
			"Rev": "39d2c24f8a92c88f7e7f4d8ec6c80d3cc8f5ac65"
		},
		{
			"ImportPath": "github.com/onsi/gomega",
			"Comment": "v1.0-71-g2152b45",
			"Rev": "2152b45fa28a361beba9aab0885972323a444e28"
		}
	]
```

**Comment by Zteve** [comment]
PS: Installed go with macports.

**Comment by robdimsdale** [comment]
I don't know of many people that have install golang with macports - homebrew seems far more common.

That being said, a search for your issue returned the following thread: https://groups.google.com/forum/#!topic/golang-nuts/Fk5KSGs-kYA

A similar issue appeared to be resolved by ensuring `GOPATH` is set correctly - it might be worth checking that is set before running the tests again.

**Comment by Zteve** [comment]
Thanks Rob; here is my output for `go env`:
```
10:43:24 : go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/spowell/dev/go"
GORACE=""
GOROOT="/opt/local/lib/go"
GOTOOLDIR="/opt/local/lib/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="/usr/bin/clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
and, as you can see, `GOPATH` is fine.

The interesting things is `GORACE`, which I've never seen before; and that `GOBIN` is not set to anything.  I've checked and the directory `/opt/local/lib/go/pkg/darwin_amd64_race` doesn't exist (obviously) and it is likely that it doesn't have permission to create it because the ownership of `pkg` is `root/admin`.

BTW: I cannot use both homebrew and macports, and I need macports for other projects.

This could be a Macports installation issue.

**Comment by Zteve** [comment]
More info: I have uninstalled (using Macports) go 1.5.1 (and its dependency go 1.4.3 !!?!) and reinstalled go 1.5.1 (which reinstalls go 1.4.3 !!?!) and now my tests run fine.  I've no idea why this should have happened, but all is well now. [Well, except that two of my tests failed, but I know how to fix those :-)]

Thanks!
