### ISSUE TITLE
Color of nested context verbose description invisible using the Solarized theme

### ISSUE THREAD

**Issue by ashb** [onsi/ginkgo#194]
Best describe with two pictures:
![screen shot 2015-11-17 at 22 38 01](https://cloud.githubusercontent.com/assets/34150/11227085/ebb38734-8d7b-11e5-8f37-e9bfb489742e.png)

And if I highlight that gap:
![screen shot 2015-11-17 at 22 38 15](https://cloud.githubusercontent.com/assets/34150/11227088/ee9e9128-8d7b-11e5-8c44-4cd6fcd0b7eb.png)

I'm not saying you should support my colour scheme of choice (because that way lies madness) but it would be nice if I could have the hooks to tweak it for my color scheme

**Comment by onsi** [comment]
hi @ashb - sorry for the delay.  I can imagine a number of ways of doing this.

I've long wanted to add support for a `.ginkgo` file that will allow users to override certain Ginkgo defaults.  The `.ginkgo` file could appear in the user's home director and be overridden by more `.ginkgo` files in source code root directories.  I think this sort of configuration file would be a great place to "theme" the default reporter's output.

It's not a lot of work, but I don't have as much time as I'd like to these days.

If anyone's interested in working up a PR for this, I'd be happy to think the idea through with them.

**Comment by ashb** [comment]
I understand entirely - finding time for open source is work is hard.

I'd like to say "I'll get right on it - here's a PR" but in practice I also don't have any spare time February. If no one gets to it by then I'll see if I can find a weekend to try this.

**Comment by pib** [comment]
In the meantime, if you happen to be using iTerm2 in OSX, there is a "Minimum contrast" setting in the "Colors" section of the settings which you can use to fix the issue.

![screen shot 2015-12-07 at 6 25 46 pm](https://cloud.githubusercontent.com/assets/32910/11644260/27e83f30-9d10-11e5-81f4-ea76d744d59a.png)
![screen shot 2015-12-07 at 6 25 33 pm](https://cloud.githubusercontent.com/assets/32910/11644267/3071edea-9d10-11e5-8edb-cccdd9fb40b5.png)

**Comment by onsi** [comment]
This issue has grown stale.  Closing it out.
