### ISSUE TITLE
Question: Output descriptions of passing specs?

### ISSUE THREAD

**Issue by ches** [onsi/ginkgo#195]
Hi, thanks for making Ginkgo and Gomega!

Just a quick question—from reading through the docs and past issues on GitHub I'm not finding it so I assume the answer is no, but I'm somewhat surprised: is there any option for outputting descriptions of all specs, including passing ones? I'm thinking of something like RSpec's `specdoc` formatter, if you're familiar, where there is an indented outline of nesting similar to the output of `--noisyPendings`, colorized on TTY.

I imagine this would be custom reporter territory, and an HTML (or JSON) reporter would probably be more useful than a CLI one for the use case of publishing browsable specification-like output (and I've seen that there are open issues for those), I just wanted to make sure it's not already there and I'm overlooking it somehow :smile:

**Comment by onsi** [comment]
Closest thing out of he box today is `ginkgo -v`

Otherwise, yes, you're in custom reporter territory.

**Comment by ches** [comment]
Okay, thanks for the quick response. I'll close this and re-open if it is something I have a chance to take a stab at (and/or #143 instead).
