### ISSUE TITLE
The unicode code point 2022 BULLET "•" resulting in terminal beeps

### ISSUE THREAD

**Issue by cstockton** [onsi/ginkgo#198]
I was trying to use Ginkgo for the first time, I happen to be on windows and I was hearing the BELL sound.. it was driving me insane because it would go off dozens of times per run! At first I figured it was powershell / cmd.exe not handling the colors output properly and a 0x7 sneaking through somewhere.. so I tried -noColors.. still beeped. I dug through the code a bit and saw the Announce naming in stenographer.go for the reporter and started to think it was printing it somewhere but didn't see the BELL char anywhere.. and I went into all the println's and did a if 0x7 { panic.. }.. nothing. Reduced the output and eventually found the perpetrator to be []byte{226, 128, 162}.

Was rather unusual but this article explained it [How a bullet turns into a beep](http://blogs.msdn.com/b/oldnewthing/archive/2007/01/04/1411080.aspx) .. I silenced the error by typing [chcp 65001](http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how/388500#388500). My cursory read of the docs leads me to believe I could also fix this with a customer reporter, however I don't run go in a command prompt very often. A flag which converted bullet to something like "-"  or if it was done by default with -noColors may be reasonable. I'll let project maintainers decide if this is worth taking action on, the fix would be simple but Go in windows command prompt is likely a pretty small demographic. Regardless having this issue here may save someone else the time of figuring out those wretched beeps :- ) Great project, so far I really like ginkgo and I was able to get my tests running in it pretty quickly. Thanks.

**Comment by onsi** [comment]
Wow... bizzare!  Thanks for digging into this @cstockton 

I'd be happy to pull in a PR.  Your patch to the stenographer looks good but rather than key off of the `color` bool, you could detect whether or not `ginkgo`'s running on windows (I do this in https://github.com/onsi/ginkgo/blob/master/ginkgo/run_watch_and_build_command_flags.go#L91)

Would you mind putting something together?

**Comment by cstockton** [comment]
@onsi Here ya go: https://github.com/onsi/ginkgo/pull/200

**Comment by onsi** [comment]
Hooray!
