### ISSUE TITLE
Duplicate test collection

### ISSUE THREAD

**Issue by marun** [onsi/ginkgo#202]
I'm seeing duplicate collection of tests in the [openshift origin](https://github.com/openshift/origin/) networking test suite.  My intent is to run a subset of the [kubernetes](http://github.com/kubernetes/kubernetes/) e2e tests alongside some new tests in the origin tree, and the origin tests are always collected twice.  Here are the origin tests in question:

 - https://github.com/openshift/origin/blob/master/test/extended/networking/sanity.go

For a given duplicate test, I'm seeing different RUN lines, with the first appearing as follows:

    RUN "test/extended/networking/sanity.go":

The second instance of the test will have the same status line minus the first 8 characters:

    RUN "ended/networking/sanity.go":

Is it possible that the problem involves unintended path modification during test collection?

To reproduce (test runner requires linux with golang installed):

    git clone https://github.com/openshift/origin
    # Fake out test runner script's configuration detection
    mkdir /tmp/openshift.local.config
    touch /tmp/openshift.local.config/node-config.yaml
    # Look for duplicate test collection of:
    #   networking: sanity should function for pod communication on a single node
    #   networking: sanity should function for pod communication between nodes    
    OPENSHIFT_CONFIG_ROOT=/tmp test/extended/networking.sh --ginkgo.dryRun

**Comment by onsi** [comment]
Hey @marun,

There's a ton of complexity in your setup scripts.  Can you provide a simpler repro case that reproduces the issue in ginkgo?  Or, at the very least, figure out precisely what your networking.sh script actually ends up invoking?

One thing I'm noticing is you have some Ginkgo tests defined in an `_test.go` file and others in the networking package itself.  While I think this should work, it's an uncommon pattern and might be causing trouble, try appending _test to all the files in this directory, maybe?

**Comment by marun** [comment]
@onsi Not sure what we were doing wrong, but the problem has since gone away.  Sorry for the false alarm.
