### ISSUE TITLE
ginkgo -r and vendor

### ISSUE THREAD

**Issue by james-lawrence** [onsi/ginkgo#211]
ginkgo when provided the -r argument attempts to run tests within the vendor directory.

**Comment by james-lawrence** [comment]
side note this can be fixed using ```-skipPackage vendor``` as a work around.

**Comment by jim-slattery-rs** [comment]
Not sure if this has been addresses already here: https://github.com/onsi/ginkgo/pull/204 ?

**Comment by james-lawrence** [comment]
possibly, my version might be old on this machine =) will double check.

**Comment by james-lawrence** [comment]
outdated version =D
