### ISSUE TITLE
--skip option behaves differently depending upon the order of the values given

### ISSUE THREAD

**Issue by keaty** [onsi/ginkgo#215]
We're getting different behavior from the Ginkgo `--skip` option depending upon the order in which the values are given.

When "Getting instance information" is adjacent to "NO_DIEGO_SUPPORT" (the only other spec skipped from the Apps suite) both specs are skipped.

```
+ ginkgo -skip=NO_DIEGO_SUPPORT|Getting instance information|SSO Lifecycle|scp|sftp --slowSpecThreshold=480 . apps detect internet_dependent security_groups docker operator routing routing_api services ssh v3

[1453909668] Applications - 39/41 specs
```

When "Getting instance information" _isn't_ adjacent to "NO_DIEGO_SUPPORT", and is instead placed at the end or in the middle, it is not skipped.

```
+ ginkgo -skip=NO_DIEGO_SUPPORT|SSO Lifecycle|scp|sftp|Getting instance information --slowSpecThreshold=480 . apps detect internet_dependent security_groups docker operator routing routing_api services ssh v3

[1453849003] Applications - 40/41 specs
```

The order in which the suites are run seems to have an impact as well. When the SSH suite is run first, its three skipped scp and sftp tests were no longer skipped.

```
+ ginkgo --skip=NO_DIEGO_SUPPORT|insufficient resources|SSO Lifecycle|scp|sftp --slowSpecThreshold=480 . ssh apps detect internet_dependent security_groups docker operator routing routing_api services v3

[1453923845] SSH - 8/8 specs
```

But when we moved those tests to the beginning of the --skip input, they were.

```
+ ginkgo --skip=scp|sftp|NO_DIEGO_SUPPORT|insufficient resources|SSO Lifecycle --slowSpecThreshold=480 . ssh apps detect internet_dependent security_groups docker operator routing routing_api services v3

[1453923922] SSH - 5/8 specs
```

To replicate the problem:
1. clone https://github.com/pivotal-cf/micropcf, update submodules within the /test directory
2. follow the instructions in the README.md to spin up and target microPCF
3. run `./bin/cats local.micropcf.io`.

**Comment by robdimsdale** [comment]
@keaty you have spaces in your strings which are probably not being handled by the shell in the way you might expect. Have you tried adding double quotes around the entire skip string e.g. `ginkgo--skip="NO_DIEGO_SUPPORT|insufficient resources|SSO Lifecycle|scp|sftp"`

**Comment by keaty** [comment]
Hey Rob, my bad, I copied the output of the CATs test script (with set +x at the top). The actual call to `./bin/test` in CATs looks like:

```
./bin/test --skip='scp|sftp|NO_DIEGO_SUPPORT|insufficient resources|SSO Lifecycle' --slowSpecThreshold=480 ${@:2} . apps detect internet_dependent security_groups docker operator routing routing_api services ssh v3
```

**Comment by robdimsdale** [comment]
@keaty given you're quoting the strings, I agree that seems that unexpected behavior. My initial suspicion would be the way regex is being parsed, but I'm not really sure.

If you're interested in driving this behavior out, you could take a look at the [tests around skipping specs](https://github.com/onsi/ginkgo/blob/master/internal/spec/specs_test.go#L122). I don't have the bandwidth to dig into this at the moment.

**Comment by williammartin** [comment]
@keaty Did you ever get to the bottom of this? I added the `requires-investigation` label but I'm secretly hoping it's not a problem anymore :)

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.
I'm going to close this for now, but feel free to reopen it if you'd like.
