### ISSUE TITLE
Advise needed on setup/teardown for multiple packages

### ISSUE THREAD

**Issue by mpmlj** [onsi/ginkgo#218]
Hi,

Before my tests I need to setup 3 test databases and pre-fill them with mock data. In the end - I need to drop them.
I could use BeforeSuite & AfterSuite for setup/teardown, but the problem is that I split the code into services, each being a separate package:
/services/music
/services/events
/services/posts
etc.
Looks like I cannot join them into a single Ginkgo test suite and that leads to necessity to setup & teardown the DBs for each service/package and I have a lot of them. (and imagine this running under "ginkgo watch -r").

Others mentioned before "BeforeAll" and "AfterAll". However I believe my case is somewhat different. I do not care about dependency. My setup and teardown are fire-and-forget tasks to handle databases and I do not need to pass dependencies or share some state. hm... Maybe I'm overcomplicating things and that's something already possible with Go/Ginkgo?

Please advise!

Thank you,
D.

**Comment by onsi** [comment]
hi @mpmlj - I might need some more information.  Are you trying to spin up and populate *one* shared global database for *all* your tests across *all* your packages?  If so, how do you avoid test pollution?

In cases like these, each package's test suite typically spins up a database, fills it with mock data, and then tears it down using `BeforeSuite` and `AfterSuite` (in fact, to avoid test pollution, the database is often reset between each test with code in `BeforeEach`).  If you need to do identical/similar setup across all your test packages you could pull out a helper into some sort of `internal` test helpers package.

If you are trying to test how the various services interact together then you're really talking about an integration test.  This is typically a *separate* test suite that live in its own package (often called `integration`) that spins up the database and calls into the various services as needed.

Does that help?  Perhaps if you point me at some code I can be more helpful?

**Comment by mpmlj** [comment]
@onsi , hi!

_>> Are you trying to spin up and populate one shared global database for all your tests across all your packages? _

Correct.

_>> If so, how do you avoid test pollution?_
During setup I'm adding a part of mock data that will be used by all tests and is not supposed to be mutated. For example: tags, a set of test users of all types and roles, relations between these users and their content, etc. Each suite, however, adds and destroys additional mocks of its own (articles, comments, additional users for these tests only, etc.)

_>>In cases like these, each package's test suite typically spins up a database, fills it with mock data, and then tears it down using BeforeSuite and AfterSuite (in fact, to avoid test pollution, the database is often reset between each test with code in BeforeEach)_

And that's what I'm doing right now - creating and dropping DBs for each package. I believe my question is originating in my frustration related to a test watcher and multiple packages due to:
1. I'm keeping components separate, getting ready to move them out into separate micro-services and to cleanly separate responsibilities. Otherwise I would dump everything into a single "services" directory/package and my test setup would be dead simple. However now, I have to create 3 databases, fill each of them with mocks and drop for each of my 13 packages (and growing). It does not take too long now on my core i7+ssd, but watcher is restarting this process on every save and starts kind of choking. Sure, its not a problem with a watcher )), its just I'm trying to find a way to trace & test everything I do in parallel with my work.
2. It really feels good and is truly safer when I have a test watcher running while I'm working. Too many component relations to keep in mind. If I'll be running a separate integrations suite less frequently I'll likely get in a situation when lots of updates have been added and tracing and reverting an issue will become a substantial effort + will need to support one more process/harness.


_>> If you are trying to test how the various services interact together then you're really talking about an integration test. This is typically a separate test suite that live in its own package (often called integration) that spins up the database and calls into the various services as needed._

While I do have a number of unit tests, due to the nature of the system I'm working on (lots of interrelated components) I'm primarily concerned with integration/acceptance tests and they constitute total majority of my tests. Unless I'm missing some point, I feel its better to keep them separated by services and not in one integration package as its easier to track this way what happened where and this single package will most likely contain 80-90% of my tests.

_>> Does that help? Perhaps if you point me at some code I can be more helpful?_
Really appreciate your proposal to help! Unfortunately I won't be able to provide access to the code/repo :(. With BeforeAll/AfterAlI I just wanted to avoid messing with external stuff like, for example, guys are doing here http://clypd.com/container-technology-integration-testing-with-docker/ with shell scripts etc. and wanted to stay within the go/ginkgo testing setup only while running integration tests with watcher detecting changes.
But again, maybe I'm trying to fit the project into a too simple/improper workflow. Any thoughts are appreciated. Especially, regarding BeforeAll/AfterAll idea - is having them introduces any anti-pattern?

Thank you!
D.

**Comment by onsi** [comment]
I see.  There is no `BeforeAll/AfterAll` as you describe it -- it sounds like you want a way to set up the world, then invoke `ginkgo watch`, and then tear down the world when you `^C`.  A simple script to set up the database and then tear it down might be the way to go here - but I agree that isn't great because you'll want to have that behavior in each test as well.

Terrible idea: how important is it for you to clean up the database after the test runs?  You could, instead, have the `BeforeSuite`s all only create and populate the database if it isn't ready... that way the first test to run sets it up and none of the other tests have to do any work.  You'll have to make sure the tests don't clean it up afterwards... maybe you could have that be configurable based on an environment variable that you pass in with `ginkgo watch`?  I dunno.. I can try to describe what I'm thinking more clearly if you're interested...

**Comment by mpmlj** [comment]
@onsi 
Thank you, I got the idea.
Could you add BeforeAll/AfterAll functions to Ginkgo or is this a bad thing (some anti-pattern) for some reason? If latter, I would really appreciate your vision on why this is bad!

Thank you!

**Comment by robdimsdale** [comment]
@mpmlj the question about `BeforeAll/AfterAll` was originally raised in https://github.com/onsi/ginkgo/issues/70 - hopefully that should answer your questions

**Comment by mpmlj** [comment]
ok, thank you
