### ISSUE TITLE
Mechanism for broader programmatic skipping before dryRun happens

### ISSUE THREAD

**Issue by jayunit100** [onsi/ginkgo#226]
**it would be great if ginkgo supported a broader array of metadata in the top level test tree, so that the need for runtime skips were minimized.**  Examples 
- skips based on the test file's compiled path
- skips which are detected by the test tree path walker thingy, i.e. if we could 
  `test.EditSuite(func(subjectNode SubjectNode){ return true }`

These are just some rough ideas:  Im not sure what the best way to add more information content to the test walker is...

_concretely, here is what im trying to avoid_ 
- we are  using `BeforeEach` coupled with a `Skip()` to skip 100s of tests,  The before each is quite simple: It just checks file names.  This should be calculable before runtime. 
- thus: we cant use dryRun at all to validate what is being skipped before a long test run starts.  

Is there a way to do a last minute filter before all the tests run , which dryRun will be able to be aware of? Or maybe send it a function?

Since this is a somewhat deep question, i guess maybe only @onsi will know :)

**Comment by jayunit100** [comment]
One possible way to skip @smarterclayton has used is the FileName metadata.  It appears to only be referenced at runtime, however, and not during dryRun.   
```
type CodeLocation struct {
	FileName       string
	LineNumber     int
	FullStackTrace string
}
```
I've never really dived much into ginkgo internals : so any clues would be useful, but I think there might be a way we add a top level option which is able to filter tests based on the codeLocation metadata (i.e. FileName).  if we can do that then,

**Comment by jayunit100** [comment]
ah actually `newRunner`  inside of leafnodes/runner.go gets called via dryRunner , which indeed has access to codeLocation etc.  So i guess rigging codeLocation into the top level runner path won't be too bad.

**Comment by jayunit100** [comment]
`SynchronizedBeforeSuite` might do the trick?

**Comment by jayunit100** [comment]
`SynchronizedBeforeSuite` might do the trick? update:SubjectNodes have BasicNodes which have code paths in em.  So i think this is indeed readily available during pre processing.

**Comment by jayunit100** [comment]
Okay, i figured out a simple way to do what i want:   Updating the focus implementation to match on a string that includes the file name, gives you tons of flexibility in pretest skipping... like so:

ginkgo/internal/spec/specs.go 

`toMatch := []byte(description + " " + spec.ConcatenatedString() + " " +spec.subject.CodeLocation().FileName)`.

I can craft a PR for this as well, adding it into `skip` as well as `focus` as a filter option.

Thoughts @onsi ?

**Comment by onsi** [comment]
I'm open to this sort of PR though I'd prefer a separate `ginkgo.focusFiles` or `ginkgo.skipFiles` to avoid breaking existing behavior in subtle ways.

But.

This all feels really... odd.  Why not annotate your `Describe`s and `Context`s with tags, instead.  I prefer:

```golang
Describe("{foo} {bar} Something magical", func() {})
```

This allows you to `ginkgo --focus="{foo}"` or `ginkgo --skip="{bar}"`

Are there reasons that sort of approach wouldn't work?  I'd argue that it's more explicit?

Do you have some concrete examples of focuses/skips that you could point me to?

**Comment by jayunit100** [comment]
Hi! Ok, yes A concrete example will be useful here...

In openshift we have 100 or so tests which are packaged into the same binary as 100 or so kubernetes tests.

Right now there is some concern in the community that it isn't a good idea to tag all the tests. So the current mechanism for separating the tests is to do a FileName check at runtime and inspect the package path, and interpret ginkgo tags to do a runtime skip.

This causes dryRun to not be as useful.  

So, I'll open up a PR. I'm hesitant to add a new option unless it really does enforce hierarchy of path filter -> spec.

Because otherwise, a a new option will confuse the skip and focus tag order of operations stuff.

**Comment by jayunit100** [comment]
@onsi I'll craft the PR as a --filePathFilters=true option, that is OFF be default.  That will be perfectly flexible and explicit and won't break any existing functionality .
- backward compatible
- adds functionality to both focus and skip
- won't collide with existing precedence semantics for focus and skip

**Comment by robdimsdale** [comment]
@jayunit100 assume the PR is https://github.com/onsi/ginkgo/pull/228 ?

Can you expand a little on what you said earlier, specifically:

> Right now there is some concern in the community that it isn't a good idea to tag all the tests.

Which community? What's the rationale behind these thoughts? We use tags as onsi describes above with success, and I don't believe we've run into issues that would be solved with your proposal.

To be clear, I'm not against your PR, just trying to understand the underlying thoughts here.

**Comment by onsi** [comment]
I'm not a huge fan of using the file name for anything other than debugging purposes - if the filename carves out some sort of distinct grouping why not make that explicit in the test description?

Would a more formal tags infrastructure in Ginkgo help assuage these concerns?  You could even cook up your own convention with something like:

```
type Tags []string
func (t *Tags) ComposeWithTitle(title string) string {
    tags := ""
    for _, tag := range t {
        tags += fmt.Sprintf("{%s} ", tag)
    }
    return fmt.Sprintf("%s%s", tags, title)
}

func DescribeWithTags(title string, tags Tags, callback func()) {
    Describe(tags.ComposeWithTitle(title), callback)
}
```

Now, anyone can:

```
var _= DescribeWithTags("Describe something", Tags{"tag1", "tag2"}, func() {
    ...
})
```

And then `ginkgo --focus="{tag1}"

**Comment by jayunit100** [comment]
@robdimsdale @onsi thanks for the feedback, ill explain specifically whats going on.
- Kubernetes has an e2e build product using ginkgo for 100s of test.
- In openshift we extend that e2e build product.
- We have a form of synthetic filtering in openshift which already filters on tests, it doesn't work with DryRun at all and is very problematic when running massive ginkgo runs on 1000 node clusters.

So we have several legacy issues to work around, with large communities which move slowly, and right now, we really need to filter on files for this purpose.  

*yes* a more sophisticated test hierarchy is the long term solution, but in the interim, this option will really clean up alot of issues for us, and presumabely, have no backward effect on other tests.  We can always deprecate it at some point in the future to discourage use.

To be honest, focus, and skip  are all a little bit unnecessary if you have a sufficiently advanced set of test hierarchies, but they are really important to fully support for the time being.

I hope this helps explain the current scenario, I agree - Tag wrappers and Function wrappers are a good workaround to, but we have issues with refactoring those as well in large open source projects with 100s of tests.

**Comment by robdimsdale** [comment]
Commented on the PR at https://github.com/onsi/ginkgo/pull/228
