### ISSUE TITLE
Ginkgo timeouts array: Undocumented functionality?

### ISSUE THREAD

**Issue by jayunit100** [onsi/ginkgo#229]
The ginkgo timeouts array that is sent to `It()` clearly has a purpose, but the parseTimeout function seems to simply grab the first timeout.

What is the purpose of the var args input for ginkgo timeouts?   Maybe its just a  legacy function to keep backward compat?

@onsi maybe we should panic if folks send more than one arg (or i understand it incorrectly).

**Comment by robdimsdale** [comment]
@jayunit100 looking at the [parseTimeout function](https://github.com/onsi/ginkgo/blob/master/ginkgo_dsl.go#L552-L558) it appears you're correct.

I have no context on why this is the case, but I also don't think panicking here is a good idea either.

Have you run into issues passing multiple timeouts into the `It()` method? If so, what were you expecting to happen?

**Comment by onsi** [comment]
The var args is a hack that is used throughout Ginkgo and Gomega.  It makes it possible to *optionally* specify an additional parameter.  It's true that anything beyond the first value is ignored.

**Comment by jayunit100** [comment]
Yup I think a panic is needed then for >1 args

**Comment by robdimsdale** [comment]
I haven't seen any evidence that this is causing issues for people, so I don't feel strongly about failing when more than one is provided.

If you do feel strong, and you want to submit a PR that panics (or better still `Expect(len(args)).To(BeNumerically("<=",1))`) everywhere varargs are used in this manner as optional, then we can merge that.

If not, we will close this issue without change.

**Comment by onsi** [comment]
I'm not sure this is super valuable.  Improving the documentation might be sufficient?

**Comment by jayunit100** [comment]
At least we can start with the docs.  I feel strongly that functions shouldnt silently ignore arguments, but if others don't feel that way i wont press the issue.

**Comment by robdimsdale** [comment]
@jayunit100 I'm going to close this issue as it's been over two weeks without any update. If you'd like to continue this conversation or submit a PR please feel free to open a new issue.

Thanks,
Rob
