### ISSUE TITLE
Chaos monkey style tests

### ISSUE THREAD

**Issue by ihmccreery** [onsi/ginkgo#230]
For https://github.com/kubernetes/kubernetes/issues/15131, I would like to be able to make some assertions in parallel across some sort of mutation of the system under test (in this case, upgrading compoents).  I would like to do something like the following:

``` go
SetupTest1()
SetupTest2()

c1 := make(chan int)
c2 := make(chan int)
go func() {
  result1 := Test1(c1)
}
go func() {
  result2 := Test2(c2)
}
MutateSystemUnderTest()
c1 <- 1 // tell Test1 that upgrade is finished; stop testing
c2 <- 1 // tell Test2 that upgrade is finished; stop testing
// wait for Test1 and Test2 to complete

assert(result1)
assert(result2)
```

Given the constraints of Ginkgo, the best I've come up with is doing the whole thing in a `BeforeEach` block, and then having very short `It` blocks that just assert results, but that's really ugly.

Have you looked at tests like this before?

**Comment by ihmccreery** [comment]
To clarify, I need to be able to do these things in parallel because `MutateSystemUnderTest` takes `O(minutes)`, and the number of assertions I need to make is large, so doing this over and over again in serial is infeasible.

**Comment by ihmccreery** [comment]
Also, if you're interested in adding this functionality, I'd be happy to contribute.  Wanted to get a conversation going before writing a bunch of code.

**Comment by robdimsdale** [comment]
@ihmccreery I don't think I've seen ginkgo/gomega used in this manner before.

I think you could do this asynchronously starting the mutation logic in the `BeforeSuite`, and running the `It`s in parallel, signaling each test when the mutation is complete. Something like:

```
var (
  mutationComplete customAtomicBoolType
)

BeforeSuite(func(){
  AsynchronouslyMutateState(&mutationComplete)
})

It("does thing 1",func(){
  for {
    if mutationComplete {
      Expect(object1.State()).To(Equal(endState))
    } else {
      Expect(object1.State()).To(Equal(intermediateState))
    }
  }
})

It("does thing 2",func(){
  // Same as above test for object 2 - probably refactor into common logic.
})
```

This isn't very elegant, and requires a custom atomic bool type.

Could you provide an example of how you've achieved this with `BeforeEach`? I suspect it looks similar to my example above.

**Comment by ihmccreery** [comment]
@robdimsdale My `BeforeEach` solution is basically what I described above, where just the two `assert`s are in the `It`, and everything else is in `BeforeEach`.


```go
BeforeEach(func() {
  SetupTest1()
  SetupTest2()

  c1 := make(chan int)
  c2 := make(chan int)
  go func() {
    result1 := Test1(c1)
  }
  go func() {
    result2 := Test2(c2)
  }
  MutateSystemUnderTest()
  c1 <- 1 // tell Test1 that upgrade is finished; stop testing
  c2 <- 1 // tell Test2 that upgrade is finished; stop testing
  // wait for Test1 and Test2 to complete
})

It(func() {
  assert(result1)
})

It(func() {
  assert(result2)
})
```

At this point, we're basically getting no benefit from the `Ginkgo` structure, just piggybacking off of it to get goodies like the runner and JUnit.

Your solution comes close, but we need to actually start checking the state from before we start `AsynchronouslyMutateState`.  One could modify your solution to have `AsynchronouslyMutateState` wait for all the `It`s to pipe back acknowledgement that they've begun checking `intermediateState` via a `chan`, but that's even more hideous.

**Comment by ihmccreery** [comment]
Ah, I just realized the `BeforeEach` solution won't work either, because `BeforeEach` will run before each (duh), not just once.

I will continue working.  @onsi or @robdimsdale, do you all think this is the kind of thing that you'd like to extend Ginkgo to be able to do, or is this outside of the scope of this project?  It'd be nice to know as I'm working on this if you all want to collaborate.

**Comment by robdimsdale** [comment]
@ihmccreery I don't really have a good idea how you would implement this in ginkgo without significant restructuring of the internals. If you can figure out a way to make this work in a backwards-compatible manner it seems like desirable behavior and we would probably merge a PR.

We're quite pressed for time at the moment, so we're probably not able to help too much; apologies for that.

**Comment by onsi** [comment]
With this sort of thing it's tempting to get very precise and controlled with your tests but what you probably *actually* want is to embrace the chaos.

1. Kick off the upgrade
2. While the upgrade is running, repeatedly run a set of tests
3. When the upgrade completes, stop running tests and evaluate whether any failed

Ginkgo's going to fight you here.  It wants to compute the testing tree up-front and then run through it.  There's no way for some sort of external state to modify the repetition or timing of a part of the tree as the tree is computed up-front.

You could try to hack around with something like:

```golang
Describe("upgrades", func() {
    var c chan struct{}
    var once sync.Once
    BeforeEach(func() {
        sync.Once.Do(func() {
             c = make(chan struct{})
             go func() {
                 DoUpgrade()
                 close(c)
              }()
        })
    })

    for i := 0 ; i < NUM_LOOPS ; i++ {
         It("test1", func() {
              select {
              <-c:
                   return
              default:
              }
              //assertions
         })

         It("test2", func() {
              select {
              <-c:
                   return
              default:
              }
              //assertions
         })
    }
})
```

Crazy right?  This'll basically work but has a number of problems:

1. you'll pollute the testing tree with very many tests.
2. you'll need to pick `NUM_LOOPS` carefully.  Too few and you might burn through the `It`s and leave `DoUpgrade` running.  Leaking this behavior between tests would be very bad.
3. you can't use `ginkgo --randomizeAllSpecs` (which I *highly* recommend using in these sorts of integration tests).  If you do randomize all specs then tests that *shouldn't* run in the upgrade context will.

There is another way:

```golang
Describe("upgrades", func() {
    var c chan struct{}
    BeforeEach(func() {
         c = make(chan struct{})
         go func() {
             DoUpgrade()
             close(c)
         }()
    })

   It("should pass a battery of tests continuously", func() {
       while true {
           select {
           <-c:
              return
           default:
           }
          command := exec.Command("/path/to/tests")
          session, err := gexec.Start(command, GinkgoWriter, GinkgoWriter)
          Ω(err).ShouldNot(HaveOccurred())
          Eventually(session).Should(gexec.Exit(0))
       }
   })

   AfterEach(func() {
         <-c //block in case the It fails, don't want to leak DoUpgrade()
   })
})
```

Hacky!  But it works.  Basically, during the upgrade *run a separate test suite* repeatedly

You could even get fancy and have *this* test suite be the test suite you run but with different `--focus` flags.  Lot's of ways to go about it.
