### ISSUE TITLE
ginkgo generate flag to use normal package name.

### ISSUE THREAD

**Issue by james-lawrence** [onsi/ginkgo#232]
I understand the argument for having tests only testing the exposed api especially in behaviour testing
however, in practice I've found it annoying and more frustrating when attempting to test that internal function.

wondering if you'd even accept a PR for generate to take a flag (or maybe as a subcommand) to generate
a testing file that is within the normal package. Maybe it gives it a different name? i.e.)
ginkgo generate internal book.go -> book_internal_test.go

**Comment by robdimsdale** [comment]
@james-lawrence There was a PR to do this by default at https://github.com/onsi/ginkgo/pull/207 and after some conversation in that thread, it was rejected. I understand you are proposing a flag to optionally support this behavior, instead of making it the default, but I don't think we want ginkgo to support this functionality at all.

Allowing tests to access internal implementations is a poor testing practice, as the tests should provide a guarantee against the same API the consumers will call, therefore ginkgo should not facilitate this.

**Comment by james-lawrence** [comment]
@robdimsdale you're assertion its poor testing practice is an opinion. its fine you want to hold it but others do not share it, including those who implement the go runtime.

Testing should guarantee the API but also when developing there internals that are not exposed to the outside packages that need to be tested.

not only does it make determining the location of the bugs easier but its a more pragmatic approach by admitting there isn't a single testing module that fits all use cases.

**Comment by robdimsdale** [comment]
@james-lawrence you're correct, my statement that testing internals is a poor testing practice is an opinion I (and many others) hold. Ginkgo/Gomega is an opinionated test framework, created primarily from the opinion that the existing testing infrastructure in golang didn't offer the expressiveness and flexibility to write tests the way we want. Another opinion we hold is that testing internals is not something we want to be actively encouraging. The previous PR 

That being said, it's not surprising to us to see ginkgo/gomega used in ways we didn't anticipate, and wouldn't necessarily use ourselves. We want to see adoption of these projects, so we want to meet the requirements of current and potential users.

I agree that the cost of maintaining the proposed feature set is low, and it sounds like the frustration caused to you by the feature being missing is higher than the frustration we would feel at including and supporting it, so let's talk about the interface of the proposed solution and make sure we're on the same page about the way it looks and feels.

@onsi Given what you said in #207 I assume you have no objections:

> I don't want the default to change. I'd be happy to accept a PR that adds a flag to both generate and bootstrap to allow users to generate files without the test suffix.

I think we'd like to see something like `ginkgo generate --internal book.go` where `--internal` is an optional boolean flag, defaulting to false. Whether set or not it would write to the same file: `book_test.go` (I see no need to separate them out with separate filenames unless I'm missing something here). When set, it would write the package without the `_test` suffix. When missing or unset we see the existing behavior. For consistency I'd like to see the same behavior in `bootstrap` as well as `generate`.

Does that sound like the sort of solution you had in mind?

Thanks for engaging in dialogue, explaining your needs and use-cases in a way that helps me understand your requirements while also recognizing our opinions and preferences too.

**Comment by onsi** [comment]
I like `ginkgo generate --internal` and I think what @robdimsdale has described is correct.

(when I said "without the test suffix" I meant on the package, not the file)

**Comment by james-lawrence** [comment]
yup sounds close enough to me. I'll look at implementing it next weekend.

**Comment by james-lawrence** [comment]
sorry life has been busy, still planning on doing this might be a few weeks though =)

**Comment by ches** [comment]
I believe this can be closed 🎉

**Comment by robdimsdale** [comment]
@ches looks like you're right - thanks for bumping!
