### ISSUE TITLE
Help with testing multiple implementations

### ISSUE THREAD

**Issue by tnine** [onsi/ginkgo#236]
Hey guys,
  Sorry to open an issue for this, I couldn't find an email or IRC channel.  I'm really enjoying learning Ginkgo, and I have a problem I need a hand finding a solution.  I have an interface I want to test via Describe and IT.  This interface will have several implementations.  I'd like to re-use a single Describe, and execute all tests in the Describe on each implementation.

I'm not sure that BeforeSuite and/or BeforeEach meet my needs.  I'm not sure how to set this up in Ginkgo, would it be possible to provide some sort of example?  I can update the documentation and contribute it once I have it functioning correctly.

Thanks in advance!

**Comment by jim-slattery-rs** [comment]
Here you go, there are some options described here:
https://onsi.github.io/ginkgo/#shared-example-patterns

**Comment by robdimsdale** [comment]
@jim-slattery-rs thanks for the help. @tnine does this answer your question? Can we help more on this topic?

**Comment by angadn** [comment]
This is how I've set mine up finally:

```
var _ = Describe("MyInterface Implementation", func() {
    Describe("SpecificImplementation", func() {
        var inject MyInterface
        describe(inject)
    })
})

func describe(test MyInterface) {
    Describe...
}
```
