### ISSUE TITLE
Coverage result into on single file for processing

### ISSUE THREAD

**Issue by mantzas** [onsi/ginkgo#238]
When running the cover flag the files will be created in ach package folder.
It would be nice if we had a switch that would merge all these files into one file.
With this we could send the coverage report to sites that do coverage analysis simple and easy instead of running custom scripts in order to generate the file.

**Comment by robdimsdale** [comment]
@mantzas do you think this is covered (no pun intended) by #66 and #89 ? If so, are happy with closing this issue so we can keep the discussion in one place?

Thanks,
Rob

**Comment by mantzas** [comment]
yes it is! i am closing the issue. thanks
