### ISSUE TITLE
please tag new release

### ISSUE THREAD

**Issue by onlyjob** [onsi/ginkgo#245]
Latest release 1.2.0 was a while ago and now more and more Go applications vendor unreleased post-1.2.0 snapshots of _ginkgo_ and _gomega_ due to multiple fixes and improvements.

New release would be very helpful. Thanks.

**Comment by robdimsdale** [comment]
@onlyjob see similar comment in https://github.com/onsi/gomega/issues/144 - repeated here for convenience.

>I will let @onsi speak to this, but my interpretation is that we don't have release versions because all commits are good so you can safely use the latest SHA.

>Specific releases would provide clarity, I agree, but is there a more specific problem you're looking to solve?

**Comment by onsi** [comment]
Closing this out as I'm trying to more regularly tag new releases.
