### ISSUE TITLE
suite_test.go has some flaky tests

### ISSUE THREAD

**Issue by TheTincho** [onsi/ginkgo#247]
Hi,

I am the Debian maintainer for ginkgo. Recently I got a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819214) of ginkgo failing to build, due to a test that fails under heavy load.

The problematic line is https://github.com/onsi/ginkgo/blob/master/internal/suite/suite_test.go#L133 and the failure can be reproduced pretty consistently if running the tests with nice while hogging the cpu with some intensive task.

Can this test be made deterministic?

Thanks.

**Comment by onsi** [comment]
That should do it..

**Comment by TheTincho** [comment]
@onsi, thanks for looking at this.

My only worry is that it stays being a timing-dependant test. I can imagine that in some extreme cases, this can still be a problem. Isn't there a way to make it completely deterministic?

Thanks!

**Comment by onsi** [comment]
Not really.  The test is asserting that a method that does some timing, did some timing.  Honestly I could just delete it - very low value.  Compromise:  if it exhibits flakiness again, I kill it?





On Thu, Apr 7, 2016 at 2:55 AM -0700, "Martín Ferrari" <notifications@github.com> wrote:












@onsi, thanks for looking at this.



My only worry is that it stays being a timing-dependant test. I can imagine that in some extreme cases, this can still be a problem. Isn't there a way to make it completely deterministic?



Thanks!

**Comment by TheTincho** [comment]
On 07/04/16 16:08, Onsi Fakhouri wrote:
> Not really.  The test is asserting that a method that does some timing,
> did some timing.  Honestly I could just delete it - very low value.
>  Compromise:  if it exhibits flakiness again, I kill it?

Fair enough. Thanks!

-- 
Martín Ferrari (Tincho)
