### ISSUE TITLE
Proposal: Skip the `vendor` directory by default when using go 1.6+

### ISSUE THREAD

**Issue by sykesm** [onsi/ginkgo#249]
When dependencies are included, `ginkgo -r` tries to test them too.  We're using `ginkgo -r --skipPackage ./vendor` to avoid this behavior today.

Happy to create a PR if you're interested in this.

Thanks.
@sykesm & @rosenhouse

**Comment by robdimsdale** [comment]
@sykesm @rosenhouse check your version of ginkgo executable is up to date - this issue was raised and fixed in https://github.com/onsi/ginkgo/issues/187 (and again in https://github.com/onsi/ginkgo/issues/211) and should be fixed in newer versions of ginkgo.

Thanks,
Rob

**Comment by sykesm** [comment]
The [code] is only looking at the `GO15VENDOREXPERIMENT` environment variable and isn't taking the go version into account. With go 1.6, the vendor support is enabled by default.

Thanks.

[code]: https://github.com/onsi/ginkgo/blob/master/ginkgo/testsuite/test_suite.go#L52-L58

**Comment by robdimsdale** [comment]
Are you saying that you are using golang 1.6 and not observing the desired behavior by default (i.e. ginkgo is not skipping `./vendor`). If so, a PR would be welcome.

**Comment by onsi** [comment]
Yep, would love to have a PR for this.  I believe the original PR left the
1.6 case dangling.  We should circle back on that.  Thanks @sykesm!

**Comment by james-lawrence** [comment]
this is resolved with #253 being merged.

**Comment by robdimsdale** [comment]
@james-lawrence thanks for the update - closing this issue now. @sykesm feel free to re-open if you see anything untoward.
