### ISSUE TITLE
JUnitReporter does not handle running tests in parallel

### ISSUE THREAD

**Issue by jchauncey** [onsi/ginkgo#251]
When I run my test suite in parallel using the JUnitReporter the only values that are captured are the last node to return.

**Comment by robdimsdale** [comment]
@jchauncey can you elaborate on what you mean here? Can you provide some example output of what you saw happened and what you would expect to happen?

Thanks,
Rob

**Comment by jchauncey** [comment]
Basically when a node finishes it writes data to the file which overrides
the existing data. We basically write several files out now with random
filenames to get around this but would be nice just to have one file.

**Comment by ixdy** [comment]
@jchauncey we've been using the junit reporter + parallel mode without issue for a while. You'll need to use `config.GinkgoConfig.ParallelNode` in the filename, though, as noted in [the documentation](https://onsi.github.io/ginkgo/#generating-junit-xml-output).

**Comment by onsi** [comment]
yep, the approach that @ixdy proposes is the correct one.
