### ISSUE TITLE
Docs: Small, low-contrast text is hard to read

### ISSUE THREAD

**Issue by sgravrock** [onsi/ginkgo#255]
I don't know if this is the right place to report this kind of problem, but some of the text on http://onsi.github.io/ginkgo/ is hard for me to read:

![ginkgo docs](https://cloud.githubusercontent.com/assets/2879775/15093208/2509e254-1435-11e6-9d5e-b57c8a27fc8f.png)

Notice how the text in the red boxes doesn't contrast very much with the background. The green background image makes it worse, but such light text could be problematic even on a plain white background. The size is an issue too. Method names in the menu are rendered at 10.53px in my browser (Chrome 49.0.2623.112, OS X) which is well into squinting territory for me.

I'd suggest changing either the text color or the background colors to have higher contrast, and avoiding font sizes smaller than about 12px.

**Comment by blgm** [comment]
Hi @sgravrock. Thank you for raising this. Sorry that's it taken 4 years for someone to get round to looking at it. I've made some changes to the CSS that make the text look clearer to me. How does it for for you?

**Comment by sgravrock** [comment]
Thanks for tackling this. It's much better now and works well for my eyes. To make it accessible to everyone I recommend going for a contrast ratio of [4.5:1](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) (I measure it at 2:1 currently), but that might require more significant design changes.
