### ISSUE TITLE
covermode not supported in ginkgo

### ISSUE THREAD

**Issue by devghosh** [onsi/ginkgo#256]
My project structure has 
src/node/.. , contains code
src/test/system, contains bdd to test my project

For getting the coverage of files inside src/node by executing bdd test, I have to perform following steps:
_go test -c test/system -covermode=count -coverpkg ./...
./system.test -test.coverprofile coverage.cov
go tool cover -html=coverage.cov -o coverage.html_

I tried with ginkgo: 
_ginkgo -r -v=true -cover=true ./src/test/_
But it shows total coverage for only test files. Also no coverage file is generated.

Is there any way in ginkgo to achieve the same ?

**Comment by allenluce** [comment]
This should be taken care of by #281.
