### ISSUE TITLE
--failFast should cause all nodes to exit when running in parallel

### ISSUE THREAD

**Issue by zachgersh** [onsi/ginkgo#257]
Back a long, long time ago when this feature was first implemented @onsi stated that with `--failFast` on only the node that was running would exit (all other nodes would continue to run):

https://github.com/onsi/ginkgo/issues/56

Imagine my surprise when I wanted the whole test suite I was running in parallel, which takes around 35 minutes, to exit immediately on the first failure (I have to start it over on any failure). 

I would propose that we actually have ginkgo kill all of the nodes when `--failFast` is passed if ANY one of the nodes reports a failure.

Thoughts?

**Comment by leodotcloud** [comment]
+1

**Comment by zachgersh** [comment]
@onsi - I believe I can close this with the refactor you did to how nodes work. Is that correct?

**Comment by onsi** [comment]
Yep!

**Comment by wfernandes** [comment]
Just wanted to get some confirmation on this. Does `--failFast` now kill all the nodes when running in parallel?
