### ISSUE TITLE
Flake mitigation

### ISSUE THREAD

**Issue by lavalamp** [onsi/ginkgo#260]
My goal here is to allow some grace around flaky tests. Unfortunately, they are a fact of life for the Kubernetes project. Sometimes that's due to programmer error and sometimes due to downstream dependencies, etc--I'm not arguing that I want flaky tests, just that I need to my CI system to understand the difference between "fails occasionally" and "totally broken". So I want to implement a mode that does something like this:

You'd call something like `ginkgo ... --test-tries=2 --test-required-passes=1 ...`. This tells ginkgo that each test is allowed two attempts and must pass at least once. Then ginkgo, after it runs a spec that fails, would run it again. If it passes the second time, then the entire suite is considered to have passed, but the individual failure is still reported in the JUnit output.

Does this seem like a patch that would be accepted?

**Comment by lavalamp** [comment]
@onsi I'm looking at implementing this. Do you have suggestions on how to present this to the reporter.Reporter interface?

**Comment by tedsuo** [comment]
As an alternative, what do you think about reporting that allows you to consume the failed tests, and re-run them yourself? Would that be too onerous?

The approach you're proposing is not without merit. If we did it that way, i think I would also want a different signal on exit, so CI systems can indicate that the tests only "passed".

**Comment by lavalamp** [comment]
I want to rerun without having to go through BeforeSuite/AfterSuite. I
think what I'm proposing will still report the failures in e.g. JUnit while
claiming that the suite passed. I need that, anyway, to file issues about
the failures.

**Comment by Amit-PivotalLabs** [comment]
@lavalamp:

> I want to rerun without having to go through BeforeSuite/AfterSuite.

Fair point.

@tedsuo:

> If we did it that way, i think I would also want a different signal on exit, so CI systems can indicate that the tests only "passed".

I believe most CI systems only know passed and failed, and won't know a different exit code means scare-quotes-"passed".  I imagine if don't want test runs with retried flakes in them to count as passing builds, you simply wouldn't use the flag in your build.  I'd be curious to hear @ryanmoran's thoughts on this proposal.

**Comment by glyn** [comment]
Stipulating retries at the level of the whole build is too risky from my perspective. What if true non-deterministic bugs creep in? Then the build would likely still pass. Wouldn't it be better to identify specific flaky tests as such and supply a per-test retry count (as well as a string which could point to an issue tracker bug, for instance)?

(I wonder if @Amit-PivotalLabs wanted to hear @rmorgan's thoughts?)

**Comment by lavalamp** [comment]
I intend to use this to identify flaky tests in the first place, so requiring an up-front list of known flaky tests wouldn't work for me.

**Comment by tedsuo** [comment]
Those are some valid concerns, all around. 

I ran the following proposal by @onsi and he was down with it:

Ginkgo supports the notion of prefixing `Describe`, `Context`, and `It` blocks to enable special behavior. For example `FIt` and `FDescribe` enable focusing and `XIt` enables skipping. This proposal adds the `R` prefix to enable retries. The new functions are `RIt`, `RDescribe`, and `RContext`. These functions have the following signatures and behavior:

Default to 1 retry:
```go
var flakeyValue = 0

RIt("A flakey test",func() {
  Expect(flakeyValue).ToEqual(1)
  flakeyValue++
})
```

Set the maxRetries value by passing an iteger parameter:
```go
var maxRetries = 2 // easy to set from an environment variable
var flakeyValue = 0

RIt("A flakey test",func() {
  Expect(flakeyValue).ToEqual(1)
  flakeyValue++
}, maxRetries)
```

For async tests, maxRetries is the final parameter:
```go
var testTimeout = 0.2
var maxRetries = 2
var flakeyValue = 0

RIt("A flakey test",func(done Done) {
  Expect(flakeyValue).ToEqual(1)
  flakeyValue++
  done()
}, testTimeout, maxRetries)
```

If a retry is triggered, and then passes, ginkgo will exit with a special 198 error code:

```go
const GINKGO_RETRY_EXIT_CODE = 198
```

The command line flag `-failOnRetry=false` will cause ginkgo to exit 0. The default value is `true`.

This feels like a good middle ground, as it supports multiple levels of granularity, and requires a modicum of thought on the part of the developer without being burdensome.

**Comment by lavalamp** [comment]
So if it went that way, I'd be using Rxx everywhere. I don't think I want max retries to differ by test case, I don't want that boilerplate if possible.

**Comment by Amit-PivotalLabs** [comment]
The use cases I've seen for this are when your environment is flaky and out
of your control, not when individual tests are flaky. The "RIt" proposal
doesn't solve the environment flakiness issue, which I think is the main
issue at hand.

**Comment by lavalamp** [comment]
Yes, I agree. Individual tests that are bad should be fixed ASAP. In my case I just can't fail everyone else's PRs while I wait.

**Comment by tedsuo** [comment]
You can use `RDescribe`, so you do not need to put `RIt` everywhere. We could add a `defaultMaxRetries=4` flag could help with the rest of the boilerplate. Considering that your usecase is not the norm, a small amount of boilerplate should be acceptable. That said, if the `R` prefix is not solving any existing usecase effectively, we can keep looking.

Possibly a combo of a `maxRetries` and a `failOnRetry` flag is okay, and we can bake visualizations of this behavior into Concourse. `test-required-passes` doesn't make a lot of sense, unless your intent was that _all_ tests are retried a `test-tries` number of times?

@lavalamp, can you describe you CI issues in a bit more detail? I take it you plan on reporting the problems in some manner, and have some mechanism for proving it's the environment's fault, and have another mechanism for proving that the tests and the code are high quality?

@Amit-PivotalLabs, can you get more feedback from CF Release Engineering as to their use-case? For example, isn't it just ssh issues in their case, and thus they would only want to retry the ssh tests?

**Comment by lavalamp** [comment]
But I want things retried at the smallest level of granularity, would RDescribe propagate that way?

A global default for number of retries is more palatable.

Our (Kubernetes's) e2e testing is done via ginkgo. It runs on every PR and has to pass. Often, it fails on people for reasons that are not their fault. Right now, they have to identify an issue to ask for a retest. I want to instead rerun just the failures (for efficiency) and file issues automatically on their behalf (another system will make sure that the issues get fixed). This is a huge, huge pain point for our contributors.

We want to run even more stuff as presubmit runs. If you do the math, the flake rate just has to get impossibly low for people to have a reasonable experience this way. So we have to go the other way, and make the system make progress in the face of buggy tests. (And of course, self-correct to make the tests not buggy, but that's a separate problem.)

This means the mechanism has to be completely automatic to be useful-- no humans diagnosing things as flakes, our human review time is exceedingly scarce.

**Comment by lavalamp** [comment]
It's also worth noting that I want to run all the tests with this flake detection bit turned *off* in other configurations (in our post-submit tests)--there I already have a strategy for mitigating flakes in place, I compare between run N and N+1. That strategy doesn't work as a presubmit, because there is no N-1 run, and anyway the PR author might have broken something.

**Comment by tedsuo** [comment]
`RDescribe` would propagate in the manner you desire, it's just a level of scoping so that you don't have to say `RIt` everywhere. But I'm coming up short on actual usecases, and thinking of more edge cases (for example, failures in BeforeEach and AfterEach). So I'm starting to agree with just having a command-line option. If we need to scope it down later, we could possibly add a `--retry=REGEX` flag.

Okay, I'm done blocking. Thank you for explaining your setup. Other developers will surely abuse this, but I'm not their mom.

@onsi, any further feedback?

**Comment by Amit-PivotalLabs** [comment]
I agree with @glyn's concern that you might start to use this to deal with flakes that are out of your control, but that this may start to then mask flakes that you should be controlling.  That said, the use case seems reasonable.

If you're getting a lot of contributions, and they all need to pass e2e tests, and the e2e test setup is expensive, and expressed in ginkgo, then maybe the answer is to refactor that?  Perhaps something else should be responsible for maintaining a pool of test environments (assuming that's what your BeforeSuites are doing), and test runs should claim an environment from the pool when it needs it.  The pool can deal with logic of provisioning on demand or keeping hot standbys.

I also have a concern about the `--test-required-passes=1` idea, if it's ever set to anything other than 1.  Let's say you wanted to say every test needs to pass 9 times out of 10 attempts.  Does that mean you run every test at least 9 times?  Or do tests that pass the first time get a "free pass" when they may in fact be flaky, and fail twice if you were to run them 9 or 10 times?

**Comment by lavalamp** [comment]
> Other developers will surely abuse this, but I'm not their mom.

=D lol

> this may start to then mask flakes that you should be controlling

Yeah, agreed, I have another system in the works to get those under control. In a perfect world I wouldn't need this, but in the current world I have 50 PRs a day blocked on this :/

> I also have a concern about the --test-required-passes=1 idea, if it's ever set to anything other than 1

I'm totally fine with leaving that out and just having it always 1. But just for clarity, the way I implemented it it runs the test until it gets N passes or it's mathematically impossible to get N passes. I thought this gives a bit more flexibility but it's totally optional for my use case.

**Comment by lavalamp** [comment]
Any followup on this? #261 implements my original idea. It seems to work. I'm happy to modify as desired, I've got most of the rest of the pieces I need in my stack to make this work and I'd really hate to point at a fork temporarily while we figure this out :)

**Comment by tinygrasshopper** [comment]
Your particular use case does looks fair. But on the other hand I am yet to come across a test runner which provides rerunning of failed test as a feature. Other test runners that I have worked with, provide mechanisms to extend the test runner to handle custom use cases like these. For example in junit test retry logic can be implemented with test 'Rules'. 

I propose rather than adding retrying of test to the "core", expose a way in which a custom test runner strategy could be injected. 

One of the implementations I can think of might look like:

In ginkgo:
```go
type SpecRunnerStrategy func(spec *spec.Spec, reporter reporters.Reporter) bool 

func defaultSpecRunnerStrategy(spec *spec.Spec, reporter reporters.Reporter) bool {
  // Current implementation
  spec.Run()
  return !spec.Failed()
}
var currentSpecRunnerStrategy = defaultSpecRunnerStrategy

func SetSpecRunnerStrategy(s SpecRunnerStrategy) {
  currentSpecRunnerStrategy = s
}

// SpecRunner uses the currentSpecRunnerStrategy to run individual spec...
```

In your code:
```go
func RunSpecMulipleTimesAndCheckThreshold(spec *spec.Spec, reporter reporters.Reporter) bool {
    // Retry logic goes here
}
ginkgo.SetSpecRunnerStrategy(RunSpecsMulipleTimesAndCheckThreshold)
```

Thoughts?

**Comment by lavalamp** [comment]
@tinygrasshopper so it's the responsibility of the SpecRunnerStrategy to call the right things on the reporter? I had to tweak that a bit in my change to get it to work: https://github.com/onsi/ginkgo/pull/261/files#diff-245d401c0f93bef3b7927b60d3418905R175

**Comment by lavalamp** [comment]
I'm fine with redoing my change to look like that but I'd like some buy-in first.

**Comment by onsi** [comment]
ive commented on the pr.  i think the current direction will be fine but am asking for a few tweaks.

**Comment by lavalamp** [comment]
Thanks, appreciate it! I hope to get those done for you late today.

**Comment by ryanmoran** [comment]
@Amit-PivotalLabs I'm just seeing this thread for the first time now.

First impression: "WAT!?!?"
Second impression: "Who am I to mandate that some other developer can't use something like this in their suite".

I would never use a mechanism like this, and would probably look down upon those that did, but I can be judgmental like that up here in my ivory tower.

As for the CF Release Engineering use case, I don't think it would be wise for this to be added to any suites we run. On several occasions, what appeared to be flakey test runs actually exposed issues with our underlying infrastructure that needed to be addressed.

My view on this topic is entirely centered around ensuring we have a test suite that provides feedback. To me, "flakey" is a lazy way of describing that your distributed system is hard to reason about. You say flakey because you don't really understand the problem. For the CF Release Engineering team, much of our mandate is to understand how the system works, and how it is performing as it evolves. For us to paper-over the complexity of that system with an automated retry function would be an admission of failure to understand. We want the flexibility to retry the tests in a quick and simple fashion, but it should still come with a minor bit of pain. That pain is a reminder that something about how the system performs is not correct, or not understood well enough to mitigate the failure in a deliberate fashion.

I think if our team started using something like this, I wouldn't be doing my job.

**Comment by lavalamp** [comment]
I agree, no one should use this. My rough impression is that about half of
our flakes are real system problems.

Unfortunately, there's one of me and 700ish contributors to my project.
It's not fair to them to block their change because some test is flaking,
when they didn't write it, or they don't understand that part of the
system. There's a lot of code in our repo, and few people can fix any
problem it throws at them.

Yes, in an ideal world the flake rate is 0, and you always keep it that way
by holding merges until the tree is fixed. We tried to live in that world
and it mostly just punishes people for trying to contribute to the project,
without actually reducing the incidence of flakes. People who hit a flake
don't fix it, they just rerun, or worse, go away silently. It's open
source; we have no leverage to get different behaviour.

So now we're going to try the world where we live with flakes in the
system, but we track them and monitor them getting fixed. And we'll do
these things with automation because humans are not doing the job.

This is an extremely pragmatic argument. Most projects should not have our
problems and should not use this mechanism.

**Comment by lavalamp** [comment]
My PR was merged and documentation was, also, so I think we can close this. Thanks everyone!
