### ISSUE TITLE
Documentation for pass-through arguments

### ISSUE THREAD

**Issue by mikeatlas** [onsi/ginkgo#265]
In order to effectively use pass-through arguments in my test suite, this took me a bit of guesswork to make work, and could be documented as an example. If you want to pass-through flags from the command line, they need to be evaluated as package-level variables:

Given:

```bash
ginkgo -- -flagname=9001
```

The following code is needed at the package-level;.

```go
var myFlag = func() *int {
	testFlag := flag.Int("flagname", 1234, "help message for flagname")
	flag.Parse()
	fmt.Println("ip has value ", *testFlag)
	return testFlag
}()
```

The parsing can't happen in any `BeforeSuite`, `BeforeEach`, or `Context`, since those are all essentially deferred code that isn't available to whatever initialization hooks Go uses to pass the command line values to the `flag` package.

**Comment by onsi** [comment]
Yes that works @mikeatlas 

My preferred pattern is to define a `func init()`:

```
var myFlag string
func init() {
	flag.StringVar(&myFlag, "my-flag", "", "Heyo")
}
```

That's all you need.  Now `myFlag` will be populated with the passed in flags and made available to your tests.  Note that there's no need to call `flag.Parse()` (sigh... shared globals).  Ginkgo will call that eventually when parsing its own flags.

Are you up for a PR to the docs?  (github pages)

**Comment by mikeatlas** [comment]
You're right, `init()` makes far more sense. I'll create a PR on the gh-pages repo, sure.
