### ISSUE TITLE
Vendor tests run when building in go 1.6+

### ISSUE THREAD

**Issue by chriswhitty** [onsi/ginkgo#273]
We just pulled the latest update and found that the tests for vendored packages are now running. (we're using go1.6)

It looks like the cause is [this commit](https://github.com/onsi/ginkgo/pull/272). In the [docs](https://golang.org/pkg/go/build/)  the build tag go1.6 is documented as: `"go1.6", from Go version 1.6 onward` 

This suggests that the previous behavior was correct.

We are working around this by setting the the environment variable: `GO15VENDOREXPERIMENT=1`

**Comment by onsi** [comment]
hmmm... thanks @chriswhitty will take a look soon

**Comment by robdimsdale** [comment]
We reverted that bad commit - thanks for the heads-up and sorry for the inconvenience! This should be fixed now.

**Comment by chriswhitty** [comment]
No problem, thanks for the fix.
