### ISSUE TITLE
Pass through -work to go build

### ISSUE THREAD

**Issue by squeedee** [onsi/ginkgo#277]
We had a test polution that i suspected was removing the intermediary `go build` files. I wanted to run `ginkgo -r -work` to prove it, but that's not an option.

I admit that `go test -work ./...` get's me there, but theres a small but time-consuming cognitive dissonance switching from ginkgo's syntax to go test's packages spec.

**Comment by onsi** [comment]
I think the flag gets passed in now but Ginkgo doesn't print out the compilation output.  Will fix.

**Comment by onsi** [comment]
this is now fixed.
