### ISSUE TITLE
Why not use the `go help packages` package spec

### ISSUE THREAD

**Issue by squeedee** [onsi/ginkgo#278]
When writing #277 I realised it's inconsistent for ginkgo to use `-r` and/or requiring the packages listed out as though they are `import` statements.

So why did you eschew the packages spec (`go help packages`?)
I can understand that it's not fun to [implement](https://github.com/bunniesandbeatings/go-flavor-parser/blob/master/parser/parser.go#L35), but I was curious for your feelings about it.

**Comment by ches** [comment]
This confused me too. Concretely, trying my first `gexec` spec:

```
$ go test ./cmd/...
ok      github.com/go-kafka/connect/cmd/kafka-connect   1.993s

$ ginkgo ./cmd/...
Found no test suites
For usage instructions:
        ginkgo help

$ ginkgo -r ./cmd/...
Found no test suites
For usage instructions:
        ginkgo help

$ ginkgo -r ./cmd
Running Suite: kafka-connect CLI Suite
======================================
Random Seed: 1470468089
Will run 1 of 1 specs

•
Ran 1 of 1 Specs in 2.004 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Ginkgo ran 1 suite in 4.437792501s
Test Suite Passed
```

**Comment by onsi** [comment]
I believe this is now fixed
