### ISSUE TITLE
Expose spec suite randomization seed to test code

### ISSUE THREAD

**Issue by jawnsy** [onsi/ginkgo#286]
Hello maintainer,

Thanks for your work and for sharing this great library. We're just starting to play with ginkgo (with gomega and agouti) and things are great so far. I particularly like that specs are executed in randomized order by default, with a seed provided to enable repeatable test runs, as this was a similar technique we were exploring for randomization in our own codebase.

Please consider exposing this seed to test code (for example, the code that invokes `gk.RunSpecs`), as it would be convenient to have a single seed that controls all nondeterministic aspects of the test.

Jonathan

PS: I also noticed that the default behaviour is to use the current system time for the seed, and I wonder if it would be useful to combine this with other data, like the current process ID? I can't really think of any reason why the current scheme might be problematic, though.

**Comment by onsi** [comment]
Hey @jawnsy - glad to hear you are enjoying Ginkgo, Gomega and Agouti!

You can actually access the seed from test code.  It's a bit ugly (globals... blech) but if you import the `github.com/onsi/ginkgo/config` package you can get to it via `config.GinkgoConfig.RandomSeed`

**Comment by onsi** [comment]
and, yeah, I don't think there's any harm in using the current time.  Seemed like the simplest thing to do at the time.

**Comment by jawnsy** [comment]
Hey @onsi, that's awesome, thanks for that info & your very quick reply, I'll give it a shot!

If you can share your thoughts on how to best modify the code to expose this, I'd be happy to work on a PR - it's the least we can do, as beneficiaries of your work :smile: Fair warning, I'm a relative newbie to Go, which is probably why I wasn't able to find that global myself :laughing:

I switched over some of our code to use `time.Now().UnixNano()` for nanosecond-resolution timestamps, which seems pretty low-risk, and would make seed collisions effectively impossible. I'd be happy to submit a PR if you'd like.

cc my much smarter colleague, @ironcladlou

**Comment by onsi** [comment]
:) if you'd like you can add a `GinkgoRandomSeed` identical to `GinkgoParallelNode` here: 
https://github.com/onsi/ginkgo/blob/master/ginkgo_dsl.go#L71-L75

I'm not 100% convinced we need to worry too much about seed collision (what's the harm?) and the UnixNano numbers are pretty long.  Any strong reasons driving you towards it?

**Comment by jawnsy** [comment]
Nope, no real reason - just thinking out loud. If your tests run quickly and you run them twice in rapid succession, then you can end up with two identical seeds. We can shorten the displayed seed value by using a different encoding (hex?) and/or dropping the most significant bits, as they aren't going to change much between runs. As I don't have great reasons for making that change, it's fair to leave them as-is until someone actually encounters a problem in practice :)

**Comment by onsi** [comment]
yeah, I'd prefer to leave them as is.  But true if you are using something like `ginkgo --untilItFails` you'll have test runs with similar seeds if they run in the same second.

**Comment by jawnsy** [comment]
Created https://github.com/onsi/ginkgo/pull/293
