### ISSUE TITLE
can you add "incremental test" feature?

### ISSUE THREAD

**Issue by ddwolf** [onsi/ginkgo#289]
I.E. I modified two files and these two files only affect two test case, when I run 

``` bash
ginkgo -r some/package --someoption
```

only two test cases would run.

Can you add this feature?

~thks

**Comment by robdimsdale** [comment]
Hi @ddwolf, interesting question. How would you do this in practice? I am aware that some testing frameworks support this, but I'm not sure how they implement this logic. Do you have some ideas? We would be happy to walk through the changes needed if you were willing to submit a PR.

**Comment by ddwolf** [comment]
hi @robdimsdale thks for replying.
I think this kind of "incremental testing" can only work for file-level, not testcase-level,do you know of bazel from google? bazel can do every aspect of incremental build only if you have a proper dependency tree described in the  BUILD files, but google dont suggest using bazel in projects using golang.

**Comment by robdimsdale** [comment]
Thanks for that info. Are you aware of `ginkgo watch`? It will detect changes and re-run tests automatically. It sounds like that has some functionality you'd like, but it will run all the tests, not just the specific ones that are impact. You can read the docs [here](https://onsi.github.io/ginkgo/#watching-for-changes) ?

**Comment by ddwolf** [comment]
@robdimsdale sounds interesting, but my goal is to speed up the build process, include compile/staticCheck/test/..., now we already have incremental compile/pack, but incremental test.

**Comment by robdimsdale** [comment]
Ok makes sense. This would be a useful feature to have, especially when combined with `ginkgo watch`. Realistically we're probably not going to be able to implement it ourselves as we don't have the bandwidth, but we'd be happy to walk you through a PR if you would like?

If not, we will probably close this issue, but would be open to such a PR from yourself or others in the future.

**Comment by ddwolf** [comment]
@robdimsdale OK, thanks for your patient replies.

**Comment by onsi** [comment]
Closing this out.  `ginkgo watch` gets us partway to this functionality.
