### ISSUE TITLE
How do I exclude the vendor folder on ginkgo watch?

### ISSUE THREAD

**Issue by hermanccw** [onsi/ginkgo#292]
trying ginkgo watch -depth 0 didn't work for me.

**Comment by robdimsdale** [comment]
@hermanccw are you running the most up-to-date version of `ginkgo`? There were some issues around `vendor` that were fixed a few months back.

I cannot reproduce your problem; when I `ginkgo watch -r` I don't see anything under `vendor` in the message:

```
watching x suites:
```

and when I edit an existing file under `vendor` I don't see any tests run.

**Comment by hermanccw** [comment]
@robdimsdale, look at the last commit in our ginkgo folder (under vendor), it is `7d3240191d7b2311b60090fcbc96e56bffc45ec0` which is super old, so I guess that's why it's still reading the vendor folder.  thanks for the reply.  should I update to the latest commit in master?

**Comment by robdimsdale** [comment]
Yes, I would bump the version to latest and see if that resolves your issue.

I'm a little surprised, because that commit came after a lot of the `vendor` related work, but on the other hand I'm not sure what else it would be. What version of golang are you running?

**Comment by hermanccw** [comment]
sorted it out, turns out to be some other problem in my code base.

**Comment by robdimsdale** [comment]
Glad to hear it!
