### ISSUE TITLE
flag provided but not defined: -ginkgo.seed

### ISSUE THREAD

**Issue by mikeatlas** [onsi/ginkgo#296]
This is pretty simple. I pulled ginkgo into a new project today, and when running it from the CLI, I get:

```
➜  executor git:(develop) ✗ ginkgo 
flag provided but not defined: -ginkgo.seed
Usage of /tmp/ginkgo070877846/executor.test:
  -alsologtostderr 
  ...
```

It looks to be related to yesterday's commit https://github.com/onsi/ginkgo/commit/45a5f6ffb2a14e4f29698c16ae4c0a34018a8951 (@jawnsy) regarding random seeds.

**Comment by onsi** [comment]
woah... very strange.  I just carved out a new GOPATH, pulled the latest ginkgo and gomega, made an empty project.  All seems to work for me.

Yesterday's commit didn't touch the actual flag definitions and looking through it I can't imagine what changed.  @mikeatlas can you try rebuilding your `ginkgo`?

**Comment by mikeatlas** [comment]
I went an made sure to run `go get -u`, rebuilt the `ginkgo` binary, and manually copied the binary into my `$GOPATH/bin`. Same result from my project. But, running `ginkgo` from other paths seemed to run fine, with the standard "Found no test suites" message. 

I dug a little deeper, and in my new project, I have:
```
func init() {
	flag.Parse()
}
```
This call is what appears to be interfering with Ginkgo's flag parsing. Removing it enables `ginkgo` to run correctly. However, calling `flag.Parse()` in my own project shouldn't normally interfere/collide with Ginkgo flags, right?

**Comment by onsi** [comment]
ah makes sense.  take a look at this #285 and this comment in particular:

https://github.com/onsi/ginkgo/issues/285#issuecomment-240804867

you can only call `flag.Parse()` once.  Doing it in `init()` means other packages can't define their flags in `init()` in time (I _think_ the ordering is undefined).  Generally betters to `flag.Parse()` in `main.main()` as it is guaranteed to be a singleton.

**Comment by mikeatlas** [comment]
Thanks @onsi
