### ISSUE TITLE
Make globalSuite public

### ISSUE THREAD

**Issue by heynemann** [onsi/ginkgo#297]
Hi, thanks for the awesome testing library!

I'm trying to encapsulate some common testing logic in a new Describe (HTTPDescribe - starts a test http server and runs measure against it). I want to be able to support the same level of functionality that Describe does (FDescribe, XDescribe, etc).

The only way I could find to do that is to push it to the globalSuite as a container. The problem with that is that the globalSuite is not public. If it was I could use `	ginkgo.GlobalSuite.PushContainerNode(description, func, types.FlagTypeNone, codelocation.New(1))`.

Any ideas?

**Comment by onsi** [comment]
Rather than try to build `HTTPDescribe` "from scratch" you could compose it out of `Describes` etc.  Something like (apologies for pseudocode): 

```
func HTTPDescribe(name string, body func()) {
    Describe(name, func() {
        httpDescribe(body)
    })
}

func FHTTPDescribe(name string, body func()) {
    FDescribe(name, func() {
        httpDescribe(body)
    })
}

func PHTTPDescribe(name string, body func()) {
    PDescribe(name, func() {
        httpDescribe(body)
    })
}

// etc..

func httpDescribe(body func()) {
    BeforeEach(func() {
    }) 
}
```

**Comment by heynemann** [comment]
I did that, but I thought it a little weird, instead of just calling a method to properly register my container, test, before, etc.

Well, it's done anyway! Thanks once more for the great library!
