### ISSUE TITLE
Test failure on ppc

### ISSUE THREAD

**Issue by TheTincho** [onsi/ginkgo#301]
Hi,

I am experiencing [test failures](https://buildd.debian.org/status/fetch.php?pkg=golang-ginkgo&arch=powerpc&ver=1.2.0%2Bgit20160914.46c87bb-1&stamp=1475199110) when compiling ginkgo on powerpc/gccgo:

```
# github.com/onsi/ginkgo/internal/leafnodes_test
src/github.com/onsi/ginkgo/internal/leafnodes/shared_runner_test.go:275:3: error: 'innerCodeLocation' declared and not used
   innerCodeLocation     types.CodeLocation
   ^
FAIL	github.com/onsi/ginkgo/internal/leafnodes [build failed]
```

**Comment by onsi** [comment]
Weird.  `innerCodeLocation` is assigned to in [line 281](https://github.com/onsi/ginkgo/blob/master/internal/leafnodes/shared_runner_test.go#L281)

It's never read, however, and can just be removed (was a copy-paste issue).  I've done this on master now.  Lemme know if it helped.

**Comment by TheTincho** [comment]
It does indeed fix it, it seems that gccgo has some extra checks.

Thanks!
