### ISSUE TITLE
Need for a JustAfterEach call

### ISSUE THREAD

**Issue by kargakis** [onsi/ginkgo#303]
_JustBeforeEach blocks are guaranteed to be run after all the BeforeEach blocks have run and just before the It block has run. We can use this fact to clean up the Book specs:_
https://onsi.github.io/ginkgo/#separating-creation-and-configuration-justbeforeeach

I need a `JustAfterEach` that will run after It blocks and before AfterEach blocks so I can setup trap failures scoped to the test blocks I am working on without affecting or adding logic to the general AfterEach block that is executed for the whole test suite.

More discussion in https://github.com/kubernetes/kubernetes/issues/34318

**Comment by onsi** [comment]
Hey @kargakis can you describe exactly what you are trying to accomplish?  A `JustAfterEach` doesn't make too much sense in Ginkgo.  You *can* just have multiple, appropriately nested `AfterEach` blocks.  For example:

```
var _ = BeforeEach(func() {
    fmt.Println("B-toplevel")
})

var _ = AfterEach(func() {
    fmt.Println("A-toplevel")
})

var _ = Describe("A group of tests", func() {
    BeforeEach(func() {
        fmt.Println("B-1")
    }) 

    AfterEach(func() {
        fmt.Println("A-1")
    })

    It("tests something", func() {
        fmt.Println("It-alpha")
    })

    It("tests something else", func() {
        fmt.Println("It-beta")
    })
})

var _ = Describe("Another group of tests", func() {
    BeforeEach(func() {
        fmt.Println("B-2")
    }) 

    AfterEach(func() {
        fmt.Println("A-2")
    })

    It("tests yet another thing", func() {
        fmt.Println("It-gamma")
    })
})
```

Would print out (ignoring Ginkgo's own test output):

```
B-toplevel
B-1
It-alpha
A-1
A-toplevel

B-toplevel
B-1
It-beta
A-1
A-toplevel

B-toplevel
B-2
It-gamma
A-2
A-toplevel
```

So you can add custom logic to the `A-2` `AfterEach` for the `"Another group of tests"` block that will not affect any other tests in the suite.

**Comment by kargakis** [comment]
I would swear I was trying to use a nested AfterEach block and it wasn't working. Maybe I need to try again.. Was it a bug fixed recently in ginkgo? Kubernetes seems to be using a fairly recent [version](https://github.com/kubernetes/kubernetes/blob/3a882072e92bcce244c565f0539e4ad45d1b958c/Godeps/Godeps.json#L1559) of the framework.

**Comment by onsi** [comment]
Naw it should totes work. Try it in isolation with that version of ginkgo before putting it into the k8s integration test.

**Comment by onsi** [comment]
@kargakis thoughts?

**Comment by kargakis** [comment]
Sorry for the belated response, too many things going on.  It seems you are right, nested AfterEach blocks should work as I expect them to work. Thanks!
```
Running Suite: test
==========================
Random Seed: 1478539000
Will run 3 of 3 specs

B-toplevel
B-1
It-alpha
A-1
A-toplevel
•B-toplevel
B-1
It-beta
A-1
A-toplevel
•B-toplevel
B-2
It-gamma
A-2
A-toplevel
•
Ran 3 of 3 Specs in 0.000 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
```

**Comment by fasaxc** [comment]
@onsi My team have a good use case for JustAfterEach: dumping diagnostics after a failure.  Basically, we want to run a bunch of diags collection scripts after a failure but before the scenario gets torn down by the AfterEach blocks.  If we do that in an AfterEach, then we have to add it to the most deeply nested AfterEach in each Context, which doesn't scale well.

We're going to prototype it and see if it works well for us.  Would you accept it as a contribution if it does?
