### ISSUE TITLE
Huge slowdowns on recent commits

### ISSUE THREAD

**Issue by hcliff** [onsi/ginkgo#307]
A change introduced in the last 5-9 days is causing _huge_ slowdowns. I've seen my test times go from 2minutes to 20 minutes. Tests are running quickly themselves, it appears to be the compilation steps.

I've verified it's ginkgo by replaying old (fast) CI tests with varying versions of ginkgo, and cross referenced vanilla `go test ./...` to be safe

I've been able to fix this by checking out an old version of ginkgo. For anyone else running into this:
```
cd "$GOPATH/src/github.com/onsi/ginkgo"
git checkout 46c87bb63f2d8d62b3076873b7a84da124da72ce
go install github.com/onsi/ginkgo/ginkgo
```

**Comment by onsi** [comment]
i suspect it was this commit:

https://github.com/onsi/ginkgo/commit/afe049e1120cfc831ad789f4895818d3c6c95de8

can you confirm?

**Comment by hcliff** [comment]
yup, looks like it

**Comment by onsi** [comment]
le sigh... does anyone on the internet know how `go test -i` works... I'll revert the commit...

**Comment by hcliff** [comment]
If it's helpful ping me with a branch and I'll trial it prior to merging into master?

**Comment by onsi** [comment]
naw just pushed it to master, give it a shot @hcliff

**Comment by hcliff** [comment]
All sorted!

Great project it's been really helpful for us, thanks for your time with this issue and your wider efforts on ginkgo/gomega :)
