### ISSUE TITLE
table extension does not work with BeforeSuite or BeforeEach

### ISSUE THREAD

**Issue by jsimonetti** [onsi/ginkgo#308]
Consider the following test:

``` go
var (
    entries []TableEntry
)

var _ = BeforeSuite(func() {
    entries = append(entries, Entry("x > y", 1, 0, true))
    entries = append(entries, Entry("x == y", 0, 0, false))
    entries = append(entries, Entry("x < y", 0, 1, false))

    fmt.Printf("Entries length: %d\n", len(entries))
})

var _ = Describe("Math", func() {
    DescribeTable("the > inequality",
        func(x int, y int, expected bool) {
            Expect(x > y).To(Equal(expected))
        },
        entries...,
    )
})
```

I would have expected that 3 tests are run and they all pass.
However, it looks like the entries variable is not filled until after the DescribeTable dsl is evaluated.
Above file results in:

```
Running Suite: Table Suite
==========================
Random Seed: 1477399312
Will run 0 of 0 specs

Entries length: 3

Ran 0 of 0 Specs in 0.006 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
```

Please advise on how to use the table extension with variable length Entries.

**Comment by onsi** [comment]
The table needs to be constructed before Ginkgo starts running tests.  code like this needs to go in the top level and cannot be in a BeforeSuite.

DescribeTable is simply a thin wrapper around Describe and It and all the Describes and Its need to be specified when go loads the top level code in.
