### ISSUE TITLE
Unable to get flaky test mitigation to work

### ISSUE THREAD

**Issue by jg8481it** [onsi/ginkgo#309]
I have been trying out the --flakeAttempts flag and I keep getting a "flag provided but not defined: -flakeAttempts"

Here is an example of what I am trying to run...

$ ginkgo --flakeAttempts=3

I have a feeling I am doing this the wrong way. Any advice is appreciated. Thanks.

**Comment by robdimsdale** [comment]
@jg8481it try it with one `-` i.e. `ginkgo -flakeAttempts 3`.

**Comment by jg8481it** [comment]
@robdimsdale After trying it with... 

> ginkgo -flakeAttempts 3

I still get the same error.

**Comment by onsi** [comment]
@jg8481it did you pull the latest ginkgo and recompile the CLI (sorry... just trying to cover the basics!)

**Comment by jg8481it** [comment]
@onsi I will definitely give that a try and post an update.

**Comment by jg8481it** [comment]
@onsi @robdimsdale 

After pulling the latest ginkgo and recompiling the CLI, it's now working perfectly. I see three attempted runs. Thanks for the assistance guys!
