### ISSUE TITLE
-bash: ginkgo: command not found

### ISSUE THREAD

**Issue by ypapax** [onsi/ginkgo#313]
Commands
```
go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega
```
do not createe `ginkgo` binary in $GOPATH/bin

**Comment by onsi** [comment]
um.  just tried this with a fresh GOPATH with go1.7.1 and it works for me.  are you able to download, compile, and install other packages via `go get`?

**Comment by ypapax** [comment]
Not sure what was a reason tomorrow, today is working, thanks
