### ISSUE TITLE
Seperate fast and slow tests

### ISSUE THREAD

**Issue by LewisWatson** [onsi/ginkgo#314]
Hello, thanks for making ginkgo, I'm really liking it.

I've got a some fast tests that use an in-memory data store and some slow tests that are effectively the same but use a mongodb data store, which involves spinning up a mongoDB docker container. Is there a way for me to create my ginkgo tests so that when the I run my tests with the `-fast` flag set then only the in-memory tests run?

This is what I've got so far, but all the test run every time. 

```go

var _ = AfterSuite(func() {
	// tear down mongoDB container
})

var createUser = func(name string) string {
	// do test
}

var _ = Describe("The CarShareBack API", func() {
	
	Describe("Using in memory data store", func() {

		BeforeEach(func() {
			// create api with in memory store
		})

		It("Creates a new user", func() {
			createUser("marvin")
		})
	})

	Describe("Using MongoDB data store", func() {

		BeforeEach(func() {
			// spin up mongoDB docker container
			// create  api with mongoDB store
		})

		It("Creates a new user", func() {
			createUser("marvin")
		})
	})
})
```

**Comment by onsi** [comment]
A common approach here (admittedly a bit hacky) is to come up with a consistent tag that you apply to the relevant `Describe`s:

```go

var _ = AfterSuite(func() {
	// tear down mongoDB container
})

var createUser = func(name string) string {
	// do test
}

var _ = Describe("The CarShareBack API", func() {
	
	Describe("{fast} Using in memory data store", func() {

		BeforeEach(func() {
			// create api with in memory store
		})

		It("Creates a new user", func() {
			createUser("marvin")
		})
	})

	Describe("Using MongoDB data store", func() {

		BeforeEach(func() {
			// spin up mongoDB docker container
			// create  api with mongoDB store
		})

		It("Creates a new user", func() {
			createUser("marvin")
		})
	})
})
```

Now you can run `ginkgo --focus="{fast}"` to only run things "tagged" `fast`.  (`--focus` takes a regular expression that is applied to the concatenated set of `Describe` and `It` strings to pick out tests to run.  There's a related `--skip` flag.  Both `--skip` and `--focus` take precedence over programatic focus (`FIt`, `FDescribe`))

If you want to get fancier you can define a `DescribeFast` helper method that calls down to `Describe` but appends the `{fast}` tag to the block description string.

**Comment by LewisWatson** [comment]
Thanks onsi, that looks like an interesting approach that looks like it would work. After a bit more investigation I've managed to work out how to skip certain tests via the `-short` flag. Turns out I just needed to import the testing package.

```go
var _ = AfterSuite(func() {
	// tear down mongoDB container
})

var createUser = func(name string) string {
	// do test
}

var _ = Describe("The CarShareBack API", func() {
	
	Describe("Using in memory data store", func() {

		BeforeEach(func() {
			// create api with in memory store
		})

		It("Creates a new user", func() {
			createUser("marvin")
		})
	})

	Describe("Using MongoDB data store", func() {

		BeforeEach(func() {

			if testing.Short() {
				Skip("skipping mongoDB integration tests in short mode")
			}

			// spin up mongoDB docker container
			// create  api with mongoDB store
		})

		It("Creates a new user", func() {
			createUser("marvin")
		})
	})
})
```

Thanks again.
