### ISSUE TITLE
Feature request: Set reporter via command line flags

### ISSUE THREAD

**Issue by fredr** [onsi/ginkgo#320]
It would be great if it was possible to to specify a reporter when running `ginkgo`, so that different reporters can be used in different CI systems etc.

I.e I don't want every developer to have to remember to use `RunSpecsWithDefaultAndCustomReporters` for the tests to be picked up by CI, and I would like to not have to change every TestSuite whenever I need to add a new output format.

**Comment by msabramo** [comment]
👍 As I want to add junit reporting and would like to avoid having to modify 24 `*_suite_test.go` files.

I'm willing to take a stab at it, but I'd like to get feedback from @onsi before diving in.

**Comment by msabramo** [comment]
Here's my workaround:

```
sed -i -e 's#RunSpecs(\(.*\))$#junitReporter := reporters.NewJUnitReporter("junit.xml")\'$'\n'$'\t''RunSpecsWithDefaultAndCustomReporters\(\1, []Reporter{junitReporter}\)#' $(find . -name '*vendor*' -prune -o -name '*_suite_test.go' -print)

goimports -w $(find . -name '*vendor*' -prune -o -name '*_suite_test.go' -print)
```

**Comment by manosnoam** [comment]
Hi, I've added this PR #598 - it is passing on [travis-ci](https://travis-ci.org/onsi/ginkgo/builds/571680500). 
Please ignore the failed builds on my personal fork, probably I need to reset my fork.
@williammartin can you review please ?

**Comment by manosnoam** [comment]
@msabramo, @fredr,
You can try to pull this patch by adding to your go.mod:
`replace github.com/onsi/ginkgo => github.com/manosnoam/ginkgo v0.0.0-20190902135631-1995eead7451`

And then run:

`$ go test -v <path of packages to test> -ginkgo.reportFile junit.xml`

This is an output example:
```

=== RUN   TestRoute
 Running Suite: Route Suite
 ==========================
 Random Seed: 1567587744
 Will run 4 of 4 specs
 
 ••••
 JUnit path was configured: junit.xml
 
 JUnit report was created: /home/nmanos/go/src/github.com/submariner-io/submariner/pkg/routeagent/controllers/route/junit.xml
 
 Ran 4 of 4 Specs in 0.000 seconds
 SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 0 Skipped
 --- PASS: TestRoute (0.00s)
 PASS
 
=== RUN   TestUtil
 Running Suite: Util Suite
 =========================
 Random Seed: 1567587743
 Will run 18 of 18 specs
 
 ••••••••••••••••••
 JUnit path was configured: junit.xml
 
 JUnit report was created: /home/nmanos/go/src/github.com/submariner-io/submariner/pkg/util/junit.xml
 
 Ran 18 of 18 Specs in 0.000 seconds
 SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 0 Skipped
 --- PASS: TestUtil (0.00s)
 PASS
```
