### ISSUE TITLE
Show seed unconditionally at the end of test execution

### ISSUE THREAD

**Issue by jawnsy** [onsi/ginkgo#321]
Ginkgo's seed is printed at the beginning of the test run, but if you're running the tests locally and your scrollback buffer is small, you can lose the seed value. It'd be nice for ginkgo to unconditionally (in case of success or failure) output the seed at both beginning and end of execution.

**Comment by onsi** [comment]
HI @jawnsy I appreciate the ask but Ginkgo's output is already pretty verbose.  I'd prefer not to add more to it.
