### ISSUE TITLE
Hard to collect stack for hanging tests when run in parallel

### ISSUE THREAD

**Issue by vito** [onsi/ginkgo#323]
We often run tests with `-p` or `-nodes=X` (both in CI and during dev). Unfortunately this makes it impossible to get a stack dump when the tests are hanging. If you send `SIGQUIT` to the toplevel `ginkgo` process you just get a stack dump of the coordinating node, not the nodes actually running the tests. If you send `SIGQUIT` to the nodes running the tests, the coordinating node just prints:

```
	 -------------------------------------------------------------------
	|                                                                   |
	|  Ginkgo timed out waiting for all parallel nodes to report back!  |
	|                                                                   |
	 -------------------------------------------------------------------
```

It'd be super handy if `ginkgo` trapped `SIGQUIT`, dispatched it to each of its nodes, collected their output, and then printed them non-interleaved. It should probably also do its own stack dump + exit, in case things are stuck there.

**Comment by onsi** [comment]
Yes.  Trapping and retransmitting would be the way to go here.  I believe it already does this for SIGINT.

.......PR?

**Comment by jszroberto** [comment]
Same here. It's really tricky to find out the hanging test.

**Comment by onsi** [comment]
Interrupts are handled much more cleanly now in `v2` - sending SIGINT should get you a much clearer sense of where things are hanging.
