### ISSUE TITLE
Compiled packages removed?

### ISSUE THREAD

**Issue by joshq00** [onsi/ginkgo#325]
Onsi, thanks for this repo + gomega. Really helps our productivity at The Home Depot

After upgrading to 1.8, I've noticed that running any sort of `ginkgo` or `ginkgo watch` causes later compiles to run slowly. I use luan/vimfiles -- which run `go test -c` on every save.

An example use case:
- start tmux
- open a separate pane
  - start `ginkgo watch -r -cover`
- open vim
  - modify a file (takes 10-15 seconds)
  - save the file again (takes 10-15 seconds)

Further proof ginkgo has something to do with this:
- run `go test -i -x` (Lots of output)
- run `go test -i -x` (little output)
- run `go test -x` (little output)
- run `go test -i -x` (little output)
- run `ginkgo`
- run `go test -i -x` (lots of output)
- run `go test -i -x` (little output)
- run `go test -x` (little output)
- run `go test -i -x` (little output)

The package build output seems directly related to running ginkgo. This also affects how long it takes in vim to continue to the next command.

If anyone knows what's causing this, I'd be happy to submit a PR to help solve it, but I can't figure out why the build cache is removed for every `ginkgo` run

**Comment by joshq00** [comment]
As a side note, I've used `find . -name '*.go' | entr -r -c go test'` and there is no delay in compile or vim

**Comment by joshq00** [comment]
May be related to #258

**Comment by johanbrandhorst** [comment]
Seems to recompile a lot of the standard library whenever `--cover` or `--race` is used.

**Comment by onsi** [comment]
hi all - is this still an issue with the latest go 1.8.3 and the latest ginkgo?

**Comment by johanbrandhorst** [comment]
Doesn't seem to be a problem to me anymore, but YMMV.

**Comment by williammartin** [comment]
@johanbrandhorst @joshq00 Just doing some housekeeping. Are you still experiencing this or can I close it out with a recommendation that if people experience slowness they move to latest Go and Ginkgo? Thanks

**Comment by johanbrandhorst** [comment]
@williammartin I think this is resolved

**Comment by williammartin** [comment]
Awesome, I'm gonna close it off but definitely come back if there are any more issues.
