### ISSUE TITLE
Don't print colorized output when not outputting to a TTY

### ISSUE THREAD

**Issue by stevekuznetsov** [onsi/ginkgo#326]
With code like:

```go
import (
    "os"
    "golang.org/x/crypto/ssh/terminal"
)
 
func main() {
    return terminal.IsTerminal(int(os.Stdout.Fd()))
}
```

It should be possible to determine if the output from `ginkgo` is going to a TTY or not. It should be best practice not to spit out color escape codes if the output is _not_ a TTY.

**Comment by robdimsdale** [comment]
I can see arguments for both cases. There are examples of where you want to output color to something that isn't a TTY - concourse.ci is one of these - so if we switched the default I would still expect to see a way to configure color.

Changing the default here could cause frustrations for these users as they would lose color support until they explicitly opted-in by re-enabling color.

**Comment by stevekuznetsov** [comment]
I understand the backward compatibility argument, but given that it's a color and a flag `-color` could be used to force coloring, I think it's still true that well formed programs shouldn't output ANSI escape codes to file descriptors that aren't TTYs by default.

**Comment by vito** [comment]
FWIW, Concourse runs its tasks with a TTY, so it would be unaffected by this. I agree that by default it should omit color. Curious if Travis CI and others would be affected though?

**Comment by robdimsdale** [comment]
@vito I didn't realize that - was this always the case? I thought I've seen ANSI codes fail to be escaped in concourse, but I might be confusing it with something else.

A quick google search implies that Travis CI runs a TTY/PTY so that would likely continue to work. I vaguely remember GoCD not supporting ANSI color codes, but I'm not sure how many ginkgo users run on that system anymore.

@onsi thoughts on this potentially backwards-incompatible-but-probably-better feature request?

**Comment by onsi** [comment]
Makes sense to me.  Steve are you up for submitting a PR?

**Comment by stevekuznetsov** [comment]
Yes, I'll take a stab at it. Just to make sure we've got agreement on the change - if the output is not a TTY, act as if `-noColor` had been passed, _unless_ the user supplied `-color`.

**Comment by vito** [comment]
yep. we initially did it for Bosh cli a long time ago.

**Comment by manosnoam** [comment]
FYI,
When running in GoLand IDE, the -ginkgo.noColor removes colors from the terminal output as well:

![image](https://user-images.githubusercontent.com/9913945/63108640-0913d000-bf90-11e9-8050-91e7fbfb8f79.png)
