### ISSUE TITLE
Last tag was created over 2 years ago

### ISSUE THREAD

**Issue by drywheat** [onsi/ginkgo#338]
It looks like you were cutting _releases via tags_ a while back. Is that no longer the case?

**Comment by onsi** [comment]
Yes - not consistently.  There's still reasonably active maintenance and community development happening on master and we generally follow the Golang versioning semantics of "just use master"

Are you using some sort of dependency management tool that requires a tag to be cut?

**Comment by drywheat** [comment]
I'm currently using [Glide](https://glide.sh/) to manage dependencies. By default, it will look for and try to lock down the latest tag so you can get reproducible installs. Otherwise, using HEAD, there's an opportunity for devs (new and old) to be using different versions of ginkgo for testing.

It is not sustainable for my team/project to forgo enforcing semver. Maybe there's a different way this is done in the world of golang?

**Comment by onsi** [comment]
Yeah, understood.  Different folks do this in different ways.  I can set myself a recurring calendar reminder to cut semver-ish releases every month.

**Comment by onsi** [comment]
OK I just cut new tagged releases for both Ginkgo and Gomega.

**Comment by drywheat** [comment]
Thank you, that's very accommodating.
