### ISSUE TITLE
Suite-level BeforeEach call?

### ISSUE THREAD

**Issue by kiddrew** [onsi/ginkgo#341]
RSpec has the ability to define a BeforeEach in the config, most commonly for preparing a test database. I'm doing the same thing inside Ginkgo to set up a test Redis environment, but I'm making the call in every test file rather than at the suite level.

I've looked through documentation and examples, but I haven't found a way to make that call automatically for every test - is that possible?

**Comment by onsi** [comment]
Yep, you can define a `BeforeEach` in your `*_suite_test.go` file (you should have one of these if you used `ginkgo boostrap`).  It looks like:

```
var _ = BeforeEach(func() {
    ...
})
```

The `var _` is to get around Go's restriction around calling functions at the top level.

Here's an example from Ginkgo's integration tests:
https://github.com/onsi/ginkgo/blob/master/integration/integration_suite_test.go

**Comment by kiddrew** [comment]
Aha, thanks!
