### ISSUE TITLE
Export Specs with children/parents

### ISSUE THREAD

**Issue by fasa123** [onsi/ginkgo#343]
I am currently trying to write a parser for the Ginkgo test results. Writing a custom reporter makes things easy admittingly but I have no proper way of contextualizing each node. If I hook into SpecDidRun I do not know what that specs parent is whether it has a parent whether it has childrens. Is there any way I can do this?

**Comment by onsi** [comment]
I'm sorry, I don't follow.  What do you mean by "Parent" and "Children"?  Each Ginkgo Spec is an `It` that stands alone, it does not have parents or children.  It may be nested within several `Describes` and `Contexts` and have numerous `BeforeEach`es and `AfterEach`es around it.  But it is neither the parent of another spec nor the child of another spec.

**Comment by fasa123** [comment]
Mind me English isn't my native tongue. Let's take your example:

```
    Describe("Categorizing book length", func() {
        Context("With more than 300 pages", func() {
            It("should be a novel", func() {
                Expect(longBook.CategoryByLength()).To(Equal("NOVEL"))
            })
        })

        Context("With fewer than 300 pages", func() {
            It("should be a short story", func() {
                Expect(shortBook.CategoryByLength()).To(Equal("SHORT STORY"))
            })
        })
    })
```

I'd like to write a parser that is able to see each Describe/Context/It in their order. In this sample "Categorizing the book length" is the parent of "With more than 300 pages" which is the parent of "should be a novel".

I wanted to know is whether there is some api to get this information; I expected a Slice that includes each node (in your example "Book") with its childrens attached to it as a field.

If there is no API then go ahead just close this and I'll try to hack sth together when I have time.

**Comment by onsi** [comment]
The best I can get you now is the `ComponentTexts` and
`ComponentCodeLocations` slices (
https://github.com/onsi/ginkgo/blob/master/types/types.go#L41-L43) that are
passed into `SpecDidComplete`.  Will that work?

**Comment by fasa123** [comment]
Yea I already used them. Problem with those is that I have to do the matching on my own which is really unnecessary since Ginkgo already knows how they are related. Though thanks for the replies eventually I will try to add this functionality into Ginkgo when I have time since that seems to be the most logical option here I assume.
