### ISSUE TITLE
Custom coverage profile filename not working

### ISSUE THREAD

**Issue by bt** [onsi/ginkgo#346]
I noticed that there's a command-line option named `-coverprofile` which is supposed to take in a string and output a coverage profile to the provided string after the tests are completed.

```
  -coverprofile string
    	Write a coverage profile to the specified file after all tests have passed.
```

I can see this is mentioned here: https://github.com/onsi/ginkgo/blob/master/ginkgo/run_watch_and_build_command_flags.go#L133

However, when I run my tests like such:

```
$ ginkgo -r -coverprofile coverage.txt
```

I don't get the file at `coverage.txt`, I'll end up with multiple `.coverprofile` files.

I also noticed this isn't mentioned in the Ginkgo documentations, so is this just a feature that was never implemented?

**Comment by AlexeySoshin** [comment]
I'm on it

**Comment by onsi** [comment]
@AlexeySoshin I made a couple of comments on the PR - lemme know if you can take a look.

**Comment by AlexeySoshin** [comment]
@onsi Implemented changed. Could you please review this again?
