### ISSUE TITLE
Add a When() synonym for Context()

### ISSUE THREAD

**Issue by decibel** [onsi/ginkgo#348]
I find myself writing a lot of `Context()`s with a description in the form "when <something>", ... It(). Enough so that I'm wondering if it'd be worth adding a When() to the DSL, something along the lines of:

```func When(description string, ...) ... {
    return Context("when " + description, ...)
}```

That way if you write:

```When("something happens", func() {
...
})```

you'd get a "when" in the text output as well.

**Comment by onsi** [comment]
Makes sense and should be relatively easy.  Will try to get to this soon.

**Comment by williammartin** [comment]
This was done in https://github.com/onsi/ginkgo/pull/386. Hope it works for you.

**Comment by decibel** [comment]
Works great, thanks for your efforts!
