### ISSUE TITLE
flakeAttempts flag doesn't appear to work in ginkgo 1.2.0

### ISSUE THREAD

**Issue by joekir** [onsi/ginkgo#350]
#### Issue details

I have tried running both:
`$ ginkgo -r --flakeAttempts=10` and 
`$ ginkgo -r -flakeAttempts 10` 

Both result in the following kind of error:

```
flag provided but not defined: -ginkgo.flakeAttempts
Usage of /var/folders/8z/mqxww37d4jj0wnc10cym28bm0000gp/T/ginkgo248733489/actions.test:
```

##### Found in
```
$ ginkgo version
Ginkgo Version 1.2.0
```

**Comment by onsi** [comment]
i think this landed in 1.3.0+ @joekir - for a while I wasn't cutting regular releases but am trying to do that going forward.
