### ISSUE TITLE
Is there a way to watch everything, not just the go files?

### ISSUE THREAD

**Issue by aubm** [onsi/ginkgo#356]
I have this use case because I have a bunch of external test files that contain thing like JSON snippets, etc...

**Comment by onsi** [comment]
Sure - this would be a new feature but not too hard.  Can you do me a favor?

Can you:

1. Locally, edit [this line](https://github.com/onsi/ginkgo/blob/master/ginkgo/watch/package_hash.go#L11) and make the RegExp more permissive.

2. Recompile the Ginkgo CLI (`go install github.com/onsi/ginkgo/ginkgo`)
3.

**Comment by onsi** [comment]
(Or, if you're comfy, a PR would be great too!)
