### ISSUE TITLE
Running both golang standard testing library and ginkgo tests

### ISSUE THREAD

**Issue by jutkko** [onsi/ginkgo#358]
Hi, I am trying to figure out a way to swap out existing tests to ginkgo tests when possible. This will mean that at some point I want to be able to run both kind of tests. Is it possible?

Right now it seems when ginkgo suite is present, `go test` will only run the ginkgo tests.

**Comment by onsi** [comment]
Is the repo open source so i can take a look and help?

You can mix Ginkgo and go tests within the same package.  Both `go test` and `ginkgo` will run both tests.  You can also have some packages that are Ginkgo tests and some that are go tests.

Have you tried `ginkgo convert` - it will take all your existing go tests and turn them into Ginkgo tests and you can refactor from there.

**Comment by jutkko** [comment]
Hi @onsi I just realised that I didn't pay attention to the output. I was about to come and close the issue but you already responded! Thanks!

**Comment by jutkko** [comment]
I have never heard of `ginkgo convert`, sounds like a cool command!

**Comment by keeema** [comment]
I face probably one missing functionality in ginkgo command.
When I run

```
ginkgo --json-report=report.json */**
```

then it runs all spec as you wrote but the final summary and the __report.json__ contains only information about ginkgo tests.
