### ISSUE TITLE
How to detect test suite failed?

### ISSUE THREAD

**Issue by tamalsaha** [onsi/ginkgo#361]
I want to run suite cleanup commands, only if the test suite is passing. How do I detect that test suite has passed?

```
var _ = AfterSuite(func() {        
	// root.DeleteNamespace()
})
```

**Comment by onsi** [comment]
Hi @tamalsaha - sorry for the delay.  There isn't a great built-in way to do this but you could hack something together using `CurrentGinkgoTestDescription()` as follows:

```golang
var failed = false
var _ = AfterEach(func() {
    failed = failed || CurrentGinkgoTestDescription().Failed
})

var _ = AfterSuite(func() {
    if failed {
        fmt.Println("FAILED!")
    } else {
        root.DeleteNamespace()
   }
})
```

**Comment by williammartin** [comment]
Hi, @tamalsaha, just doing some housekeeping. Did this answer your question, do you want to make an enhancement request, or are you even interested in this anymore? Thanks!

**Comment by tamalsaha** [comment]
I would like to make an enhancement request so that this can be done in a cleaner fashion.

**Comment by williammartin** [comment]
Alright cool I've swapped the label over and hopefully someone can take a look. If you had free reign, how would you like the UX to look (no promises :)) for this feature?

**Comment by tamalsaha** [comment]
May I the AfterSuite calls with a parameter?

```
var _ = AfterSuite(func(result bool) {
    if !result {
        fmt.Println("FAILED!")
    } else {
        root.DeleteNamespace()
   }
})
```

**Comment by ckaminer** [comment]
Is there a solution for detecting failures during a recursive run?  In my CI/CD pipeline I can make the pipeline fail if I run one suite at a time.  During another stage where I recursively run multiple suites I'm having a hard time detecting at least one failure and kicking out of the pipeline.

**Comment by munnerz** [comment]
Wonder if there's anything more on this? I am running my tests in parallel as well, so the above mentioned solution (utilising a global var to mark the test as failed) will not work for me, as parallel mode spawns a gingko process for each parallel worker.

More info on my use case: our tests are mostly self contained, but have *some* 'global' addons that are used by *all* tests. I want to print logs from these global addons if *any one test fails*.

I notice that `RunSpecsWithDefaultAndCustomReporters` returns a `passed` bool, which is useful, but will only return *after* the SynchronizedAfterSuite has run (which is where we tear down these global instances). For the time being, I'm going to grab all the logs in this synchronized block and then dump the logs if `RunSpecsWithDefaultAndCustomReporters` returns false (in the main test process).

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I'm actively working on Ginkgo [V2](#711) and am planning on adding an `AfterSuiteReport(func(report Report) {})` block that will receive a complete summary of the test suite after the run has completed (this will only run on node 1 when running in parallel, and only after the suite has completed).  I think it will solve for this usecase.

I'm going to close this for now, but feel free to reopen it if you'd like.
