### ISSUE TITLE
Is it possible to set a timeout to table driven test entries?

### ISSUE THREAD

**Issue by rmohr** [onsi/ginkgo#363]
I want to specify a timeout in combination with `Done` on a table entry, like I can do it for `It`s: 
```golang
It("test", func(done Done) { 
    close(done) 
  }, 20 *time.Second)`
```
I was expecting something like

```golang
var _ = Describe("Math", func() {
    DescribeTable("the > inequality",
        func(x int, y int, expected bool, done Done) {
            Expect(x > y).To(Equal(expected))
            close(done)
        },
        EntryWithTimeout("x > y", 1, 0, true, 30 * time.Second),
        EntryWithTimeout("x == y", 0, 0, false, 30 * time.Second),
    )
})
```

Does something like that exist?

**Comment by onsi** [comment]
hi @rmohr - this isn't possible.  Can you give me an example of what you are trying to accomplish?  You can likely use Gomega's `Eventually` function to achieve what you want to achieve.

**Comment by rmohr** [comment]
hi @onsi, 

The reason why I want to do this, is the same like for [Asynchronous tests](https://onsi.github.io/ginkgo/#asynchronous-tests). I have a lot of tests, where I first change something, then I wait for events from a stream, then I continue. I can add my own timeouts to my waits, or use Eventually (and I use timeouts on them, if I want to make sure that sub-steps don't take too long), but it is quite convenient if I just set an overall timeout for the test. Mainly, to make sure that the test does not block for ages if something goes wrong. Does that make sense to you?

**Comment by onsi** [comment]
hey @rmohr - you might find the conversation on #362 interesting.  I'm wanting to deprecate Ginkgo's support for asynchronous tests because of how it can lead to confusing and frustrating flaky scenarios.  I recommend using `Eventually` where possible.

If you'd still like something similar to the current async testing behavior for table tests you can do this:

```golang
var _ = Describe("Math", func() {
    DescribeTable("the > inequality",
        func(x int, y int, expected bool, timeout time.Duration) {
            done := make(chan struct{})
            go func() {
                Expect(x > y).To(Equal(expected))
                close(done)
            }()
            Eventually(done, timeout).Should(BeClosed(), "Test timed out!")
        },
        EntryWithTimeout("x > y", 1, 0, true, 30 * time.Second),
        EntryWithTimeout("x == y", 0, 0, false, 30 * time.Second),
    )
})
```

This is effectively identical to how Ginkgo does async testing under the covers.

**Comment by rmohr** [comment]
Ok, #362 definitely explains some strange issues I have seen a few times :+1: 

I will consider moving to `Eventually` where possible.

Thanks for you help.
