### ISSUE TITLE
junit report for non-ginkgo based tests

### ISSUE THREAD

**Issue by jchauncey** [onsi/ginkgo#366]
We have a mixture of both ginkgo style unit tests and old golang unit tests. Right now we only get a junit.xml file from the ginkgo tests but I would love to get them for both suites. Is this possible right now or is something you guys would need to add?

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

Sorry - there are no plans to have Ginkgo do anything for non-ginkgo unit tests beyond simply running them.

I'm going to close this for now, but feel free to reopen it if you'd like.
