### ISSUE TITLE
Allow tests to be modified prior to run

### ISSUE THREAD

**Issue by smarterclayton** [onsi/ginkgo#371]
We import ginkgo tests into our code base that we want to add to and organize into suites (define a bulk focus that is easy to specify for end users).  There isn't an easy way to do so today other than creating a wrapper bash script to calculate a focus, but that doesn't lend itself to easy maintenance.  

One approach we've explored is to add text to the description before the runner executes so that virtual suites can be created.  To do that requires the ability to walk and modify the suite tree ahead of time.  Would there be interest in accepting a PR that added the ability to walk the tree of tests and modify the text description of each test

An example of this is here https://github.com/openshift/origin/pull/15915/commits/b7c80e4bc269cf674659d52e2a564c2f8dab47f3 and here https://github.com/openshift/origin/pull/15915/commits/5f60b0d8f53db2ee9f272f42b15e89b6be0bd97b

The example walker adds additional focus targets to certain tests (based on a regex managed in tree).  The end tester can run a single focus to get all the tests, without having to jump through additional hoops to filter the result:

    $ ginkgo ... -focus=Suite:openshift/conformance/serial

If there's interest I can open a PR to do the limited walking.

**Comment by williammartin** [comment]
@smarterclayton Thanks, just trying to understand this issue. It seems like you are suggesting you have a set of tests covering a certain behaviour that span suites, and you want to allow people to focus those, and you are currently doing that via modifying the textual descriptions?

**Comment by soltysh** [comment]
@williammartin yes, that's basically what we're doing in the linked commits. The idea is that we have a bunch of tests from both origin and k8s and we want to be able to run them using reasonable focus text. The first commit @smarterclayton pointed out is the one that is introducing that change. Are you interested in it? It basically allows one to modify the textual description like you've said to be able to narrow the focus to a single statement.
