### ISSUE TITLE
Fail when pending tests pass

### ISSUE THREAD

**Issue by gaffo** [onsi/ginkgo#374]
Would it be possible to run pending specs and only fail them when they pass? This was a nice feature of cucumber once upon a time basically saying "hey this now works" and trying to keep the number of pending specs small.

**Comment by williammartin** [comment]
@gaffo Could you elaborate on this a little, I'm not sure I fully understand the feature. What is the UX you forsee?

**Comment by gaffo** [comment]
Mainly just that if you were to make your own custom Before/After... which
I'm doing to run certain sets of befores in certain test modes.... the
errors show up correctly to the line of test not to the Before shim. Does
that make sense?

**Comment by williammartin** [comment]
No sorry, are you describing your other open issue https://github.com/onsi/ginkgo/issues/377 ?

**Comment by gaffo** [comment]
Oh duh... Sorry

**Comment by gaffo** [comment]
So basically in some other test frameworks you can run in a special mode where you say "if a pending spec passes, it should fail" this way you see the test failures as specs that should be running every time. Eg, these are specs that are accidentally off. It's a tool that helps with cleanup. I used it with cucumber before and it basically would fail the build if we had specs that should have been enabled but were not.

Does that make sense?

**Comment by williammartin** [comment]
Oh yeh that's definitely an interesting feature. Do you happen to have a link to the Cucumber feature, maybe we could follow the same UX?

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I think `--failOnPending` was introduced after this issue?  And I think it solves this use case?

I'm going to close this for now, but feel free to reopen it if you'd like.
