### ISSUE TITLE
Project with unit and integration tests

### ISSUE THREAD

**Issue by kmacmcfarlane** [onsi/ginkgo#375]
I have a project that has both unit and integration tests. I am adding build targets to the top of all of my tests marking them as 'unit' or 'integration'.

//+build integration

When I run:
`ginkgo -r -tags unit`

I expect this would only run my unit tests, instead it fails to compile, presumably because it encounters my integration_test package where all the files are marked 'integration':
```
Failed to compile integration_tests: output file "/tmp/ginkgo930430174/integration_tests.test" could not be found
Ginkgo ran 2 suites in 9.317651s
Test Suite Failed
```

When I run `ginkgo -r -tags integration integration_tests`  then it actually runs only my tests.

How do I get ginkgo to run only my unit tests? Do I really have to list all of the packages in my project except integration_tests in order to achieve this?

**Comment by onsi** [comment]
No need to use tags.  Checkout the -skipPackage flag

**Comment by kmacmcfarlane** [comment]
I just noticed I messed up the markdown on my original post.

It just seems like a bug that it fails to compile in that case.

Thanks for the tip on -skipPackage, I was looking all over the doc and couldn't find it! Doh!

**Comment by williammartin** [comment]
@kmacmcfarlane Is there anything else you need help with in this issue or can we close it out?

**Comment by kmacmcfarlane** [comment]
Nope, your suggestion works for my uses. Thanks!
