### ISSUE TITLE
No way to suppress verbose Skip output

### ISSUE THREAD

**Issue by khuddlefish** [onsi/ginkgo#376]
We are currently using Ginkgo to test a database utility that needs to interact with multiple versions of the database.  Many of our functions issue queries to the database for system catalog information that only exists in certain versions of the database, so when testing those functions against a certain database version we skip quite a few tests at runtime because they are not applicable to that version.

We'd like a way to suppress the verbose messages output when using Skip.  We noticed that a `noisySkippings=false` option was present in a prior version of Ginkgo, but was removed in [this commit](https://github.com/onsi/ginkgo/commit/d981d36e9884231afa909627b9c275e4ba678f90).  We tried the `-succinct` flag, which looks like it should work, but that isn't suppressing the messages either.  Would it be possible to re-add the removed flag, or implement a similar method to suppress skip messages?

**Comment by onsi** [comment]
Hey @khuddlefish this sounds fine to me.  PRs wecome!  I honestly don't recall why I took the `noisySkipping` flag out but I think it would be fine to put it back in.  You'll want to check and make sure it works for parallel tests as well.

**Comment by williammartin** [comment]
This looks like it was closed by https://github.com/onsi/ginkgo/pull/385 so I'm going to go ahead and close this.

Thanks @khuddlefish feel free to reopen if there's anything further.
