### ISSUE TITLE
How to constrain test execution by OS?

### ISSUE THREAD

**Issue by nwoodmsft** [onsi/ginkgo#379]
In a project which has a mixture of Linux and Windows code conditionally compiling using build constraints (https://golang.org/pkg/go/build/) is there a way to constrain ginkgo test execution such that "ginkgo -r" will not try to execute Windows tests on Linux and vice versa?

For example, if I am on Linux and I switch to a directory which only contains .go files constrained to build on Windows (all files have a "//+build windows" header). When I run ginko inside that directory, it still picks up the *_test.go files and then displays the error:

>
> Failed to compile wincode:
> 
> can't load package: package github.com/blah/wincode: no buildable Go source files in /home/user/gopath/src/github.com/blah/wincode
> 
> Ginkgo ran 1 suite in 436.634413ms
> Test Suite Failed
> 

I have tried adding a build constraint inside of the *_test.go files themselves, but this did not seem to be effective. I saw that there is a -skipPackage parameter which can be passed to Ginkgo to tell it skip certain packages, but i'm hoping there is a better solution which I have missed?

**Comment by williammartin** [comment]
If I understand the question correctly (I'm pretty weak on the build constraints stuff sorry), you can pass `-tags` as an argument to `ginkgo` or `ginkgo build`, though I'm surprised at the OS behaviour. Might have to test this one out myself.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

A few others have raised this issue and I think a common solution is to allow Ginkgo to ignore test suites with no buildable files and treat them as passed.  I'm aiming to have that land in v2.

I'm going to close this for now, but feel free to reopen it if you'd like.
