### ISSUE TITLE
Test failures in Go 1.10 due to rand.Perm changes

### ISSUE THREAD

**Issue by heschik** [onsi/ginkgo#388]
internal/spec/specs_test.go and internal/suite/suite_test.go include tests that expect rand.Perm to return a particular ordering based on a given seed. https://golang.org/cl/55972 changed the Perm algorithm, breaking those tests. This will cause trouble when 1.10 is released.

**Comment by stamblerre** [comment]
The perm change has been reverted in [http://golang.org/cl/78195](http://golang.org/cl/78195), so this is now fixed.

**Comment by williammartin** [comment]
@heschik @stamblerre Thanks for keeping an eye on this. Going to close this out.
