### ISSUE TITLE
Contribution document is out of sync with CI

### ISSUE THREAD

**Issue by hoegaarden** [onsi/ginkgo#395]
- [`CONTRIBUTING.md`](https://github.com/onsi/ginkgo/blob/master/CONTRIBUTING.md#L9) states that tests should be run as `gingko -r -p`.
- In CI [tests](https://github.com/onsi/ginkgo/blob/7a241e9c6c7fb89adf3965bd763b7369b88a51eb/.travis.yml#L15) run as `ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace`, so **not** in parallel.

#394 shows that there is a difference when tests run in parallel or not, maybe that creeped in because of the above mentioned mismatch.

**Comment by williammartin** [comment]
Hey, would definitely like a PR for this but doesn't look like we can do it correctly until https://github.com/onsi/ginkgo/issues/394 gets fixed otherwise CI will break.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.
I'm going to close this for now, but feel free to reopen it if you'd like.
