### ISSUE TITLE
Conventional import ordering in generated code

### ISSUE THREAD

**Issue by martinxsliu** [onsi/ginkgo#396]
Currently, in the code generated by the `ginkgo bootstrap` and `ginkgo generate` commands, the imports are ordered like:

```go
// ginkgo bootstrap
import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"

	"testing"
)

// ginkgo generate
import (
	. "github.com/martinxsl/foo/bar"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)
```

This goes against conventional rules which suggests that standard library imports should come first (e.g. see: https://github.com/golang/go/wiki/CodeReviewComments#imports) followed by third party imports and then followed up by local imports (which is encouraged by [goimports](https://github.com/golang/tools/commit/ed69e84b1518b5857a9f4e01d1f9cefdcc45246e)).

I propose that we reverse the grouping of imports so that it does follow conventions like so:

```go
// ginkgo bootstrap
import (
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

// ginkgo generate
import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"

	. "github.com/martinxsl/foo/bar"
)
```

I'm happy to open a PR for this.

**Comment by williammartin** [comment]
Hey @martinxsliu cool catch. Happy to review a PR for this.

**Comment by williammartin** [comment]
Merged the PR so I'm gonna close this, thanks!
