### ISSUE TITLE
Ginkgo README has a lot of duplication

### ISSUE THREAD

**Issue by williammartin** [onsi/ginkgo#407]
Seems like a lot of stuff in the README is duplicated from the docs, maybe we could just point to the docs like Gomega does and keep the README real simple?

What is in the README that isn't in the docs? What would we need to port over to the docs?

**Comment by squeedee** [comment]
I think the typical idiom is for:
  * a doc site to describe using the product, in this case, target developers using ginkgo to test their own work. 
  * the README to tell people where to get help (point to the docs) and if not seperated, to cover contribution related topics. Eg, conventions used, setting up ci, testing style etc.

**Comment by onsi** [comment]
ima massage the docs and readme as part of the v2 work... eventually.  gonna close this for now.
