### ISSUE TITLE
go test fails on pending tests

### ISSUE THREAD

**Issue by genexp** [onsi/ginkgo#411]
I'm seeing a strange issue.. for some reason, when I use `go test` instead of the Ginkgo runner, it fails when I have pending tests, but only on our CI server.

I verified both have Ginkgo 1.4 installed, and Go 1.9.2.  The CI server uses an Ubuntu image, whereas locally I'm on OSX.

**Comment by williammartin** [comment]
Any chance you can point us to / snippet the test scripts you are running / your CI server output?
