### ISSUE TITLE
Running many routines involving Sync RWMutex and atomic counters triggers a count mismatch when evaluating the test

### ISSUE THREAD

**Issue by tappoz** [onsi/ginkgo#413]
I've written a wrapper for a key/value map to store `int32` counters (as values) to track how many times `string`s representing error messages (as keys) have been seen so far.

I am currently working in Go 1.8 so I can not use `sync.Map` at the moment, however I ended up using:

- `sync.RWMutex` to control the access to read/insert/update map values
- `sync/atomic` to store the values as counters

# Testing:

- When using `ginkgo` and `gomega` and running a test with 1000 go **routines** updating the counter (map value) for the same input string (map key) using `sync.WaitGroup`, then most of the times the final counter stores 1001 instead of 1000. 
- When using `ginkgo` and `gomega` and running 10 routines this mismatch does not happen.
- When running a test using `testing.T` from the standard library, then this issue is not happening. Even with billions of routines.

# Code

The following is the piece of code managing the map:

```go
    package services
    
    import (
    	"sync"
    	"sync/atomic"
    )
    
    type ErrorsManager interface {
    	Store(errorMsg string) int32
    	GetCount(errorMsg string) int32
    }
    
    type atomicCounter int32
    
    func (ac *atomicCounter) plusOne() int32 {
    	return atomic.AddInt32((*int32)(ac), 1)
    }
    func (ac *atomicCounter) current() int32 {
    	return atomic.LoadInt32((*int32)(ac))
    }
    
    type errorsManager struct {
    	eCounterMapMutex sync.RWMutex
    	eCounterMap      map[string]atomicCounter
    }
    
    func NewErrorsManager() ErrorsManager {
    	return &errorsManager{
    		eCounterMapMutex: sync.RWMutex{},
    		eCounterMap:      make(map[string]atomicCounter),
    	}
    }
    
    func (em *errorsManager) Store(errorMsg string) int32 {
    	em.eCounterMapMutex.Lock()
    	currVal := em.eCounterMap[errorMsg]
    	currVal.plusOne()
    	em.eCounterMap[errorMsg] = currVal
    	em.eCounterMapMutex.Unlock()
    	return currVal.current()
    }
    
    func (em *errorsManager) GetCount(errorMsg string) int32 {
        // here the mismatch happens also using RLock/RUnlock
    	em.eCounterMapMutex.Lock()
    	count := em.eCounterMap[errorMsg]
    	em.eCounterMapMutex.Unlock()
    	return count.current()
    }
```

The following is the test (using `ginkgo` and `gomega`):

```go
    package services_test
    
    import (
    	"<MY_PATH_TO>/services"
    	. "github.com/onsi/ginkgo"
    	. "github.com/onsi/gomega"
    	"sync"
    )
    
    var _ = Describe("ErrorsManager", func() {
    
    	em := services.NewErrorsManager()
    
    	It("should concurrently update the counter for that error message", func() {
    		expectedTotalCount := 1000
    		errorMsg := "foo"
    		var wg sync.WaitGroup
    
    		for i := 1; i <= expectedTotalCount; i++ {
    			wg.Add(1)
    			go func(em services.ErrorsManager, errorMsg string, index int) {
    				_ = em.Store(errorMsg)
    				wg.Done()
    			}(em, errorMsg, i)
    		}
    		wg.Wait()
    
    		Expect(em.GetCount(errorMsg)).To(Equal(int32(expectedTotalCount)))
    	})
    })
```

This is the test using the standard library:

```go
package services

import (
	"fmt"
	"sync"
	"testing"
)

func TestStuff(t *testing.T) {

	em := NewErrorsManager()

        // billions of routines
	expectedTotalCount := 1000000000
	errorMsg := "foo"
	var wg sync.WaitGroup

	for i := 1; i <= expectedTotalCount; i++ {
		wg.Add(1)
		go func(em ErrorsManager, errorMsg string, index int) {
			_ = em.Store(errorMsg)
			wg.Done()
		}(em, errorMsg, i)
	}
	wg.Wait()

	found := em.GetCount(errorMsg)
	expected := int32(expectedTotalCount)
	if found != expected {
		t.Error(fmt.Sprintf("Mismatch! Expected: %v but found: %v", expected, found))
	}
}
```

**Comment by williammartin** [comment]
Hmmm, I ran the ginkgo test you provided `-untilItFails` and got 1000 successful runs in a row on:

```
go version go1.9.2 darwin/amd64
ginkgo sha: bc14b66 (origin/master right now)
```

Any chance you can try your reproduction using latest versions and see if it reproduces?

**Comment by tappoz** [comment]
My setup is the following:
```
$ go version
go version go1.8.5 linux/amd64
$ ginkgo version
Ginkgo Version 1.4.0
```

Unfortunately I can not quickly update those versions.

By the way: the test I mentioned earlier with the standard library usage run against 100,000 routines (not billions). Apologies for that.

**Comment by williammartin** [comment]
@tappoz Just to check I'm accurately reproducing, can you:

```
go get github.com/williammartin/rwmutextest
cd $GOPATH/src/github.com/williammartin/rwmutextest
ginkgo -untilItFails
```

And if it's not failing, let me know what is wrong with the reproduction case? Thanks.

**Comment by tappoz** [comment]
Uhm, no errors. I've run it for 1685 times (then hit ctrl+c). 

I have to say this failing test is running among other test files involving real TCP calls and real ICMP calls. ICMP calls on Linux mean using raw sockets, so I have to run those tests as root with an alias to `sudo` to be able to include `$GOPATH/bin` in the environment of `sudo`.

**Comment by williammartin** [comment]
So within that suite of tests, if you focus this test, is it stable?

**Comment by tappoz** [comment]
With `FIt(...)`? Yes it's stable. 

That `Describe(...)` is actually running another test changing the same map. Apologies, my bad, it seems I was misusing the test suite when sharing the map instance among many tests.

**Comment by williammartin** [comment]
🥇  So we're good and can close this out?

Doh, there are some other golang test libraries around that don't use closures to help avoid test pollution. Wondering if we should look at those moving forward for inspiration in this area. :)

**Comment by tappoz** [comment]
Thanks for the support, this was just a naive mistake. Once I realized those multiple tests sharing the same instance I felt a bit ashamed :)

**Comment by williammartin** [comment]
No problem, we've all been there.
