### ISSUE TITLE
Need a flag to turn off Focus Test exits with error code 

### ISSUE THREAD

**Issue by rancheral** [onsi/ginkgo#416]
Currently, ginkgo exits with error code 197 when running focused tests.  However, that causes certain ides to not provide coverage reports because it thinks the testing failed.  I can't find a flag for turning this behaviour on/off.  Please provide a failOnFocus flag similar to failOnPending flag.

**Comment by onsi** [comment]
#367 should resolve this.  Take a look!

**Comment by rancheral** [comment]
Verified that setting GINKGO_EDITOR_INTEGRATION=true before running focus test resolved this issue.  Thanks!

**Comment by EronWright** [comment]
In VS Code, configure the setting named "Go: Test Env Vars":

```json
    "go.testEnvVars": {
        "GINKGO_EDITOR_INTEGRATION": "1"
    },
```
