### ISSUE TITLE
Unable to read coverage file

### ISSUE THREAD

**Issue by genexp** [onsi/ginkgo#417]
Hey all - Strangely, on our CI system I get the error "Unable to read coverage file" about 30% of the time.   The error seems to be here:
```
https://github.com/onsi/ginkgo/blob/11459a886d9cd66b319dac7ef1e917ee221372c9/ginkgo/run_command.go#L173
```

In any case, the error is due to the following Ginkgo command:
```
ginkgo -r -race -outputdir=. -coverprofile=coverage.txt -covermode=atomic .;
```

I'm really not sure why it happens, or only some of the time.  I suspect perhaps its trying to consolidate cover profiles before they're actually written?

**Comment by genexp** [comment]
To give a little more background here, I am generating both per-package level profiles, as well as a consolidated one.  To get things working again, I ended up getting get of -outputdir and wrote a bash script to combine profiles.  I'm up and working, just wanted to log this as a low-priority. :)

**Comment by williammartin** [comment]
@genexp Can you paste the full error here? Also, can you confirm that is the exact command you are running, and it's not being killed mid-run or anything?

Thanks

**Comment by genexp** [comment]
Hey @williammartin sure!  I actually think this might have to do with the race condition I'm getting, and the job failing.  Closing this until I do more investigation.

**Comment by williammartin** [comment]
The reason I'm suspicious is that if you `ctrl+C` ginkgo right after starting it, because of the interrupt handling, you'll end up with a similar error (might be worth an issue of its own to avoid confusion). Good luck
