### ISSUE TITLE
Data Race

### ISSUE THREAD

**Issue by genexp** [onsi/ginkgo#418]
We're getting a data race condition in some of the concurrent portions of our code, probably based on a misunderstanding of how we should be using Ginkgo.  We're wondering, how does this work:

```
var _ = Describe("Solver when Solving", func() {
	var (
		person *Person
	)

	BeforeEach(func() {
		person = NewPerson()
	})

	It("Should do something that spawns a Go routine and modifies person", func() {
        }

	It("Should also do something that spawns a Go routine and modifies person", func() {
        }
}
```

We're getting test failures when we enable "--race".  I assumed that (somehow) BeforeEach was being run before each IT statement, and each subsequent IT wouldn't run until the previous completed.

Am I right in this assumption?

**Comment by onsi** [comment]
Yes, `BeforeEach` runs before each `It` and that `It`s always run in series.  However an `It` has no idea if you've spawned a goroutine and it's on you to block until all your goroutines have finished.

A hokey example:

```
var _ = Describe("Solver when Solving", func() {
	var (
		person *Person
	)

	BeforeEach(func() {
		person = NewPerson()
	})

	It("Should do something that spawns a Go routine and modifies person", func() {
              done := make(chan struct{})
              go func() {
                  person = NewPerson("again")
                  close(done)
              }()
              
             Eventually(done).Should(BeClosed()) //this is using Gomega which has strong support for asynchronous assertions.
        }

	It("Should also do something that spawns a Go routine and modifies person", func() {
        }
}
```
Does that make sense?  If you have a more fleshed out example I can try to be more specific and helpful.

**Comment by genexp** [comment]
Thanks @onsi yeah, that makes sense.  We're theoretically firing up go routings and blocking until they are complete within the function we're testing (so it *should* feel like a normal function).

That said, likley PEBKAC. :)

Thanks for the hand!

**Comment by onsi** [comment]
yeah - if the function is blocking it should be fine.  are you reassigning `person` or modifying it (with some sort of atomic primitive to ensure modifications are threadsafe?) - if you are reassigning it the race detector may be catching the fact that you're making a non-threadsafe change to `person` from two different goroutines (even though you might know the goroutines can't run in parallel, I don't think the race detector cares).

**Comment by williammartin** [comment]
@genexp If you want to drop a more complete example/reproduction, I'm happy to have a look at it for you.

**Comment by genexp** [comment]
Thanks all!  I'm going to close this to keep the Issue list clean, and will reopen if I'm still stuck after I investigate a bit more.

@onsi @williammartin Thank you!
