### ISSUE TITLE
Ginkgo callbacks ?

### ISSUE THREAD

**Issue by arthurgustin** [onsi/ginkgo#422]
Hi, I'm in a situation where I have asynchronous magic stuff, and I want to test the content of a specific log number, and this log depends on a POST timeout I set in a http client, and the limit number of goroutine I set (those goroutines make concurrent POST request to different host), but it does not matter.

I got this function to test the total number of logs made:

```
assertWarnLogCount = func(count int) {
	It("should log warning", func() {
		Eventually(warnCount, 15*time.Second, 1*time.Second).Should(Equal(count))
	})
}
```
Which works well.

And this horrible function to test that I successfully logged a `timeout` in my function.
I'm forced to do this because my function does not return an error, it should be ignored in the workflow but we still want the information.

```
assertWarnWithFields = func(num int, fieldName, fieldValue string) {
	It("should warn with fields", func() {
		// black magic. the idea is to be sure that all logs have been made to check the logs content
		timeToSleep := time.Duration(float64(postNotificationTimeout)/float64(maxConcurrentNotifications)) + serverWaitBeforeRespond
		time.Sleep(timeToSleep*time.Second)
		call := mockLogger.CallsForMethod("Warn")[num]
		fields := call.Arguments.Get(2).(logger.Fields)
		Expect(fields[fieldName]).To(ContainSubstring("request canceled (Client.Timeout exceeded while awaiting headers)"))
	})
}
```

Any ideas ? Not sure if my explanation was clear enough. I think it would have been easier if we could attach callbacks that triggers when the `Eventually` becomes true, but that's not very go-lish

**Comment by williammartin** [comment]
Sorry @arthurgustin I'm not sure what you're asking here. Maybe you could write some code that represents what you would like?

I don't see how a callback differs in this case from doing:

```
Eventually()
Callback()
```

**Comment by arthurgustin** [comment]
What I want to do is trigger another test when `Eventually` becomes true because I don't know when my goroutines finish and there are things I can only test *after* my goroutines finish

**Comment by onsi** [comment]
Ah I see.  It's important to understand that Ginkgo takes the stance that your `It`s should be completely independent of each other.  This enables race-free paralellization and test randomization (which is important for sussing out test pollution).

In this case you could combine these into one `It`.  Or put `Eventually(warnCount, 15*time.Second, 1*time.Second).Should(Equal(count))` into a `BeforeEach`.

**Comment by arthurgustin** [comment]
Wow that was that simple ok
```
testOnsi = func(count int, num int, fieldName, fieldValue string) {
	It("should log warning", func() {
		Eventually(warnCount, 15*time.Second, 1*time.Second).Should(Equal(count))
		call := mockLogger.CallsForMethod("Warn")[num]
		fields := call.Arguments.Get(2).(logger.Fields)
		Expect(fields[fieldName]).To(ContainSubstring("request canceled (Client.Timeout exceeded while awaiting headers)"))
	})
}
```

Need to lint the code a bit but it works as expected.
Thanks @onsi

**Comment by williammartin** [comment]
Thanks @arthurgustin, can we close this out now?

**Comment by arthurgustin** [comment]
yep
