### ISSUE TITLE
Have some question about Eventually()

### ISSUE THREAD

**Issue by MrDaBIng** [onsi/ginkgo#425]
I define a variable outside of Eventually (), modify that variable within the method in Eventually ():
```golang
It("Eventually test", func() {
	var str string
	Eventually(func() string {
		str = "1234"
		return ""
	}).Should(Equal("345"), fmt.Sprint("str = ", str))
})
```
The result is : 
```
Timed out after 1.001s.
  str =
  Expected
      <string>:
  to equal
      <string>: 345
```
why dose the str print ""??

**Comment by williammartin** [comment]
I think that at the time you are calling `.Should(Equal("345"), fmt.Sprint("str = ", str))`, the `fmt.Sprint` is being evaluated. The `Should` is evaluated _before_ your anonymous function is executed, so the value of `str` will not have been updated. 

Also, for future, this is really a question about the `Gomega` matching library. Hope that helps.

**Comment by williammartin** [comment]
I'm going to close this out, feel free to reopen if you need further help.

**Comment by MrDaBIng** [comment]
ok, thanks
