### ISSUE TITLE
JUnit Test Reporter

### ISSUE THREAD

**Issue by yaede7** [onsi/ginkgo#428]
Is there any possible way to use the JUnit reporter across many suites that merge into one directory?

```
//Test Suite A in ./dirA/a_suite_test.go
RegisterFailHandler(Fail)
junitReporter := reporters.NewJUnitReporter("../merged.xml")
RunSpecsWithDefaultAndCustomReporters(t, "A Suite", []Reporter{junitReporter})

//Test Suite B in ./dirB/b_suite_test.go
RegisterFailHandler(Fail)
junitReporter := reporters.NewJUnitReporter("../merged.xml")
RunSpecsWithDefaultAndCustomReporters(t, "B Suite", []Reporter{junitReporter})
```

The desired output would be the merged results of both A Suite and B Suite in the merged.xml file

Any ideas or input on this would be greatly appreciated.

**Comment by johnSchnake** [comment]
FWIW the junit specification seems to support multi-suite results: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd (just thought I'd drop this here as I am investigating if ginkgo supports this and if not, why)

**Comment by Athosone** [comment]
Hi did you figured this out?

**Comment by onsi** [comment]
If the schema supports this we can add this to Ginkgo, likely in the v2 timeframe.  I could have the CLI own merging the various output xmls into a singular combined file if the user passed `--junit-report=destination.xml`

to the folks on this issue: would you ever want individual reports from individual suites?  or just the one combined report? my instinct is that `ginkgo --junit-report=foo.xml` should *always* produce exactly one report at the specified location regardless of test parallelization, number of suites running, etc. and never pollute the various test suite directories with individual reports.  Does that sound right?

**Comment by onsi** [comment]
A beta for Ginkgo V2 that addresses this issue was just released - Ginkgo can now produce combined Unit reports as well as keep them separate.   [Please try out the beta](https://github.com/onsi/ginkgo/issues/809)!

**Comment by aojea** [comment]
> to the folks on this issue: would you ever want individual reports from individual suites? or just the one combined report? my instinct is that `ginkgo --junit-report=foo.xml` should _always_ produce exactly one report at the specified location regardless of test parallelization, number of suites running, etc. and never pollute the various test suite directories with individual reports. Does that sound right?

@onsi is it possible to choose the old behavior or to select a rotation by size per example?

using an individual file makes the output so big that some tools are not able to process them
https://github.com/kubernetes/kubernetes/issues/111510
