### ISSUE TITLE
Helper functions for logging?

### ISSUE THREAD

**Issue by attila123** [onsi/ginkgo#429]
I'm new to Go and ginkgo (selected that because seems to be the most feature packed test framework out there :) ).
The documentation mentions GinkgoWriter (but assumes to find out more details about io.writer to use it), and for me it seems to be used  mostly in these ways:
io.WriteString(GinkgoWriter, "Some log text")
or maybe:
io.WriteString(GinkgoWriter, fmt.Sprintf("Some log text: %v\n", someVariable))
Both of them seem to be a bit too long (boilerplate-ish).
What about creating some wrapper functions for these 2 most common logging use cases following the interface of log.Println and log.Printf?
E.g.
GinkgoPrintln("Some log text:", someVariable)
GinkgoPrintf("Printf style logging of %v and %v", someVar1, someVar2)

**Comment by jsamr** [comment]
+1
Although this is easier

```go
fmt.Fprintf(GinkgoWriter, "Some log text: %v\n", someVariable)
```

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I'll be adding `GinkgoPrintln` and `GinkgoPrintf` to v2

I'm going to close this for now, but feel free to reopen it if you'd like.

**Comment by onsi** [comment]
A beta for Ginkgo V2 that addresses this was just released.  `GinkgoWriter` now provides a bunch of [convenience methods](https://github.com/onsi/ginkgo/blob/ver2/core_dsl.go#L61-L70).    [Please try out the beta](https://github.com/onsi/ginkgo/issues/809)!
