### ISSUE TITLE
Improve error reporting with table driven tests

### ISSUE THREAD

**Issue by relnod** [onsi/ginkgo#431]
Hi, I have the following test:
```go
var _ = DescribeTable("Foo",
	func(in int, expected int) {
		Ω(in).Should(BeNumerically("==", expected))
	},
	Entry("first entry", 1, 1),
	Entry("second entry", 1, 2),
)
```
When I run the test suite, the second entry fails, which is expected. The problem I have is, that the error reporter says, that the failed test is in the line, where the assert happend instead of the line, where I declared my second entry.

Ideally the reporter would tell me both lines. The line of the assert and the line of the entry.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

The error report also includes the location of the entry that failed - it'll be just before the failure message.

I'm going to close this for now, but feel free to reopen it if you'd like.
