### ISSUE TITLE
ginkgo unfocus should remove FSpecify

### ISSUE THREAD

**Issue by mezis** [onsi/ginkgo#433]
`ginkgo unfocus` [removes](https://github.com/onsi/ginkgo/blob/4e84bbfb7d968ebd967a58e4af1015c9d8dc5275/ginkgo/unfocus_command.go#L23-L28) focus for most blocks, except `FSpecify`.

Unless there's a valid reason I'm missing, should we amend it to also unfocus `FSpecify`?

**Comment by nodo** [comment]
@mezis I agree, it definitely should 👍  would you be happy to create a PR?

**Comment by mezis** [comment]
@nodo will do!
