### ISSUE TITLE
Run AfterEach function if failFast is enabled

### ISSUE THREAD

**Issue by ianvernon** [onsi/ginkgo#437]
I would like the ability to run the `AfterEach` function for each test if `-failFast` is provided as an option to run Ginkgo. This allows for certain operations that I'd like to run after every test even in the case of failure to occur, but without running subsequent tests.

**Comment by williammartin** [comment]
Hi @ianvernon can you provide a more concrete example of the behaviour you'd like, I can't quite picture the use case. Thanks.

**Comment by ianvernon** [comment]
Closing this for now. Sorry for the noise.
