### ISSUE TITLE
Which variables are shared when running specs in parallel?

### ISSUE THREAD

**Issue by kchristidis** [onsi/ginkgo#440]
## Background

Consider these bits from [the documentation](http://onsi.github.io/ginkgo/):

1. You can add a single spec by placing an `It` block within a `Describe` or `Context` container block.
2. In general, the only code within a container block should be an `It` block or a `BeforeEach`/`JustBeforeEach`/`AfterEach` block, or closure variable declarations.
3. It is a mistake to initialize a closure variable in a container block. If one of your `It`s mutates that variable, subsequent `It`s will receive the mutated value. This is a case of test pollution and can be hard to track down. Always initialize your variables in `BeforeEach` blocks.
4. When running in parallel, each parallel process will run `BeforeSuite` and `AfterSuite` functions.
5. Ginkgo has support for running specs in parallel. It does this by spawning separate `go test` processes and serving specs to each process off of a shared queue. This is important for a BDD test framework, as the shared context of the closures does not parallelize well in-process.

## Example

Now consider a simplistic (and rather nonsensical) suite that consists of 2 specs.

(As I understand it from item 5 in the "Background" section, an `It` block constitutes a spec.)

```go
func TestIntegration(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Integration Suite")
}

var _ = Describe("Parallelism", func() {
	var foo int
    GinkgoWriter.Write([]byte("Do I see this line twice?\n"))

	BeforeEach(func() {
		rand.Seed(time.Now().UnixNano())
		foo = rand.Intn(1000) + 1
	})

	Specify(fmt.Sprintf("Node %d of %d should find foo to be non-negative", config.GinkgoConfig.ParallelNode, config.GinkgoConfig.ParallelTotal), func() {
		GinkgoWriter.Write([]byte(fmt.Sprintf("Spec #1 foo address: %p\n", &foo)))
		GinkgoWriter.Write([]byte(fmt.Sprintf("Spec #1 foo value: %d\n", foo)))
		Expect(foo).Should(BeNumerically(">", 0))
	})

	Specify(fmt.Sprintf("Node %d of %d should find find foo to be non-negative", config.GinkgoConfig.ParallelNode, config.GinkgoConfig.ParallelTotal), func() {
		GinkgoWriter.Write([]byte(fmt.Sprintf("Spec #2 foo address: %p\n", &foo)))
		GinkgoWriter.Write([]byte(fmt.Sprintf("Spec #2 foo value: %d\n", foo)))
		Expect(foo).Should(BeNumerically(">", 0))
	})
})
```

Note that the suite above follows rules 2 and 3 from the "Background" list.

## Test Output

I execute this suite in parallel, on 2 nodes.

Run #1 — notice how the addresses for `foo` are identical:

```bash
$ ginkgo -nodes=2 -v -stream
[1] Do I see this line twice?
[2] Do I see this line twice?
[2] Running Suite: Integration Suite
[2] ================================
[2] Random Seed: 1520699572
[2] Parallel test node 2/2.
[2]
[1] Running Suite: Integration Suite
[1] ================================
[1] Random Seed: 1520699572
[1] Parallel test node 1/2.
[1]
[2] Parallelism
[2]   Node 0 of 0 should find foo to be non-negative
[2]   /Users/kchrist/Go/src/github.com/hyperledger/fabric/integration/integration_suite_test.go:27
[2] Spec #1 foo address: 0xc4200168f8
[2] Spec #1 foo value: 762
[1] Parallelism
[1]   Node 0 of 0 should find find foo to be non-negative
[1]   /Users/kchrist/Go/src/github.com/hyperledger/fabric/integration/integration_suite_test.go:33
[1] Spec #2 foo address: 0xc4200168f8
[1] Spec #2 foo value: 957
[2] •
[2] Ran 1 of 1 Specs in 0.001 seconds
[2] SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
[1] •
[1] Ran 1 of 1 Specs in 0.001 seconds
[1] SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Ginkgo ran 1 suite in 756.704788ms
Test Suite Passed
```

Run 2 — notice how the addresses for `foo` are now different:

```bash
$ ginkgo -nodes=2 -v -stream
[1] Do I see this line twice?
[2] Do I see this line twice?
[1] Do I see this line twice?
[2] Do I see this line twice?
[1] Running Suite: Integration Suite
[1] ================================
[1] Random Seed: 1520699630
[1] Parallel test node 1/2.
[1]
[2] Running Suite: Integration Suite
[2] ================================
[2] Random Seed: 1520699630
[2] Parallel test node 2/2.
[2]
[1] Parallelism
[1]   Node 0 of 0 should find foo to be non-negative
[1]   /Users/kchrist/Go/src/github.com/kchristidis/foo/integration/integration_suite_test.go:27
[1] Spec #1 foo address: 0xc4200168f8
[1] Spec #1 foo value: 707
[2] Parallelism
[1] •
[2]   Node 0 of 0 should find find foo to be non-negative
[1] Ran 1 of 1 Specs in 0.001 seconds
[1] SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
[2]   /Users/kchrist/Go/src/github.com/kchristidis/foo/integration/integration_suite_test.go:33
[2] Spec #2 foo address: 0xc420090858
[2] Spec #2 foo value: 286
[2] •
[2] Ran 1 of 1 Specs in 0.001 seconds
[2] SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Ginkgo ran 1 suite in 789.530981ms
Test Suite Passed
```

## Observations

1. The value of `foo` is different between specs, which confirms item 4 from the "Background" list; each process executes the `BeforeSuite` function (and the randomization contained within).
2. The "Do I see this line twice?" string is printed twice, which suggests that it is not only the `BeforeEach` and an `It` block that each process executes. It is also the rest of the code (i.e. the closure variable declaration) in the `Describe` block.

## Question

Why does test run 1 suggest that each process operates on a separate copy of `foo`, while test run 2 suggests that this isn't the case? (Compiler optimization?)

I would have expected the output to be deterministic. And based on observation item 2, I would have only expected the output of test run 1.

I suspect I may be missing/misinterpreting something fundamental here. What is it? Thanks!

**Comment by amitkrout** [comment]
I am also having the same observation while running my test on four test node

```
package integration

Test suite file
```
import (
	"os"
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"github.com/openshift/odo/tests/helper"
)

func TestIntegration(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Integration Suite")
}

var _ = BeforeSuite(func() {
	var clusterURL, userName, password string
	if os.Getenv("CLUSTER_LOGIN_URL") == "" {
		clusterURL = ""
	} else {
		clusterURL = os.Getenv("CLUSTER_LOGIN_URL")
	}
	if os.Getenv("CLUSTER_USER_NAME") == "" {
		userName = "developer"
	} else {
		userName = os.Getenv("CLUSTER_USER_NAME")
	}
	if os.Getenv("CLUSTER_PASSWORD") == "" {
		password = "developer"
	} else {
		password = os.Getenv("CLUSTER_PASSWORD")
	}
	helper.CmdShouldPass("odo", "login", "-u", userName, "-p", password, clusterURL,"--insecure-skip-tls-verify")
})

var _ = AfterSuite(func() {
	helper.CmdShouldPass("odo", "logout")
})
```

Test result:
```
$ ginkgo -v -nodes=4 -focus="odoWatchE2e" slowSpecThreshold=120 -randomizeAllSpecs  tests/integration/ -timeout 1800s
Running Suite: Integration Suite
================================
Random Seed: 1563170518
Will run 90 specs

Running in parallel across 4 nodes

Running odo with args: [login -u developer -p developer --insecure-skip-tls-verify] 
[odo] Connecting to the OpenShift cluster
[odo] 
[odo] Login successful.
[odo] 
[odo] You have one project on this server: "myproject"
[odo] 
[odo] Using project "myproject".


Running odo with args: [login -u developer -p developer --insecure-skip-tls-verify] 
[odo] Connecting to the OpenShift cluster
[odo] 
[odo] Login successful.
[odo] 
[odo] You have one project on this server: "myproject"
[odo] 
[odo] Using project "myproject".

SSSSS
------------------------------
Running odo with args: [login -u developer -p developer --insecure-skip-tls-verify] 
[odo] Connecting to the OpenShift cluster
[odo] 
[odo] Login successful.
[odo] 
[odo] You have one project on this server: "myproject"
[odo] 
[odo] Using project "myproject".


Running odo with args: [login -u developer -p developer --insecure-skip-tls-verify] 
[odo] Connecting to the OpenShift cluster
[odo] 
[odo] Login successful.
[odo] 
[odo] You have one project on this server: "myproject"
[odo] 
[odo] Using project "myproject".

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[...]
```

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now, I'm sorry I couldn't engage with it back in 2018!  I have much more time to work on Ginkgo these days and am trying to go through and look at all existing issues as I work towards [v2](#711).

To answer your questions:

> Why does test run 1 suggest that each process operates on a separate copy of foo, while test run 2 suggests that this isn't the case? (Compiler optimization?)

I know this is an unsatisfying answer but I think what you saw was a coincidence.  There are two separate processes running here.  They simply can't be sharing data.

> I would have expected the output to be deterministic. And based on observation item 2, I would have only expected the output of test run 1.

You will see `"Do I see this line twice?\n"` once for each node you run (so `ginkgo -nodes=7` would have printed it out seven times).  It will be printed when the tree is first traversed.  You will _not_ see it printed more than once.  Try running with `-nodes=2` but adding several more tests to the container.  You'll note that the line isn't printed again.

You can learn more about the tree traversal phase vs the test running phase [here](https://onsi.github.io/ginkgo/#understanding-ginkgos-lifecycle).

I'm going to close this for now, but feel free to reopen it if you'd like.
