### ISSUE TITLE
ginkgo produces unparseable by cmd/test2json output

### ISSUE THREAD

**Issue by zolotov** [onsi/ginkgo#447]
Given a test file:

```
package main

import (
	"testing"
)

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

//Bootstrap ginkgo
func TestContext(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Testing the scheduler")
}
```

While running with an official `test2json` utility, it doesn't produce `TestPassed` event, because of missing `\n` after status line: 

https://github.com/onsi/ginkgo/blob/5ca121185e255e5041d7727d77992618545a93d2/reporters/stenographer/stenographer.go#L181

```
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped --- PASS: TestContext (0.00s)
```

should be 

```
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestContext (0.00s)
```

**Comment by nodo** [comment]
Hey @zolotov,

Thanks! This sounds like an issue! Would you be able to open a PR for that?
