### ISSUE TITLE
Ginkgo leaking color encoding in test logs

### ISSUE THREAD

**Issue by mjaiswal90** [onsi/ginkgo#449]
##Summary 

On running the test suite, sometimes the test suite leaks the color encoding in the test log making it unreadable.(See the testlog screenshot).I suspect that these are getting leaked from the  ginkgo/main.go 

lines 135-138
const greenColor = "\x1b[32m"
const redColor = "\x1b[91m"
const defaultStyle = "\x1b[0m"
const lightGrayColor = "\x1b[37m"

Also from diff_test.go:-

Line 958
Expected: "a\n\x1b[31m<B>b</B>\x1b[0m\x1b[32mc&d\x1b[0m",

![screen shot 2018-04-02 at 5 38 40 pm](https://user-images.githubusercontent.com/10431760/38223788-8ffc5e1c-36a1-11e8-915d-3285b89263df.png)

**Comment by nodo** [comment]
Hi @mjaiswal90,

does this happen using a specific suite? If this is the case please could you post it so that it's easier to reproduce the issue?

**Comment by williammartin** [comment]
I'm interested in what you mean by "sometimes the test suite" demonstrates this behaviour. I would have expected this to be an issue with terminal colour configuration.

**Comment by zolotov** [comment]
This is issue of GoLand. See https://youtrack.jetbrains.com/issue/GO-5467

**Comment by mjaiswal90** [comment]
What @zolotov said seems to be the reason for this issue . Thanks for participating in the conversation guys. I will close this issue now.
