### ISSUE TITLE
When are you creating the next release? 

### ISSUE THREAD

**Issue by mirandamauricio** [onsi/ginkgo#454]
My company has a policy to only use released versions and there are lots of bugs resolved and not released.

**Comment by williammartin** [comment]
@mirandamauricio I don't see any reason we couldn't release imminently really, though I'd have to check with other maintainers. Would it help you if we did so?

**Comment by mirandamauricio** [comment]
Sure!

**Comment by mirandamauricio** [comment]
Is there anything I can do to help speedup this process?

**Comment by mirandamauricio** [comment]
Thanks very much.
