### ISSUE TITLE
Support warnings

### ISSUE THREAD

**Issue by stevenroose** [onsi/ginkgo#458]
Support for warnings would be nice. Something that leaves a clear message in the output, but still marks the test as succeeded.

Syntactically could be like 
```go
Warn(Expect(answer).To(Equal(42)))
```
or
```go
Expect(answer).To(Equal(42)).OrWarn()
```

**Comment by williammartin** [comment]
I think this is a Gomega issue, would you like me to open it there (https://github.com/onsi/gomega) or do you want to do so? Thanks for the issue, looks like an interesting one to discuss.

**Comment by stevenroose** [comment]
Hmm, well it could be ginkgo only, I guess. If ginkgo registers in the `Warn` function that it's in warning mode, if could then determine what to do inside `Fail`, since you declare `RegisterFailHandler` anyway. gomega can just fail, while ginkgo can catch it, knowing that the fail was produced in a `Warn` section.

**Comment by nodo** [comment]
It's a very interesting idea!

I think both options have pros and cons. Do you think that users of gomega and not ginkgo would benefit from this feature? If this is the case let's do it in gomega.

IMO I would implement it in gomega for the reason above, but happy to discuss.

**Comment by blgm** [comment]
The Golang philosophy is to not have warnings.  While I understand why people sometimes want them, it tends to drive behaviours that are in the end unhelpful.  The idea of a test is that it tells you whether some code is good or bad.  If you get a warning, then you either ignore it (in which case, what's the point of it?), or you spend time investigating and understanding it (which is unproductive).

Many things that are warnings in other languages (unused variables, type inference) are hard failures in Golang.  While I've often found that annoying, it forces the behaviour of always having clean code, and making hard decisions up front.

While I'm sure this is being suggested with the best motivation, and I'm sure there are situations where a warning might make sense, I'd worry about the implications it could have for less experienced programmers.

**Comment by stevenroose** [comment]
True. When ginkgo is primarily aimed at building test suites for Go code, I
agree that warnings don't make sense. I'm using it for some other means
(testing different servers for API compliance), where it would make sense.

**Comment by blgm** [comment]
Maybe an extension could be the right way forward?  It's great that Ginkgo has used beyond classical unit testing.  In the same way that Gomega is a pluggable extension, perhaps there could be a Gomega-warnings package that adds the functionality described?

**Comment by ZeroChanceCompile** [comment]
I know this is old but I'd also love to see warnings.
I'd use them in the BeforeEach. We do some test setup that uses external resources that occasionally fails. It would be nice to be able to differentiate between failed tests and failed setups.

**Comment by blgm** [comment]
Hi @ZeroChanceCompile. You could call `Skip()` if the setup fails, so you would end up with a skipped test rather than a failure.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

As part of the V2 work I'm adding the ability for the user to send structured data and messages to the Ginkgo reporter.  This would then be reported regardless of whether the test fails or succeeds.  I think that could help for this use case.

I'm going to close this for now, but feel free to reopen it if you'd like.
