### ISSUE TITLE
It() inside a for loop

### ISSUE THREAD

**Issue by vedujoshi** [onsi/ginkgo#462]
I am trying to understand ginkgo styling before proceeding to write tests.
When i run the below code, the It() is not executed. 
```
var _ = Describe("Name Tests", func() {
    var (
        names []string
        i string
    )
    BeforeEach(func() {
        names = []string{ "Vedu", "Joshi"}

    })

    Context("One way of testing...", func() {

            for _ , i = range names {
                It("should start with V", func() {

                    fmt.Println("i is %v", i)
                    By(fmt.Sprintf("Checking %s ", i))
                    Expect(string(i[0])).To(Equal("V"))
                })
            }

    })
})

```
But if I have the for loop inside It(), the test is run. Could you please help me understand why so? 
```
    Context("Another way of testing...", func() {
                It("should start with V", func() {
                    for _ , i = range names {
                       fmt.Println("i is %v", i)
                       By(fmt.Sprintf("Checking %s ", i))
                       Expect(string(i[0])).To(Equal("V"))
                   }
                })
    })
```

Is there a recommended way to pass args to It() or should I be thinking differently ? 
Also, The It() also has a float64 argument. May I know what is this for ?

**Comment by williammartin** [comment]
Hey @vedujoshi great questions.

The first one is a painful result of the multi-step flow Gingko does. Simplified it has two stages:
1. Parse: Execute the anonymous funcs passed to each container node (Describe, Context mainly) and store runtime blocks for later execution (Before*, It, After*)
2. Run the runtime blocks

What this means is that for your example, the for loop evaluates as part of step 1, but the assignment of `names` happens in step 2. Therefore, there are no values in the `names` slice, and no `It` blocks are stored for step 2.

You cannot pass extra args to `It`, but if you tell me more why you'd like to do that, hopefully I can help you with alternatives.

You can find information about the `float64` arg in the Ginkgo documentation (https://onsi.github.io/ginkgo/). In this case, it is referring to a timeout you can pass such that Ginkgo will fail test (https://onsi.github.io/ginkgo/#asynchronous-tests). I would recommend that you do not make use of this, and if you require failure after a certain time you make use of Gomega's `Eventually` or `Consistently` assertions (https://onsi.github.io/gomega/#making-asynchronous-assertions). The asynchronous timeout a candidate for removal if we ever do a major version bump.

Hope this helps!

**Comment by vedujoshi** [comment]
@williammartin Thanks very much...i get it now. Somehow, the help topic did not seem to reflect this info.
 
I was thinking about having ways to pass values to It() so that the same test can be run with different args(and thus reported as multiple tests)

The reason why i asked about float64 in It() above was because the function definition looked to accept a list of float64s ..am i reading correctly ?
https://github.com/onsi/ginkgo/blob/43392d5cb858ad4d08383cbe4f04850be9e97e29/ginkgo_dsl.go#L338

**Comment by williammartin** [comment]
I can't make much sense of the variadic float64, maybe @onsi can?

Would a table test work for you? https://onsi.github.io/ginkgo/#table-driven-tests

**Comment by williammartin** [comment]
@vedujoshi Any thoughts?

**Comment by vedujoshi** [comment]
@williammartin Thanks, it should do.

**Comment by MoserMichael** [comment]
But having a Context clause in a loop works. (It doesn't work in a loop but Context does). Go figure.

**Comment by williammartin** [comment]
@MoserMichael I'm not exactly sure what situation you are describing here. Given the example at the top of this spec:

```
var _ = Describe("Name Tests", func() {
	var (
		names []string
		i     string
	)
	BeforeEach(func() {
		names = []string{"Vedu", "Joshi"}

	})

	Context("One way of testing...", func() {

		for _, i = range names {
			It("should start with V", func() {
				fmt.Printf("i is %v\n", i)
				By(fmt.Sprintf("Checking %s ", i))
				Expect(string(i[0])).To(Equal("V"))
			})
		}
	})
})
```

which produces no tests for the reasons described above, the same is true if the loop wraps the `Context`:

```
var _ = Describe("Name Tests", func() {
	var (
		names []string
		i     string
	)
	BeforeEach(func() {
		names = []string{"Vedu", "Joshi"}

	})

	for _, i = range names {
		Context("One way of testing...", func() {

			It("should start with V", func() {
				fmt.Printf("i is %v\n", i)
				By(fmt.Sprintf("Checking %s ", i))
				Expect(string(i[0])).To(Equal("V"))
			})
		})
	}
})
```

Maybe you are facing some other issue with loops in Ginkgo? Would be happy to look into it if you raise an issue.
