### ISSUE TITLE
ginkgo only as a testrunner

### ISSUE THREAD

**Issue by vedujoshi** [onsi/ginkgo#463]
If I write non-BDD-style tests using stdlib testing module and want to use ginkgo as a testrunner(does it make sense?), would I be able to make use of these features:

- GinkgoWriter ( I guess the answer is yes here)
- dryRun 
- Randomizing testcases
- parallel tests( and thus junitxml reports)

**Comment by onsi** [comment]
Ginkgo will run the tests.  But it won't have any visiblity into if they've failed or not as you need to call Ginkgo's fail method.  It also wont' have any visibility into the test structure as it does not try to gain access to the list of stdlib tests (I'm not sure if this is possible yet).

As such it will not be able to perform a dryRun, randomize the tests with a consistent seed, or run them in parallel in a safe multi-process way.

If your concerns are around nesting tests in `Describe`s and `Context`s you can get all of these benefits with none of the BDD-style complexity by simply structuring your tests as a series of top-level `It`s.

**Comment by vedujoshi** [comment]
I would then better set string inside the It() to look like a function name so that it can be referred easily.
