### ISSUE TITLE
Flaky interrupt test fails with wrong exit code

### ISSUE THREAD

**Issue by williammartin** [onsi/ginkgo#464]
Occasionally when running the ginkgo integration tests I see:

```
• Failure in Spec Setup (BeforeEach) [5.731 seconds]
Interrupt when interrupting a suite [BeforeEach] should emit the contents of the GinkgoWriter 
/tmp/build/a94a8fe5/gopath/src/github.com/onsi/ginkgo/integration/interrupt_test.go:41

  No future change is possible.  Bailing out early after 0.071s.
  Expected
      <int>: 130
  to match exit code:
      <int>: 1

  /tmp/build/a94a8fe5/gopath/src/github.com/onsi/ginkgo/integration/interrupt_test.go:38

  Full Stack Trace
  	/tmp/build/a94a8fe5/gopath/src/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:135 +0x53c
  github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).Should(0xc4200a7e80, 0xab58a0, 0xc4204270c0, 0x0, 0x0, 0x0, 0xc4200a7e80)
  	/tmp/build/a94a8fe5/gopath/src/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:48 +0x77
  github.com/onsi/ginkgo/integration_test.glob..func11.2.1()
  	/usr/local/go/src/testing/testing.go:777 +0x16e
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:824 +0x565
```

**Comment by williammartin** [comment]
I _think_ this is happening due to a race condition in interrupt handling setup. We register for signals here: https://github.com/onsi/ginkgo/blob/master/internal/specrunner/spec_runner.go#L218 but this function is called in a goroutine here: https://github.com/onsi/ginkgo/blob/master/internal/specrunner/spec_runner.go#L59

It's possible that we start running the specs (and then get signalled by the integration test here: https://github.com/onsi/ginkgo/blob/master/integration/interrupt_test.go#L37) before signal handling is entirely set up.

I'm not 100% convinced of this because it's quite a small window, but it intuitively makes sense and the error is reproducible if we put a `time.Sleep()` at the top of the `registerForInterrupts` function.

**Comment by nodo** [comment]
I think you are right @williammartin, putting a sleep before https://github.com/onsi/ginkgo/blob/master/internal/specrunner/spec_runner.go#L218 makes the test fail consistently.
