### ISSUE TITLE
Errors should be written to Stderr

### ISSUE THREAD

**Issue by stephanwesten** [onsi/ginkgo#471]
func (reporter *JUnitReporter) SpecSuiteDidEnd(...) writes errors to Stdout instead of Stderr. See:

fmt.Printf("Failed to create JUnit report file: %s\n\t%s", reporter.filename, err.Error())

and

fmt.Printf("Failed to generate JUnit report\n\t%s", err.Error())

**Comment by williammartin** [comment]
Hey @stephanwesten seems like a sensible change to make. Is this causing you a problem? Would you be ok opening a PR?

**Comment by stephanwesten** [comment]
Our Jenkins job ignores stdout and only captures stderr - this is why it is an issue. We work around it for now by also capturing stdout.

The bigger issue is that sometimes the junit file / report is not generated on Jenkins, no clue yet why.

**Comment by sowmiyamuthuraman** [comment]
can I work on this?

**Comment by williammartin** [comment]
Sure @sowmiyamuthuraman, thanks!
