### ISSUE TITLE
The order problem

### ISSUE THREAD

**Issue by fanux** [onsi/ginkgo#473]
How to control the order in which test cases are executed?

Each module test code in different `Discribe`, module B is rely on module A, for example, we must run create a user test  before create app test. and those code in different modules.

**Comment by williammartin** [comment]
Hi @fanux,

Can you please explain why your user test must run before create app test? I think there are probably better solutions, but before I propose one I'd like to understand exactly why you have this dependency?

**Comment by fanux** [comment]
Thank you, I got it,  it will be some duplicate code in our project 😭.
