### ISSUE TITLE
How to programatically set recursive option

### ISSUE THREAD

**Issue by vedujoshi** [onsi/ginkgo#474]
I see that the recursive option is set here https://github.com/onsi/ginkgo/blob/b36a6e0e910d6eb5b776ab0fec410a9183ca7530/ginkgo/run_watch_and_build_command_flags.go#L13

If i want to set the -r config programatically similar to other config such as https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L192, how could i do it ?

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.  What you're trying to do can only be accomplished with the cli.

I'm going to close this for now, but feel free to reopen it if you'd like.
