### ISSUE TITLE
Proposal: add testable examples to ginkgo!

### ISSUE THREAD

**Issue by nodo** [onsi/ginkgo#476]
`go test` can be used to write [testable examples](https://blog.golang.org/examples). Basically, it is possible to write special tests that automatically end up in the godoc.

For instance, given a package hello:
```go
package hello

import "fmt"

func Hello(s string) string {
	return fmt.Sprintf("Hello, %s", s)
}
```

And a hello_test:

```go
package hello_test

import (
	"fmt"

	"github.com/nodo/misc/hello"
)

func ExampleHello() {
	fmt.Println(hello.Hello("Andrea"))
	// Output: Hello, Andrea
}
```

`godoc` will automatically generate automatically this:
![issue](https://user-images.githubusercontent.com/829178/40622722-da9e5392-629a-11e8-99fd-c14c0a53ab07.png)

What do you think about adding this feature to Ginkgo?

We could write an extension to the DSL, say `Example`, which gives special meanings to the inner nodes, or add different inner nodes such as `Output`.

I have a few ideas about the UX we could use, but first I wanted to validate whether this proposal makes sense or not.

What do you think?

**Comment by onsi** [comment]
hey @nodo - sorry I never found time to engage with this back in 2018.  I think folks can continue to use `Example` alongside existing Ginkgo tests and am not sure Ginkgo would had a lot to add on top of what native go can do.  Am gonna close this for now but feel free to reopen if you'd like.

**Comment by TheDiveO** [comment]
Maybe I've found a use case years after: documenting matcher usage examples.

**Comment by TheDiveO** [comment]
Okay, that seems to do the trick:

```go
package matcher

import (
	"github.com/thediveo/whalewatcher"

	"github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

func ExampleHaveName() {
	RegisterFailHandler(ginkgo.Fail)
	container := whalewatcher.Container{
		Name: "foolbar",
		ID:   "12deadbeef89",
	}
	Expect(container).To(HaveName("foolbar"))
	Expect(container).NotTo(HaveName("foobar"))
	// Output:
}
```

**Comment by TheDiveO** [comment]
Is there any bad side effect from either registering the same fail handler multiple times, or alternatively doing it once per package in an `Init()` instead of a `TestXXX()`?

**Comment by onsi** [comment]
hey @TheDiveO - the `Examples` will run out of band from GInkgo's test runner so I'm confident that `ginkgo.Fail` won't actually hook into Ginkgo's failure handling.  My expectation is that `ginkgo.Fail` will panic when it is called and the `Example` will fail.  Which is, maybe, OK?

My understanding is that the `ExampleX` functions pass or fail on the basis of their generated output.  And so I would expect `// Output:`. will pass only if there is no output generated.  We can use this to our advantage and register a custom `Fail` handler with Gomega that simply spits out the failure message when it is called.  That should be enough to trigger the example failure.

And yes, that `Fail` handler could be called in a top-level `Init` so long as we aren't mixing `Example`s in the same package as a Ginkgo suite (which will need Ginkgo's `Fail` handler registered globally).

I think I see two solutions for this use case:

```go
package matcher

import (
	"github.com/thediveo/whalewatcher"

	. "github.com/onsi/gomega"
)

func init() {
	RegisterFailHandler(func(message string, _ ...int) {
		fmt.Println(message)
	})
}

func ExampleHaveName() {
	container := whalewatcher.Container{
		Name: "foolbar",
		ID:   "12deadbeef89",
	}
	Expect(container).To(HaveName("foolbar"))
	Expect(container).NotTo(HaveName("foobar"))
	// Output:
}
```

this uses the Gomega globals.  Alternatively, we can create a new gomega instance at the top-level:

```go
package matcher

import (
	"github.com/thediveo/whalewatcher"

	. "github.com/onsi/gomega"
)

var g Gomega

func init() {
	g = NewGomega(func(message string, _ ...int) {
		fmt.Println(message)
	})
}

func ExampleHaveName() {
	container := whalewatcher.Container{
		Name: "foolbar",
		ID:   "12deadbeef89",
	}
	g.Expect(container).To(HaveName("foolbar"))
	g.Expect(container).NotTo(HaveName("foobar"))
	// Output:
}
```

which makes the examples a bit less readable but has the advantage of being something you can mix in with a Ginkgo suite.

**Comment by onsi** [comment]
> Ouch, this doesn't work correctly, as Tests seem to run before Examples, and RegisterFailHandler currently does not allow to replace and later restore an existing fail handler.

makes sense.  I think you'll need:

```go
package matcher

import (
	"fmt"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

func sendFailuresToStdout() {
	RegisterFailHandler(func(message string, _ ...int) {
		fmt.Println(message)
	})
}}

func init() {
	sendFailuresToStdout()
}

func TestMatcher(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "lxkns/test/matcher package")
	sendFailuresToStdout()
}
```

That should work... maybe?

**Comment by TheDiveO** [comment]
I think so; `defer sendFaimuresToStdout()` would cover all Gophers. 😁
