### ISSUE TITLE
Faulty pointer management with variable declared in method name

### ISSUE THREAD

**Issue by haichuanyu** [onsi/ginkgo#477]
Hi,

When I stepped through the following method being executed by a test, I found that at the top of the method, the variable myVar was in fact initialized to some corrupted values. This caused my tests to fail.

`func myGetFunc(ctx common.RequestContext) (myVar []myModel, err error) {
  ...
  err = ctx.Tx().Select(&myVar, prepared, args...)
  return
}`

I tried several things to try to fix this issue. One of them was to declare a new variable myNewVar, and return it explicitly. This worked - at the top of the method, myNewVar was uninitialized (as expected) and myNewVar was correctly populated by the select method. Is this a known issue?

**Comment by nodo** [comment]
Hi @haichuanyu,

please, could you share more context about your test? In particular, what do you mean by corrupted value? Also, how do you exactly call the `myGetFunc` function?

**Comment by williammartin** [comment]
bump @haichuanyu

**Comment by haichuanyu** [comment]
hi sorry, we seem to have worked around this by adopting the practice of not using unnamed returns. don't have the bandwidth to really return to this and try to reproduce the issue.
