### ISSUE TITLE
Panic in a goroutine crashes test suite

### ISSUE THREAD

**Issue by natemara** [onsi/ginkgo#480]
When a goroutine panics during a ginkgo test, there is no way to tell what test the panic was associated with. The whole test suite crashes, and there's very little information given to the user.

Example code:

```
package foo

import (
	"testing"
	"time"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

func TestMain(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Main Suite")
}

var _ = Describe("Thing", func() {
	It("Should panic", func(done Done) {
		go func() {
			time.Sleep(2)
			panic("ERROR!")
			close(done)
		}()
	})

	It("Should work", func(done Done) {
		go func() {
			time.Sleep(2)
			close(done)
		}()
	})
})
```

This suite fails with the following error:

```
λ go test test_test.go
Running Suite: Main Suite
=========================
Random Seed: 1527798017
Will run 2 of 2 specs

panic: ERROR!

goroutine 34 [running]:
command-line-arguments.glob..func1.1.1(0xc4200b6600)
	/Users/me/go/src/test_test.go:20 +0x46
created by command-line-arguments.glob..func1.1
	/Users/me/go/src/test_test.go:18 +0x3f
FAIL	command-line-arguments	0.018s
```

I would expect Ginkgo to provide the name of the test that failed, the same as it does for a panic in a normal function when I remove the goroutine in the `Should panic` test:

```
λ go test test_test.go
Running Suite: Main Suite
=========================
Random Seed: 1527798044
Will run 2 of 2 specs

•! Panic [0.000 seconds]
Thing
/Users/me/go/src/test_test.go:16
  Should panic [It]
  /Users/me/go/src/test_test.go:17

  Test Panicked
  ERROR!
  /usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505

  Full Stack Trace
  	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
  command-line-arguments.glob..func1.1(0xc4200b6600)
  	/Users/me/go/src/test_test.go:20 +0x46
  reflect.Value.call(0x1344320, 0x13ee478, 0x13, 0x13cf342, 0x4, 0xc4201cef68, 0x1, 0x1, 0x0, 0x13417e0, ...)
  	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:447 +0x969
  reflect.Value.Call(0x1344320, 0x13ee478, 0x13, 0xc420041f68, 0x1, 0x1, 0x0, 0x0, 0x0)
  	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:308 +0xa4
  github.com/onsi/ginkgo/internal/leafnodes.newRunner.func1(0xc4200b6600)
------------------------------
•

Summarizing 1 Failure:

[Panic!] Thing [It] Should panic
/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505

Ran 2 of 2 Specs in 0.001 seconds
FAIL! -- 1 Passed | 1 Failed | 0 Pending | 0 Skipped --- FAIL: TestMain (0.00s)
FAIL
FAIL	command-line-arguments	0.016s
```

Is there any way to do this, or does go's concurrency model make it very difficult? I know I could put `defer GinkgoRecover()` at the top of my goroutine, but the function that creates the goroutine is in my application code, and I don't think there should be a call to a test library in my app code.

**Comment by vhosakot** [comment]
I see this issue too with the following code:

```
$ cat my_test.go 
package main

import (
	"testing"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

func TestFunc(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "TestFunc Suite")
}

var _ = Describe("Test panic", func() {
	It("Test panic", func() {
		go func() {
			panic("ERROR!")
		}()
	})
})
```

Output:

```
$ go test -v my_test.go 
=== RUN   TestFunc
Running Suite: TestFunc Suite
=============================
Random Seed: 1551818405
Will run 1 of 1 specs

•panic: ERROR!

goroutine 18 [running]:
command-line-arguments.glob..func1.1.1()
	/Users/username/go/src/test/my_test.go:17 +0x39
created by command-line-arguments.glob..func1.1
	/Users/username/go/src/test/my_test.go:16 +0x35
FAIL	command-line-arguments	0.019s
```

My go version:

```
$ go version
go version go1.11.5 darwin/amd64
```

**Comment by williammartin** [comment]
@vhosakot Can you describe what you're doing that you want your tests to result in a panic, that you aren't trying to assert on? Is it just that you had a panic and it was hard to debug?

**Comment by onsi** [comment]
Also - there is no way, in Golang, for one goroutine/thread to capture a panic emitted by another goroutine.  This is why you have to call `defer GinkgoRecover()`


@natemara I appreciate this comment:
> but the function that creates the goroutine is in my application code, and I don't think there should be a call to a test library in my app code

but would offer the test is giving you some actionable feedback about your code.  Your code launches a goroutine that can panic in a way that cannot be trapped, thereby crashing the application.  Perhaps that's by design - but perhaps it's an opportunity to refactor.

**Comment by vhosakot** [comment]
Thanks for the info @williammartin, @onsi. Yeah, unexpected panic in code crashed the test suite and hence was hard to debug.
