### ISSUE TITLE
Around block

### ISSUE THREAD

**Issue by adambuckland** [onsi/ginkgo#481]
:wave:

Something that would be very useful is the ability to do an `AroundEach` similar to how it works in [ActiveRecord](https://relishapp.com/rspec/rspec-core/v/2-0/docs/hooks/around-hooks)

A good use case for this, would be wrapping tests in DB transactions, to ensure a clean DB between tests. 

I don't know the feasibility of this, but it's an idea. An example is below:

```go
AroundEach(func(test func()) {
    db.Rollback(func() {
        test()
   })
})
```

**Comment by grosser** [comment]
Yes please, also useful for things like chDir / ENV changes / etc global changes so they can all live in a shared space and not be split between the before/after

**Comment by grosser** [comment]
FYI as a workaround I tried this:

```go
regularIt := It
It := func(name string, fn func()) {
  regularIt(name, fn)
}

It("x", func() {
  Expect(1).To(Equal(1))
})
```

which works ... but if there are any more wrapper functions like:

```go
It("x", func() {
  withEnv("foo", "bar", func(){
    Expect(1).To(Equal(1))
  })
})
```

it turns into:

```
panic: You are trying to make an assertion, but Gomega's fail handler is nil.
If you're using Ginkgo then you probably forgot to put your assertion in an It().
Alternatively, you may have forgotten to register a fail handler with RegisterFailHandler() or RegisterTestingT().
Depending on your vendoring solution you may be inadvertently importing gomega and subpackages (e.g. ghhtp, gexec,...) from different locations.


goroutine 1 [running]:
github.com/grosser/go-testcov/vendor/github.com/onsi/gomega.ExpectWithOffset(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x41)
	/Users/mgrosser/Code/go/src/github.com/grosser/go-testcov/vendor/github.com/onsi/gomega/gomega_dsl.go:146 +0xbb
github.com/grosser/go-testcov/vendor/github.com/onsi/gomega.Expect(0x0, 0x0, 0x0, 0x0, 0x0, 0xc420018007, 0x31)
```

... so this might work, but would need some changes to the backtrace logic, but even if it works it's kinda ugly and cannot be covered into an AroundEach unless It is made into a `var` (not sure ...)

**Comment by lawrencejones** [comment]
+1 for this. This interface has the happy bonus of re-enabling the use of `defer` for test suite cleanup- something like this:

```go
	BeforeSuite(func() {
		ctx, cancel = context.WithCancel(context.Background())
		cluster = StartCluster(context.Background())
	})

	AfterSuite(func() {
		if cluster != nil {
			cluster.Shutdown()
		}

		cancel()
	})
```

becomes

```go
	AroundSuite(func(run func()) {
		ctx, cancel = context.WithCancel(context.Background())
		defer cancel()

		cluster = StartCluster(context.Background())
		defer cluster.Shutdown()

		run()
	})
```

There are several benefits here, such as allowing golint to pickup un-cancelled contexts, and removing the need for you to check a resource has been initialized before tearing it down in the `AfterX` block.

**Comment by ClayShentrup** [comment]
I found this thread looking for an `AroundEach` for the _exact same purpose_ — DB rollbacks like ActiveRecord. 😄

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I'm trying to wrap my head around the problem here.  My sense is you can basically accomplish this today with `BeforeEach` and `AfterEach` and in cases where you want to wrap your tests you can introduce functions that wrap functions at will.  Ginkgo v2 is under active development and one thing I'm going to add is the ability to dynamically add `AfterEach` blocks so that setup and cleanup can be more closely connected:

```
BeforeEach(func() {
    orig := GetEnv("foo")
    SetEnv("foo", "bar")
    GinkgoCleanup(func() {SetEnv("foo", orig)}
})
```

(still deciding on the name and UI - `GinkgoCleanup` is a placeholder for now).

I'd prefer to not add `AroundEach` at this time as it will add a degree of new complexity to the codebase.  Am gonna close this for now but please feel free to reopen if you'd like.

**Comment by ClayShentrup** [comment]
Thanks. This solves the problem but does feel it a bit awkward in how it's less constrained (more room for bike-shedding).

For instance, I can write things out of order like this:

```go
BeforeEach(func() {
    orig := GetEnv("foo")
    GinkgoCleanup(func() {SetEnv("foo", orig)}
    SetEnv("foo", "bar")
})
```

Or I can use one vs. multiple calls to `GinkgoCleanup()`.

```go
BeforeEach(func() {
    orig := GetEnv("foo")
    SetEnv("foo", "bar")
    GinkgoCleanup(func() {SetEnv("foo", orig)}

    orig2 := GetEnv("foo2")
    SetEnv("foo2", "bar")
    GinkgoCleanup(func() {SetEnv("foo2", orig2)}
})
```

Whereas an `AroundEach()` like this is more restrictive. And has clear immediately recognizable semantics, rather than a cleanup call (which is really an `after`) inside of a call to `BeforeEach`.

Not to look a gift horse in the mouth. Just my opinion.

**Comment by onsi** [comment]
Thanks for the thoughtful reply @ClayShentrup - this horse hasn't left the stable yet, so now's definitely the time to check it's teeth 😉 

I agree that `AroundEach()` has stronger, more opinionated, semantics.  But the more I think about `GinkgoCleanup` the more I start to like the ~~bikesheds~~ patterns that emerge.  I'm gonna share a few - please don't feel like you need to respond in detail but I wanted to put this out there and would love to hear folks' thoughts.

First off, to define `GinkgoCleanup` more precisely, it can be passed a single function with no arguments:
```go
GinkgoCleanup(func() {
    ...
})
```
which effectively creates an `AfterEach` dynamically and calls the passed in function when that `AfterEach` is called.  (Note that `GinkgoCleanup` can happen anywhere - in a `BeforeEach` or an `It`, or even an `AfterEach`)

Alternatively, it can be passed a function that takes arguments.  And then a series of arguments to pass to that function:
```go
GinkgoCleanup(func(a string, b int) {
   GinkgoWriter.Printf("%s - %d", a, 17)
}, "foo", 17)
```
would emit "foo - 17" when the dynamically generated `AfterEach` is called.  What's powerful here is the arguments are captured at the moment `GinkgoCleanup` is called so you don't have to worry about closure variables changing from underneath you.

With that definition of `GinkgoCleanup` these sorts of patterns emerge (in addition to the ones you outlined above):

**The succinct in-line cleanup pattern:**
```go
BeforeEach(func() {
    GinkgoCleanup(SetEnv, "foo", GetEnv("foo"))
    SetEnv("foo", "bar")
})
```

**The shared test-helper code that magically does it's own clean up pattern:**
```go
func SetEnvForTest(key string, value string) {
   orig := GetEnv(key)
   SetEnv(key, value)
   GinkgoCleanup(func() {
        SetEnv(key, orig)
    })
}

BeforeEach(func() {
    SetEnvForTest("foo", "bar")
})
```

**The less magical test-helper code that returns a clean-up function pattern:**
```go
func SetEnvForTest(key string, value string) func() {
   orig := GetEnv(key)
   SetEnv(key, value)
   return func() {
        SetEnv(key, orig)
    }
}

BeforeEach(func() {
    GinkgoCleanup(SetEnvForTest("foo", "bar")) //you'd better remember to call GInkgoCleanup, though!
})
```

It's all kinda growing on me and I'm liking where it's headed.  The test-helper patterns, in particular, could lead to helpful code reuse across test suites and libraries.

**Comment by ClayShentrup** [comment]
I guess I can't recall, in the 12 or so years I've been using RSpec, ever needing to do something like this:

```go
GinkgoCleanup(func(a string, b int) {
   GinkgoWriter.Printf("%s - %d", a, b)
}, "foo", 17)
```

I would just do something like:

```go
run()
GinkgoWriter.Printf("%s - %d", "foo", 17)
```

Or for the other pattern, we'd just do:
```go
AroundEach(SetEnvForTest("foo", "bar")) // This returns a function that takes `run` as an argument ofc.
```

Which is fine as long as `AroundEach` can be invoked multiple times.

You could also do this with a single `AroundEach` where you can call run() as many times as needed and pass it into multiple functions like this by using a waitgroup and specifying upfront how many times you're going to call run. Not that I'd suggest something that clever.

Thin `GinkgoCleanup` approach just seems like a bit of a bright shiny object. I'd wager that if you published both API's, the former would be used much more often than the latter. Just my 2¢.

**Comment by onsi** [comment]
They're certainly not mutually exclusive.  One of the motivating factors behind `GinkgoCleanup` is to support the same pattern that go test uses:

https://golang.org/pkg/testing/#T.Cleanup

as some test libraries out there want a `testing.T` that they can register cleanup functions with and Gingko doesn't yet support this.

So I'm inclined to start there and see where how the dust settles and what usage patterns emerge before embarking on `AroundEach`
