### ISSUE TITLE
WIBNI there was a JustAfterEach

### ISSUE THREAD

**Issue by lwr20** [onsi/ginkgo#483]
In the kubernetes end to end tests (which use Ginkgo), the structure is that there is a general framework and then specific test cases.  Both have BeforeEach and AfterEach statements and the execution order is 
```
Framework BeforeEach
  Test BeforeEach
    Test runs
  Test AfterEach
Framework AfterEach.
```
Quite often, the Test's BeforeEach sets up some infrastructure required for the test and the AfterEach tears it down.

However, if a test fails, we want to collect diags as close to the failure as possible.  We *could* find and modify all the innermost AfterEach's and add diags to them all.  But it would be much nicer to be able to have a JustAfterEach in the Framework that all the tests use that works in a similar way to JustBeforeEach. 

This problem was mentioned in https://github.com/kubernetes/kubernetes/issues/34318, although that wasn't explicitly about this.

**Comment by lwr20** [comment]
Just found https://github.com/onsi/ginkgo/issues/303

**Comment by lwr20** [comment]
I have the beginning of a PR for this - working code, but no tests or documentation yet.

**Comment by lwr20** [comment]
Added some tests.

**Comment by williammartin** [comment]
At first glance I think I can see the value this would provide. Historically we've had some push back on the nature of `JustBeforeEach` being confusing so I am slightly hesitant with regards to `JustAfterEach` but I'll give it some more thought - I'm definitely not opposed by default. 

I'm having a bit of trouble forseeing the potential consequences of supporting this, and how it might be abused 😆 

Thanks for the PR and discussion

**Comment by fasaxc** [comment]
FWIW, we're using this in anger now in our tests and it's been very helpful to be able to do pre-tear-down operations such as diags collection.

**Comment by williammartin** [comment]
Can you link to that please?

**Comment by fasaxc** [comment]
Unfortunately not, they're in a private repo :-(

**Comment by williammartin** [comment]
PR has been merged. Thanks all.
