### ISSUE TITLE
message element in JUnitReporter xml 

### ISSUE THREAD

**Issue by mkj28** [onsi/ginkgo#490]
Not sure if issue or feature request, also may be related to https://github.com/onsi/ginkgo/issues/486

Essentially asking for `message` element to be included in case of failure. What I get is:
```
<testcase name="AfterSuite" classname="Search Results" time="0.0001581">
    <failure type="Panic">.../default/suite_setup.go:74&#xA;Test Panicked&#xA;/usr/local/go/src/runtime/panic.go:502</failure>
</testcase>
```

I would love to get is:
```
<testcase name="AfterSuite" classname="Search Results" time="0.0001581">
    <failure message=".../default/suite_setup.go:74&#xA;Test Panicked&#xA;/usr/local/go/src/runtime/panic.go:502" type="Panic">.../default/suite_setup.go:74&#xA;Test Panicked&#xA;/usr/local/go/src/runtime/panic.go:502</failure>
</testcase>
```

Main reason is https://github.com/allure-framework/allure2 looks for it....

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I'm going to be cleaning up the JUnit reporter as part of the v2 work and will see about pulling this in.  Any chance you know if it's still an issue?

**Comment by mkj28** [comment]
> I'm going to be cleaning up the JUnit reporter as part of the v2 work and will see about pulling this in. Any chance you know if it's still an issue?

seeing same behavior with ginkgo v1.16.1

**Comment by onsi** [comment]
A beta for Ginkgo V2 that fixes this issue was just released.   [Please try out the beta](https://github.com/onsi/ginkgo/issues/809)!
