### ISSUE TITLE
Don't show assertions as the backtrace

### ISSUE THREAD

**Issue by grosser** [onsi/ginkgo#491]
Given a test helper like this:

```go
ExpectFoo := func() {
  Expect(1).To(Equal(2))
}

It("shows the It as backtrace", func(){
  ExpectFoo()
})
```

I expect the backtrace to point to `ExpectFoo()` and not `Expect(1).To(Equal(2))`,
could backtraces for methods that have a certain prefix like `Expect` or `expect` or `assert` be filtered out when trying to find the backtrace ?

**Comment by williammartin** [comment]
Interesting. I'm not sure how we could do this in a sane manner. The current solution to this problem is to use `ExpectWithOffset`: https://godoc.org/github.com/onsi/gomega#ExpectWithOffset

**Comment by grosser** [comment]
nice, that's helpful!
