### ISSUE TITLE
RFC: pass SIGTERM/SIGINT to precompiled suite run with ginkgo

### ISSUE THREAD

**Issue by chuckha** [onsi/ginkgo#493]
The problem I'm trying to solve relates to the [kubernetes e2e tests][k8se2e]. This test suite will output some junit data that I'm interested in, even for a partial run. I'd like to be able to timeout and still get results. You can see the exact command that resulted in surprising behavior in our [kube-conformance repo][kc].

Ignoring the bad bash in that file, when I run this command by hand and send SIGTERM to the ginkgo process, nothing happens. However, when I send a SIGTERM to the suite binary that is running the tests exit correctly.

I think I've traced it to the [notification runner][runner] that spawns subprocesses but does not handle signals.

It's also possible this is the wrong approach, I would love some pointers if you can think of any, no worries though because I have a solution for now.

[k8se2e]: https://github.com/kubernetes/kubernetes/blob/c005b9d0ab6cd963abf66a9a12fb8ad5e48121ad/test/e2e/e2e.go#L332
[kc]: https://github.com/heptio/kube-conformance/blob/c43a9d2d1f096ccff8d5b069691a523b1b517b8e/run_e2e.sh#L39
[runner]: https://github.com/onsi/ginkgo/blob/master/ginkgo/notifications.go#L106

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I'm going to close this for now, but feel free to reopen it if you'd like.
