### ISSUE TITLE
Failed to compile ginkgo-arch-specs: output file ".../ginkgo-arch-specs.test" could not be found

### ISSUE THREAD

**Issue by BooleanCat** [onsi/ginkgo#495]
Ginkgo fails to compile suites that have no specs for an architecture when there are specs for other architectures.

# Reproduction

Consider this project: https://github.com/BooleanCat/ginkgo-arch-specs

There is a package `ginkgo_arch_specs.go`, which is tested by:

```
ginkgo_arch_specs_linux_test.go
ginkgo_arch_specs_suite_linux_test.go
```

If I `ginkgo run .` this package from an archecture other than linux (I reproduced this with Darwin), then I see:

```
± tg |master ✓| → ginkgo .
?       github.com/BooleanCat/ginkgo-arch-specs [no test files]

?       github.com/BooleanCat/ginkgo-arch-specs [no test files]

?       github.com/BooleanCat/ginkgo-arch-specs [no test files]

?       github.com/BooleanCat/ginkgo-arch-specs [no test files]

?       github.com/BooleanCat/ginkgo-arch-specs [no test files]

?       github.com/BooleanCat/ginkgo-arch-specs [no test files]

Failed to compile ginkgo-arch-specs: output file "/var/folders/fl/67s579h57hj7r4bpl6zyt29w0000gn/T/ginkgo203116881/ginkgo-arch-specs.test" could not be found
Ginkgo ran 1 suite in 814.993584ms
Test Suite Failed
```

# Expectation

I would expect ginkgo to succeed, running 0 specs on Darwin. On Linux, it should run the linux specs.

# Notes

[This block of code](https://github.com/onsi/ginkgo/blob/228e3a805a0579a328589d6810bc1edd03f2299f/ginkgo/testrunner/test_runner.go#L156-L170) in Ginkgo considers no files existing after a successful go build of the test files to be an error - I don't have contest on why.

**Comment by BooleanCat** [comment]
Note that we add an empty test file `ginkgo_arch_specs_test.go`, this resolves the immedate issue but l leaves artifacts in `C:\Windows\Temp`. Eventually our Windows CI machine will have so much stuff in its temp dir that it refuses to write anything else to it because of weird Windows fragmentation limitations. (https://garden.ci.cf-app.com/teams/main/pipelines/main/jobs/groot-windows-periodic/builds/874)

**Comment by nodo** [comment]
Interesting @BooleanCat! thanks for raising that.

FWITW It think the behaviour of `ginkgo` it's a bit similar to `go test`:

```
$ go test
?   	github.com/nodo/ginkgo-arch-specs	[no test files]
```

**Comment by BooleanCat** [comment]
It seems that the result of invoking ginkgo for my example suite is an exit code of -1 - a failure. Running `go test` in the same package results in an exit code of 0 - success.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I'll add this to the v2 backlog that's under active development.  I agree that this should not result in ginkgo marking the test as failed.  The cruft accumulating in /tmp should have been solved a few months ago.
