### ISSUE TITLE
log.SetOutput(GinkgoWriter) necessary for parallel testing?

### ISSUE THREAD

**Issue by pohly** [onsi/ginkgo#498]
I ran across a rather puzzling issue: I was running `ginkgo -p` on a tests suite, but it never spawned more than one instance of the test program. Only after adding the usual `log.SetOutput(GinkgoWriter)` to the suite (which was missing before, not sure why - I didn't write it) did I get parallel test execution.

Does that make any sense? If so, should this be documented somewhere?

I only found out about it after comparing with a suite that did run in parallel.

**Comment by nodo** [comment]
Hey @pohly,

could you share a reproducer of the issue?  As far as I understand, this is not the right behaviour.

**Comment by pohly** [comment]
I can't reproduce it anymore. I'm pretty sure I went back and forth with just changing the logging, but there's no way to verify that now.
