### ISSUE TITLE
Improve error message for BeNumerically with ~

### ISSUE THREAD

**Issue by grosser** [onsi/ginkgo#503]
`Expect(elapsed).To(BeNumerically("~", 3*time.Millisecond, time.Millisecond))`

current:
```
    Expected
        <time.Duration>: 1454875
    to be ~
        <time.Duration>: 3000000
```

desired:
```
    Expected
        <time.Duration>: 1454875
    to be within 1000000 of
        <time.Duration>: 3000000
```

**Comment by williammartin** [comment]
Makes a lot of sense to me to provide the threshold with the error message. Would you be up for opening a PR?

**Comment by grosser** [comment]
I'll give it a try
