### ISSUE TITLE
How to use lazy evaluation and subject like rspec

### ISSUE THREAD

**Issue by junpayment** [onsi/ginkgo#512]
I want to use some functions of rspec.

- Lazy evaluation like rspec's "let"
- Subject like "subject"

Are there any rules to write them?

Thaks great products!

**Comment by nodo** [comment]
Hey @junpayment,

Please can you share a specific example for your use-case?

As a first step, I suggest you to have a look at the [docs](https://onsi.github.io/ginkgo/). In particular, the section related to [structuring tests](https://onsi.github.io/ginkgo/#structuring-your-specs).

**Comment by junpayment** [comment]
Hi @nodo, Thanks your reply.

I mainly use golang however sometimes use other scripting languages like Ruby or PHP.

In Rspec, ruby BDD testing gem, we can write like below.

```ruby
describe 'Somthing' do
  subject(Some.get_unix_time_now())

  let(:count) do
    Time.now.to_i
  end

  it do
    expect { subject }.to equal(count)
  end
end
```

in ginkgo..

```go
var _ = Describe("Somthing", func() {
   var (
     count    int64
     subject int64
   )

  BeforeEach(func() {
    count = time.Now().Unix()
    subject = GetUnixTimeNow()
  })

  Context("Something", func() {
     It("should be equal", func() {
        Expect(subject).To(Equal(count))
     })
  })
}
```

Based on the above code two questions.
- Is there a way to clarify the test object in one describe like the subject of rspec?
- Is it correct to write in the block of the BeforeXXX method to delayly evaluate the variable to be tested like let or subject of rspec?

These are just a question, not a request or opinion.

Thanks your great product.

**Comment by nodo** [comment]
This will work if you have a `flatten` structure. If you have nested `context`s you might want to check out `JustBeforeEach`. This would run every single it, similarly to `let` and `subject`. Does this answer your question?

**Comment by junpayment** [comment]
@nodo Thanks a lot. I'll try it.
