### ISSUE TITLE
Debugging tests inside describe using delve debugger

### ISSUE THREAD

**Issue by himanshu219** [onsi/ginkgo#514]
I have tests written in following way and when I have placed a breakpoint inside one of the IT 

    Describe("Testing Application", func() {
        It("test 1", func() { 
              runtime.Breakpoint()
        }) 
        It("test 2", func() { 
     
        }) 
     })

When I execute the command `dlv test test_suite.go`  tests are not running. How can debug tests with breakpoints?

**Comment by thesmiley1** [comment]
This works for me:

* `cd /path/to/project/mypkg`
* `dlv test`
* `continue`

Tests run and `runtime.Breakpoint()` breakpoints are hit.
