### ISSUE TITLE
Is there a way to measure the processing time for each `By` block ?

### ISSUE THREAD

**Issue by dulltz** [onsi/ginkgo#516]
I want to measure the processing time for each `By` STEP.
Is there a way to do it?

**Comment by nodo** [comment]
Hey @dulltz,

`By` steps are just log lines, so `ginkgo` does not support benchmarking on them.

A possible suggestion would be to re-structure your tests to use https://onsi.github.io/ginkgo/#benchmark-tests . Would this solve your issue?

**Comment by dulltz** [comment]
@nodo 
> `By` steps are just log lines, so `ginkgo` does not support benchmarking on them.

> A possible suggestion would be to re-structure your tests to use https://onsi.github.io/ginkgo/#benchmark-tests . Would this solve your issue?

Thank you for telling me,
but it seems difficult to rewrite it with `It` or` Measure`, 
because my integrated-style test codes contain a lot of processing to be executed sequentially.

I will try to measure in a primitive way using `Time` package.

Thank you for replying.
