### ISSUE TITLE
Hung tests only when run in parallel and without -stream

### ISSUE THREAD

**Issue by rgalanakis** [onsi/ginkgo#517]
I'm seeing some very strange behavior when running tests in parallel (OSX, running CLI from HEAD, vendored version is 1.6).

- If I run tests in parallel (`-p` or `--nodes=2`), specs hang.
- If I run in serial, specs work fine.
- If I run in parallel, with `-stream`, specs work fine.
- None of the other debug flags (`-race`, `-v`, --v`, --debug`, `--progress`) make a difference.

The last chunk of output before hanging is always something like:

```
Ran 20 of 20 Specs in 3.159 seconds
FAIL! -- 19 Passed | 1 Failed | 0 Pending | 0 Skipped
```

But the number of specs is not deterministic (and it happens whether any specs fail or not).

I ran with `--debug` and what's written to the files was totaling 13, not even 20, so I don't know where that 'Ran 20 of 20 Specs' came from (there are 27 specs total in the test suite, not 20). Nothing strange in there, other than the potential race that happens due to a ctrl+c interrupt.

Happy to provide whatever other information I can, or try out some stuff locally. I'm pretty stumped with what I could try next, so am going back to serial for now. Thanks!

**Comment by nodo** [comment]
Thanks for taking the time to opening the issue @rgalanakis . This is a known bug unfortunately. I guess that you cannot share the test suite and / or the log files, right ?

There is one thing I am curious about though. Are you seeing the tests hanging intermittently or every time you try to run them?

**Comment by rgalanakis** [comment]
I was able to create a minimal repro case.

Create files `file1_test.go` and `file2_test.go` in a folder
The contents should be:

```go
package ginkgorepro
import (
	"testing"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)
func TestFile1(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "File1 Suite")
}
```
and:
```go
package ginkgorepro
import (
	"testing"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)
func TestFile2(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Test File 2")
}
```

Run: `ginkgo --nodes=2 --debug ./...`

Observe the output:

```
Running Suite: File1 Suite
==========================
Random Seed: 1533667223
Will run 0 specs

Running in parallel across 2 nodes


Ran 0 of 0 Specs in 0.001 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped
```

The contents of the logs. Node 1:
```
Running Suite: Test File 2
==========================
Random Seed: 1533667223
Parallel test node 1/2.


Ran 0 of 0 Specs in 4.096 seconds
FAIL! -- 0 Passed | 0 Failed | 0 Flaked | 0 Pending | 0 Skipped
```

Node 2:
```
Running Suite: Test File 2
==========================
Random Seed: 1533667223
Parallel test node 2/2.


Ran 0 of 0 Specs in 4.097 seconds
FAIL! -- 0 Passed | 0 Failed | 0 Flaked | 0 Pending | 0 Skipped
```

If you comment out the contents of one of those files (leaving only the package declaration),
run the same command and observe that the tests pass:

```
Running Suite: Test File 2
==========================
Random Seed: 1533667363
Will run 0 specs

Running in parallel across 2 nodes


Ran 0 of 0 Specs in 0.001 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped


Ginkgo ran 1 suite in 923.942771ms
Test Suite Passed
```

New log file output. Node 1:
```
Running Suite: Test File 2
==========================
Random Seed: 1533667484
Parallel test node 1/2.


Ran 0 of 0 Specs in 0.001 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Flaked | 0 Pending | 0 Skipped
```

Node 2:
```
Running Suite: Test File 2
==========================
Random Seed: 1533667484
Parallel test node 2/2.


Ran 0 of 0 Specs in 0.001 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Flaked | 0 Pending | 0 Skipped
```

So it appears to be something about having multiple Test functions in the same package.

**Comment by rgalanakis** [comment]
To answer your latter question- locally, and with these repro cases, I see it every time. On our CI server running integration tests in parallel, it was intermittent (though probably more common than a success).

**Comment by rgalanakis** [comment]
I think whoever set up the initial ginkgo patterns in our repos (probably me, though maybe I copied the one other place it was used when I started here) set it up that way and I copied it- it wasn't clear from the docs that this is discouraged. It may also have to do with running specs in Goland/Intellij, but I'd need to confirm. Is there never a reason for multiple test functions?
Thanks for responding to this issue so quickly! (and of course thank you for these libraries, my work life would be pretty depressing if I had to be using standard Go tests...)

**Comment by williammartin** [comment]
Yeh there's not really any reason I can think of to have multiple test functions in a suite, since the test graph is built up by the top level `var _ = Describe` statements and then run via `RunSpecs(t, "...")`. I suspect Ginkgo would be trying to do a bunch of stuff twice.

I reproduced just running from the CLI.

**Comment by onsi** [comment]
Hey - to clarify.  The issue isn’t multiple `TestXxx` per se - it’s that you are calling `RunSpecs` twice.

Ginkgo will work fine with multiple `TestXxx` though it cannot report on these tests and when you run in parallel all the non-ginkgo tests will run on each parallel node.

**Comment by onsi** [comment]
V2 now warns the user about calling `RunSpecs` twice.
