### ISSUE TITLE
Combining the coverprofiles to one file should remove the mode (mode: xxx) line

### ISSUE THREAD

**Issue by 27149chen** [onsi/ginkgo#518]
When combining the coverprofiles to one file, ginkgo should remove the mode (mode: xxx) line, it is the first line in every single profile. Otherwise, running "go tool cover -html=" will report "cover: line [] doesn't match expected format: ^(.+):([0-9]+).([0-9]+),([0-9]+).([0-9]+) ([0-9]+) ([0-9]+)$"

Using ginkgo 1.6

**Comment by williammartin** [comment]
Hi. Would welcome a PR to fix this if you are up for it.

**Comment by rafaeleyng** [comment]
@williammartin I could try it, could you give me just a direction where to start looking for it on the codebase?
