### ISSUE TITLE
getting "version queue is empty, should not happen" when using dep.

### ISSUE THREAD

**Issue by zkrhm** [onsi/ginkgo#522]
hello, I am using dep to add ginkgo as my dependency but getting error : 
"panic: version queue is empty, should not happen"

I execute this command : 
```bash

dep ensure -add github.com/onsi/ginkgo
```

what do I do wrong?

**Comment by blgm** [comment]
I’ve seen that before, and I think it’s a bug in `dep`. I’ve worked round it in the past by running `go get ...`, and running `dep ensure` afterwards.

**Comment by zkrhm** [comment]
hey, I tried and it's works. thanks!

**Comment by grosser** [comment]
FYI dep issue is https://github.com/golang/dep/issues/1799

**Comment by grosser** [comment]
FYI switching to go modules also works :)

**Comment by wxy325** [comment]
In my case, adding 

```
[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.7.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify"
  version = "1.4.7"
```

in `Gopkg.toml` works
