### ISSUE TITLE
Misspelling in docs

### ISSUE THREAD

**Issue by wnxn** [onsi/ginkgo#525]
Hi Onsi,
At `Miscellaneous` section in [docs](http://onsi.github.io/ginkgo/#running-tests), I found the word `paried` might be replaced by `paired` in `This is best paried with -v to preview which tests will run.`

**Comment by nodo** [comment]
@wnxn would you like to open a PR for that?

**Comment by wnxn** [comment]
Hi @nodo , I am glad to open a PR for typo. But I want to know where is the source file to generate website http://onsi.github.io/ginkgo/.

**Comment by williammartin** [comment]
It's under the gh-pages branch.

**Comment by 21stio** [comment]
can it be closed?
