### ISSUE TITLE
How to serialize tests within a package

### ISSUE THREAD

**Issue by rosenhouse** [onsi/ginkgo#526]
We sometimes encounter cases where a particular package manages global state, so making the tests safe to run in parallel is challenging.

To keep other packages running in parallel, we resort to complex scripts that include [a list of "serial packages"](https://github.com/cloudfoundry/cf-networking-release/blob/f82cf0d5f0a467b419b24e41df009f1d934d043e/scripts/unit-and-integration-tests#L8-L13).  We run `ginkgo` separately for each of those packages, and then do a single multi-package run for the rest that can run in parallel.

Is there an easier way to do that, either with the `ginkgo` CLI or by writing some config inside the test package itself?

**Comment by onsi** [comment]
Looks like I'll be addressing this eventually in v2.  I'm planning on making it possible to configure per-suite settings/defaults that the `ginkgo` CLI will honor as it runs through a test suite.  I might circle back with some design decisions for feedback - but I'm not quite sure when I'll get to it on the v2 roadmap yet.

**Comment by onsi** [comment]
Not quite what this issue is asking for, but on the [ver2](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta) branch you can now mark tests as `Serial`.  This will be guaranteed to run in series, never in parallel with other test.
