### ISSUE TITLE
Question: Does it support cucumber gherkin parser? If no is there any plan for it

### ISSUE THREAD

**Issue by amitkrout** [onsi/ginkgo#535]
Something i am looking for solution like simple readable english sentence in a feature file and the implementation will be somewhere in the other go file. For example 
```
Given [initial context]
When [event occurs]
Then [ensure some outcomes]
```

**Comment by amitkrout** [comment]
Hope you guys ate listening, a gentle reminder.

**Comment by williammartin** [comment]
Thanks for the reminder @amitkrout, we do listen, but have limited time. Appreciate you poking us gently :)

Ginkgo doesn't support Cucumber/Gherkin parsing and I think it's unlikely we ever will. Ginkgo was never intended to be a way to communicate with non-technical stakeholders, simply to allow engineers to write better, more descriptive tests.

I don't think we would ever merge a Cucumber like feature into the core, but that doesn't mean we wouldn't try and help someone who wanted to start a project to provide this. I believe that the folks over at stream were trying to do something along these lines, but I'm not sure how they progressed: https://getstream.io/blog/how-we-test-go-at-stream/. You might have some luck following up with them.

**Comment by amitkrout** [comment]
@williammartin Thanks for the info and pointers too. Will try it out for sure
