### ISSUE TITLE
Parallel compilation may be causing go module races

### ISSUE THREAD

**Issue by tylerphelan** [onsi/ginkgo#537]
We've observed non-deterministic behavior when running ginkgo:
```
for i in `seq 1 20`; do rm -rf /root/go/pkg; ginkgo -r -skipPackage=integration,brats; done
```
Produces a roughly 50% failure to compile with varying compilation errors.

```
for i in `seq 1 20`; do rm -rf /root/go/pkg; ginkgo -r -skipPackage=integration,brats -compilers=1; done
```
Succeeds 100% of the time.

Forcing module download before running tests, for example with `go mod download`, will also produce 100% success rate.

Our theory is that parallel compilation, and thus parallel module fetching, really confuses go, leading to races in module resolution/solving/whatever you call it.

@zanadar

**Comment by onsi** [comment]
I think this is surfacing a bug in `go mod download`.  Seems like `go` should be able to handle multiple downloads in parallel.  I'd suggest y'all open an issue there.

For now the `-compilers=1` flag workaround will have to do :/

**Comment by tylerphelan** [comment]
Looks like the issue is https://github.com/golang/go/issues/26794

**Comment by tylerphelan** [comment]
Will close for now.
