### ISSUE TITLE
use glog 

### ISSUE THREAD

**Issue by magicsong** [onsi/ginkgo#540]
Can we use `glog` in ginkgo right now? I can use glog in `go test` however not work in  `ginkgo` cli, do i miss something?

**Comment by wingyplus** [comment]
The possible solution that I try is compile test to binary and set flag to it.

This is my source code.

```
$ cat glog/third_test.go 
package main

import (
        "testing"

        "github.com/golang/glog"
        "github.com/onsi/ginkgo"
        "github.com/onsi/gomega"
)

func TestThird(t *testing.T) {
        gomega.RegisterFailHandler(ginkgo.Fail)
        ginkgo.RunSpecs(t, "Google glog suite")
}

var _ = ginkgo.Describe("glog", func() {
        ginkgo.It("should log", func() {
                glog.V(1).Info("hello")
        })
})
```

Then compile and run: 

```
$ go test -c ./glog && ./glog.test -v 1 -logtostderr
Running Suite: Google glog suite
================================
Random Seed: 1544159077
Will run 1 of 1 specs

I1207 12:04:37.650681    5483 third_test.go:18] hello
•
Ran 1 of 1 Specs in 0.000 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
```

**Comment by magicsong** [comment]
@wingyplus you can use `go test` without using main function. My question is use `glog` in ginkgo cli, like `ginkgo  -v 1 -logtostderr` . when using `go test` , it is very inconvenient to use  flag of ginkgo-cli.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I don't have any plans to introduce `blog` to Ginkgo.

I'm going to close this for now, but feel free to reopen it if you'd like.
