### ISSUE TITLE
What versions of Go should Ginkgo support

### ISSUE THREAD

**Issue by williammartin** [onsi/ginkgo#544]
Following on from Gomega #315.

Gomega now uses type aliasing which is only available in Go 1.9+. Currently our Travis tests run against 1.6+, so there are build failures.

The Go support policy is N-1 major releases, so Go 1.11 and Go 1.10 will receive security patches (. I'd suggest we aim to keep a similar policy, I don't want us to be hamstrung by supporting older versions.

**Comment by williammartin** [comment]
Merged a PR that resolves the build failures. Would someone like to create a PR to note our policy in docs so we can close this?

@nodo Do you remember what bits of code there are in Ginkgo that required older versions of Go?

**Comment by nodo** [comment]
I was thinking about these files:
- https://github.com/onsi/ginkgo/blob/master/ginkgo/testsuite/vendor_check_go15.go
- https://github.com/onsi/ginkgo/blob/master/ginkgo/testsuite/vendor_check_go16.go
