### ISSUE TITLE
Ginkgo doesn't support -blockprofile flag from go test.

### ISSUE THREAD

**Issue by wingyplus** [onsi/ginkgo#545]
The `ginkgo` binary has only `-blockprofilerate` flag but not for `-blockprofile`. This should be add support for this?

**Comment by onsi** [comment]
This is definitely broken - Ginkgo was not managing the profile flags correct.  This will be fixed in v2.

**Comment by onsi** [comment]
A beta for Ginkgo V2 that fixes this issue was just released.  Profiling support is much improved now.   [Please try out the beta](https://github.com/onsi/ginkgo/issues/809)!
