### ISSUE TITLE
ginkgo cover output to cobertura

### ISSUE THREAD

**Issue by tejashwikalptaru** [onsi/ginkgo#548]
When we use 
`ginkgo -r -cover -outputdir=./shippable/codecoverage/ -coverprofile=coverage.txt`
It will create a combined output of coverage to a single file, I am unable to convert this output to equivalent Cobertura format (shippable expects Cobertura format for coverage reports)

Also, when using `-outputdir` flag, it should create a combined coverage output instead of creating coverage file in each package and then combined result in the output directory.

I tried converting cover output via `gocov-xml` and `gocover-cobertura` and both failed.

Also, when generating a combined output, it should skip the `mode:`, issue is already created [here](https://github.com/onsi/ginkgo/issues/518)

**Comment by tejashwikalptaru** [comment]
Nevermind, figured out myself.

Generate the cover using covermode as set
`ginkgo -r -cover -covermode=set -outputdir=shippable/codecoverage/ -coverprofile=coverage.out`

Now, we need to remove duplicate entries of `mode: set`
`awk '!seen[$0]++' shippable/codecoverage/coverage.out > shippable/codecoverage/coverage-fix.out`

Finally, convert to Cobertura
`gocov convert shippable/codecoverage/coverage-fix.out | gocov-xml > shippable/codecoverage/coverage.xml`

**Comment by williammartin** [comment]
Thanks for your investigation. I noted on #518 that I'd very happily take a PR to fix that up.
