### ISSUE TITLE
how do i set up my suite test?

### ISSUE THREAD

**Issue by skydai** [onsi/ginkgo#549]
I'm using Ginkgo, and this is my starting directory structure:

**
project/test/test_suite_test.go
project/test/component1/component1_test.go
project/test/component2/component2_test.go
project/test/component3/component3_test.go
.......**

because of each test must run after i start a informer and message queue, so i write it in BeforeSuites, located on **project/test/test_suite_test.go**
```
func TestProject(t *testing.T) {
	RegisterFailHandler(Fail)
	junitReporter := reporters.NewJUnitReporter("junit.xml")
	RunSpecsWithDefaultAndCustomReporters(t, "Test Suite", []Reporter{junitReporter})}

var _ = BeforeSuite(func() {
	gopath := os.Getenv("GOPATH")
	if gopath == "" {
		gopath = build.Default.GOPATH
	}
	setting.Config.KubeConfig = &setting.KubeConfig{
		Config: gopath + "/src/walm/test/k8sconfig/kubeconfig",
	}

	setting.InitConfig(gopath + "/src/walm/walm.yaml")
	setting.Config.KubeConfig.Config = gopath + "/src/walm/test/k8sconfig/kubeconfig"


	informer.StartInformer(stopChan)
	task.GetDefaultTaskManager().StartWorker()
})

```
But i found when i run **ginkgo -r**  in project/test/, no specs would be run, unless i put the **suite file** and **test file** in the **same package**. I write the ginkgo docs, know that intent with Ginkgo is that there be one test suite per package. 

But I need to keep the project structure as above to **keep order.** How can i  **set up** my suite test so that I can keep suite file and test file in different package but also works.
Thanks a lot!!!

**Comment by williammartin** [comment]
Hi, when you say "to keep order", do you mean temporal ordering, or do you mean tidiness?

**Comment by skydai** [comment]
tidiness, I want the category looks hierarchical.

**Comment by williammartin** [comment]
I don't believe there is any way to achieve what you want here and I'm not sure that it's idiomatic Go either, as it would encourage your packages to be coupled in an unusual way. That's your decision to make of course.

The best thing I can think to suggest right now is to provide the functionality in your `BeforeSuite` as a utility and create very thin `suite` files in each of your packages. Suites will never run in parallel, so there's no risk of pollution between them.

I'm not sure that I would accept a change that allowed the behaviour you desire. I'm not even sure of a good way to achieve it. Sorry I can't help you more.
