### ISSUE TITLE
[question] how to know whether the spec is focused

### ISSUE THREAD

**Issue by detailyang** [onsi/ginkgo#553]
Hello.

I want to know is there any way to know whether ginkgo is used `--FOCUS`.  

Now my before/after suite is blocking 2 seconds via `time.Sleep`. Even if I use `--FOCUS` it also will blocking the non-target tests.  So when I run tests via --FOCUS=xx, I wish to skip the non-target tests in my code.

Is there any way to get it? Many thanks:)

**Comment by blgm** [comment]
Hi @detailyang, as far as I'm aware, if a test is focused then before/after suites for other tests should not be run. To be very clear on what is being focused, you can use `FIt()` instead of `It()` so that you can avoid any issues with the `--focus` regular expression.

**Comment by detailyang** [comment]
consider it closed:)
