### ISSUE TITLE
suite parametrization and parallel

### ISSUE THREAD

**Issue by chordabmx** [onsi/ginkgo#561]
Hi @onsi, first of all thanks for this awesome framework!
I would like to know is it possible to parameterize test suite and run it in parallel?
Something like this:
```
func TestSomething(t *testing.T) {
	RegisterFailHandler(Fail)
	for _, i := range []string{"a", "b", "c", "d"} {
		RunSpecs(t, i)
	}
}
```
ginkgo -p would run 4 nodes

1 node RunSpecs(t, a)
2 node RunSpecs(t, b)
3 node RunSpecs(t, c)
4 node RunSpecs(t, d)

**Comment by onsi** [comment]
Hey @chordabmx what problem are you trying to solve?  Digging into that might help us suggest a solution.

**Comment by chordabmx** [comment]
@onsi Thanks for your reply!
I wrote templated tests, for a lot of web pages, and run them passing variable in RunSpec to do assertions.
Ex:
```
It("5375:Getting social media", func() {
   expectedElements := v.PageConfig.GetStringSlice(fmt.Sprintf("social.%s.followus", variable))
  Expect(shortcuts.GetKeys(page.Header.GetFollowUsElems())).Should(ConsistOf(expectedElements))
})
```
Also a i have integration with testrail, so the point is to run teplated tests for all pages in parallel, and fill in testruns in testrail.

**Comment by wingyplus** [comment]
@chordabmx Is `github.com/onsi/ginkgo/extensions/table` can be solve your problem?

**Comment by chordabmx** [comment]
@wingyplus it used to parametrize each test, but dont work for parametrization of whole spec, or am i missing something?

```
table.DescribeTable("test", func(name string) {
			variable = name
			RunSpecs(t, variable)
		},
			table.Entry("Name","a"),
                         table.Entry("Name","b"),
		)
```

**Comment by onsi** [comment]
ok got it - so you’ve templatized all tests and want to run them a handful of times with different variables.  and you’d like the tests to run in parallel.

The approach with calling `RunSpecs` multiple times won’t work, unfortunately, as (a) GInkgo expects `RunSpecs` to be called just once and (b) the test tree is constructed when the program is loaded into memory (all those `Describes`) are executed and cannot be adjusted dynamically (i can get into the reasons why but that’s not super relevant).

I see a few options:

1. Orchestrate this externally.  Basically - invoke a few independent test runs by calling `ginkgo`  and passing each a parameter that configures the test suite.  <= ugly

2. Adopt a Shared Examples pattern like so:
- build a collection of functions that take a parameter and generate the tests.  So for each test file you’ve got do something like:

```
func GenerateFooTests(p Parameters) {
    Describe(“....”, func() {
            It(“...”, func() {
                  //do stuff, use `p` to parameterize
            })
    })
}
```

and then have a single top-level Describe that does:

```
var _ = Describe(“All the tests”, func() {
    for _, p := range parameters {
          GenerateFooTests(p)
          GenerateBarTests(p)
           ....
    }
})
```

This will generate the testing tree on start up and all the tests you need will be loaded into memory across all parallel nodes and will execute in parallel as you want.  The downside is you’ll have to wrap things in these `Generate` functions and every time you add a new one will need to update the top level Describe.  but it’ll get you closer to what you want i think

**Comment by chordabmx** [comment]
@onsi tnx for your answer, it helped a lot, i guess we can close this issue.
