### ISSUE TITLE
Add "Helper()" to GinkgoTInterface

### ISSUE THREAD

**Issue by shaunc** [onsi/ginkgo#563]
`https://github.com/bradleyjkemp/cupaloy` uses [Helper()](https://godoc.org/testing#T.Helper) could this be added to the mock?

**Comment by shaunc** [comment]
Also is missing "Name()". As a rough workaround, the following seems to work:
```
type TestingT struct {
	GinkgoTInterface
	desc GinkgoTestDescription
}

func NewTestingT() TestingT {
	return TestingT{GinkgoT(), CurrentGinkgoTestDescription()}
}

func (i TestingT) Helper() {

}
func (i TestingT) Name() string {
	return i.desc.FullTestText
}
```

**Comment by blgm** [comment]
It looks like this has already been implemented in commit https://github.com/onsi/ginkgo/commit/b5fe44d9e12817942846c49d35804c5100e05327 so I'm going to close this. Please let me know if I missed something.
