### ISSUE TITLE
Help should be printed to stdout

### ISSUE THREAD

**Issue by akshaymankar** [onsi/ginkgo#567]
`ginkgo -h` produces a lot of output. Sometimes I am looking for something and grepping doesn't help me unless I redirect stderr to stdout. It would be really nice if the help was printed to stdout.

**Comment by blgm** [comment]
I've just done an experiment with the `git`, `curl` and `bosh` on a Mac, and they all send help messages to STDOUT and not STDERR.  This change suggestion does seem both helpful and more "standard".

**Comment by williammartin** [comment]
@akshaymankar Would you open a PR for this?

**Comment by akshaymankar** [comment]
@williammartin The PR is ready, let me know what you think.
