### ISSUE TITLE
JUnitReporter doesn't generate raport when tests time out 

### ISSUE THREAD

**Issue by serathius** [onsi/ginkgo#579]
When tests are called with '--timeout' and this timeout is reached, then raport will not be generated.
I think this should be fixed as this flag is documented and supported by ginkgo.

Is there any way to get around this before fix is implemented?

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I'm changing how ginkgo handles the timeout in v2 which will fix this issue.

I'm going to close this for now, but feel free to reopen it if you'd like.
