### ISSUE TITLE
tagging tests

### ISSUE THREAD

**Issue by srinubalsu** [onsi/ginkgo#580]
Is there a way that I can tag each test so that I could decide which test to run on different test environments?

That makes my life little bit easier.

**Comment by blgm** [comment]
Yes.  You can use the [`-tags`](http://onsi.github.io/ginkgo/#the-ginkgo-cli) flag which is passed to the Go compilation step, allowing you to use Go's built in tagging functionality, which is now called [Build Constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints)

**Comment by srinubalsu** [comment]
Hi George,
Thanks a lot for immediate and quick response. 

Coming to my issue, the solution that you have suggested will eliminate whole file. In my case, for example, I have test file with 50 tests, I want to run 20 in Dev Env, but in QA Env I want run 20 of same Dev Tests along with 10more tests.

How can I use this tags flag for this?

One more thing, with in the same file, I have positive and negative tests, I want to run then separately. Hope there is way for the same.

**Comment by blgm** [comment]
The `—focus` and `—skip` flags can do this based on test descriptions. See the section “Focused Specs” in the docs for more information.

**Comment by srinubalsu** [comment]
Hi George,
I am currently using those options for my runs, I wanna check out if any other option available.

**Comment by blgm** [comment]
It would be possible to implement a helper function such as `SkipIfDev()` that could examine the environment and conditionally run the built-in `Skip()`. Could that help?

**Comment by onsi** [comment]
Support for test labels is coming in 2.0.  Will close this for now.
