### ISSUE TITLE
Allow failFast to run teardown code

### ISSUE THREAD

**Issue by cliu-splunk** [onsi/ginkgo#581]
Hi,

Please correct me if I am wrong but I notice that the teardown code (AfterEach or AfterSuite) will not be run with --failFast option specified.

It causes a resource leaking problem for us that the resources tests create will not be cleaned up if any test fails, especially in our CICD. We have to remove the failFast option for now but would like to fail fast because it takes quite long or all tests to finish.

Thanks,
Chen

**Comment by jakubdyszkiewicz** [comment]
Hey,

I think this is not right. I had to put
```
if CurrentGinkgoTestDescription().Failed && config.GinkgoConfig.FailFast {
	return
}
```
into `AfterEach` to prevent it from being executed. I on the other hand wanted the resources to stay as they are.

**Comment by onsi** [comment]
yep - `--failFast` will run the teardown functions.
