### ISSUE TITLE
Executing a specific ginkgo test programatically

### ISSUE THREAD

**Issue by hh** [onsi/ginkgo#588]
I'm exploring adding Gherkin support for kubernetes to separately define our behaviours/features from our tests.

We currently make heavy use of Ginkgo, and much of our infrastructure is based on it.

I'd like create a set of .features referencing our existing ginkgo tests, while allowing us to make use of `Feature:`, `Scenario:`, and `tagging` via Gherkin. It would help projects like ours that already gherkin usage, but would like to benefit from separating BDD files from the test implementations.

```feature
Feature: Use existing ginkgo framework
  As a test contributor
  I want to not throw away all our old tests
  In order to retain the value generated in them
  @ginko @k8s.io @Conformance @NodeConformance
  Scenario: Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart exec hook properly
    Given existing gingko test "[k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart exec hook properly [NodeConformance] [Conformance]"
    When I run the test
    Then the existing test will pass
    And this is fine
  @ginko @k8s.io @NodeConformance
  Scenario: Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret
    Given existing gingko test "[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]"
    When I run the test
    Then the existing test will pass
    And this is fine
```
I'm exploring this via kubernetes/kubernetes#79914

**Comment by hh** [comment]
https://github.com/kubernetes/kubernetes/pull/79914/files#r302236077 is focused on the function that has the existing ginkgo test string. I'm unsure if it's possible to call into the Ginkgo framework to execute the test from here.

**Comment by onsi** [comment]
I'm going to be adding support for test labels and the ability to focus on a given file:line combo in Ginkgo 2.0.  Will close this for now.
