### ISSUE TITLE
How we can send test data to "ginkgo" test.go file from console or any file formats?

### ISSUE THREAD

**Issue by VasanthiVM** [onsi/ginkgo#597]
It("Allow issuer to issue new commercial paper", func() {
			expectcc.ResponseOk(paperChaincode.Invoke(`issue`, &cpaper.IssueCommercialPaper{
				Issuer:       IssuerName,
				PaperNumber:  "0001",
				IssueDate:    time.Now(),
				MaturityDate: time.Now().Add(time.Hour * 24 * 30 * 6),
				FaceValue:    100000,
			}))
		})

**Comment by blgm** [comment]
Hi @VasanthiVM. If a Ginkgo test needs to read some data in, then it can do so using the standard Go library. I would not recommend sending test data in via the console as it makes it harder to run the tests - people expect to be able to just run `ginkgo` without having to pipe data.
