### ISSUE TITLE
Constant git login prompts after installation

### ISSUE THREAD

**Issue by quick-question** [onsi/ginkgo#604]
After installing Ginkgo via `go get github.com/onsi/ginkgo/ginkgo` and attempting to run tests, Windows constantly pop-up requesting a git login. Issue stops after reboot but I cannot use the ginkgo CLI because of this.

Is this a known issue? I can't find anything similar. It's worth noting that my git credentials are already cached.

**Comment by blgm** [comment]
My guess would be that `go` is trying to download modules using the `git` protocol. Is it possible to examine the process tree to see which process is driving the prompt?

**Comment by quick-question** [comment]
@blgm Thanks for the quick response! Not sure what the problem really was but I reinstalled/reconfigured git and it fixed whatever wasn't right. :)
