### ISSUE TITLE
BeforeSuite set up for database using gorm . invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by noralinlll** [onsi/ginkgo#605]
In my main.go 
it is ok to run 

`
db, err := gorm.Open("postgres", "host=127.0.0.1 user=postgres dbname=mydb
`

however  when I run go test it ouccred error
model_suite_test.go
`package model_test

var DB *gorm.DB

func TestModel(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Model Suite")
}
var _ = BeforeSuite(func() {
	db, err := gorm.Open("postgres", "host=127.0.0.1 user=postgres dbname=mydb sslmode=disable password=123456")
        DB = db
	Expect(err).NotTo(HaveOccurred())
})

var _ = AfterSuite(func() {
	DB.Close()
})`

 Test Panicked
  runtime error: invalid memory address or nil pointer dereference
  /usr/local/opt/go/libexec/src/runtime/panic.go:82

  Full Stack Trace
        /Users/xxx/go/pkg/mod/github.com/onsi/ginkgo@v1.8.0/internal/leafnodes/runner.go:107 +0x73
  panic(0x1a27ba0, 0x24fa1e0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
  github.com/jinzhu/gorm.(*DB).Close(0x0, 0x20, 0xc0036ed820)

**Comment by blgm** [comment]
For context, the `Describe()`, `Context()`, `When()`, etc... blocks are run at the start to define the list of tests. Once the list of tests is defined, the `BeforeSuite()`, `BeforeEach()` etc... blocks are run, and the all the `It()` blocks.
