### ISSUE TITLE
Ginkgo parallel tests confusing text when using focus

### ISSUE THREAD

**Issue by jpalmerpivotal** [onsi/ginkgo#612]
## Summary:
Go version: go1.12.5
Ginkgo Version: 1.8.0
When we run either of the commands:
`ginkgo -focus "foo" -p integration/`
`ginkgo -p integration/` with focused tests (`FIt`)
The text upon starting a parallel run `Will run ## specs` is inconsistent with the non parallel.

## Extended:
We were looking to run 3 tests in file `foo_and_bar_test.go` which were all contained in a `Describe("foo", `. 
Initially we ran the tests focused `FIt` style serially and saw the expected `Will run 3 of 36 specs`; however, the tests were quite slow and fully parallelizable. So to save time we decided to use `-p`.

Upon running the command `ginkgo -p integration/` we saw 
```
Will run 36 specs

Running in parallel across 7 nodes
```
We were concerned that this was running all the tests and cancelled the test run.

We then ran `ginkgo -focus "foo" -p integration/` and once again saw 
```
Will run 36 specs

Running in parallel across 7 nodes
```

We then went back to not running it with the `-p` flag and un`FIt`ting the test and running `ginkgo -focus "foo" integration/` and once again saw the expected `Will run 3 of 36 specs`

Upon allowing the `ginkgo -p -focus "foo" integration/` to run further, it became evident that the tests were actually being skipped appropriately even though the text output said:
```
Will run 36 specs

Running in parallel across 7 nodes
```

Seems like a nice small QoL improvement.

**Comment by tyacovone** [comment]
+1.
This appears to still be the case for:
```
Ginkgo Version 1.12.1
go version go1.14.2 darwin/amd64
```

**Comment by onsi** [comment]
This is fixed in V2
