### ISSUE TITLE
`--reportFile` flag provided but not defined?

### ISSUE THREAD

**Issue by davisford** [onsi/ginkgo#614]
```
$ ginkgo -reportFile=testout.txt .
flag provided but not defined: -reportFile
```

```
$ ginkgo version
Ginkgo Version 1.10.2
```

This option appears to [be in the code](https://github.com/onsi/ginkgo/blob/034fd2551d22c8367966d0b80e1bb60326a513ee/config/config.go#L56) -- what am I missing?

**Comment by blgm** [comment]
Thank you for raising this @davisford. Do you think it could be the same as #602?

**Comment by ansd** [comment]
@davisford , the `-reportFile` flag got introduced in ginkgo `v1.10.3` by [this commit](https://github.com/onsi/ginkgo/commit/034fd2551d22c8367966d0b80e1bb60326a513ee). You're using `v1.10.2`.

**Comment by blgm** [comment]
Looks like an upgrade would fix this. Let us know if it does not.
