### ISSUE TITLE
Corrupt test coverage output with parallel, recursive tests

### ISSUE THREAD

**Issue by manno** [onsi/ginkgo#617]
When running with `-r -p -coverprofile file -outputdir coverage` the lines in the resulting coverage files are missing newlines:

```
github.com/onsi/ginkgo/integration/_fixtures/combined_coverage_fixture/first_package/coverage.go:19.17,21.2 1 0github.com/onsi/ginkgo/integration/_fixtures/combined_coverage_fixture/second_package/coverage.go:3.17,5.2 1 1
```

I added an example test here: 
https://github.com/manno/ginkgo/commits/test-parallel-recursive-coverage

**Comment by onsi** [comment]
This is fixed in v2
