### ISSUE TITLE
Can not find any ginkgo log output document and code example

### ISSUE THREAD

**Issue by yiyanwannian** [onsi/ginkgo#619]
As a new comer, I can not find any ginkgo log output detail document or code example, I can only find source code in console_logging.go, but don't figure out how to use this private methods in my test project, Is that we can 
 only use fmt.Print() or other logs libs inner test case ?

**Comment by yiyanwannian** [comment]
import "github.com/onsi/ginkgo/internal/writer"  encounter "Use of internal package is not allowed"

**Comment by onsi** [comment]
I'm working through old Ginkgo issues.  If this is still an issue for you then please give me a bit more detail.  Generally speaking you can write to ginkgo's `GinkgoWriter` can get logging output when a test fails.

Am going to close this for now, but feel free to reopen if you'd like.

**Comment by ahhmarr** [comment]
I suppose you are facing difficulty in fetching log output 
My guess would be that you re missing `-v` flag while running tests
an example log would be 

`fmt.Fprintf(GinkgoWriter, "Some log text: %v\n", expectedResponse)`

and logs should be visible with the following command `ginkgo -v`
