### ISSUE TITLE
Ginkgo customReporters does not keep status of all specs if multiple test files are present in same test suite.

### ISSUE THREAD

**Issue by amitkrout** [onsi/ginkgo#628]
I am facing an issue of missing few random test spec in reports generated by ginkgo ```RunSpecsWithDefaultAndCustomReporters``` for each ginkgo parallel test run. 

**Current scenario:**

I have three test files [1] and comprises total no of 15 specs. I am calling the test suite [2] through an .PHONY statment [3] ```make test-e2e-all```.

The console result looks good to me, however the generated reports looks weird (missing test specs) for each test i run

[1] https://github.com/openshift/odo/tree/master/tests/e2escenarios
[2] https://github.com/openshift/odo/blob/master/tests/e2escenarios/e2escenarios_suite_test.go#L13
[3] https://github.com/openshift/odo/blob/master/Makefile#L227

Attaching screenshot for your reference
Test run1 reports:
<img width="1429" alt="Screen Shot 2019-11-19 at 5 46 56 PM" src="https://user-images.githubusercontent.com/19851115/69145868-9cf7b980-0af4-11ea-910a-e87212e7576c.png">

Test run2 reports:
<img width="1436" alt="Screen Shot 2019-11-19 at 5 47 54 PM" src="https://user-images.githubusercontent.com/19851115/69145965-d0d2df00-0af4-11ea-9191-99dc48604ce2.png">

Test run3 reports:
<img width="1429" alt="Screen Shot 2019-11-19 at 5 49 01 PM" src="https://user-images.githubusercontent.com/19851115/69146013-e6e09f80-0af4-11ea-8604-a260f232eeed.png">

**Comment by amitkrout** [comment]
Can somebody address this please ? Seems ```RunSpecsWithDefaultAndCustomReporters``` does not properly in parallel run.

**Comment by onsi** [comment]
Hey @amitkrout - sorry that I missed this.  please take a look at the Junit reporter docs:
http://onsi.github.io/ginkgo/#generating-junit-xml-output

Specifically when running in parallel you need to point each node's Junit reporter at its own report file.  What you're seeing is the result of all nodes writing to the same file.  At this time the Junit reporter doesn't concatenate the results into a single file after the test ends so you'll need to do that manually.

**Comment by anandrkskd** [comment]
I have verified as per the doc on latest ginkgo version and it works fine

**Comment by anandrkskd** [comment]
@amitkrout I think you can close the issue, as per my last comment.

**Comment by amitkrout** [comment]
> @amitkrout I think you can close the issue, as per my last comment.

Awesome!!!
thanks @anandrkskd for verifying it.
