### ISSUE TITLE
Gingko should exit with non-0 exit code if any of the tests are focused even if all focused tests pass

### ISSUE THREAD

**Issue by cppforlife** [onsi/ginkgo#63]
...to avoid accidently committing focused tests and CI not turning red (since it's not running all the tests)

**Comment by mmacheerpuppy** [comment]
@onsi Ginkgo for me is currently exiting with this status code when I call `go test ./... -v` but all tests defined pass. Not sure how to resolve, this is important for CI/CD!

**Comment by blgm** [comment]
@mmacheerpuppy are any of the tests focused? Does the same happen when you run `ginkgo -r`?
