### ISSUE TITLE
GinkgoWriter io.Writer does not print immediately when running with 'go test -v'

### ISSUE THREAD

**Issue by distorhead** [onsi/ginkgo#633]
Have a print statement like:

```
_, _ = fmt.Fprintf(GinkgoWriter, "[DEBUG] OUTPUT LINE: %s\n", line)
```

If run with ginkgo cli `ginkgo -v ...` then the output is realtime, lines are printed immediately when test succeeded or failed (as expected).

If run with golang cli `go test -v ...` then:
- No output at all when test succeeded.
- No realtime output when test has failed.

Expected to see realtime output in both succeeded and failed tests using `go test -v`.

**Comment by marccarre** [comment]
I am also experiencing this issue, which is rather annoying, especially for long running tests/integration tests. Here is a repository reproducing the issue: https://github.com/marccarre/ginkgo-633
```console
$ go version
go version go1.13.7 darwin/amd64
$ mkdir -p ${GOPATH}/src/github.com/marccarre
$ cd ${GOPATH}/src/github.com/marccarre
$ git clone git@github.com:marccarre/ginkgo-633.git
$ cd ginkgo-633
$ go test -tags integration ./integration/tests/... -ginkgo.v -ginkgo.progress -test.v
[...] no output printed until after all tests run (15s)
```

**Comment by onsi** [comment]
seems like a limitation in `go test` here maybe?  @marccarre you're passing `-ginkgo.v` which will cause Ginkgo to emit to stdout immediately.  How does `go test -v` behave when running multiple packages?

It kinda makes sense that `go test` doesn't emit output in realtime as you would see interleaved output from multiple tests running in parallel...  Getting sane readable output in near-realtime is one reason why Ginkgo runs test suites in series and why parallelization within a given suite is so carefully orchestrated.  FWIW it should be possible to parallelize suites as well and manage the output carefully - if time allows perhaps that is something I can work on someday.

**Comment by tartale** [comment]
I experienced this as well; however I think I figured out how to make it work with `go test`; it requires both the `-v` option and you need to append `-args ginkgo.v`; e.g.:
```
go test -v  ./my-tests/... -args -ginkgo.v
```

**Comment by onsi** [comment]
yes @tartale that works if you are only running one package.  fwiw i recommend using the ginkgo test runner as it handles things like parallelization and orchestrating test output for you.
