### ISSUE TITLE
bootstrap should generate a file that passes gofumpt

### ISSUE THREAD

**Issue by briansorahan** [onsi/ginkgo#636]
I'm happy to open a PR for this since it would be a minor change that would fix the default behavior of `ginkgo bootstrap` for the builds we're using at my company.
We've just started using [gofumpt](https://github.com/mvdan/gofumpt) instead of gofmt, and ginkgo bootstrap should put the "testing" import at the top of the import in a separate group.
If you don't want this then please feel free to close this issue.

**Comment by blgm** [comment]
Hi @briansorahan. As I understand it, `gofumpt` would change
```go
package a_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"

	. "a"
)

var _ = Describe("Foo", func() {

})
```
to
```go
package a_test

import (
	. "a"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("Foo", func() {
})
```

So the import of the package under test would move to the top?

**Comment by briansorahan** [comment]
@blgm That's correct. We would do this for the "testing" import in the generated file.

**Comment by onsi** [comment]
I'd prefer to stick with the current use of `gofmt` vs pulling in a new external dependency.
