### ISSUE TITLE
Immediate execution inside Describe

### ISSUE THREAD

**Issue by zendril** [onsi/ginkgo#637]
Perhaps I need to 'think different' but I'm seeing the statements inside of a describe be executed even before the suite runs. 

```go
	Describe("Version Check", func() {
		fmt.Println("=========] Inside Version Check")
		Describe("Given a call to the /v2/ endpoint", func() {
			fmt.Println("=========] Given a call")
			resp, err := resty.R().Get(baseURL + "/v2/")
			It("should return nil error", func() {
				fmt.Println("=========] should return nil error")
				Expect(err).Should(BeNil())
			})
			It("should return 200 status code", func() {
				fmt.Println("=========] should return 200 status code")
				Expect(resp.StatusCode()).To(Equal(200))
			})
		})
	})
```

prints out

```shell
=========] Inside Version Check
=========] Given a call
Running Suite: Conformance Suite
================================
Random Seed: 1578078082
Will run 2 of 2 specs

=========] should return nil error
•=========] should return 200 status code
•
Ran 2 of 2 Specs in 0.000 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped


```

I would expect that they would be added to the stack and popped off in order.

This causes an issue because if I were to make multiple rest calls inside the `Describe`, but outside the `It`, then the specs inside the `It` are only operating on the context after those other calls have finished.. 

Another example, showing where this is a problem.
This fails:

```go
	Describe("Version Check", func() {
		Describe("Given a call to the /v2/ endpoint", func() {
			resp, err := resty.R().Get(baseURL + "/v2/")
			It("should return nil error", func() {
				Expect(err).Should(BeNil())
			})
			It("should return 200 status code", func() {
				Expect(resp.StatusCode()).To(Equal(200))
			})

			resp, err = resty.R().Post(baseURL + "/v2/z/blobs/uploads/")
			It("should return nil error", func() {
				Expect(err).Should(BeNil())
			})
			It("should return 202 status code", func() {
				Expect(resp.StatusCode()).To(Equal(202))
			})

		})
	})
```

```shell
Running Suite: Conformance Suite
================================
Random Seed: 1578078371
Will run 4 of 4 specs

•
------------------------------
• Failure [0.001 seconds]
Version Check
/home/zendril/projects/github/zendril/distribution-conformance/pkg/compliance/v1_0_0/version.go:27
  Given a call to the /v2/ endpoint
  /home/zendril/projects/github/zendril/distribution-conformance/pkg/compliance/v1_0_0/version.go:28
    should return 200 status code [It]
    /home/zendril/projects/github/zendril/distribution-conformance/pkg/compliance/v1_0_0/version.go:33

    Expected
        <int>: 202
    to equal
        <int>: 200

    /home/zendril/projects/github/zendril/distribution-conformance/pkg/compliance/v1_0_0/version.go:34
------------------------------
••

Summarizing 1 Failure:

[Fail] Version Check Given a call to the /v2/ endpoint [It] should return 200 status code
/home/zendril/projects/github/zendril/distribution-conformance/pkg/compliance/v1_0_0/version.go:34

Ran 4 of 4 Specs in 0.001 seconds
FAIL! -- 3 Passed | 1 Failed | 0 Pending | 0 Skipped

```

**Comment by blgm** [comment]
Hi @zendril, all code relating to tests and test setup/teardown should be in an `It()`, `Specify()`, `BeforeEach()`, `AfterEach()` etc...

`Describe()`, `Context()`, `When()`, etc... are used to organise test code in containers. Ginkgo runs all the code in these containers at the start. This behavior is common to BDD frameworks.

There are a number of styles to solve problems of the kind you have described.  My personal preference here would be to bunch the expectations in the same `It()` as they all relate to the same behavior.
```go
	Describe("Version Check", func() {
		Describe("Given a call to the /v2/ endpoint", func() {
			It("returns 200 for GET", func() {
				resp, err := resty.R().Get(baseURL + "/v2/")
				Expect(err).NotTo(HaveOccurred())
				Expect(resp.StatusCode()).To(Equal(200))
			})
		})
	})
```

An alternative could be to use a `BeforeEach()`:
```go
	Describe("Version Check", func() {
		Describe("Given a GET call to the /v2/ endpoint", func() {
			var resp Response
			var err error
			BeforeEach(func() {
				resp, err := resty.R().Get(baseURL + "/v2/")
			})

			It("should return nil error", func() {
				Expect(err).Should(BeNil())
			})

			It("should return 200 status code", func() {
				Expect(resp.StatusCode()).To(Equal(200))
			})
		})

		Describe("Given a POST call to the /v2/ endpoint", func() {
			var resp Response
			var err error
			BeforeEach(func() {
				resp, err = resty.R().Post(baseURL + "/v2/z/blobs/uploads/")
			})

			It("should return nil error", func() {
				Expect(err).Should(BeNil())
			})

			It("should return 202 status code", func() {
				Expect(resp.StatusCode()).To(Equal(202))
			})

		})
	})
```

Does this help?

**Comment by zendril** [comment]
That indeed helps. Thanks so much for the quick response.

Two quick things.

- Other than opening issues, is there a forum or slack channel to have questions/discussions?
- As a different point of view (not saying it is better), I originally wrote the given/when/then syntax into the EasyB BDD framework (years ago before Cucumber and Gherkin adopted it) and it read more naturally for me when the `given` was the preconditions, the `when` was an action and the `then` were the checks (or specs as Ginkgo refers to them). They were invoked in order at the time the spec was run. So that is why I was bringing those assumptions along with me when trying to understand the behavior (no pun intended) of Gingko's `Describe`.

**Comment by blgm** [comment]
@zendril:
- That's a good question. We are looking into having a Slack channel, but are not quite there yet, so for now feel free to raise issues for questions.
- I agree that the execution order is confusing at first, and I have found it's pretty similar in other BDD frameworks that I've used in JavaScript and Ruby. I don't think it would be possible to change Ginkgo because there are so many tests that rely on it working this way.

I'm going to close this issue for now, but please feel free to re-open it, or open a new issue.
