### ISSUE TITLE
Provide vscode extensions to run individual tests

### ISSUE THREAD

**Issue by vincepri** [onsi/ginkgo#647]
One great feature for vscode, and other editors as well is to have the ability to quickly run a particular test that I (as a developer) might be working on. It'd be great to provide lens support for ginkgo tests in vscode.

**Comment by blgm** [comment]
Hi @vincepri. I agree that it would be great. I'm assuming that you know about the ability to focus a test, and that you're suggesting something more sophisticated. Do you have any ideas on how it might work?

**Comment by vincepri** [comment]
@blgm Thanks for pointing out the test focus feature, it could probably be used here as well

IIRC when I looked into this it needs to be a vscode lens extension, which would provide something like 
<img width="439" alt="Screen Shot 2020-03-18 at 8 37 42 AM" src="https://user-images.githubusercontent.com/3118335/76978337-ccc49b80-68f3-11ea-9ad7-9c8308cd47d3.png">.

when I run that, in vscode the output shows 
```
Running tool: /usr/local/bin/go test -timeout 30s sigs.k8s.io/cluster-api/controlplane/kubeadm/controllers -run ^(TestClusterToKubeadmControlPlane)$ -v -count=1
```

**Comment by joselitofilho** [comment]
Hello,
@vincepri and @blgm 

I've implemented a VSCode extension to help us on development using the Ginkgo framework. For more information, please see [ginkgo test explorer](https://marketplace.visualstudio.com/items?itemName=joselitofilho.ginkgotestexplorer)

**Comment by vincepri** [comment]
Woah this is great! Can't wait to show it around :)

**Comment by joselitofilho** [comment]
Please, let me know if you like it! (or not 😆 )
