### ISSUE TITLE
Ginkgo covert utility doesn't recognize t.Run( ) from *testing.T 

### ISSUE THREAD

**Issue by harishsurf** [onsi/ginkgo#649]
When using ginkgo convert utility to convert existing go tests to ginkgo, t.Run( ) is not defined by GinkgoTInterface and hence the conversion doesn't recognize this method. I wanted to know if I can leverage Ginkgo to achieve the equivalent of t.Run( ) / Data-driven testing
My use case: I have a `params = [] struct {}` which has my test parameters each of which is passed to the same function `TestMyFunc` to be tested. How I achieve this in go test: 
```
params = []struct{} 
for _, eachItem := range params {
  t.Run(eachItem.name, func() {
        // use `eachitem` inside this func 
})
```
Thanks in advance!

**Comment by blgm** [comment]
One way to achieve this would be with a table test: https://onsi.github.io/ginkgo/#table-driven-tests

```go
DescribeTable(
  "some description",
  func(i struct{}) {
    // do test here
  },
  Entry("zero", struct{}),
  Entry("one", struct{}),
)
```

A caveat to this approach is that all the values in the `Entry`s need to be constant or easy to calculate up-front.

**Comment by harishsurf** [comment]
@blgm, I was able to use ginkgo's `DescribeTable` for my use case. Thanks for the suggestion!
