### ISSUE TITLE
ginkgo's convert utility leaves out comments from old tests during the conversion

### ISSUE THREAD

**Issue by harishsurf** [onsi/ginkgo#651]
Ginkgo's convert utility currently does not include the comments from tests that are being converted by default. 
There are two ways to solve this problem:
1. provide a command-line flag whether or not to include comments
2. make it a default option to include the comments - this is a minor-change
I personally believe it is beneficial to retain the comments by default, but I'll wait for a confirmation before creating a PR.

**Comment by blgm** [comment]
@harishsurf, our impression is that `ginkgo convert` is rarely used. I agree that this is a bug, and I'd happily review a PR to fix it.

**Comment by blgm** [comment]
Resolved by #657
