### ISSUE TITLE
Gomock + Ginkgo - tests hanging after unexpected call to a mock

### ISSUE THREAD

**Issue by delta-bravo** [onsi/ginkgo#654]
My tests use Gomock + Ginkgo; With `GinkgoT()` controller.
When mocks get an unexpected invocation gomock calls `Fatalf()` on controller which invokes `Fail()` in`ginkgo_dsl.go`
```
func Fail(message string, callerSkip ...int) {
	skip := 0
	if len(callerSkip) > 0 {
		skip = callerSkip[0]
	}

	globalFailer.Fail(message, codelocation.New(skip+1))
	panic(GINKGO_PANIC)
}
```

After `panic(GINKGO_PANIC)` is called the test suite hangs (doesn't pass or fail and needs to be killed)

Tried this with `1.12.0` version of ginkgo. What could cause this behaviour?

Thanks

**Comment by blgm** [comment]
Hi @delta-bravo. Integration with Gomock is documented but I don't think it's something that many Ginkgo users do, and unfortunately it seems that there are no tests for it. There were some Gomock issues worked on in 2014, and it's conceivable that a change in Ginkgo, gomock, or Go has broken things in the last six years.

Is this something that has never worked for you, or was it working previously?

**Comment by delta-bravo** [comment]
I am not sure this has ever worked @blgm 
There is a fair bit of concurrency in my test, I will keep looking. 

Has anyone ever reported issues like this?

**Comment by delta-bravo** [comment]
OK solved using approach suggested in documentation

https://onsi.github.io/ginkgo/#asynchronous-tests
