### ISSUE TITLE
Gingko didn't use vendor dir when run with -mod=vendor flag with Golang 1.14

### ISSUE THREAD

**Issue by bklaubos** [onsi/ginkgo#655]
I used Go 1.14 to create a vendor dir.
(1) Next, I  delete the mod cache and build cache
`go clean -modcache -cache -x`
(2) I was able to compile using `go build -mod=vendor ./...`  without triggering any go modules downloading from  the Internet. This shows the vendoring is working correctly.
(3) Lastly, I run the Gingko:
`ginkgo -mod=vendor -v ./...`
It pauses  for 1-2 mins before running tests
(4) I checked and see that the Go module cache is being populated again!

**Comment by blgm** [comment]
Hi @bklaubos, thank you for reporting this.
- Is this something that used to work and is now broken?
- Do any of the tests build Go programs as they run, for instance do they use `gomega.gexec` or something similar?
- Does the problem occur when the vendor option is set via an environment variable? For instance: `GOFLAGS="-mod=vendor" ginkgo -v ./...`

**Comment by bklaubos** [comment]
You can close this issue. The issue is that need to change the go.mod to require "go 1.14"

**Comment by blgm** [comment]
Thank you @bklaubos
