### ISSUE TITLE
GinkgoT.Skip does not skip

### ISSUE THREAD

**Issue by pohly** [onsi/ginkgo#659]
According to https://godoc.org/github.com/onsi/ginkgo#GinkgoT, `GinkgoTInterface` can be used for code that expects similar behavior to `* testing.T` through an interface. `Skip`, `Skipf` and `SkipNow` are implemented, but do not follow the semantic of the corresponding functions in `testing.T`:

https://github.com/onsi/ginkgo/blob/b8861366892e5d67a347e72ce9124b59e13de51b/internal/testingtproxy/testing_t_proxy.go#L63-L65

What's missing is:
- marking the test as skipped
- actually aborting the current test

**Comment by onsi** [comment]
This was fixed on master recently
