### ISSUE TITLE
Ginkgo should support sending coverage reports directly to coveralls.io

### ISSUE THREAD

**Issue by onsi** [onsi/ginkgo#66]
Something like:

ginkgo -cover -coverallsToken=YOUR_TOKEN -coverallsService=travis

**Comment by zachgersh** [comment]
@onsi - I'd actually love to know the `why` behind the decision change. I know quite a few projects outside of our use cases that actually like to use coverage reports.

I'd be happy to put something together on this unless you think there is something super complex here?

**Comment by robdimsdale** [comment]
Reopening as it looks like there's some community interest. @zachgersh can you provide a highlight of what you'd like to do in a PR?

**Comment by zachgersh** [comment]
So, coming back to this:

Currently uploading coverage reports for go is not simple. You need two tools and it just seems like a bit of a mess to get everything running correctly :/

The two other tools you need in addition to the go coverage tool are:
`github.com/modocache/gover`
`github.com/mattn/goveralls`

It would be so much easier for people to be able to simple do something like this in ginkgo

`COVERALLS_TOKEN=test ginkgo -cover`

Ginkgo would then handle collecting all of the various coverage files and uploading them straight to coveralls.io. Existence of the COVERALLS_TOKEN dictates whether or not the coverage report is uploaded (I am fine with this being a flag as well).

cc @robdimsdale @onsi

**Comment by robdimsdale** [comment]
@zachgersh there's a fair bit of community interest so if you want to submit a PR I think it would be welcome.

What changes do you propose to make to ginkgo to achieve your goals above?

**Comment by james-lawrence** [comment]
not a huge fan of this honestly, too tightly coupled with coveralls/gover. I'd be more interested in something that combines the individual cover reports and outputs a single file.

**Comment by robdimsdale** [comment]
We haven't had any activity on this thread in six months - I'm closing it (again).
