### ISSUE TITLE
go get -u github.com/onsi/ginkgo/ginkgo starts throwing error all of a sudden

### ISSUE THREAD

**Issue by chenpfeisoo** [onsi/ginkgo#661]
When I run go get -u github.com/onsi/ginkgo/ginkgo
Output is as follows
```
-> go get -u  github.com/onsi/ginkgo/ginkgo

go: found github.com/onsi/ginkgo/ginkgo in github.com/onsi/ginkgo v1.12.0
go: golang.org/x/sys upgrade => v0.0.0-20200406155108-e3b113bbe6a4
go get: upgrading gopkg.in/fsnotify.v1@v1.4.7: gopkg.in/fsnotify.v1@v1.4.9: invalid version: go.mod has non-....v1 module path "github.com/fsnotify/fsnotify" at revision v1.4.9
```
```
->go version
go version go1.14.1 darwin/amd64
```
My whole development environment is new, so I don't know where the dependency problem is

**Comment by chenpfeisoo** [comment]
So how did you solve the problem in the end? I also have this problem now. Go version 1.14.1

**Comment by ryancurrah** [comment]
@chenpfeisoo I think this issue is resolved as of yesterday. A PR was merged that changed the package that caused this error.

**Comment by chenpfeisoo** [comment]
👍
