### ISSUE TITLE
combineCoverprofiles fails if a coverprofile is blank

### ISSUE THREAD

**Issue by NilsJPWerner** [onsi/ginkgo#662]
PR #552 solved the issue of removing the duplicate `mode: xxx` in the combined coverage profile. However it introduced a bug where if a coverage profile file is blank except for the mode line, the combining function encounters an index error [here](https://github.com/onsi/ginkgo/blob/master/ginkgo/run_command.go#L196).

```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
main.(*SpecRunner).combineCoverprofiles(0xc00000e320, 0xc000178100, 0x11, 0x20, 0xc000136828, 0x0)
	/go/src/github.com/onsi/ginkgo/ginkgo/run_command.go:196 +0x7bd
main.(*SpecRunner).RunSpecs(0xc00000e320, 0xc0001780b0, 0x0, 0x5, 0xc92b58, 0x0, 0x0)
	/go/src/github.com/onsi/ginkgo/ginkgo/run_command.go:116 +0xb41
main.(*Command).Run(0xc000106180, 0xc000178000, 0xb, 0x10, 0xc92b58, 0x0, 0x0)
	/go/src/github.com/onsi/ginkgo/ginkgo/main.go:158 +0xb8
main.main()
	/go/src/github.com/onsi/ginkgo/ginkgo/main.go:206 +0x13d
```

This is because the length of the contents in this case are 0. Thus `contents[len(contents)-1]` will fail.

**Comment by rafaeleyng** [comment]
It seems to have been fixed in https://github.com/onsi/ginkgo/pull/670/files
