### ISSUE TITLE
How to disable the logging of each step, except that can be modified by custom reporter?

### ISSUE THREAD

**Issue by phoenixking25** [onsi/ginkgo#675]

**Comment by williammartin** [comment]
Can you provide some specific examples of what you would like to do and what you would like to see?

**Comment by phoenixking25** [comment]
> /home/phoenix/GO/src/sigs.k8s.io/multi-tenancy/benchmarks/e2e/tests/block_host_ipc/block_host_ipc.go:23
[It] validate tenants can't share HostIPC
  /home/phoenix/GO/src/sigs.k8s.io/multi-tenancy/benchmarks/e2e/tests/block_host_ipc/block_host_ipc.go:32
STEP: tenant ${user} cannot create pod with HostIPC set to true%!(EXTRA string=t0-admin0-tenant0admin-kind-kind)
May 21 20:44:49.190: INFO: t0-admin0-tenant0admin-kind-kind must be unable to create pod with HostIPC set to true
[BeforeEach] [k8s.io] [PL1] [PL2] [PL3] Test across tenants permission
  /home/phoenix/GO/src/sigs.k8s.io/multi-tenancy/benchmarks/e2e/tests/block_other_tenant_resources/block_other_tenant_resources.go:27
STEP: get tenant's namespace wide api-resources
May 21 20:44:49.192: INFO: Running '/snap/bin/kubectl -n tenant0admin api-resources --namespaced=true -o=name'

Just wanna remove the [BeforeEach], STEP lines.
