### ISSUE TITLE
Cannot use SynchronizedBeforeSuite with DescribeTable

### ISSUE THREAD

**Issue by roni-frantchi** [onsi/ginkgo#682]
Trying to write something like:  
```go
SynchronizedBeforeSuite(func() []byte {
    // setup
    return setupResult
  }, func(setupResult []byte) {
    DescribeTable("foo", func() {
      // something that needs setupResult
    } ,testEntries)
})
```

Will result in `You may only call It from within a Describe, Context or When`.  

How am I meant to setup something (like db) once across all of my table test cases?

**Comment by blgm** [comment]
Hi @roni-frantchi. Ginkgo does not let you write a test as part of a setup hook.

Both the functions passed to `SynchronizedBeforeSuite()` are setup functions. The first function runs one node 1, and the other function runs on all nodes, and is still for setup.

The documentation shows an example use of `SynchronizedBeforeSuite()` for database setup:
```go
var _ = SynchronizedBeforeSuite(func() []byte {
    port := 4000 + config.GinkgoConfig.ParallelNode

    dbRunner = db.NewRunner()
    err := dbRunner.Start(port)
    Expect(err).NotTo(HaveOccurred())

    return []byte(dbRunner.Address())
}, func(data []byte) {
    dbAddress := string(data)

    dbClient = db.NewClient()
    err = dbClient.Connect(dbAddress)
    Expect(err).NotTo(HaveOccurred())
})
```
In this example, all nodes would then have access to `dbClient` for testing, for example:
```go
var _ = Describe("my tests", func() {
  DescribeTable(
    "my test",
    func() {
      // a test that uses dbClient
    },
    Entry("one"),
  )
})
```

How helpful was this?

**Comment by roni-frantchi** [comment]
Thank you @blgm !  
I think the part in the documentation that threw me off is this line:
```go
    Expect(err).NotTo(HaveOccurred())
```

This assertion had let me to think that the second function is where I should place my tests.  

> In this example, all nodes would then have access to dbClient for testing, for example:

So `dbClient` should be declared outside the scope of both `SynchronizedBeforeSuite` and that `Describe`?  
And my `Describe` will wait for `SynchronizedBeforeSuite` to complete?  
In other words, you're saying what I'm looking for is something like:  

```go
var dbClient NewClient

var _ = SynchronizedBeforeSuite(func() []byte {
    port := 4000 + config.GinkgoConfig.ParallelNode

    dbRunner = db.NewRunner()
    err := dbRunner.Start(port)
    Expect(err).NotTo(HaveOccurred())

    return []byte(dbRunner.Address())
}, func(data []byte) {
    dbAddress := string(data)

    dbClient = db.NewClient()
    err = dbClient.Connect(dbAddress)
    Expect(err).NotTo(HaveOccurred())
})

// Will this wait for dbClient to set?
var _ = Describe("my tests", func() {
  DescribeTable(
    "my test",
    func() {
      // a test that uses dbClient
    },
    Entry("one"),
  )
})
```

**Comment by blgm** [comment]
> I think the part in the documentation that threw me off is this line:

Strangely you can put Gomega assertions in setup, but they report as setup failures rather than test results.

> // Will this wait for dbClient to set?

Yes, it will. Specifically when Go runs the `Describe()` function it *registers* the test functions, and does not call them immediately. Once the pre-requisite setup steps have completed, Ginkgo will call the test functions.

**Comment by blgm** [comment]
And...
> So dbClient should be declared outside the scope of both SynchronizedBeforeSuite and that Describe?

Exactly.

**Comment by roni-frantchi** [comment]
Thanks @blgm.  
Much appreciated!  
That makes more sense.  

Unfortunately, I still can't get it to work for my use case.  
You see, my test cases are determined based on some fixtures read from the filesystem - what I'm trying to do is have them defined first on node0, and then run the test cases based on that.  
But this code:
```go
var testEntries []table.TableEntry

var __ =	SynchronizedBeforeSuite(func() []byte {
	testEntries = getEntries()
	return nil
}, func(_ []byte) {
})

var _ = Describe("foo", func() {
	table.DescribeTable("bar",
		func(entryDir string, suiteDir string) {
                     Expect(...)
		}, testEntries...,
	)
})
```

Will end up resulting in:
```
testing: warning: no tests to run
PASS
```
I guess what happens is exactly what you said - Go registers the test functions first, which is an empty table when it does so, and only then runs my setup...  
I'm not sure how I should tackle this one then.

**Comment by onsi** [comment]
hey @roni-frantchi  - I'll try to find some time to pull together a writeup of the ginkgo lifecycle.  It's fairly straightforward, if opaque, and I think helping everyone have a clearer mental model will go a long way.

For now - a work around might look like this:

```go

var testEntries = getEntries()

var _ = Describe("foo", func() {
	table.DescribeTable("bar",
		func(entryDir string, suiteDir string) {
                     Expect(...)
		}, testEntries...,
	)
})
```

i.e. do this at the top level, outside of any test setup.  This will run when the test binary is first launched and set up the tree of tests _before_ the tests begin to run.

To ensure parallelization works you'll need to make sure that the order is fully deterministic.  Ginkgo implements parallelization by running multiple processes - one for each parallel node.  The nodes must compute the same test tree and will then deterministically agree on a test order and divvy up the work among themselves.

Lemme know if that doesn't make sense/doesn't work and I'll try to help some more.

**Comment by blgm** [comment]
I think your explanation is correct. Here are some thoughts on options (one of which is almost identical to @onsi's above, but I had already written it):

1) Don't use Ginkgo, but still use Gomega. Because this is hard to reason about, and it's not really using the key features of Ginkgo, this could be done using the Go testing package, and it would probably make more sense to people in the future. You can do parallel tests and subtests with Go's testing package.

2) If `getEntries()` is lightweight, could something like this work?
```go
var _ = Describe("foo", func() {
	table.DescribeTable("bar",
		func(entryDir string, suiteDir string) {
                     Expect(...)
		}, getEntries()...,
	)
})
The aim is that the slice should not be empty when `DescribeTable()` is called
```

I'm sure there are many other options.

**Comment by roni-frantchi** [comment]
Hey, @onsi thanks for helping out!  
When picking up Ginkgo I actually naively tried exactly what you had suggested.  
But then, every time I ran my test I got a different set of suites that got skipped.  
Sometimes 0 tests were ran. Sometimes 1, sometimes 2...  
I couldn't wrap my head around why that is, and figured the fact I'm doing something outside the scope of the test must be causing it, so I tried `SynchronizedBeforeSuite`.  

Now thanks to your answer, I think I understand the reason why - I'm using https://github.com/bmatcuk/doublestar recursively glob for my fixtures - probably getting them in a different order each time, causing the parallel process to not distribute the work properly as you had suggested.  

I can see if adding sorting the cases out first helps.  
Will post here as soon as I try that.

**Comment by onsi** [comment]
Great!  If you can’t get it figured out point me at some code (if it’s
online) and I can help out.

**Comment by roni-frantchi** [comment]
Thanks again @blgm .  
While waiting to hopefully hear back from you guys here, I actually tried using Gomega on its own with Go test like so:  

```go
func TestFoo(t *testing.T) {
	t.Parallel() 

	for _, tt := range terraform11Entries {
		tt := tt 
		t.Run(tt.suite, func(t *testing.T) {
			t.Parallel() 
			g := NewGomegaWithT(t)
			g.Expect(...)
		})
	}
}
```

That had a bizarre effect of showing the results of test case 1 shown right after those of test case 2.  

The documentation on Gomega ( as you probably well known ;) ) doesn't have an example of using it with Go 1.7's named tests.. So maybe I didn't use it properly.  (maybe I should open an issue on https://github.com/onsi/gomega ?).

**Comment by roni-frantchi** [comment]
Hey @onsi - sorting the entry files right before running it didn't help - my test cases still sometime simply do not run, sometimes runs only 1 test case... sometimes 2.  
I'll try and create a smaller sample I can share, but in essence it really is simply your example, while having `getEntries()` return the entries based on a bunch of files.

**Comment by onsi** [comment]
If you're up for making a sharable sample I'd love to help.

**Comment by onsi** [comment]
I've added some documentation about Ginkgo's lifecycle here:
http://onsi.github.io/ginkgo/#understanding-ginkgos-lifecycle
