### ISSUE TITLE
Stop using dot import for the package under test in ginkgo generate

### ISSUE THREAD

**Issue by alex-slynko** [onsi/ginkgo#683]
Hi there

I am happy user of Ginkgo for almost five years.
I am always puzzled by the default behaviour of `ginkgo generate` command. It generates output that includes dot import of the package under test. (Ie. `import . my_package`)

I went through repositories of some main Ginkgo contributors and saw that they don't do the dot import. It is similar to my experience - dot imports make code reading harder. 

I propose to replace dot import with normal import in the test.

**Comment by onsi** [comment]
hey @alex-slynko that a sounds good to me.  Want to submit a PR?  you might want to tweak the `gh-pages` branch too.

**Comment by alex-slynko** [comment]
Sure, I'll send the PR later
