### ISSUE TITLE
Why does the BeforeEach block not init the value of DescribeTable

### ISSUE THREAD

**Issue by b675987273** [onsi/ginkgo#685]
![image](https://user-images.githubusercontent.com/44078961/83733979-ec609a00-a680-11ea-98fc-ebc0c0ff1bc1.png)

```go
       BeforeEach(func() {
               ....
		mpijobTable = ...
	})

	DescribeTable("vertify mpijob create by ", func(testElem Mpijob, ErrNotNull bool) {
		....
	},
		Entry("Creat a same mpijob.", mpiJobTpl, true),
		...
	)
```

**Comment by blgm** [comment]
Hi, this is a very similar issue to #682, and it relates to the Ginkgo lifecycle which unfortunately is not documented yet...

A Ginkgo test runs in two phases:
- *Registration* - this is where Ginkgo **registers** (and does not run) all the BeforeEach, Describe, DescribeTable, Entry, It, etc... and works out what to run and in what order
- *Execution* - this is where Ginkgo runs all the things it has worked out in the previous phase

What's going on here is that `Entry(...)` is running at *registration* time when `mpijobTable` is empty, and the `BeforeEach()` is running at *execution* time which is too late.

Here are some options:

**Option 1**
Just set the value of `mpijobTable` when it is declared

**Option 2**
Given that `mpijobTable` is global, you could just access it directly in the test function:
```go
BeforeEach(func() {
               ....
		mpijobTable = ...
	})

	DescribeTable("vertify mpijob create by ", func(ErrNotNull bool) {
		// mpijobTable is available here
	},
		Entry("Creat a same mpijob.", true),
		...
	)
```

**Option 3**
Pass a function:
```go
BeforeEach(func() {
               ....
		mpijobTable = ...
	})

	DescribeTable("vertify mpijob create by ", func(func () testElem Mpijob, ErrNotNull bool) {
		....
	},
		Entry("Creat a same mpijob.", func() Mpijob { return mpiJobTpl }, true),
		...
	)
```

Do any of these work for you?

**Comment by b675987273** [comment]
Ok, i will change it  into the option 2.

**Comment by blgm** [comment]
Hi. I'm going to close this as I think it's resolved, but please re-open or open a new issue if there are any more questions or problems.

**Comment by onsi** [comment]
I've added some documentation about Ginkgo's lifecycle here:
http://onsi.github.io/ginkgo/#understanding-ginkgos-lifecycle
