### ISSUE TITLE
Ginkgo isn't reporting the proper location of tests

### ISSUE THREAD

**Issue by fraenkel** [onsi/ginkgo#69]
When I run from the root of my tree, and hit a failure, I see something like:

Failed to compile varz:

 github.com/cloudfoundry/gorouter/varz_test
./varz_test.go:76: unknown route.Endpoint field 'Host' in struct literal
./varz_test.go:77: unknown route.Endpoint field 'Port' in struct literal

However, there are 2 varz_test.go (don't ask), but they are located at:
./common/varz_test.go
./varz/varz_test.go

So which one failed?

**Comment by jayunit100** [comment]
Is it true that `_test.go` is a requirement for the ginkgo executables?

**Comment by onsi** [comment]
Yes _test.go is necessary.  Ginkgo is just calling go test under the hood.
