### ISSUE TITLE
Incomplete ginkgo report records, missing records

### ISSUE THREAD

**Issue by chenpfeisoo** [onsi/ginkgo#696]
I have 33 cases, all of which pass after execution, but only 7 of the report records

`
Ran 33 of 33 Specs in 121.786 seconds
SUCCESS! -- 33 Passed | 0 Failed | 0 Pending | 0 Skipped
`

report total=7

`<?xml version="1.0" encoding="UTF-8"?>
  <testsuite name="Workload Suite" tests="7" failures="0" errors="0" time="121.786">
  ....
  </testsuite>`

What is the reason why the report is not fully recorded?

**Comment by chenpfeisoo** [comment]
Find an interesting phenomenon: if I use `-- nodes = 4` locally, report is incomplete

If I delete `--node `report is complete

How to make report record all execution records in concurrent cases

cmd
`ginkgo -keepGoing -reportPassed -progress -trace --nodes=4 --reportFile=workload_junit.xml`

`ginkgo -keepGoing  --reportFile=workload_junit.xml`

**Comment by williammartin** [comment]
Hi @chenpfeisoo, is there any chance you can share a reproduction?

**Comment by onsi** [comment]
hey @chenpfeisoo this is documented here:

https://onsi.github.io/ginkgo/#generating-junit-xml-output

when running in parallel we recommend building the reporter manually and passing it a report file per node.

**Comment by chenpfeisoo** [comment]
@onsi  How to set up single node parallel operation？

**Comment by onsi** [comment]
Sorry @chenpfeisoo <https://github.com/chenpfeisoo> I don't understand the
question.
