### ISSUE TITLE
Ginkgo should print verbosity when run with `go test -v`

### ISSUE THREAD

**Issue by williammartin** [onsi/ginkgo#697]
See discussion here: https://gophers.slack.com/archives/C181J3WUR/p1592433406010800

Is there any reason we should not respect this flag?

**Comment by onsi** [comment]
seems fine to me.  but keep `ginkgo.v` as well to not break everything.  are you up for a PR @williammartin ?

**Comment by williammartin** [comment]
Yep will do.
