### ISSUE TITLE
Subprocess test and exit matcher

### ISSUE THREAD

**Issue by codeblooded** [onsi/ginkgo#699]
Hi, I was wondering the recommended way to test the exit of a process with ginkgo.

For reference, Andrew Gerrand showed a technique in his [Testing Techniques](https://talks.golang.org/2014/testing.slide#23) slide deck.

I noticed that there are no matchers for processes and, I think, there is no builtin way to do this in ginkgo. Would this be a useful feature and set of matchers for ginkgo/gomega or is it too OS-specific?

**Comment by onsi** [comment]
There's a Gomega library called `gexec` dedicated to this:
Section in Gomega docs: http://onsi.github.io/gomega/#gexec-testing-external-processes
[godoc](https://godoc.org/github.com/onsi/gomega/gexec)

To test the exit status of a process you can:

```
command := exec.Command("...")
session, err := gexec.Start(command, GinkgoWriter, GinkgoWriter) //Gomega docs explain why `GinkgoWriter`
Expect(err).NotTo(HaveOccurred()) //make sure we successfully launched the process
Eventually(session).Should(exec.Exit(1)) //assert that the process should eventually exit with exit code 1
```

Note that the use of `Eventually` is important here.  In the example you link to the call to `cmd.Run()` can sit forever if the process does not exit.  `Eventually` asserts that the session exits with exit code 1 within the default `Eventually` timeout (1 second).

**Comment by onsi** [comment]
There's also a lot of support for making assertions against the process output that leverages Gomega's `gbytes` package.  So you can do stuff like:

```
Eventually(session.Err).Should(gbytes.Say("process failed because foo"))
Eventually(session).Should(gexec.Exit(1))
```

**Comment by codeblooded** [comment]
Oops... sorry onsi... I can't believe I missed this. Thanks.
