### ISSUE TITLE
tools.go instructions seem wrong

### ISSUE THREAD

**Issue by NilsJPWerner** [onsi/ginkgo#703]
The [go module installation section](https://github.com/onsi/ginkgo#go-module-tools-package) on how to install the ginkgo cli using tools.go seems to be wrong. It says to install the tool by adding tools/tools.go with the following: 
```go
// +build tools

package tools

import (
	_ "github.com/onsi/ginkgo"
)
```

However when I then try to run tests using go run I get the following error: 
```
> go run github.com/onsi/ginkgo/ginkgo                         
package github.com/onsi/ginkgo/ginkgo: cannot find package "." in:
        /Users/conferencemac/Code/go/predictions-service/vendor/github.com/onsi/ginkgo/ginkgo
```

It works if I instead import the full path: 
```go
// +build tools

package tools

import (
	_ "github.com/onsi/ginkgo/ginkgo"
)
```

**Comment by blgm** [comment]
You're absolutely correct @NilsJPWerner. I'll fix that.
