### ISSUE TITLE
Build ginkgo binary from a specific tag

### ISSUE THREAD

**Issue by amitkrout** [onsi/ginkgo#707]
I am looking for building the ```ginkgo``` binary for a specific tag. Actually ```go get -u github.com/onsi/ginkgo/ginkgo``` give me the latest version which needs a consistent monitor for me to update the ```glide.yaml``` and ```glide.lock``` time to time.

I could not find any related doc reference on how to build ginko from a specific tag.

NOTE: I am using go 1.13.* and glide package manager.

**Comment by amitkrout** [comment]
probably this could be helpful - http://phylo.bio.ku.edu/ginkgo/installing.html#ginkgo-from-source

**Comment by amitkrout** [comment]
Can you folks address this please ?

**Comment by blgm** [comment]
Hi @amitkrout, to `go get` a specific tag you can run `go get github.com/onsi/ginkgo@<tag>`

Does that answer your question?

**Comment by amitkrout** [comment]
@blgm It does not work because my project dos not use go mod package management. 
```
$ go get github.com/onsi/ginkgo@1.12.0
go: cannot use path@version syntax in GOPATH mode
```
The new feature in go version ```1.4.*``` can fetch the specific tag version like ```go get github.com/onsi/ginkgo@<tag>``` but my environment comprises go version ```1.13.*```. I am not sure how can i build the specific ginkgo binary with such env having glide package manager and go version ```1.13.*```.

Question: How you are building ginkgo binary ? may be i will follow the same step and build the binary until we move to go mod package management or go version 1.14.*

**Comment by blgm** [comment]
I guess you could `git checkout` to select the tag, for example:
```bash
pushd $GOPATH/src/github.com/onsi/ginkgo
  git checkout v1.13.0
  go install github.com/onsi/ginkgo/ginkgo
popd
```

The way that I fix the version of Ginkgo on projects that I work on is to [use a tools.go file](https://github.com/onsi/ginkgo#go-module-tools-package), but I think that only works with Go modules.

**Comment by amitkrout** [comment]
Thanks!!!
