### ISSUE TITLE
Multiple test files resulting in interluding of test execution and resulting in flaky tests and incorrect spec count

### ISSUE THREAD

**Issue by puppet-py** [onsi/ginkgo#708]
`Ginkgo version:` The issues is seen in both 1.10 and 1.14

`Scenario:` There are multiple tests files(_test) in the `pkg` dir. Each test file has one or more containers of tests(multiple `Describe`s and their `It`s OR single `Describe` with multiple `It`s. Gingko/Gomega native funcs and matchers are defined/imported in one of the `uats_T38136_test.go` file while the other `_test.go` resolves those references from the `uats_T38136_test.go` <<< Mentioning the file name as is if it helps to correlate with the attached log

`Observations:`
1. As per log (`ginko -v` OR `go test`)many tests from one testsuite seen to be repeatedly executed during the run of another testsuite. This is what I meant interluding
2. As per the log, sometimes some of the test of one testsuite is just not executed during the run of that testsuite but is getting executed in another testsuite. 
3. Although the tests are all containerized, flaky tests are seen which logs this error `You may only call It from within a Describe, Context or When`

`Impact`: 
1. Incorrect count of spec and thereby cannot be the source of truth
2. Since these tests are interluded and often repeated, it increases the test execution time unnecessarily

Attached is the test run log. Request you to search this string `<<<< Mycomments`
[log.txt](https://github.com/onsi/ginkgo/files/5037415/log.txt)

**Comment by onsi** [comment]
@puppet-py can you point me at a sample repo that reproduces this behavior?  in ginkgo there is a 1:1 mapping between packages and test suites.  all the _test.go files in a given package are part of that package's one suite.  You should only call `RunSpecs` once in a single bootstrap file per package.

**Comment by puppet-py** [comment]
@onsi You can find the files here >> https://github.com/puppet-py/ginkgoTest (files of interest have their names starting with `uat_*`)

From your above comment, I believe I am going wrong in my test structure.
However, I would still request you to take a look at the above sample repo which is consistently reproducing this behavior. Looking forward to your inputs

**Comment by onsi** [comment]
Thanks for the code.  You are, indeed, calling `RunSpecs` multiple times in a few different `TestX` functions.  It may be that Ginkgo's documentation ([here](http://onsi.github.io/ginkgo/)) is not clear enough.  You should only have **one** `TestX` function that calls `RunSpecs` for a given Go package.  You can have multiple `_test` files with as many `Describe`s, `Context`s, and `It`s etc... as you like - they will all be run and managed by that single `RunSpec` call (FWIW this is consistent with how `go test` works - a single package is considered a single suite).

As the [documentation](http://onsi.github.io/ginkgo/#getting-started-writing-your-first-test) describes it is common to have a single bootstrap file (which you can generate with `ginkgo bootstrap`) that includes the `RunSpec` call alongside multiple `test` files (which you can generate with `ginkgo generate`) that simply define tests using Ginkgo's DSL.  In the case of the repo you pointed me at, I would recommend running `ginkgo bootstrap` to generate the one bootstrap file and then removing all the `TestX` functions that call `RunSpecs`.

It's a bit dense but you might also want to read the [Ginkgo's Lifecycle](http://onsi.github.io/ginkgo/#understanding-ginkgos-lifecycle) part of the documentation as it discusses the test lifecycle in more depth, including information about test tables.

**Comment by puppet-py** [comment]
@onsi Thanks much !!
