### ISSUE TITLE
Timeout types should always be time.Duration

### ISSUE THREAD

**Issue by Evertras** [onsi/ginkgo#710]
The timeout for asynchronous tests is described as float64, which requires that I check documentation to see what unit it expects.  This creates a lot of confusion and doesn't reuse the much more friendly `time.Duration` which is used everywhere else.

For a non-breaking change, changing the parameter name to `timeoutSeconds` would be a great help in reducing confusion.

**Comment by blgm** [comment]
Hi @Evertras, the recommended way to do asynchronous testing is to use `gomega.Eventually()`: http://onsi.github.io/gomega/#eventually

Timeouts for `Eventually()` behave as you describe:
> These can be passed in as time.Durations, string representations of a time.Duration (e.g. "2s") or float64 values (in which case they are interpreted as seconds).

The style of asynchronous testing in Ginkgo using a `Done` channel has proved quite problematic (issues with leaking Goroutines and wrong tests being marked as failed), so it is no longer under active development, and may be removed in a future version of Ginkgo.

Should you wish to, you can convert existing tests using something like this:
```go
It("does something asynchronous", func() {
	done := make(chan interface{}, 0)
	go func() {
	    c := make(chan string, 0)

	    go DoSomething(c)
	    Expect(<-c).To(ContainSubstring("Done!"))

	    close(done)
	}()

	Eventually(done).Should(BeClosed(), 0.2)
})
```
