### ISSUE TITLE
`-skipPackage` has to be ahead of `-r package` to take effect

### ISSUE THREAD

**Issue by zzxwill** [onsi/ginkgo#715]
`ginkgo -v -r e2e -skipPackage apiserver,setup` will NOT skip package `apiserver` and `setup` while `ginkgo -v -skipPackage setup,apiserver -r e2e` could.

The placement of `-skipPackage` and `-r` should not affect the package skipping funciton.

**Comment by onsi** [comment]
i appreciate this behavior is annoying/surprising but i don't want to add complexity to flag parsing as this seems to be a limitation of the go flags package.
