### ISSUE TITLE
Request: make the output greppable

### ISSUE THREAD

**Issue by fasaxc** [onsi/ginkgo#718]
If you have a test the logs a lot then it can be very hard to find the messages from ginkgo because they are multi-line with lots of formatting characters that defeat simple regexes.  I know that Ginkgo is focussed on smaller tests but it has been used for end-to-end tests in some large projects (such as Kubernetes) and they can last minutes and log thousands of lines of output.

In verbose mode, how about emitting some logs explicitly for grepping?  We've found it useful to add logs like this in strategic BeforeEach and AfterEach blocks, but it's not a great solution because we have to arrange to do it for every package (and some of the tests we run come from external projects, making it impossible).
```
TEST-STARTING <full name of test>
TEST-RESULT PASS <full name of test>
TEST-RESULT FAIL <full-name of test>
TEST-TEARDOWN-START <full name of test>
TEST-TEARDOWN-END <full name of test>
```

**Comment by onsi** [comment]
I'm adding support for a JSON-formatted report in v2.  Perhaps that can help with this use case (browsing structured data or leveraging tooling like `jq`)?  I'd prefer not to pollute the test output with grew-able logs by default.

The other thing to try is `-v --progress` - that will emit some consistently formatted stuff around each test component.
