### ISSUE TITLE
Request: IDE Integration and running a single test?

### ISSUE THREAD

**Issue by victor-cui-discovery** [onsi/ginkgo#719]
With the testify package it's possible to run an individual test inside an IDE and on the command line using `go test -run`. Could ginkgo add IDE integration in order to run a specific test spec (within an `It` block), and is it possible to run a specific test spec on the command line?

I've attached a screenshot of the way Visual Studio integrates with the testify package below.

![image](https://user-images.githubusercontent.com/68564381/93388767-35f08180-f839-11ea-9829-0f35fb3f17da.png)

**Comment by HagaiBarel** [comment]
If you're using `vscode`, check out https://marketplace.visualstudio.com/items?itemName=joselitofilho.ginkgotestexplorer, it's a pretty new extension but I have been working with it for a while now and it works great
