### ISSUE TITLE
Getting error while installing ginkgo

### ISSUE THREAD

**Issue by somprabhsharma** [onsi/ginkgo#723]
Getting below error while using `go get -u -v github.com/onsi/ginkgo/ginkgo` command.

`../../onsi/ginkgo/ginkgo/generate_command.go:244:9: undefined: strings.ReplaceAll`

**Comment by blgm** [comment]
Hi @somprabhsharma, which version of Go are you using? `strings.ReplaceAll` is part of the [Go standard library](https://golang.org/pkg/strings/#ReplaceAll), so it might be fixed by using a more recent version of Go. The current supported versions of Go are 1.14 and 1.15.
