### ISSUE TITLE
Missing -ginkgo.randomizeSuites flag?

### ISSUE THREAD

**Issue by dylankb** [onsi/ginkgo#729]
This [part](
https://onsi.github.io/ginkgo/#spec-permutation) of the documentation notes that there are `--seed=SEED` and `--randomizeSuites` flags for the `ginkgo` binary. However if you are using `go test` rather than `ginkgo` to run your tests, there is a `-ginkgo.seed` flag but not a `-ginkgo.randomizeSuites` flag like I'd expect.

Why can you set a seed to randomize on your suites but there's no flag to actually use the randomization? Apologies if I'm missing anything - thanks!

I'm using ginkgo version 1.14.1 and the 1.14.2 update doesn't look like made any changes in this area.

**Comment by dylankb** [comment]
I actually have a similar question re: the `-race` flag and the apparent absence of `-ginkgo.race`.

**Comment by onsi** [comment]
sorry for the delay here.  when you run multiple test suites with the `ginkgo` cli (e.g. `ginkgo -r` or `ginkgo /path/to/suite1 /path/to/suite2 ...`) the `ginkgo` cli figures out which suites are going to run and decides what order to run them in.  it then (under the hood) calls `go test` for each one.  So the `--randomizeSuites` flag is only attached to the `ginkgo` cli as only the cli manages the suite order, not the ginkgo library (as opposed to `seed`, which informs both the cli and the library).

does that make sense?

**Comment by dylankb** [comment]
Got it, thanks for the explanation! My issue was actually trying to figure out how to use these flags with a test binary built via ginkgo, but then I found the [relevant area](https://onsi.github.io/ginkgo/#spec-permutation#precompiling-tests) documentation.

**Comment by dylankb** [comment]
Actually, I have a follow up question. Are there any plans to supply a flag for `ginkgo build` to randomize the suites when compiling the test binary?

>I actually have a similar question re: the -race flag and the apparent absence of -ginkgo.race.

I also answered by own question here when I figured out `-race` was a supported flag under `ginkgo build`.

**Comment by onsi** [comment]
No - the randomization behaviors are configured and happen at runtime.

**Comment by onsi** [comment]
Out of curiosity- what are the reasons you're using `go test` instead of `ginkgo`?

**Comment by dylankb** [comment]
For CI we typically build binaries to run in containers if there are external dependencies, so that's probably why we reached for building the precompiled `package.test` binary for running our integration tests. Initially it also seemed like running the tests via `package.test` provided all the options that the `ginkgo` CLI did - it's not quite obvious to me at least from the docs [here](https://onsi.github.io/ginkgo/#precompiling-tests) that there was much of a difference.

I suppose we could switch to just copying over source code into the container and just using the `ginkgo` CLI, but the `package.test` binary actually seems to provide all the `ginkgo` CLI testing options we're interested in (`--trace`, `--race`, and `--randomizeAllSpecs`) except for `--randomizeSuites`.

**Comment by dylankb** [comment]
Also, thanks for the response :)

**Comment by onsi** [comment]
Sure thing - the usecase definitely makes sense.  fwiw you can point the
ginkgo cli binary at a precompiled test and get all the functionality of
the cli (parallelization, randomization, etc) and the utility/consistency
of precompiled tests.

**Comment by dylankb** [comment]
Ah, good to know. I saw that `ginkgo -p package.test` worked from the docs, but I assumed you didn't get most CLI functionality by pointing `ginkgo` a package.test since `ginkgo --race package.test` didn't seem to work (you needed to use `-race` flag in the build). Tested with `ginkgo --randomizeAllSpecs package.test` and that does seems to work. Good to know and thanks again!
