### ISSUE TITLE
How to run tests in a specific order?

### ISSUE THREAD

**Issue by songleo** [onsi/ginkgo#730]
I use ginkgo to write some test, including: 

- books_suite_test.go
- install_test.go
- reading_test.go
- isbn_test.go
- uninstall_test.go

how to run these tests in a specific order as following:

`install_test.go -> reading_test.go -> isbn_test.go -> uninstall_test.go`

I found ginkgo can not ensure the test order. Is there any way to do this?

**Comment by onsi** [comment]
hey @songleo - what's the underlying problem you are trying to solve by specifying test order?  Ginkgo's opinion is that individual tests should be wholly independent so that test randomization and parallelization are possible- this in turn enables a reduction in test flakiness and an increase in test speed.

**Comment by songleo** [comment]
Yes, I see what you mean. But if you can't ensure the test order. Test cases can go wrong, such as when I run an uninstalled test case without installing it. we need to split the test case by feature or module. This makes it easier to maintain and add tests.

**Comment by onsi** [comment]
@songleo Ginkgo has ways to handle all of this - often I find that once you get a mental model for how Ginkgo's structures it's tests and how the test runner works you're able to accomplish complex test setups quite elegantly.  If you have an example you could share or point me to I'd be happy to show you how this works (see, for example, the conversation at #731 ).  I also recommend reassign through the [docs](http://onsi.github.io/ginkgo/#structuring-your-specs)

**Comment by songleo** [comment]
@onsi thanks for your detailed answers. here is my example, my test file as following:

## test suite
- books_suite_test.go
```golang
package books_test

import (
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

func TestBooks(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Books Suite")
}

```
## test spec
- install_test.go
```golang
package books_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("install:", func() {
	Context("", func() {
		It("case1", func() {
			Expect(nil).NotTo(HaveOccurred())
		})
	})
})

```
- read_test.go
```golang
package books_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("read:", func() {
	Context("", func() {
		It("case2", func() {
			Expect(nil).NotTo(HaveOccurred())
		})
	})
})

```
- isbn_test.go
```golang
package books_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("isbn:", func() {
	Context("", func() {
		It("case3", func() {
			Expect(nil).NotTo(HaveOccurred())
		})
	})
})

```
- uninstall_test.go
```golang
package books_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("uninstall:", func() {
	Context("", func() {
		It("case4", func() {
			Expect(nil).NotTo(HaveOccurred())
		})
	})
})

```

when I run my test twice: 

```bash
ssli@order-demo(master)$ ginkgo -v
Running Suite: Books Suite
==========================
Random Seed: 1604045666
Will run 4 of 4 specs

uninstall:
  case4
  /Users/ssli/share/git/go_practice/ginkgo-demo/order-demo/uninstall_test.go:10
•
------------------------------
read:
  case2
  /Users/ssli/share/git/go_practice/ginkgo-demo/order-demo/read_test.go:10
•
------------------------------
install:
  case1
  /Users/ssli/share/git/go_practice/ginkgo-demo/order-demo/install_test.go:10
•
------------------------------
isbn:
  case3
  /Users/ssli/share/git/go_practice/ginkgo-demo/order-demo/isbn_test.go:10
•
Ran 4 of 4 Specs in 0.000 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 1.563022387s
Test Suite Passed
ssli@order-demo(master)$ ginkgo -v
Running Suite: Books Suite
==========================
Random Seed: 1604045673
Will run 4 of 4 specs

isbn:
  case3
  /Users/ssli/share/git/go_practice/ginkgo-demo/order-demo/isbn_test.go:10
•
------------------------------
uninstall:
  case4
  /Users/ssli/share/git/go_practice/ginkgo-demo/order-demo/uninstall_test.go:10
•
------------------------------
install:
  case1
  /Users/ssli/share/git/go_practice/ginkgo-demo/order-demo/install_test.go:10
•
------------------------------
read:
  case2
  /Users/ssli/share/git/go_practice/ginkgo-demo/order-demo/read_test.go:10
•
Ran 4 of 4 Specs in 0.000 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 1.039894448s
Test Suite Passed
```

I get 2 orders:

- case4 -> case2 -> case1 -> case3
- case3 -> case4 -> case1 -> case2

I hope my test run in the following order:

- case1 -> case2 -> case3 -> case4

we need to split the test case by feature or module. This makes it easier to maintain and add tests. so I'll have multiple test files(install_test.go/read_test.go/isbn_test.go/uninstall_test.go). and I hope the test file run as following roder:

- install_test.go -> read_test.go -> isbn_test.go -> uninstall_test.go

i want help : (
how could i do it in ginkgo?

**Comment by onsi** [comment]
hey @songleo your example is fairly generic and I'm still not understanding the underlying problem you are trying to solve.  In general, Ginkgo encourages you to design your tests such that they are order independent.  Again the [docs](http://onsi.github.io/ginkgo/#structuring-your-specs) and recent example at #731 should help.

Without more information it's hard to give you a truly helpful answer, but often times what you're trying to accomplish would probably end up looking like this:

```go
var _ = Describe("The Behavior of Module A", func() {
	BeforeEach(func() {
		//do the work to set up the module    
		//e.g. this may be where you do your "install" stuff
	})

	AfterEach(func() {
	    //do the work of cleaning up the module
		//e.g. this may be where you do your "uninstall" stuff
	})

	Describe("The behavior of feature A", func() {
		It("Does sometihing...", func() {
			Expect(...).To(...)
		})

		It("Does something else...", func() {
			Expect(...).To(...)
		})
	})
})
```

Again without a more specific example of what you are trying to do I don't think I can offer more help.  Do you have a code base you can point me at so I can better understand what you're trying to do?

**Comment by songleo** [comment]
@onsi thanks for your help.

**Comment by AdarshdeepCheema** [comment]
Im having the same issue:
as described here https://github.com/onsi/ginkgo/issues/730#issuecomment-719408543
I always want my tests to run in order `install_test.go -> reading_test.go -> isbn_test.go -> uninstall_test.go`,
but https://github.com/onsi/ginkgo/issues/731 is not very helpful
@onsi Can u please explain in more details
