### ISSUE TITLE
How to organize the executing ordering of test-cases ?

### ISSUE THREAD

**Issue by bytesmaker** [onsi/ginkgo#731]
![image](https://user-images.githubusercontent.com/67078837/97506186-4efe5d80-19b5-11eb-9c1e-a0d5cfc79241.png)
![image](https://user-images.githubusercontent.com/67078837/97506983-2d9e7100-19b7-11eb-9a54-5212133e30b8.png)

As you see, there is one Describe block contains two When blocks. but if I should run it, the second When block would be invoked before the first When block. It is not my hope. Because I thought the When block should not be independent in semantic. We always say do A when B, and resulted in R(B). If I should conquer the B, I could do A when C, and resulted in R(E)... But the design that each test block is independent can not achieve that as I said.

I want help : (
HOW COULD I DO IT IN GINKGO?

**Comment by onsi** [comment]
Hey @bytesmaker you shouldn't need to worry about your test order and you can use Ginkgo's setup/teardown nodes to accomplish what you're doing.  I recommend reading the [documentation](http://onsi.github.io/ginkgo/#structuring-your-specs) to learn more.  For your specific example, here's how you could do it:

```go
var _ = Describe("Players in Rooms", func() {
	var room Room
	var player Player

	BeforeEach(func() {
		var err error
		room, err = NewRoom()
		Expect(err).NotTo(HaveOccurred())

		player, err = NewPlayer()
		Expect(err).NotTo(HaveOccurred())
	})

	When("the player has not joined the room", func() {
		It("should not have the player", func() {
			Expect(room.Has(player.ID())).To(BeFalse())
		})
	})

	When("the player has joined the room", func() {
		BeforeEach(func() {
			err := room.Join(player)
			Expect(err).NotTo(HaveOccurred())
		})

		It("should now have the player", func() {
			Expect(room.Has(player.ID())).To(BeTrue())
		})

		Describe("finding players", func() {
			It("should succesffuly find players who have joined", func() {
				foundPlayer, err := room.Find(player.ID())

				Expect(err).NotTo(HaveOccurred())
				Expect(foundPlayer).To(Equal(player))
			})
		})
	})
})
```

These tests are completely independent,  have cleanly shared setup with no possibility of test pollution, and are reusing setup.

Note that this is one way to do this. You'll sometimes see differing styles in Ginkgo codebases but the basic idea is usually the same.
