### ISSUE TITLE
Please add Context global BeforeAll/AfterAll 

### ISSUE THREAD

**Issue by thallgren** [onsi/ginkgo#738]
The lack of `BeforeAll()` and `AfterAll()` forces any tests that must have common environment prerequisites to live in a package of its own because the `BeforeSuite()` and `AfterSuite()` are package global. This is an unnecessary and annoying limitation in an otherwise excellent test framework.

I have plenty of examples of where I want a `Context()` to have its own environment setup. It can be setting up and tearing down a database, database tables, or table content, modifying a kubernetes cluster, docker images, a daemon process, etc. The time to set up and tear down such environments ranges from a second to a minute. Moving every such context into a suite (and hence a directory) of its own is not an option because the contexts often reflect different aspects of one and the same test subject, or its undesirable to export the functions that are tested.

At present, the global `BeforeSuite()` and `AfterSuite()` limits randomizing specs to one package at a time. That's nice of course, but why can't that limit just as well be on a `Context()` if the user so desires? In my case it would vouch for a much better organization of the specs.

I see that implementations start to pop up that provides `BeforeAll()` and `AfterAll()` such as this [Ciliums e2e testing](https://docs.cilium.io/en/v1.8/contributing/testing/e2e/#ginkgo-extensions). Wouldn't it be nicer to have ginkgo provide this?

Also see #70 for more discussion around this.

**Comment by williammartin** [comment]
Hi @thallgren,

**Comment by thallgren** [comment]
Hi @williammartin . Yes, the `OrderedContext` looks like a great solution. It provides exactly what I'm after.

**Comment by thallgren** [comment]
The "Rough Timeline" in the document suggests a 2.0 release sometime in November/December. Does that hold still? It's unclear to me where the current 2.0 work takes place. What can I do to contribute?

**Comment by williammartin** [comment]
@onsi for updates on this, as he is doing the actual v2 work and I'm hardly involved at all anymore :)

**Comment by onsi** [comment]
Because of covid and schools shutting down I've not had as much focused time to dedicate to Ginkgo as I'd originally planned.  Nov/Dec doesn't seem viable right now but - as with all things 2020 - that could change.

The work is happening on a branch but there's not much to show yet.  Thanks for the offer to help - at this point I'm wanting to do some much needed clean up (which is kind of the point of bumping the major version) which feels to me like a blocker before others can contribute... but if I'm still the bottleneck in a few months I may have to change tack and ask for help!

**Comment by onsi** [comment]
[V2](#711) is under active development now and I've got more consistent time to put towards it these days - I hope to get to this particular feature in the next month or two and to ship the whole thing in June/July.

**Comment by onsi** [comment]
The V2 beta shipped last week and includes support for `BeforeAll` and `AfterAll` in contexts that are marked as `Ordered`.  Docs for using the beta are [here](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta) and the docs for `Ordered` are [here](https://github.com/onsi/ginkgo/blob/ver2/docs/index.md#ordered-containers).
