### ISSUE TITLE
Request: print timestamps before and after each `It` block.

### ISSUE THREAD

**Issue by masa213f** [onsi/ginkgo#739]
I want to print timestamps before and after each `It` block.
Is it possible to add an option to Ginkgo?

I think the printing timestamps feature is useful to debug the target program.
The feature makes it easy to compare the ginkgo's result with the log of the target program.

I know, I can realize it by using `BeforeEach` and `AfterEach`, but it’s redundant to set to my all repository and (complicated) test.

P.S. Thanks for this great project. My team uses Ginkgo and Gomega a lot!

**Comment by onsi** [comment]
Hey @masa213f - sorry for the delay in getting back to you.  I don't have plans to add time stamps throughout the output and would recommend decorating tests with timestamp output as needed.
