### ISSUE TITLE
Call Measure from within a Describe, Context or When

### ISSUE THREAD

**Issue by SamYuan1990** [onsi/ginkgo#741]
I have a multi threads code block.
As consumers and producers, 
data from one producers -> into n channel and consumed by multi consumers.
to keep threads safety, I have look inside data structure{}

then, I want to Call Measure in Describe table.
I want to verify for 1,2,3,4,7,11 ... concurrents, the code block running effective enough, as it can be completed with in a time duration.

to avoid copy & paste myself, I want the test case can be written as:
```
DescribeTable('xxxx',func(concurrents int, timelimit float){
Measure(){
// code block here
}
}, 
Entry(1,0.001),
Entry(2,0.001),
Entry(3,0.002),
....
Entry(11,0.002)
```

**Comment by onsi** [comment]
I'm planning on moving `Measure` out of Ginkgo and into Gomega as a separate Gomega package.  That will make it possible to do this sort of thing.

**Comment by onsi** [comment]
Take a look at the new [gomega/gmeasure](https://github.com/onsi/gomega/tree/master/gmeasure) package.

**Comment by SamYuan1990** [comment]
Will take a look later.
