### ISSUE TITLE
Empty test suite beforesuite / aftersuite does not need to be executed

### ISSUE THREAD

**Issue by chenpfeisoo** [onsi/ginkgo#744]
Ginkgo - R -- focus "lable" when executing a case through a label, if a test suite does not have a selected case beforesuite / aftersuite, it will still be executed. This is not desired, and the test time will be increased

**Comment by onsi** [comment]
That's a good call out - I'll need to look into how feasible this will be to remedy and have added it to the 2.0 roadmap.

**Comment by onsi** [comment]
This is fixed in [v2](#711)

**Comment by chenpfeisoo** [comment]
When will V2 be released？

**Comment by onsi** [comment]
I'm hoping around June/July

**Comment by onsi** [comment]
The V2 beta includes this change.  Docs for using the beta are [here](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta).
