### ISSUE TITLE
Failed to compile integration

### ISSUE THREAD

**Issue by rnapoles-rh** [onsi/ginkgo#746]
I get Failed to compile integration right after trying to execute a test suite:

```
ginkgo .\tests\integration\
Failed to compile integration:
# github.com/onsi/ginkgo
vet.exe: decoding facts for "github.com/onsi/ginkgo/internal/remote": EOF
FAIL
Ginkgo ran 1 suite in 16.956306s
Test Suite Failed
```

OS: Windows 10

**Comment by blgm** [comment]
Does `go test` work?

**Comment by joselitofilho** [comment]
@rnapoles-rh
are you using git-lfs? If yes, consider executing the `git lfs pull` before.

**Comment by rnapoles-rh** [comment]
suddenly things started working
