### ISSUE TITLE
Need more info to be written into report when panic in BeforeSuite

### ISSUE THREAD

**Issue by JiaYongfei** [onsi/ginkgo#764]
panic in BeforeSuite didn't write ForwardedPanic into report. It's better we dump the same info as we did in each Spec.
Related code to build the failure message for Spec:
`if specSummary.State == types.SpecStatePanicked {
			testCase.FailureMessage.Message += fmt.Sprintf("\n\nPanic: %s\n\nFull stack:\n%s",
				specSummary.Failure.ForwardedPanic,
				specSummary.Failure.Location.FullStackTrace)
		}`

**Comment by onsi** [comment]
This is fixed in [v2](#711)

**Comment by onsi** [comment]
V2 is beta and should now solve for this use case.  Docs for using the beta are [here](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta).
