### ISSUE TITLE
CPU Profiling/pprof for the underlying test

### ISSUE THREAD

**Issue by angadn** [onsi/ginkgo#766]
**Replication**

* `ginkgo -cpuprofile file.prof`
* `ginkgo -- cpuprofile file.prof`

Both seem to be ignored/don't generate the file needed for `pprof`. It seems like the flag is ignored. Am I missing something? 🤔 

**Workaround**

* `go test -cpuprofile file.prof`

**Comment by onsi** [comment]
hmm - definitely looks like a legit bug, thanks for sharing @angadn.  Ginkgo is passing `cpuprofile` in at build time when it compiles the test using `go test -c` but not at runtime when it actually invokes the test.  in fact, none of the go flags are passed in at runtime which is likely a problem for at lest a few of them.  i'll need to dig into it.

**Comment by joselitofilho** [comment]
@onsi 
Do you know whether someone works on that? if not, let me know if you'd like me to make this fix.

**Comment by onsi** [comment]
i’m working on this, yes.  it’ll be a few more weeks still as i’m doing it as part of the v2 work

**Comment by onsi** [comment]
this is now fixed on the v2 branch

**Comment by angadn** [comment]
Awesome. Thank you so much @onsi!

**Comment by joselitofilho** [comment]
Very good @onsi. I will test it and implement a new feature on the plugin to show coverage of the code using the Ginkgo executable.

**Comment by onsi** [comment]
Thanks y'all.  @joselitofilho in case you're interested the json formatted report is also available on the v2 branch if you run with `--json-report=...`
