### ISSUE TITLE
Ginkgo doesn't generate the cover profile file when running inside a Docker container

### ISSUE THREAD

**Issue by the-gigi** [onsi/ginkgo#767]
I run ginkgo in a docker container built using the following Dockerfile:

```
FROM golang

WORKDIR /

RUN apt-get update && apt-get install -y vim

RUN go get -u github.com/onsi/ginkgo/ginkgo && \
    go get -u github.com/onsi/gomega/... && \
    go get -u github.com/blang/semver && \
    go get -u github.com/mitchellh/go-homedir && \
    go get -u github.com/spf13/cobra && \
    go get -u github.com/spf13/viper
```

I can run ginkgo tests just fine. When I run `ginkgo -cover` I see the coverage results, but no coverage profile file is generated. I tried explicitly passing `ginkgo -coverprofile=coverage.out` without success. The tests pass I see the coverage number, but not profile file. Also, tried with absolute path: `ginkgo -coverprofile=/tmp/coverage.out`.

I have write permissions to the current directory (some of my tests write files successfully too).

If I run ginkgo locally the coverage profile file is generated successfully.

**Comment by onsi** [comment]
hey @the-gigi not sure why this would be happening.  Does `go test -coverprofile=coverage.out` work in the docker container?

**Comment by onsi** [comment]
Closing this out for now - please reopen if you'd like.
