### ISSUE TITLE
Proposal: Use VS Code Extension for Ginkgo

### ISSUE THREAD

**Issue by joselitofilho** [onsi/ginkgo#773]
I have been working on a visual studio code extension to provide support for the Ginkgo framework. You can view the test tree, run them individually or run the entire suite. For more information visit [here](https://github.com/joselitofilho/ginkgoTestExplorer).

![Ginkgo Test Explorer](https://github.com/joselitofilho/ginkgoTestExplorer/raw/main/media/ginkgotest.gif)

What do you think about spreading it to the Ginkgo community, @onsi?

**Comment by onsi** [comment]
This is cool!  neat to see you building off of @dlipovetsky's work so quickly :)

I think it would be great to advertise this with the community.  I think the simplest thing would be to add a new Tools and Integrations section to the readme and advertise this and [vscode-ginkgo-tools](https://github.com/dlipovetsky/vscode-ginkgo-tools) there.  Any other thoughts?

**Comment by onsi** [comment]
oh also - i'm curious.. you mentioned:
> run them individually or run the entire suite

 how do you tell ginkgo which individual tests to run?  do you apply an `Fit` focus?  or some other approach?

**Comment by joselitofilho** [comment]
> how do you tell ginkgo which individual tests to run? do you apply an `Fit` focus? or some other approach?

I've been using the ginkgo's `-focus` flag, for example:
```go
var _ = Describe("Example", func() {
	It("works", func() {})
})
```
```bash
ginkgo -focus "Example works" -reportFile report.xml 
```

**Comment by joselitofilho** [comment]
> I think it would be great to advertise this with the community. I think the simplest thing would be to add a new Tools and Integrations section to the readme and advertise this and [vscode-ginkgo-tools](https://github.com/dlipovetsky/vscode-ginkgo-tools) there. Any other thoughts?

I agree with you. I thought the same thing. Do ginkgo have any slack channel?
If yes, we could advertise there as well.

**Comment by onsi** [comment]
There is one over in the gophers slack instance - it's not super big
though.  I'll update the main readme in the next few days.
