### ISSUE TITLE
How ginkgo ends the test actively

### ISSUE THREAD

**Issue by chenpfeisoo** [onsi/ginkgo#778]
How ginkgo ends the test actively？

When I encounter a failure case, I want the test to stop and locate the problem in the existing environment. How can I stop ginkgo

**Comment by blgm** [comment]
```
ginkgo -h
...
-failFast
    	If set, ginkgo will stop running a test suite after a failure occurs.
```

If you're not running in parallel, and you have a single suite then this might be what you're looking for.

**Comment by chenpfeisoo** [comment]
Great. That's it. Thank you @blgm
