### ISSUE TITLE
SynchronizedAfterSuite Stucked

### ISSUE THREAD

**Issue by richard667** [onsi/ginkgo#781]
Hi，I wrote a SynchronizedAfterSuite  like this: 
```
var _ = ginkgo.SynchronizedAfterSuite(func() {
	klog.Info("Running afterSuite actions on all nodes")
}, func() {
	klog.Info("Running afterSuite actions on node 1")
})
```
and run ginkgo command like this `ginkgo --  --ginkgo.parallel.total=2 -ginkgo.focus=time`，but the test stuck at end.
![image](https://user-images.githubusercontent.com/38872395/111313793-b898b300-869b-11eb-9bf3-5fa59b16e244.png).

It seems that this function is in dead look, 
```
func (node *synchronizedAfterSuiteNode) waitUntilOtherNodesAreDone(syncHost string) {
	for {
		if node.canRun(syncHost) {
			return
		}

		time.Sleep(50 * time.Millisecond)
	}
}
```
```

func (node *synchronizedAfterSuiteNode) canRun(syncHost string) bool {
	resp, err := http.Get(syncHost + "/RemoteAfterSuiteData")
	if err != nil || resp.StatusCode != http.StatusOK {
		return false
	}

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return false
	}
	resp.Body.Close()

	afterSuiteData := types.RemoteAfterSuiteData{}
	err = json.Unmarshal(body, &afterSuiteData)
	if err != nil {
		return false
	}

	return afterSuiteData.CanRun
}
```
I am confused on how to use SynchronizedAfterSuite. Why we send a get request to `syncHost`, should I setup a server on my host?

**Comment by richard667** [comment]
And when I set `--ginkgo.parallel.total=2`, then only half of my cases runs on my host. Does this parameter means I need two hosts to run all cases?

**Comment by onsi** [comment]
You must use the ginkgo cli to support parallel tests.  try `ginkgo -p`

**Comment by onsi** [comment]
also the docs explain how parallel tests work in ginkgo with more detail:

http://onsi.github.io/ginkgo/#parallel-specs

**Comment by richard667** [comment]
I have tried `ginkgo -p`, but it doesn't take effect, and other flags like `ginkgo -focus` also don't take effect. If I want to foucs on part of cases, I have to use `ginkgo -- -ginkgo.focus xxx`. `ginkgo -- --help` command returns flags same as https://github.com/onsi/ginkgo/issues/634. 
It seems only this flag can help me run specs in parallel.
```-ginkgo.parallel.total int
        The total number of worker nodes.  For running specs in parallel. (default 1)
```
so do you have any suggestion on how to use this flag? Or any idea of why `ginkgo -p` don't take effect?

**Comment by onsi** [comment]
that’s all quite strange and not something i’ve ever seen before.  any chance you could send me a link to your code so i can take a look?

**Comment by richard667** [comment]
> that’s all quite strange and not something i’ve ever seen before. any chance you could send me a link to your code so i can take a look?
> […](#)
> On Mar 16, 2021, at 8:22 PM, Liuqing Liao ***@***.***> wrote: ﻿ I have tried ginkgo -p, but it doesn't take effect, and other flags like ginkgo -focus also don't take effect. If I want to foucs on part of cases, I have to use ginkgo -- -ginkgo.focus xxx. ginkgo -- --help command returns flags same as #634. It seems only this flag can help me run specs in parallel. The total number of worker nodes. For running specs in parallel. (default 1) so do you have any suggestion on how to use this flag? Or any idea of why ginkgo -p don't take effect? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Here is a minimal demo. 
```
├── testtt
│   ├── demo
│   └── demo.go
│   ├── go.mod
│   ├── go.sum
│   ├── my.go
│   ├── my_test.go
```
> demo.go
```
package demo

import (
	"github.com/onsi/ginkgo"
	"time"
)


var _ = ginkgo.Describe("time", func() {
	ginkgo.Context("10s", func() {
		ginkgo.It("1s[only]", func() {
			time.Sleep(time.Second)
		})
		ginkgo.It("1s", func() {
			time.Sleep(time.Second)
		})
		ginkgo.It("1s", func() {
			time.Sleep(time.Second)
		})
		ginkgo.It("1s", func() {
			time.Sleep(time.Second)
		})
		ginkgo.It("1s", func() {
			time.Sleep(time.Second)
		})
		ginkgo.It("1s", func() {
			time.Sleep(time.Second)
		})
		ginkgo.It("1s", func() {
			time.Sleep(time.Second)
		})
		ginkgo.It("1s", func() {
			time.Sleep(time.Second)
		})
		ginkgo.It("1s", func() {
			time.Sleep(time.Second)
		})
	})
})
```
> my_test.go
```
package testtt

import (
	"flag"
	"math/rand"
	"os"
	"testing"
	"time"
	_ "aa/demo"
)

var AvailableRegion string

func RegisterFlags(flags *flag.FlagSet) {
	flags.StringVar(&AvailableRegion, "available-region", "", "The available region for adding node.")
}

func handleFlags() {
	RegisterFlags(flag.CommandLine)
	flag.Parse()
}

func TestMain(m *testing.M) {
	var versionFlag bool
	flag.CommandLine.BoolVar(&versionFlag, "version", false, "Displays version information.")

	// Resister test flags, then parse flags
	handleFlags()

	rand.Seed(time.Now().UnixNano())
	os.Exit(m.Run())
}

func TestE2E(t *testing.T) {
	RunCPSE2ETests(t)
}
```
> my.go
```
package testtt

import (
	"fmt"
	"github.com/onsi/ginkgo"
	"github.com/onsi/gomega"
	"testing"
)

var _ = ginkgo.SynchronizedBeforeSuite(func() []byte {
	setupSuite()
	return nil
}, func(data []byte) {
	// Run on all Ginkgo nodes
	setupSuitePerGinkgoNode()
})

var _ = ginkgo.SynchronizedAfterSuite(func() {
	fmt.Println("Running afterSuite actions on all nodes")
}, func() {
	fmt.Println("Running afterSuite actions on node 1")
})

func RunCPSE2ETests(t *testing.T) {
	gomega.RegisterFailHandler(ginkgo.Fail)
	ginkgo.RunSpecs(t, "my test")
}

func setupSuite() {
	// Run only on Ginkgo node 1
	fmt.Println("Running setupSuite actions on node 1")

}

func setupSuitePerGinkgoNode() {
	fmt.Println("Running setupSuite actions on all nodes")
}
```
With `ginkgo -p` or `ginkgo --focus only`, it will run all 9 cases, and takes over 9 seconds. My pc has 8 core.

With `ginkgo -- -ginkgo.focus only`, then it only run 1 case.

**Comment by onsi** [comment]
hey @richard667 - reproduced this briefly but then could not reproduce it again.  very strange.

here's what i think the issue is: Ginkgo registers its flags in a `func init()`.  This functions needs to be called before flags are parsed.  Which means Ginkgo needs to be imported by the package under test.  With your specific setup, `my_test.go` does not import ginkgo but `my.go` does - however, `my.go` is not in the test package as it is not a `_test.go` file.

I think you an fix this by either moving `my.go` to `foo_test.go` thereby placing it in the test package *or* by adding

`import _ "github.com/onsi/ginkgo"` to `my_test.go`.

Can you try either of those and tell me if `ginkgo -p` starts working again?

**Comment by richard667** [comment]
> hey @richard667 - reproduced this briefly but then could not reproduce it again. very strange.
> 
> here's what i think the issue is: Ginkgo registers its flags in a `func init()`. This functions needs to be called before flags are parsed. Which means Ginkgo needs to be imported by the package under test. With your specific setup, `my_test.go` does not import ginkgo but `my.go` does - however, `my.go` is not in the test package as it is not a `_test.go` file.
> 
> I think you an fix this by either moving `my.go` to `foo_test.go` thereby placing it in the test package _or_ by adding
> 
> `import _ "github.com/onsi/ginkgo"` to `my_test.go`.
> 
> Can you try either of those and tell me if `ginkgo -p` starts working again?

yeah, you are right. Import ginkgo package to my `_test.go` file solved my problem. Thanks.

**Comment by onsi** [comment]
glad it helped!
