### ISSUE TITLE
Preventing Huge Object Dump

### ISSUE THREAD

**Issue by khaf** [onsi/ginkgo#783]
I have an error type that includes an object which when dumped, is close to 200MB in text. Needless to say, I'd really like to control how this object is printed in the terminal when that error occurs. Is there a way to force Ginkgo to format text representation of objects in a custom fashion? (the Stringer interface didn't work).

**Comment by onsi** [comment]
Assuming you're using gomega there is a way to do this yes:

http://onsi.github.io/gomega/#adjusting-output

**Comment by khaf** [comment]
Thanks for your help. Seems I have reported this in the wrong repo. Closing with gratitude.
