### ISSUE TITLE
When the `--focus` flag argument contains metacharacters the test skips.

### ISSUE THREAD

**Issue by joselitofilho** [onsi/ginkgo#786]
Running this focused test with `--focus="should MyMethod() $called"`:

```Go
It("should MyMethod() $called", func() {
    println("MyMethod")
})
```

Output:

```Bash
ginkgo -focus "Testing various flags the focused set --focus flag argument contains metacharacters should MyMethod() $called"

Running Suite: Flags Suite
==========================
Random Seed: 1616239881
Will run 0 of 16 specs

SSSSSSSSSSSSSSSS
Ran 0 of 16 Specs in 0.016 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 16 Skipped
PASS

Ginkgo ran 1 suite in 2.8910226s
Test Suite Passed
```

However, if I running without the `--focus` flag was set it runs.

I've been working on it. Can I open a PR for this?

**Comment by onsi** [comment]
hey @joselitofilho - i appreciate the behavior is a bit confusing, but `--focus` (like `go test -run`) is actually designed to accept a regular expression.  By quoting the metacharacters it becomes no longer possible for users to pass a meaningful regexp to `--focus`.

**Comment by joselitofilho** [comment]
I got it @onsi.
I wonder if we could another flag to accept regex. For example `--focusx`, `--focux` or `--regex-focus`. Something like that. Maybe help newest user.

What do you think?

**Comment by onsi** [comment]
My plan here - with [v2](#711) over the next couple of months - is to introduce labels.  So users can annotate tests with labels and more explicitly control which tests they focus.

I assume your usecase has to do with the viscose plugin?  For now I'd say you should escape the string in the plug-in.  What i'm hoping to do in v2 is offer better support for programmatic interaction with ginkgo.  Two ideas:

1. ability to tell ginkgo to focus on a given source file + line number.

2. ability for ginkgo to emit a json formatted report

**Comment by joselitofilho** [comment]
> My plan here - with v2 over the next couple of months - is to introduce labels. So users can annotate tests with labels and more explicitly control which tests they focus.

That sounds good. 🤓 

> I assume your usecase has to do with the viscose plugin?

Yes, it is. For now, I will recommend not using the metacharacters in the name of cases.

> thoughts on those two ideas?

I appreciate that two ideas. Helps so much. Especially the second.

> 2. ability for ginkgo to emit a json formatted report

Thanks, @onsi. I will close the PR.

**Comment by joselitofilho** [comment]
@onsi 

One more thing. I think the `--focus` behavior should not have the same behavior of `go test -run` in relation to regex. They are slightly different. I mean, the `go test -run` will apply the regex in the name of the test methods, the `--focus` will apply regex in the text (BDD case).

It's just a question to think about. 😃
