### ISSUE TITLE
Support for mixed test suites

### ISSUE THREAD

**Issue by mig4** [onsi/ginkgo#788]
I couldn't find anything mentioned in docs or any previous issues, so this is more of a question rather than a feature request.

Is it possible to have a mixed test suite consisting of both Ginkgo and regular Go [testing](https://golang.org/pkg/testing/) tests, and have them play well together with regards to test ordering? E.g. `BeforeSuite` runs before any `Test*` functions, `AfterSuite` runs after, etc.

What I'm currently seeing is that it appears that all `Test*` functions execute before `BeforeSuite`, and also in directories where I only have Ginkgo's `suite_test.go` with setup and teardown functions and all tests are just regular `Test*` functitons, Ginkgo's output says `Will run 0 of 0 specs`.

Just in case you're wondering, the reason I'm asking is that I'm working with folks mostly used to Go [testing](https://golang.org/pkg/testing/) tests and I'm trying to add some Ginkgo, but trying to avoid pushback I'd get if I tried to convert everything in one go.

**Comment by onsi** [comment]
hey @mig4

unfortunately, no.  ginkgo's lifecycle operates entirely within the confines of the single TestX that launches the test suite via `RunSpecs`

Moreover Ginkgo's support for test randomization and parallelization requires finer control than the go testing framework provides - so to make effective use of those features you'll want to have a separate suite that doesn't mix ginkgo tests with testing tests.

I can't speak to the org/people complexities of introducing Ginkgo/Gomega to your particular organization.  My suggestion would be to identify a test suite or part of the code that would especially benefit from Ginkgo/Gomega and pull out a new additional suite alongside the existing one.  One place to look is integration testing.  Ginkgo and Gomega were built to make fluent effective integration testing possible - even enjoyable.  And you'll get significant performance gains from Ginkgo's parallelization in such contexts.

**Comment by mig4** [comment]
Riiight, that makes sense :bulb: 

Thanks for prompt and enlightening answer @onsi, that will help me restructure things a bit and like you said still use Ginkgo+Gomega for integration tests. :heart: 

I'm going to close this then as there's nothing to do. Thanks, have a lovely day!
