### ISSUE TITLE
AfterEach can not get correct value of a variable

### ISSUE THREAD

**Issue by richard667** [onsi/ginkgo#789]
Here is my test case
```
	ginkgo.Context("xxxxxxx", func() {
		initName := "wkspace" + rand.String(5)
		var test *server.CreateWorkspaceResponse

		ginkgo.AfterEach(func() {
			logger.Infof("ttttttttttttttttttt %v", *test)
		})

		ginkgo.FIt("xxxxx", func() {
			test = &server.CreateWorkspaceResponse{Item: &server.Workspace{
				Id:          "aaa",
			}}
			expect.Equal(test.Item.Id, "aaa")
			test, _, _ := createWorkspace(cpClient, initName)
			logger.Infof("=========%v", test)
		})
	})
```

and here is the log 
![image](https://user-images.githubusercontent.com/38872395/112603452-fe9a0780-8e4f-11eb-9150-8d3fc8a859d9.png)

In `It`, the value of test is the desired value, but in `AfterEach`, the value of test become another one. And I wrote a similar case to reproduce the problem，like this
```
	ginkgo.Context("test", func() {
		var a *TestStruct
		ginkgo.AfterEach(func() {
			logger.Infof("a--------%v", *a)
		})
		ginkgo.FIt("only", func() {
			a = &TestStruct{Str: "xyz"}
			a = ReturnTestStruct()
			logger.Infof("a======%v", *a)

		})
	})
```
but the result is ok, the value of a are same. 
![image](https://user-images.githubusercontent.com/38872395/112604162-d1018e00-8e50-11eb-89f0-fbc067f9cda0.png)

that a little confusing.

**Comment by blgm** [comment]
I think the issue is with
```go
test, _, _ := createWorkspace(cpClient, initName)
```

This is creating a new variable called test which "hides" the previous value.

Static code analysis (like go vet, golint, or staticcheck) can be very helpful in warning about these kinds of situations.

**Comment by richard667** [comment]
> I think the issue is with
> 
> ```go
> test, _, _ := createWorkspace(cpClient, initName)
> ```
> 
> This is creating a new variable called test which "hides" the previous value.
> 
> Static code analysis (like go vet, golint, or staticcheck) can be very helpful in warning about these kinds of situations.

yeah, you are right. Thanks.
