### ISSUE TITLE
Stream deprecation notice always displayed on windows

### ISSUE THREAD

**Issue by piksel** [onsi/ginkgo#793]
Running ginkgo v1.16 on windows always shows a deprecation notice, since the default value for `--stream` is `true` on windows:
```go
c.FlagSet.BoolVar(&(c.ParallelStream), "stream", onWindows, "stream parallel test output in real time: less coherent, but useful for debugging")
```
This means that you have to add `--stream=false` to every command to not get the deprecation warnings, which are really distracting.
Perhaps adding a way to disable the warning globally and add that to the message, or disable the warning on windows? That is, if you cannot detect whether it was explicitly specified.

<details>
<summary>Example</summary>

```
$ ginkgo 
You're using deprecated Ginkgo functionality:
=============================================
Ginkgo 2.0 is under active development and will introduce (a small number of) breaking changes.
To learn more, view the migration guide at https://github.com/onsi/ginkgo/blob/v2/docs/MIGRATING_TO_V2.md
To comment, chime in at https://github.com/onsi/ginkgo/issues/711
  --stream is deprecated and will be removed in Ginkgo 2.0
  Learn more at: https://github.com/onsi/ginkgo/blob/v2/docs/MIGRATING_TO_V2.md#removed--stream

Running Suite: Example Suite
===========================
Random Seed: 1617791580
Will run 6 of 6 specs

++++++
Ran 6 of 6 Specs in 0.020 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 1.2055008s
Test Suite Passed
```

</details>

**Comment by onsi** [comment]
Thanks for filing this - I'm going to remove the deprecation warning on Windows until there is something actionable for the user to do.
