### ISSUE TITLE
go get -u ignores ginkgo and does not update it

### ISSUE THREAD

**Issue by jpalermo** [onsi/ginkgo#794]
If we include ginkgo in the project via the `tools` package suggested in the ginkgo readme, a `go get -u ./...` does not update ginkgo.

Some details are here: https://github.com/golang/go/issues/32345

Although that issue seems to imply that the issue was fixed back in 1.13 in 2019 but we're still seeing the same problem using go 1.15.8.

Thoughts?

**Comment by onsi** [comment]
hey @jpalermo!

I don't know too much about the tools stuff - i think @blgm wrote up that part of the readme so maybe he has a bit more context.

I can poke around next time i'm at a computer.

**Comment by blgm** [comment]
I can reproduce this: `go get -u ./...` does not update Ginkgo (or anything else), but: `go get -u github.com/onsi/ginkgo/ginkgo` does update Ginkgo.

I think this is principally a Go design decision that I'm not sure I particularly like, but it seems to be working as documented - `go help get` says:
```
The -u flag instructs get to update modules providing dependencies
of packages named on the command line to use newer minor or patch
releases when available.
```
And it seems that when you "name" `ginkgo` it does update, and when you don't it doesn't.

My top recommendation would be to use something like Dependabot to watch your repo and give you PRs for updates. An advantage of this is that it can trigger testing through GitHub Actions (or CI of your choice) so you can tell whether or not an update will break before it gets merged.

An alternative would be to do something like:
```
go list -m -f '{{.Path}}' all | xargs -n1 go get -u
```
This command is not quite correct, but you could play around with it until it does what you want.

Does this help, or have I not quite understood the problem?

**Comment by jpalermo** [comment]
No, I think this is helpful. From the linked issue this also seems to work
```
go get -tags=tools -u ./...
```
but then later in that issue it also seems to imply the "problem" was fixed, so I wasn't sure if I was missing something.
