### ISSUE TITLE
Error building ginkgo binary with go 1.16

### ISSUE THREAD

**Issue by avorima** [onsi/ginkgo#796]
Building the ginkgo binary with go 1.16.3 fails with:

```
$ go build -o ginkgo github.com/onsi/ginkgo/ginkgo
/go/pkg/mod/github.com/onsi/ginkgo@v1.16.1/ginkgo/bootstrap_command.go:15:2: missing go.sum entry for module providing package github.com/go-task/slim-sprig (imported by github.com/onsi/ginkgo/ginkgo); to add:
        go get github.com/onsi/ginkgo/ginkgo@v1.16.1
```

To reproduce:

```
cd $(mktemp -d)
go mod init test
echo 'package main' > main.go
echo 'import _ "github.com/onsi/ginkgo"' >> main.go
go get github.com/onsi/ginkgo@v1.16.1
go build -o ginkgo github.com/onsi/ginkgo/ginkgo
```

Running this in a container (`golang:1.16` or `golang:1.16-alpine`) will result in the same error.

**Comment by onsi** [comment]
thanks for the report - i'll take a look soon and let you know once it's fixed.  /cc @HagaiBarel have you seen any issues like this with resolving the slim-sprig dependency?

**Comment by HagaiBarel** [comment]
@onsi haven't seen this before, would like me to take a look?

**Comment by onsi** [comment]
If you’re up for it and have the time that would be wonderful thanks!  No worries if not.

**Comment by blgm** [comment]
I've had a quick look at this. I really like the recreate scenario because it's simple and demonstrates the error message.

I think there's some confusion here between:
- `go get github.com/onsi/ginkgo@v1.16.1` which get Ginkgo library (with `Describe`, `It` etc...)
- `go get github.com/onsi/ginkgo/ginkgo@v1.16.1` which gets the Ginkgo command

`go get` tries to be efficient and get only what's needed. Because the `go get` and the `import` only specify the Gingko library, that's all that's fetched. To build the Ginkgo command, it's necessary to add the second `/ginkgo`. This is easy to get wrong, and I've made this mistake many times.

Does this help?

**Comment by avorima** [comment]
In my example the `go get` is only so the dependency is in the go.mod file and the `import _` is just so `go mod tidy` doesn't remove it. I need to `go build` it though, because I need the binary locally in CI and use `go.mod` for versioning of that binary.

I found a solution: pass `-mod=mod` flag to `go build`.

Seems I should've read the [release notes](https://golang.org/doc/go1.16):
>Build commands like go build and go test no longer modify go.mod and go.sum by default. Instead, they report an error if a module requirement or checksum needs to be added or updated (as if the -mod=readonly flag were used). Module requirements and sums may be adjusted with go mod tidy or go get.

This should probably be added as a caveat to the README [here](https://github.com/onsi/ginkgo#go-module-tools-package), since `go run` also needs that flag.

**Comment by avorima** [comment]
Still weird that it somehow works for ginkgo v1.14.2

**Comment by blgm** [comment]
That's certainly curious. My guess is that because Ginkgo v1.14.2 had `go 1.13` in the `go.mod` file, maybe Go has a compatibility behavior that was making it work. But it's just a guess.

**Comment by blgm** [comment]
I think that if the import reads:
```go
import _ "github.com/onsi/ginkgo/ginkgo"
```
Then the `-mod=mod` flag should not be needed.

**Comment by avorima** [comment]
Yes, that's right. I'll close this issue then.
Thanks for taking your time to look into this.
