### ISSUE TITLE
How to run Ginkgo in parallel with bazel?

### ISSUE THREAD

**Issue by kaoet** [onsi/ginkgo#800]
Our project is using [Bazel](https://bazel.build) and [rules_go](https://github.com/bazelbuild/rules_go). We want to run tests in parallel to speed up our tests. However, it seems that it needs the `ginkgo` command line to start the test. And we cannot use `go test` only to run them in parallel. The problem is that the [`go_test`](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go_test) rules used by `rules_go` can only start the test with `go test`. How to solve the problem?

```bazel
load("@io_bazel_rules_go//go:def.bzl", "go_test")

go_test(
    name = "exp_test",
    srcs = ["suite_test.go"],
    args = [
        "--ginkgo.parallel",  # <-- This option is not supported.
    ],
    deps = [
        "//vendor/github.com/onsi/ginkgo",
        "//vendor/github.com/onsi/gomega",
    ],
)
```

I image can we have something like "in process parallel" to simply spawn the test cases with Go routines, so we can support `go test . --ginkgo.parallel`?

**Comment by onsi** [comment]
you're going to need to be able to invoke the ginkgo binary to run in parallel.  there is no support for in-process parallelism and there won't be with the current design.  i don't know what's entailed in writing a custom bagel rule set but that would be the direction to go in IMO.

**Comment by kaoet** [comment]
We end up writing a custom wrapper around `go_test`.

```python
load("@bazel_skylib//lib:shell.bzl", "shell")

def _ginkgo_test_impl(ctx):
    wrapper = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.write(
        output = wrapper,
        content = """#!/usr/bin/env bash
set -e
exec {ginkgo} {ginkgo_args} {go_test} -- "$@"
""".format(
            ginkgo = shell.quote(ctx.executable._ginkgo.short_path),
            ginkgo_args = " ".join([shell.quote(arg) for arg in ctx.attr.ginkgo_args]),
            # Ginkgo requires the precompiled binary end with ".test".
            go_test = shell.quote(ctx.executable.go_test.short_path + ".test"),
        ),
        is_executable = True,
    )

    return [DefaultInfo(
        executable = wrapper,
        runfiles = ctx.runfiles(
            symlinks = {ctx.executable.go_test.short_path + ".test": ctx.executable.go_test},
            transitive_files = depset([], transitive = [ctx.attr._ginkgo.default_runfiles.files, ctx.attr.go_test.default_runfiles.files]),
        ),
    )]

ginkgo_test = rule(
    implementation = _ginkgo_test_impl,
    attrs = {
        "data": attr.label_list(allow_files = True),
        "go_test": attr.label(executable = True, cfg = "target"),
        "ginkgo_args": attr.string_list(),
        "_ginkgo": attr.label(default = "//vendor/github.com/onsi/ginkgo/ginkgo", executable = True, cfg = "target"),
    },
    executable = True,
    test = True,
)
```

So we can write a `ginkgo_test` rule below `go_test` and pass the `-p` flag.
```bazel
go_test(
    name = "exp_test",
    ...
)

ginkgo_test(
    name = "exp_ginkgo_test",
    args = [...],
    data = [...],
    ginkgo_args = ["-p"],
    go_test = ":exp_test",
)
```

**Comment by onsi** [comment]
that's awesome - thanks for sharing @kaoet in case others come across the same need.

**Comment by rmohr** [comment]
> We end up writing a custom wrapper around `go_test`.

@kaoet that's exactly what I needed. :+1:
