### ISSUE TITLE
Feature request: Acknowledge Deprecation Warnings

### ISSUE THREAD

**Issue by carldunham** [onsi/ginkgo#802]
Otherwise, it's going to be a long couple of months... 😅

**Comment by onsi** [comment]
😅 heh, indeed.  Which deprecation are you hitting in particular?

**Comment by carldunham** [comment]
So far, just the JUnit generation that we use for CI

**Comment by onsi** [comment]
Yeah makes sense.  That particular deprecation is not actionable yet.  I'm inclined to do something like:

"If the environment variable `GINKGO_ACK_DEPRECATIONS=1.16` is set then Ginkgo won't emit deprecations.  Subsequent version of 1.x will emit new deprecations though until you bump the version number in the deprecations env var."

The intent there is to make it so folks notice the new deprecations.  Thoughts/ideas?

**Comment by carldunham** [comment]
That would be awesome.

**Comment by onsi** [comment]
hey @carldunham - this is now done in v1.16.2.  Give it a whirl.  I went with `ACK_GINKGO_DEPRECATIONS=1.16.2` for the environment variable.

**Comment by carldunham** [comment]
@onsi that works great. Thank you!
