### ISSUE TITLE
Using Gomock with Ginkgo crashes test suite

### ISSUE THREAD

**Issue by abaturovskyi** [onsi/ginkgo#805]
I have a simple mock and a consumer that uses this mock in a goroutine. When an unexpected Gomock function call occurrs - Ginkgo panics and outputs no additional information. Based on the output, I can't tell why my test failed.

```
var _ = Describe("Replicator", func() {
	var (
		ctrl *gomock.Controller
		mock *Mockiterator
	)

	BeforeEach(func() {
		ctrl = gomock.NewController(GinkgoT())
		mock = NewMockiterator(ctrl)
	})

	AfterEach(func() {
		ctrl.Finish()
	})

	It("should fail", func() {
		wg := sync.WaitGroup{}
		wg.Add(1)

		go func() {
			mock.Next()
			wg.Done()
		}()

		wg.Wait()
	})
})
```

Output:
```
Running Suite: Replicator Suite
===============================
Random Seed: 1620629221
Will run 1 of 1 specs

panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

	defer GinkgoRecover()

at the top of the goroutine that caused this panic.


goroutine 34 [running]:
github.com/onsi/ginkgo.Fail(0xc0002b2000, 0xd5, 0xc00029a018, 0x1, 0x1)
	/home/user/go/pkg/mod/github.com/onsi/ginkgo@v1.16.2/ginkgo_dsl.go:284 +0xc8
github.com/onsi/ginkgo/internal/testingtproxy.(*ginkgoTestingTProxy).Fatalf(0xc000298000, 0x7c9f34, 0x2e, 0xc0002ac000, 0x5, 0x5)
	/home/user/go/pkg/mod/github.com/onsi/ginkgo@v1.16.2/internal/testingtproxy/testing_t_proxy.go:62 +0xc2
github.com/golang/mock/gomock.(*Controller).Call.func1(0xc0002900c0, 0x771b20, 0xc000296030, 0x7b3de4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/pkg/mod/github.com/golang/mock@v1.5.0/gomock/controller.go:231 +0x47d
github.com/golang/mock/gomock.(*Controller).Call(0xc0002900c0, 0x771b20, 0xc000296030, 0x7b3de4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/pkg/mod/github.com/golang/mock@v1.5.0/gomock/controller.go:247 +0xb4
github.com/b/m/replicator_test.(*Mockiterator).Next(0xc000296030, 0x0)
```

The problem is that it is not my code produced panic - it is gomock's call to `testingproxy` which calls Ginkgo's `Fail` with panic at the end of the function. Basically it is impractical to make asynchronous tests with Ginkgo and Gomock, as based on output - I can't tell what caused the problem. Is there any way to make it work? Maybe there is something I'm making wrong?

**Comment by onsi** [comment]
So it's clear you'll want:

```

go func() {
   defer GinkgoRecover()
	mock.Next()
	wg.Done()
}()

```

**Comment by abaturovskyi** [comment]
Sorry for late response, so basically if there is an async code encapsulated in some struct function, and it is using a mock, you can't control that using `defer GinkgoRecover()` as you need to place it into the panicking goroutine?

**Comment by onsi** [comment]
That's correct: a goroutine cannot capture a panic emitted by another goroutine.  If you can't control the goroutine in question there is this workaround that I mentioned recently on a similar issue:

https://github.com/onsi/ginkgo/issues/813#issuecomment-851685310

**Comment by abaturovskyi** [comment]
Thanks, I'll have a look.
