### ISSUE TITLE
Invalid package names generated when folder name starts with a number

### ISSUE THREAD

**Issue by RomanKornev** [onsi/ginkgo#809]
1. `mkdir 5`
1. `cd 5`
1. `ginkgo generate`
1. `ginkgo bootstrap`
1. `cat 5_test.go` should not begin with `package 5...` since it's not a valid package name
1. same with `cat 5_suite_test.go`

**Comment by blgm** [comment]
Agreed. A package name in Go must be a valid identifier, which must begin with a letter.
- what's the impact of this for you? Is it causing a problem, or is this issue more about correctness?
- what do you think Ginkgo should do in this situation?

**Comment by RomanKornev** [comment]
1. I found a workaround: set the correct package name in a file first, then run the generators. Ginkgo picks up the correct package name from an existing file.
2. Maybe start with an underscore `_`?

**Comment by onsi** [comment]
I've added this to the v2 backlog.
