### ISSUE TITLE
It's not a good choice to connect textname of describe, context and it with space in JUnit

### ISSUE THREAD

**Issue by chenpfeisoo** [onsi/ginkgo#812]
At present, our use case names are connected by the textname of describe, context and it with spaces, which has no effect on the execution of use cases and the record of case execution,

However, when we try to analyze JUnit reports automatically, find the failed cases and re execute them, because there are spaces in different levels of textname, it will be difficult to deal with when parsing test cases. We don't know where to start splitting multiple spaces

So it is a better way to recommend special characters instead of spaces

```go
func (reporter *JUnitReporter) SpecDidComplete(specSummary *types.SpecSummary) {
	testCase := JUnitTestCase{
		Name:      strings.Join(specSummary.ComponentTexts[1:], "_"),
```

**Comment by onsi** [comment]
I know I keep repeating myself about V2 - but i do think the JSON-formatted reports in V2 will be much more useful here.  The JUnit format just isn't expressive enough.  I don't want to change the behavior with the JUnit reporter - perhaps you can look at the location information (filename, line number) for now.  I think the JUnit report includes that information?

**Comment by chenpfeisoo** [comment]
OK, thank you very much. (file name, line number) is useful
