### ISSUE TITLE
Checksum mismatch for v1.16.3 tag.

### ISSUE THREAD

**Issue by jmalloc** [onsi/ginkgo#814]
Hi there,

I am seeing a checksum mismatch when attempting to install v1.16.3:

```
verifying github.com/onsi/ginkgo@v1.16.3: checksum mismatch
	downloaded: h1:3s86PZkI1ApJh6HFIzC1gXby/mIyZqfE5zxSvtoBSsM=
	go.sum:     h1:nbWI/w6DYT9gXDQi59Mht//PLPPFv/Hc3fHms4eVUK0=
```

This error is occurring in builds for PRs created by Dependabot ([example](https://github.com/dogmatiq/kyu/pull/22)).

Separate, but related, our corporate Go proxy happened to cache the version with the hash of `nbWI/w6DYT9gXDQi59Mht//PLPPFv/Hc3fHms4eVUK0=`, which does _not_ contain a CHANGELOG.md entry for v1.16.3. For this reason I suspect that this tag was pushed and then later replaced.  Before I updated my `go.sum` files, can you please confirm if this is the case?

If the above is indeed what happened, could I respectfully suggest strict adherence to [this clause](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version) from the semver spec in the future. Perhaps even deleting the faulty tag is preferable to overwriting it (?).

Thanks :)

/cc @danilvpetrov, @na4ma4

**Comment by onsi** [comment]
hey @jmalloc - yeah i accidentally tagged the wrong commit.  i fairly quickly removed the tag and then reattached the tag to the subsequent correct commit - not realizing it would wreak havoc!  any suggestions on what to do on my end?  i could cut a new 1.16.4 tag and mark 1.16.3 as [retracted](https://golang.org/ref/mod#go-mod-file-retract)

**Comment by jmalloc** [comment]
> i could cut a new 1.16.4 tag and mark 1.16.3 as [retracted](https://golang.org/ref/mod#go-mod-file-retract)

I'd forgotten all about the `retract` keyword, that sounds perfect!  

Added bonus for those of us that use Dependabot, it'll see the new tag and replace the failing PRs with good ones :+1:

**Comment by onsi** [comment]
ok thanks.  sounds good.  i’m out of town for a bit but will do this in the next couple of days.

**Comment by jmalloc** [comment]
No worries, thanks for the quick replies :)

**Comment by bohdantrotsenko** [comment]
Oh, I also came here with this issue as CI (using a cache) started failing on me.

**Comment by onsi** [comment]
alright fixed and pushed out 1.16.4 - please let me know if y'all continue to see issues.

**Comment by blgm** [comment]
1.16.4 is working for me

**Comment by jmalloc** [comment]
Confirmed on my end, too. Thanks again!
