### ISSUE TITLE
Question: why aren't my spec names showing up in verbose output?

### ISSUE THREAD

**Issue by jakerobb** [onsi/ginkgo#815]
I have a new app and just added my first Ginkgo test. I've used Ginkgo before, but I wasn't the one who set it up.

The test looks like this:

 ```go
package mypkg_test

import (
  . "github.com/onsi/ginkgo"
  ...
)

var _ = Describe("some test", func() {
  ...
  Context("some context", func() {
    It("should do a thing", func() {
      ...
    })
  })
})
```

And when I run it in verbose mode:

```
$ go test ./mypkg -v 
=== RUN   TestSuite
Running Suite: Mypkg Test Suite
================================
Random Seed: 1623188973
Will run 1 of 1 specs

•
Ran 1 of 1 Specs in 0.123 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestSuite (0.12s)
PASS
ok  	github.com/myorg/myapp/mymodule/mypkg
```

The output I expected would have been:
```
$ go test ./mypkg -v 
=== RUN   TestSuite
Running Suite: Mypkg Test Suite
================================
Random Seed: 1623188973
Will run 1 of 1 specs

• some test some context should do a thing
Ran 1 of 1 Specs in 0.123 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestSuite (0.12s)
PASS
ok  	github.com/myorg/myapp/mymodule/mypkg
```

Presumably I've missed some small detail that is preventing the strings I pass to `Describe()`, `Context()`, and `It()` from appearing in the verbose output. The test itself runs correctly and passes, and I actually have four tests so far (I've manipulated the output above for simplicity and brevity), and I get four of the little bullet-point characters, but no spec names.

What am I missing? Thanks in advance for any help. :)

**Comment by onsi** [comment]
hey @jakerobb 

I generally recommend using the `ginkgo` cli over `go test` as you'll get support for a bunch of additional features.  `ginkgo -v` will give you the verbosity you desire.

with that said using `go test` is fully supported (modulo a few missing features that you can only get with the cli) however you need to pass in ginkgo's flags namespaced appropriately.  to get verbosity you need `go test -v -ginkgo.v`

**Comment by jakerobb** [comment]
Understood, but when I run with `go test -v` in the other app, I see test names in the output, and I was trying to figure out why.

I ended up making a copy of the older app and paring it down as much as possible to figure out what was different. Turns out it uses Terratest, and every test has at least some log output. Terratest prints the full name (describe + context + it) of each test at the beginning of every log line. Go prints its green bullet points without a trailing line feed, and so what you end up with in your output is a green dot followed by a test name, and if you look far enough to the right, some log output which I apparently learned to ignore most of the time. 🤣 

Worth noting: in the output I thought I wanted, the green dot comes _after_ the test completes (of course). This means that on a line of output with a green dot and a log line from Terratest, the name of the test shown to the right of the green dot is not the name of the test that passed, but rather that of the one that ran next. We had many hundreds of tests, and I was never focused on the first one or the last one, and so I never noticed the mismatch. 🤦🏻‍♂️

For example:
```go
package mypkg_test

import (
  "github.com/gruntwork-io/terratest/modules/logger"
  . "github.com/onsi/ginkgo"
  . "github.com/onsi/gomega"
)

var _ = Describe("Verify Ginkgo behavior", func() {
  Context("by confirming that", func() {
    It("42 equals 42", func() {
      logger.Log(GinkgoT(), "Log from 42 test")
      Expect(42).Should(Equal(42))
    })
    It("24 equals 24", func() {
      logger.Log(GinkgoT(), "Log from 24 test")
      Expect(24).Should(Equal(24))
    })
  })
})
```

Output:
```
$ go test -v ./...
=== RUN   TestSuite
Running Suite: Test Suite
=========================
Random Seed: 1623248597
Will run 2 of 2 specs

Verify Ginkgo behavior by confirming that 42 equals 42 2021-06-09T10:23:17-04:00 server_test.go:12: Log from 42 test
•Verify Ginkgo behavior by confirming that 24 equals 24 2021-06-09T10:23:17-04:00 server_test.go:16: Log from 24 test
•
Ran 2 of 2 Specs in 0.000 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestSuite (0.00s)
PASS
ok  	github.com/riptano/stargazer/auth-manager/mypkg	0.494s
```

And when using `ginkgo`:
```
$ ginkgo -v ./...
Running Suite: Test Suite
=========================
Random Seed: 1623248705
Will run 2 of 2 specs

Verify Ginkgo behavior by confirming that 
  42 equals 42
  /Users/jakerobb/Projects/sscce/ginkgo/mypkg/server_test.go:11
Verify Ginkgo behavior by confirming that 42 equals 42 2021-06-09T10:25:07-04:00 server_test.go:12: Log from 42 test
•
------------------------------
Verify Ginkgo behavior by confirming that 
  24 equals 24
  /Users/jakerobb/Projects/sscce/ginkgo/mypkg/server_test.go:15
Verify Ginkgo behavior by confirming that 24 equals 24 2021-06-09T10:25:07-04:00 server_test.go:16: Log from 24 test
•
Ran 2 of 2 Specs in 0.000 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 2.136015237s
Test Suite Passed
```

Ginkgo CLI's output is much less misleading!

Thanks again.

**Comment by tombh** [comment]
Apologies for reviving an old thread, but I just want to double check if I need to write my own reporter or not. Basically I want the output of `ginkgo -v` but without the logs (they're overwhelmingly large). Like what `rspec` does: 
![image](https://github.com/onsi/ginkgo/assets/160835/ff8117a5-e9af-45dc-a99c-7b17b3fd4f97)

The output of `ginkgo -v` seems to be entirely on STDOUT so I can't grep filter to get what I want. I see that `--json-report` has everything I need, and I'm very happy to script something together to get what I want. I'm just a little surprised that something like this wouldn't already exist.

The idea is just that I'd like to show my team —that aren't so familiar with testing— something that helps them get an idea of what the test suite is doing.

Thanks for any ideas ✨

**Comment by onsi** [comment]
hey @tombh if your goal is just to showcase what's running when you can do `ginkgo -v -dry-run`.  Today `-v` is fairly blunt and causes everything to be emitted verbosely - I may be tweaking that in the future to be a bit more granular.  But I don't have a timeline so you may just want to build on top of the JSON format.

FWIW something like `--format nested` isn't strictly straightforward as Ginkgo assumes [tests are independent](https://onsi.github.io/ginkgo/#mental-model-ginkgo-assumes-specs-are-independent) and supports randomization and parallelization which means that tests aren't guaranteed to run in nesting order.

**Comment by tombh** [comment]
Oh! That `ginkgo -v -dry-run` is reeeally handy, thank you. I think that's going to be enough for me at the moment.

And good point about the nesting, I'll bear that in mind when I get round to making something with the JSON format.
