### ISSUE TITLE
Noisy Skippings seems to be broken

### ISSUE THREAD

**Issue by SamuelCabralCruz** [onsi/ginkgo#817]
Hi there,

It seems that noisySkippings flag does not work anymore since I get the same result no matter its value:
on:
![image](https://user-images.githubusercontent.com/15621634/123176092-d9b63000-d450-11eb-9468-2fa018564fee.png)
off:
![image](https://user-images.githubusercontent.com/15621634/123176138-e76bb580-d450-11eb-8875-a51f21afe91d.png)

Expected behavior:
with `--noisySkippings=false` I don't get any reporting what so ever for skipped tests
I get none of this part in the output:
![image](https://user-images.githubusercontent.com/15621634/123176256-1aae4480-d451-11eb-9ca3-7086d5590bc4.png)

**Comment by onsi** [comment]
hey @SamuelCabralCruz - I think `--noisySkippings` has always been a bit broken.  In fact I'm removing it in [v2](#711) which should be shipping in the next few months.  In V2 Ginkgo simply honors `--succinct` and `--v` to control verbosity, including verbosity for skipped tests.

**Comment by SamuelCabralCruz** [comment]
@onsi all right, thanks for the quick feedback and for your great work 💪 can't wait for this V2, it looks really promising 🙏

**Comment by onsi** [comment]
thanks for the kind words @SamuelCabralCruz !
