### ISSUE TITLE
Error when running tests across multiple tests files within the same package

### ISSUE THREAD

**Issue by thomas-bousquet** [onsi/ginkgo#820]
It seems like when there is more that one test file in the same package, it triggers the error : 
`You may only call It from within a Describe, Context or When`

Can be reproduced on this repo https://github.com/thomas-bousquet/play-wih-ginkgo, with `go test ./...`  command.
go version go1.16.5 darwin/amd64

**Comment by onsi** [comment]
hey @thomas-bousquet - sorry for the cryptic error you are getting (it should be much improved in v2).

i'd suggest a quick skim through the docs [here](https://onsi.github.io/ginkgo/#getting-started-writing-your-first-test)  but the short version is: you don't need (in fact, should **not** have) multiple calls to `RunSpecs` - a single call from a single `TestX` function is all you need per package (multiple test files in a directory are coalesced into a single test package for the package in that directory - similar to how Go thinks about files and directories in general).

A common pattern is to run `ginkgo bootstrap` to generate that `TestX` hook and then use `ginkgo generate` to generate as many test files in the package as you want.

**Comment by thomas-bousquet** [comment]
Thanks @onsi for the quick response!
