### ISSUE TITLE
Q: Parallel nodes and dynamically generating tests

### ISSUE THREAD

**Issue by avrahams** [onsi/ginkgo#822]
I followed the pattern for [dynamically generating tests](https://onsi.github.io/ginkgo/#patterns-for-dynamically-generating-tests) to dynamically create a spec for each on my custom "testcase" objects
Since my testcases need long preparation time (create db, prepare namespace etc.) , the testcase .prepareForTest() function is called outside the spec  and returns a channel in which the the preparation result will be sent when done 
When the spec runs it will first wait for the preparation result on the channel 

```
var _ = Describe("dynamically generated tests ", func() {
	Context("Create a spec for each testcase", func() {
		for _, testcase := range testcases {
			testcase := testcase
			//start preparing for test and get the result channel  (this is long operation)
			testcaseChannel := testcase .prepareForTest() 
			It("Running test for "+tc.description(), func() {
				By("Wait for test case preparation to complete")
				prepareResult := <-testcaseChannel 
```

This works perfectly when running ginkgo on a single node.

But I am not sure that this will work when running specs in [parallel](https://onsi.github.io/ginkgo/#parallel-specs)
Since each node will run in a different process I suspect that when running in parallel each node will call testcase .prepareForTest() instead of having it called once, per testcase 
Can you please confirm explain the flow when running ginkgo in parallel ?
Thanks

**Comment by onsi** [comment]
Hey @avrahams - you are correct that when running in parallel each process will need to construct the testing tree, and therefore each process will need to execute the `Describe` and `Context` blocks you've shared above.  And that when they do, each process will range over all the `testcases` and then call `testcase.prepareForTest()` for each one.  After that, each process will have a complete list of all the tests, and then the processes will start divvying up those tests among themselves.  So, when running with two parallel processes, process A will wait on one `testcaseChannel` while process B will wait on the `testcaseChannel` for a different test.

Obviously, this is not what you want!

The following change, however, _should_ do the trick:

```
var _ = Describe("dynamically generated tests ", func() {
	Context("Create a spec for each testcase", func() {
		for _, testcase := range testcases {
			testcase := testcase
			It("Running test for "+tc.description(), func() {
				By("preparing for the test")
				testcaseChannel := testcase.prepareForTest() 
				By("Wait for test case preparation to complete")
				prepareResult := <-testcaseChannel 
```

Now, each process will compute the same set of tests.  The processes will then divvy up the tests and only the process that runs a given testcase will call `prepareForTest()` for that testcase.

If you wanted to separate out test setup from the test itself a bit more you could also do:

```
var _ = Describe("dynamically generated tests ", func() {
	for _, testcase := range testcases {
		testcase := testcase
		Context(testcase.description(), func() {
			var result ResultType
			BeforeEach(func() {
				result = <-testcase.prepareForTest()
			})
			It("runs the test", func() {
				//do stuff with result
			})
		})
	}
})
```

At this point I would probably be inlining the body of `prepareForTest` into the `BeforeEach` and just doing the work in the test and simply having `testcase` be a bag of configuration data that feeds into the test vs an object that does things outside of the test.  (Unless, of course, you're reusing that test setup across other contexts in which case keeping it as a separate callable entity makes sense).

Hope that helps....

**Comment by avrahams** [comment]
Thanks @onsi 
Actually my purpose was to save preparation time for a testcase which can take up to 15 minutes
In my current implementation the testcases will do the preparations  in the background while first test is running 
Placing it inside the It will not have this benefit 

I was wondering if there is something I can do with SynchronizedBeforeSuite 
For instance defining which testcases each node should handle (e.g. node1 = 1-3, nod22: 4-5, ...)
But I guess that SynchronizedBeforeSuite  also is called after the tree is constructed 

Is there another hook I that I can use like SynchronizedBeforeSuite  that will be called before the tree is constructed ?

**Comment by onsi** [comment]
Ah, I see.  Can you help me understand a bit more about your test suite so we can brainstorm some solutions together?  A few questions:

How many testcases are there?
Is there just one that takes ~15 minutes to set up?
How long do the others typically take? (1 minute each? 5 minutes each?)
How much parallelism can you throw at the problem?  Can you run them all at the same time?  Just a handful at a time?
Any chance the source code is open source and online so I could take a look?

In general i've found that if one case takes 15 minutes then most cases are taking somewhere in the neighborhood of a few minutes.  In that case I just ask Ginkgo to randomize all the specs and odds are that at some point one of the parallel processes will pick up the super slow test while the others are running.  Can't guarantee and optimal runtime every time but it's often good enough and allows me to avoid too much additional complexity in how the tests are set up and distributed.

Aside from that there is no way to specify ahead of time which process gets which test.  But if you can share a bit more information I can try to help you think through some more options.

**Comment by avrahams** [comment]
There could be dozens of test cases in the system 
Each testcase take 15 minutes to prepare 
Each test per testcase takes ~40 minutes to complete 
Theoretically all the testcases can run in parallels - but because of system resources like number of available DBs  I was planning to run 2-3 nodes 

Question:
What if I will add conditional spec creation according to the running node like in the sample below - will it work ?
This will make each node to have a different specs tree 

```
func shouldHandleTestcase(testcaseIndex int) bool{
     myNode := config.GinkgoConfig.ParallelNode
     totalTestcases := len(testcases)
     totalNodes := config.GinkgoConfig.ParallelTotal
     //shouldhandle := some logic to to distribute N-Testcase over N-workers and see what my worker should handle  
     return shouldHandle
}

var _ = Describe("dynamically generated tests ", func() {
	Context("Create a spec for each testcase", func() {
		for index , testcase := range testcases {
			testcase := testcase
			//start preparing for test and get the result channel  (this is long operation)
			var testcaseChannel chan *result
			if !shouldHandleTestcase(index){
			        continue; //do not create the it for this node          			
                        }
                        //else - this node will handle this test case 
                        testcaseChannel  := testcase .prepareForTest() 
			It("Running test for "+tc.description(), func() {
				By("Wait for test case preparation to complete")
				prepareResult := <-testcaseChannel 
```

**Comment by avrahams** [comment]
So for 10 test cases with 15 minutes preparation and 40 minutes test 
With your approach in parallel  with 2 nodes will take  (15 min preparation + 40 mins test)*10/2 = 275 minutes

and with the current implementation 
15 min preparation + (40 mins test*10) = 415 minutes 

So for me best to condition the current implementation only when running with ParallelTotal == 1 and place it inside the It if it is bigger then one 

Thanks

**Comment by onsi** [comment]
Yes, that's one option.  I think I understand your context a bit more now.  I confess it's a bit different from any I've seen before.  Normally if running each individual test takes this long and you hit system resource issues when running with a parallelism of 2-3 then you typically _also_ see test preparation hit similar system resource limits and so you need to limit parallelism of both the tests and the test preparation.  In your case it sounds like you can really run as much setup in parallel as you'd like but only need to limit the test runs.

Given that, you can also try something like this:

```go
var preparedResults map[string]TestCaseResult

var _ = SynchronizedBeforeSuite(func() []byte {
	// set up all the tests up front, with maximal concurrency, on Ginkgo process 0
	results := map[string]TestCaseResult{}
	lock := &sync.Mutex{}
	wg := &sync.WaitGroup{}
	wg.Add(len(testcases))
	for _, testcase := range testcases {
		testcase := testcase
		go func() {
			result := <-testcase.prepareForTest()
			lock.Lock()
			results[testcase.id()] = result
			lock.Unlock()
			wg.Done()
		}()
	}
	wg.Wait()

	// encode the results and pass them to all processes
	encoded, _ := json.Marshal(results)
	return encoded
}, func(encodedResults []byte) {
	// decode the results on each process
	preparedResults = map[string]TestCaseResult{}
	json.Unmarshal(encodedResults, &preparedResults)
})

var _ = Describe("dynamically generated tests ", func() {
	Context("Create a spec for each testcase", func() {
		for _, testcase := range testcases {
			tc := testcase
			It("Running test for "+tc.description(), func() {
				By("Wait for test case preparation to complete")
				result := preparedResults[tc.id()]
				//do stuff
			})
		}
	})
})
```

This does all the setup on the first Ginkgo process and assumes you can JSON encode the prepared results to distribute them to the other processes.  If your test setup is really only 15 minutes regardless of the degree of concurrency then this approach will give you (15 min preparation + (40 min test*10)/N) where N is the number of parallel nodes.  If N=2 (your example above) you'll get down to 215 minutes with this approach.

**Comment by avrahams** [comment]
This is a good solution 
Thanks

I was thinking also on a different option but I am not sure this is possible 
Q: is there a way to know from inside BeforeSuite which specs will run on the current node ?
In this case I can run prepareForTest only for the testcases that will related to the specs that will run on this node
This way I can do it in-proc and still use channels instead of serializing results to json

**Comment by onsi** [comment]
Nope there's no way to know ahead of time which process a given test will run on.  That's because the tests are randomized and ginkgo doesn't know beforehand how long each test will take.

Glad to hear we may have arrived at a more optimal solution for your usecase.  One thing I'd suggest looking at and investing effort in would be around resource reuse.  Is there any way for you to reduce the setup and/or test runtime?

For example I've seen situations where it's possible to shard a database such that each ginkgo process accessed its own shard and simply clears out the shard between tests vs having to instantiate a new separate shard for each test.  That tends to go faster.  I don't have any context on the actual underlying architecture/problem you are testing though so take this with a grain of salt!

**Comment by avrahams** [comment]
yes, This is our e2e suite with real cluster and other distributed systems so it not so standard as our mock bdd suite

**Comment by onsi** [comment]
sounds good @avrahams - i'll go ahead and close out this issue.  please feel free to reopen if you hit any snags.
