### ISSUE TITLE
Running a reporter before AfterEach blocks to collect data

### ISSUE THREAD

**Issue by rmohr** [onsi/ginkgo#823]
Would it be possible to extend reporters so that they can be run before the first `AfterEach` is called?

The main purpose of this would be to collect information before the cleanup of the tests are happening in `AfterEach` blocks, since that destroys evidence.

Is there a way to do that already?

**Comment by onsi** [comment]
There is not a way to do that today via custom reporters.  In fact custom reporters will be going away in [V2](#711) in favor of a [more flexible set of mechanisms for reporting on tests](https://github.com/onsi/ginkgo/blob/v2/docs/MIGRATING_TO_V2.md#improved-reporting-infrastructure).

If you want to extract information about your test just after the `It` runs but before any `AfterEach` nodes run you can add a single top-level `JustAfterEach` - this will run just after every `It` in the test.  In the body of your `JustAfterEach` you can call `CurrentGinkgoTestDescription()` to get information about the current test.

**Comment by rmohr** [comment]
> If you want to extract information about your test just after the `It` runs but before any `AfterEach` nodes run you can add a single top-level `JustAfterEach` - this will run just after every `It` in the test. In the body of your `JustAfterEach` you can call `CurrentGinkgoTestDescription()` to get information about the current test.

Thanks for the suggestion. What I find nice about reporters is that i can register them globally and keeping the actual tests completely free of any traces of them.  Is there a way to register something like a global `JustAfterEach` without having to wrap the whole description block?

**Comment by rmohr** [comment]
> Thanks for the suggestion. What I find nice about reporters is that i can register them globally and keeping the actual tests completely free of any traces of them. Is there a way to register something like a global `JustAfterEach` without having to wrap the whole description block?

Never mind. I could have tried it out. I can register it. Thanks. That should be good enough for me.

**Comment by onsi** [comment]
Yes you can do it at the top-level.  Or even in a library when you import it.
