### ISSUE TITLE
How to get the failure info in AfterEach

### ISSUE THREAD

**Issue by JiaYongfei** [onsi/ginkgo#824]
We want to implement a feature that notifying the user immediately when a test failed. In AfterEach block, we can use CurrentGinkgoTestDescription() to get most of the key info except the test failure. Any suggestions?

**Comment by onsi** [comment]
hey @JiaYongfei - sadly this is a limitation in Ginkgo v1.  It is resolved in v2 which should be available in the next few months.

**Comment by JiaYongfei** [comment]
ok. Looking forward to ginkgo v2
