### ISSUE TITLE
What is the best practice to benchmark memory allocation with ginkgo?

### ISSUE THREAD

**Issue by piratf** [onsi/ginkgo#825]
Go test benchmarking with memory profiler will print like this:
``` bash
BenchmarkAvgHalfAllocs-4          50000000    29.2 ns/op    64 B/op   0 allocs/op
```
This is a very convenient and intuitive way to do it.

For my test, I tried ginkgo in docker because it needs some setup. 
I compiled the testing code with "go test -c -race -o xxx" and run with "-test.benchmem" like suggested.
But ginkgo still only prints time.
![image](https://user-images.githubusercontent.com/9389616/127076643-8e05b0d9-ab75-4bfb-abab-aca80eecda39.png)

I tried using `pprof.WriteHeapProfile` in function `AfterSuite`, but it doesn't print the testing part(I'm using `FDescribe` to focus on the measurement part.)
``` golang
AfterSuite(func() {
    if enableProfile {
        memFile, err := os.Create("./output/mem.profile")
        if err != nil {
            log.Error("create mem profile err: ", err)
        }
        err = pprof.WriteHeapProfile(memFile)
        if err != nil {
            log.Error("write heap profile err: ", err)
        }
        defer pprof.StopCPUProfile()
    }
})
```
![image](https://user-images.githubusercontent.com/9389616/127078936-8935a906-663d-4769-b2b1-65c824407e77.png)

What is the best practice to benchmark memory allocation with ginkgo?

**Comment by onsi** [comment]
There isn't first-class support for it at this point and I'm removing `Measure` from Ginkgo V2 in favor of [gmeasure](https://github.com/onsi/gomega/tree/master/gmeasure).  I could see adding first-class support for more granular memory allocaiton measurement to `gmeasure` but I don't have plans to do that before Ginkgo V2 ships.  V2 does, however, better support `go test`'s various profiling flags.
