### ISSUE TITLE
Silent failures when running out of memory

### ISSUE THREAD

**Issue by rlpowell** [onsi/ginkgo#826]
See also https://github.com/golang/go/issues/47467

Normal run:

<pre>
$ docker run -v $(pwd):/go/src --rm -it ginkgo_mem bash -c 'go mod tidy ; ginkgo -v -trace -progress'
Running Suite: Main Suite
=========================
Random Seed: 1627602484
Will run 3 of 3 specs

Book Use a decent amount of RAM Don't Care
  should trivially succeed 1
  /go/src/go_suite_test.go:18
[It] should trivially succeed 1
  /go/src/go_suite_test.go:18
•
------------------------------
Book Use a decent amount of RAM Don't Care
  should not crash
  /go/src/go_suite_test.go:21
[It] should not crash
  /go/src/go_suite_test.go:21
•
------------------------------
Book Use a decent amount of RAM Don't Care
  should trivially succeed 2
  /go/src/go_suite_test.go:27
[It] should trivially succeed 2
  /go/src/go_suite_test.go:27
•
Ran 3 of 3 Specs in 2.906 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 7.744270223s
Test Suite Passed
</pre>

Memory limited run:

<pre>
$ docker run -v $(pwd):/go/src --rm -m 100M -it ginkgo_mem bash -c 'go mod tidy ; ginkgo -v -trace -progress'
Running Suite: Main Suite
=========================
Random Seed: 1627602620
Will run 3 of 3 specs

Book Use a decent amount of RAM Don't Care
  should trivially succeed 1
  /go/src/go_suite_test.go:18
[It] should trivially succeed 1
  /go/src/go_suite_test.go:18
•
------------------------------
Book Use a decent amount of RAM Don't Care
  should not crash
  /go/src/go_suite_test.go:21
[It] should not crash
  /go/src/go_suite_test.go:21

Ginkgo ran 1 suite in 24.17928429s
Test Suite Failed
</pre>

Note that there's no error message of any kind (not even the "signal: killed" that "go test" gives) and that without -progress there's no indication at all of what test failed or anything.  I spent many hours trying to understand my problem when it turned out it was "bump Docker's RAM in Docker for MacOS".

The code:

<pre>
$  cat go_suite_test.go
package main_test

import (
  "testing"

  . "github.com/onsi/ginkgo"
  . "github.com/onsi/gomega"
)

func TestMain(t *testing.T) {
  RegisterFailHandler(Fail)
  RunSpecs(t, "Main Suite")
}

var _ = Describe("Book", func() {
  Describe("Use a decent amount of RAM", func() {
    Context("Don't Care", func() {
      It("should trivially succeed 1", func() {
        Expect(2).To(Equal(2))
      })
      It("should not crash", func() {
        defer GinkgoRecover()

        bytes := make([]byte,1)
        for i := 0; i < (1024*1024*1024); i++ {
          bytes = append(bytes,1)
        }
      })
      It("should trivially succeed 2", func() {
        Expect(4).To(Equal(4))
      })
    })
  })
})
</pre>

The dockerfile:

<pre>
FROM golang:1.16.6

ENV GOPATH=/root/go

RUN go install github.com/onsi/ginkgo/ginkgo@v1.16.4
RUN go get github.com/onsi/gomega@v1.14.0
RUN cp ${GOPATH}/bin/ginkgo /usr/local/bin

WORKDIR /go/src
</pre>

**Comment by onsi** [comment]
@rlpowell I'm sorry to hear this turned into a multi-hour debug session for you.  I'll look into why the `signal: killed` message is being swallowed, presumably by the Ginkgo CLI, but as the go issue you link to explains - there's probably not much more to be done to identify that the kill signal is due to the OOM killer.

**Comment by rlpowell** [comment]
Yeah, I'm not particularly surprised; thanks for taking a look at it.

**Comment by rlpowell** [comment]
What ended up being the fix here?
