### ISSUE TITLE
Suspicious use of break statement in switch-case

### ISSUE THREAD

**Issue by chavacava** [onsi/ginkgo#827]
While developing the new linting rule `useless-switch` for [revive](https://github.com/mgechev/revive) I've used ginkgo codebase for testing the rule and I've found the following suspicious use of `break` statement

https://github.com/onsi/ginkgo/blob/f2509775374631f799f8c5a8ddc5224cad0e5b4b/ginkgo/convert/ginkgo_ast_nodes.go#L52-L59

It seems that the intention is to exit the loop as soon as a function literal is found in the arguments but the [`break` will not get the control out of the loop but out of the switch](https://play.golang.org/p/_iZLP9UTE5E).

**Comment by onsi** [comment]
hey @chavacava  - thanks for calling this out.  `convert` will not be in Ginkgo V2 so I'm going to close this issue out.
