### ISSUE TITLE
Is there any flow chart or architecture showing how ginkgo works?

### ISSUE THREAD

**Issue by JiaYongfei** [onsi/ginkgo#831]
Is there any flow chart or architecture for better understanding of how ginkgo works? specially for the parallel feature and log aggregator part.

I'm asking because I'd like to introduce ginkgo to someone else. It'll be easier to understand ginkgo if we have some chart.

**Comment by onsi** [comment]
Hey @JiaYongfei - sadly there are no diagrams or flow charts to help teach the various features.  The [documentation here](https://onsi.github.io/ginkgo) covers most of this stuff and this section on [Understanding Ginkgo's Lifecycle](https://onsi.github.io/ginkgo/#understanding-ginkgos-lifecycle) gets into some of the more subtle parts of Ginkgo.  But I admit it's not very well-written and can be confusing to someone new to Ginkgo.
