### ISSUE TITLE
Is there any way in Ginkgo to run a suite in order instead of opting alphabetical order

### ISSUE THREAD

**Issue by newbie-learner** [onsi/ginkgo#834]
Hi 
I have test directory where i have multiple suite likes
 ls -lrth test
total 12K
drwxrwxr-x 2 siddharth siddharth 4.0K Aug 19 11:04 tcp_testcase
drwxrwxr-x 2 siddharth siddharth 4.0K Aug 20 17:32 slice
drwxrwxr-x 2 siddharth siddharth 4.0K Aug 20 17:32 servicediscovery

i am exeucting to run a suite in test directory : ginkgo -r test
but it's pick a suite in alphabetical order
Instead of alphabetical order i would like to run in following mention order
1. Slice suite
2.  tcp_Testcase suite
3. servicediscovery
is there any way to achieve this ?

**Comment by blgm** [comment]
Ginkgo takes the view that ideally tests are self-contained and do their own setup and teardown, so it should not matter what order they are run in. In fact it can be beneficial to run them in random order.

Having said that, pragmatically sometime we do need to run tests in a particular order. The simplest way to achieve this in your case in probably to use the `-focus` flag. From the help:
```
  -focus value
    	If set, ginkgo will only run specs that match this regular expression. Can be specified multiple times, values are ORed.
```

So you could run:
```
ginkgo -r test -focus "slice"
ginkgo -r test -focus "tcp"
ginkgo -r test -focus "servicediscovery"
```
This relies on matching descriptions in the `Describe()` and `It()` (etc...) functions.

Ginkgo V2 (not yet released) will have additional control for running tests in a specific order, so hopefully in the future this could be achieved by running Ginkgo once.

**Comment by onsi** [comment]
hey @newbie-learner I'd love to hear what problem you are trying to solve.  Why do your tests need to run in a given order?
