### ISSUE TITLE
Is it possible to Stream output with SynchronizedBeforeSuite and SynchronizedAfterSuite

### ISSUE THREAD

**Issue by dkoshkin** [onsi/ginkgo#835]
Im using `SynchronizedBeforeSuite` and `SynchronizedAfterSuite` in my suite to run some longer setup and teardowns, ~20 mins and `15 mins. There are no `BeforeSuite` or `AfterSuite`.

Running the test with:
```
ginkgo -v --progress -p
```

Because of the `-p` flag the tests in `Describe` wait for the test to finish before printing its output which makes sense.

But is it possible to stream the output realtime when `SynchronizedBeforeSuite` and `SynchronizedAfterSuite` are running.

I know about the `-stream` flag but that will interleave the test output.
Is there something that would `-stream` just the output from `SynchronizedBeforeSuite` and `SynchronizedAfterSuite` as those will only run on 1 node at a time?

**Comment by onsi** [comment]
hey @dkoshkin - this is now live on the ver2 branch.    Docs for using the beta are [here](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta).
