### ISSUE TITLE
Ginkgo verbose mode not outputting "By" steps

### ISSUE THREAD

**Issue by LennDG** [onsi/ginkgo#836]
I have an It() step with several By() functions in it to structure the step clearly in the output, as per the docs: https://onsi.github.io/ginkgo/#documenting-complex-its-by

It states that the By steps are output with the GinkgoWriter when the tests are ran with `ginkgo -v ./...`.

Is there anything additional I need to do in this code?

```golang
package project_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("Issue", func() {
	Context("This needs to work", func() {
		It("should print these bys", func() {
			By("correctly comparing")
			Expect(1).To(Equal(1))

			By("Incorrectly comparing")
			Expect(1).To(Equal(2))
		})
	})
})
```

**Comment by jooseppi-luna** [comment]
Was there any resolution to this issue? I'm having a similar issue where I am running with ginkgo -v and not seeing any output unless I kill the test, and then it all gets printed.

**Comment by LennDG** [comment]
Sorry, this was quite a while ago and I have since left the job. I don't think I ever had a resolution otherwise I would have updated this post.
