### ISSUE TITLE
fail on focus option

### ISSUE THREAD

**Issue by lanwen** [onsi/ginkgo#842]
It would be nice to have same as `--fail-on-pending` option to fail on focus, as on CI we want to notify developers if they forgot to remove that.

There is an option `ginkgo unfocus` but it works only with v1 style `F` prefix and not with v2 `Focus` arg and also doesn't prevent that from being committed.

p.s.
```
ginkgo version
Ginkgo Version 2.0.0-beta
```

**Comment by onsi** [comment]
hey @lanwen good catch on `ginkgo unfocus` not catching `Focus`.  I'll fix that ahead of the RC for v2.

Ginkgo's current behavior is that it emits a non-zero exit code if it detects a programmatically focused test (i.e. `FIt` or `It(...,Focus,...)`).  If you use the Ginkgo CLI it should interpret that non-zero exit code and give you a helpful message.
