### ISSUE TITLE
Captured GinkgoWriter Output messes up text with %

### ISSUE THREAD

**Issue by mat007** [onsi/ginkgo#843]
This is Ginkgo V2, I’m doing something like
```
By("serving file https---my-file-with%20spaces%20in%20it")
```

and here is the output at the end when a test fails
```
Begin Captured GinkgoWriter Output >>
  STEP: serving file https---my-file-with%!s(string=09/28/21 07:42:03.466)paces%!i(MISSING)n%!i(MISSING)t
…

We may need to escape the % in the internal formatting code?

**Comment by onsi** [comment]
Welp - thanks for calling this out.  It looks like `By` is passing your string into `fmt.Sprintf` without escaping it.  Will fix on the ver2 branch soon.

**Comment by onsi** [comment]
this is now fixed
