### ISSUE TITLE
Report a coding issue that possibly leaks memory due to unclosed resource

### ISSUE THREAD

**Issue by guodongli-google** [onsi/ginkgo#849]
In the following code
https://github.com/onsi/ginkgo/blob/f43583d78dd771a06b6f0eb07b6627b6e7fa467d/internal/suite/suite.go#L110-L113

According to the Go documentation (https://pkg.go.dev/net/http), when `err` is `nil`, `resp` always contains a non-nil `resp.Body`, caller should close `resp.Body` when done reading from it, otherwise the memory held by`resp.Body` will not be released.

A fix is:
```
	resp, err := http.Get(config.SyncHost + "/has-counter")
	if err == nil {
        	defer resp.Body.Close()
	}
	if err != nil || resp.StatusCode != http.StatusOK {
		iterator = spec_iterator.NewShardedParallelIterator(specs.Specs(), config.ParallelTotal, config.ParallelNode)
	}
``` 
or at least:
```
	resp, err := http.Get(config.SyncHost + "/has-counter")
	if err != nil || resp.StatusCode != http.StatusOK {
		iterator = spec_iterator.NewShardedParallelIterator(specs.Specs(), config.ParallelTotal, config.ParallelNode)
	} else {
        	resp.Body.Close()
        }
``` 

**Found by static analyzer "DeepGo"**

**Comment by onsi** [comment]
thanks for sharing - this is resolved in V2 which will ship soon.
