### ISSUE TITLE
[Ginkgo 2] expose current context's test information

### ISSUE THREAD

**Issue by nmiculinic** [onsi/ginkgo#852]
I have the following code:

```go
lifecycle := func(...) {
   It(...)
   It(...)
}

When("", Ordered, func(){
   lifecycle(..)
})
```

and it's important that the `lifecycle` function is only called within `Ordered` section...otherwise things will not do what I want. I'd love to have:

```
GinkgoTestInfo()
```

function or something similar giving me all information about the current test/context:

* is it focused or not
* All labels
* Is it ordered
* etc.

**Comment by onsi** [comment]
All this to say I may eventually implement `BeforeAll` support within nested containers - but I want to get 2.0 out first and can then build on the new feature set over time.

**Comment by nmiculinic** [comment]
My use-case is two-fold:

* One is having a pretty big setup, which I want to do assertions on. Think:

```go
var _ = Describe("aa", Ordered, func () {
   BeforeAll(func(){ // big expensive setup})
  
   // varios assertions for the setup. It's either this or one big It block
   // This is kinda suite within a suite
   It(...)
   It(...)
})
```


The second use case is workflow/lifecycle/test scenario. e.g. I have:

```go
var _ = Describe("aa", Ordered, func () {
   It("step1", ...)
   It("step2", ...)
})
```

It blocks mutate the state under test, using same local variables.  Supporting nested BeforeAll/Ordered blocks would enable nested helper functions, but yeah...it may not be worth it to block v2 release.

**Comment by onsi** [comment]
hey @nmiculinic yep those usecases make sense and are why `Ordered` now exists.  I'm gonna keep pressing on with 2.0 and have added nester `BeforeAll/AfterAll`to the backlog.  will update this thread when they land.

**Comment by onsi** [comment]
Well, it proved to be pretty complex because of all the edge cases and interplay with flaky spec retries - but nested `BeforeAll/AfterAll` just landed on the latest ver2.

**Comment by nmiculinic** [comment]
Awesome @onsi ! :)
