### ISSUE TITLE
How to reuse expensive test initialisation?

### ISSUE THREAD

**Issue by mdbooth** [onsi/ginkgo#853]
I'm working on an e2e test suite which uses Ginkgo, specifically https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/82bc42efb0485efeddd3a3907cfdf553d529c2c8/test/e2e/suites/e2e/e2e_test.go

There are lots of problems here, but to avoid too many rabbit holes I want to concentrate on just one. The simplified structure is something like this (or it would be if we refactored it a bit: not this rabbit hole!):

```
BeforeSuite: Very expensive infra initialisation
  Describe: Cluster config A on shared infra
    BeforeEach: Fairly expensively create a cluster with config A
      It: tests something on cluster type A
      It: tests something else on cluster type A
  Describe: Cluster config B on shared infra
    BeforeEach: Fairly expensively create a cluster with config B
      It: tests something on cluster type B
      It: tests something else on cluster type B
```

Each of the tests for cluster config A are independent and relatively cheap. They could even potentially be run in parallel (but we probably wouldn't in practice due to potential resource usage spikes). However, if I were to keep them as separate tests I would have to destroy and recreate cluster type A for each test. Consequently, what we seem to be ending up with is a single It() for each cluster config which just gets bigger and bigger, combining multiple unrelated tests.

AFAICT the only block which allows me to share expensive initialisation between multiple tests is `BeforeSuite`, but we're already using that for a higher level of expensive initialisation. I think the semantics I'm looking for would be best described by replacing `BeforeEach` with a `Before` block, which would only run once in the containing context. This would allow me to:

* Create multiple shared clusters on a single shared infra
* Run multiple tests on each shared cluster

Is there already an idiomatic way to achieve this?

**Comment by onsi** [comment]
hey @mdbooth Ginkgo 2.0 is coming soon and will provide [`Ordered` containers](https://github.com/onsi/ginkgo/blob/ver2/docs/index.md#ordered-containers) that will support `BeforeAll` nodes that are intended to solve for this use case. Within an `Ordered` container `BeforeAll` nodes are guaranteed to run only once and `AfterAll` nodes are guaranteed to only once after the last spec in the container runs.  The `It`s within an `Ordered` container are guaranteed to run in order which means they are never randomized or parallelized with-respect-to each other but they _can_ be parallelized/randomized with respect to other specs in the suite.  Let me know if you think that'll satisfy your usecase.

You can start [using 2.0 today](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta) - I'd love feedback.  As for timelines - Ginkgo 2.0 has a release candidate out and should go GA within a month or so.

**Comment by mdbooth** [comment]
Yes, I think Ordered containers would do the job! It's stricter than we need because we don't need them to be ordered or (strictly) serialised, but the additional semantics wouldn't cause us a problem.

**Comment by onsi** [comment]
hey glad to hear it.  Please share your thoughts feedback if you do end up giving the RC a try.

While we're talking about it I'd love to ask a few follow-up questions.  I've designed things this way to control the amount of complexity going into 2.0.  Once i ship, though,  I'll be able to layer on more functionality/complexity.

Would it be valuable to you to be able to run specs which shared setup in parallel?  I can think of a few sane ways to accomplish this but don't want to block 2.0.  At the same time if the ordered semantics are good enough for most folks then I might avoid adding the additional complexity.  Anywho - just fishing for more input as I think about the roadmap.

**Comment by mdbooth** [comment]
In theory, yes. In this specific instance, I don't think we'd use it, or at least we'd probably want to limit which tests ran in parallel to ensure we never exceed resource constraints during a test run.

We actually have 3 levels of shared setup:
* Prior to running Ginkgo, but for every test run, we install a [small OpenStack cloud](https://docs.openstack.org/devstack/latest/) as our test target.
* BeforeSuite installs a [kind cluster](https://kind.sigs.k8s.io/) and configures it to run [Cluster API](https://cluster-api.sigs.k8s.io/).
* BeforeEach installs a kubernetes cluster in VMs created on the target cloud using Cluster API

Individual tests might test that the configuration of the cluster on the target cloud is as expected, which is pretty cheap and can run in parallel. Or they might create new nodes on the target cluster with specific configurations, which is not cheap and uses additional resources on the target cloud. These can theoretically run in parallel, but if we run too many we'll start getting errors when the target cloud runs out of resources. The order they run in is never important.

Incidentally, I guess BeforeSuite and BeforeAll feel like the same thing to me: they're just ways to have shared setup. Could they both be the same thing, with parallelism controlled by whatever container they're in?

Thanks for a great project, btw!

**Comment by onsi** [comment]
Thanks for sharing the additional context @mdbooth - I'll keep it in mind as I think about the roadmap.  And thanks for the kinds words!

Also - yes, `BeforeSuite` and `BeforeAll` are quite similar.  In fact, if you think about it, enabling a `BeforeAll` that can run, just once, for a set of specs that can run in parallel, would also require a `SynchronizedBeforeAll` similar to `SynchronizedBeforeSuite` so that  information can be conveyed from the process running the `SynchronizedBeforeAll` to all other processes.  It's all doable, but the complexity definitely starts to grow!
