### ISSUE TITLE
BeforeAll/AfterAll doesn't execute for each attempt when specify flake-attempts parameter

### ISSUE THREAD

**Issue by Juliia13** [onsi/ginkgo#857]
Here is the schema of my **Ordered** test
```
{
 ...
[BeforeAll]
[BeforeEach]

[It]
[It]
...

[AfterAll]
}
```

When I run the tests, I use the `flake-attempts` parameter to rerun the failed test.

The issue that I faced is that `BeforeAll ` is executed only once before the first attempt, and the `AfterAll ` is executed also only once after the last attempt. BUT, there are situations when the issue itself occurs in the BeforeAll function, and all that attempts makes no sense because what I really need is to rerun ALL scenario starting from the BeforeAll function. 

Here is the schema of the output
```
{

test started...
**BeforeAll** started execution ... _(f.e. the failure is happen here)_

test failed, starting the second attempt
**BeforeEach** started execution _(NOTE, the BeforeAll is not executed )_ 
**It** test started the execution _(f.e. some failure here, because the pre-condition wasn't run successfully)_
**AfterAll** started the execution _(also only once)_

}
```

What I would expect is executing the BeforeAll and AfterAll at each attempt.

**Comment by onsi** [comment]
hey @Juliia13 - thanks for catching this.  The interplay between spec retires and `Ordered` is unfortunately complex - but I think the behavior you're expecting is the more intuitive one and Ginkgo's current behavior is incorrect.

I'll work on some changes to fix this.  I'll have `BeforeAll` rerun _only_ in the case where the failure occurs in the `BeforeAll`

**Comment by onsi** [comment]
I've pushed some changes out to ver2 - this should be working now.

**Comment by YuliiaLizanets** [comment]
Hey @onsi 
Applied fix, everything works. Thank you!
