### ISSUE TITLE
github:topics: add repo topics to easily find ginko on github [trivial]

### ISSUE THREAD

**Issue by tixxdz** [onsi/ginkgo#866]
Hi maintainers,

You should tag the repo with topics, I was looking for **testing** packages for Golang , but did not see ginkgo, I did read about it in the past that's why I'm here, otherwise I would have missed it...

https://github.com/topics/testing?l=go

Maybe it was suggested in the past ?

Thanks!

**Comment by onsi** [comment]
oh hey thanks!  I had no idea this was a thing on Github.  fixed now!
