### ISSUE TITLE
Request: Allow flexibility to avoid having codeLocation and time in AddReportEntry

### ISSUE THREAD

**Issue by anshuljayn** [onsi/ginkgo#868]
As of now when report entry are added it it puts location and time stamp. There should be option to ignore writing these - 

code location can be ignored by passing types.CodeLocation{}, but with time it is not possible as nil time is not possiible

		AddReportEntry("foo", "bar",ReportEntryVisibilityNever, types.CodeLocation{})
		AddReportEntry("foo", "baz",ReportEntryVisibilityNever, types.CodeLocation{},time.Time{})

<testcase name="[It] TEMP" classname="Test Suite1" status="passed" time="4.6372e-05">
<system-out> Report Entries: foo :0 2021-12-17T17:59:21.873934Z bar -- baz :0 0001-01-01T00:00:00Z qux </system-out>

if there can be args (e.g. ignoreTimeReportEntry)  to pass to avoid printing time 

		AddReportEntry("foo", "bar",ReportEntryVisibilityNever, types.CodeLocation{})
		AddReportEntry("foo", "baz",ReportEntryVisibilityNever, types.CodeLocation{},ignoreTimeReportEntry)

<testcase name="[It] TEMP" classname="Test Suite1" status="passed" time="4.6372e-05">
<system-out> Report Entries: foo :0 2021-12-17T17:59:21.873934Z bar -- baz :  qux </system-out>

**Comment by onsi** [comment]
hey @anshuljayn thanks for using the 2.0 beta/rc!  As it's a new feature, I'd love to learn more in general about how you're using report entries.

I can add these additional configuration options to give you more control at the per-ReportEntry level but I'd like to learn more about your use case to see if there are alternative solutions.  For example, I  wonder if it would work for you if Ginkgo only emitted code location+timestamp if a failure has occurred _or_ you are explicitly running in verbose mode with `-v`. 

Thoughts?

**Comment by anshuljayn** [comment]
Hi @onsi, I am using junit reports and using AddReportEntry to persist some of the transaction data (e.g. - id, uuid etc) to junit reports which can be checked in future retrospectively or can be used to generate the html reports. I'll save this irrespective if failure or success as end system can't be automated and we need to manually validate the transaction. So rather looking for logs and get the transaction data from console or Jenkins logs, I'll prefer to save the data in junit reports it self.

**Comment by onsi** [comment]
hey @anshuljayn thanks for sharing how you're using the new feature.

When you say you want the flexibility to avoid including CodeLocation and Time do you mean in the JUnit file?  Or in the stdout output of the test run itself?  If you mean in the stdout output then I'd love to hear your thoughts on what I'm proposing above (namely: location and time are only visible during failures or when running with `ginkgo -v`).

As an aside I'd recommend checking out the new [JSON format](https://github.com/onsi/ginkgo/blob/ver2/docs/index.md#generating-machine-readable-reports) - the JUnit specification is somewhat limited and Ginkgo's native JSON format provides a lot more information about your test suites.

**Comment by anshuljayn** [comment]
Just to control the output in the jUnit report, I am using Jenkins junit plugin which generate reports as follow - 

Standard Output
Report Entries:
baz
/Users/user1/GitHub/tempe2etemp/temp.go:35
2021-12-19T21:27:37.761123207Z
bux
--
foo
/Users/user1/GitHub/tempe2etemp/temp.go:36
2021-12-19T21:27:37.761123207Z
bar

Where as I would prefer it to be able to have it as below for better readability and less data (which is not required in my case)
Standard Output
Report Entries:
baz : bux
--
foo : bar

if something can be done would be great else I can use some workaround.

**Comment by onsi** [comment]
hey sorry for the delay on my end.

thanks for the additional detail.  imo the junit and json report formats should have as much information as possible and formatting/visibility should be controlled downstream by whatever agent is constructing the view of the report.  I'm not super-inclined to add complexity in the form of configurability for the machine-readable formats.
