### ISSUE TITLE
Detecting if a suite has failed in `AfterSuite` blocks

### ISSUE THREAD

**Issue by austince** [onsi/ginkgo#873]
Hi there, I'm currently trying to check if any of the specs in a suite have failed during test cleanup. If so, I'd like to collect some debug information and write it to a file before cleaning up the created resources.

In ginkgo 1, a custom reporter works ok for this, but I know they have been removed in ginkgo 2. I've considered the new `ReportAfterEach`, but these run after the cleanup code and feels like abusing the constructs to put cleanup code in there. Is there another way to detect if a suite has failed before cleaning up? 

Thanks!

**Comment by onsi** [comment]
hey @austince - I think it would help to have a bit more detail about the use case and lifecycle for your specs but some quick thoughts ahead of that.

If the intent is to save off debug information after each failed spec then I'd put that code in an `AfterEach` and use [`CurrentSpecReport()`](https://onsi.github.io/ginkgo/#getting-a-report-for-the-current-spec) to figure out if the spec failed or not.  If it failed - I'd store off the debug information and then cleanup.

One question is _where_ to put the debug information.  You can write it to the filesystem but that could get tricky if you want to run in parallel.  In Ginkgo V2 I'd suggest adding the debug information as a `ReportEntry` via [`AddReportEntry`](https://onsi.github.io/ginkgo/#attaching-data-to-reports).  This information will then end up in the JSON/JUnit output (if you use `--json-report/--junit-report`) and on the console.

If the intent is to save off debug information at the _very end_ of the entire suite then I'd use `ReportAfterSuite` to figure out what failed and then save off the diagnostics.

If what you want is to aggregate debug data for failures as the suite runs and then produce a single coherent report in your own format that includes the debug information I'd combine the two approaches.  I'd use `AddReportEntry` to attach information to each failed spec, then I'd use `ReportAfterSuite` to walk through the specs, find the failed specs, pull and rehydrate the relevant `ReportEntries` and generate your own custom report that way.

If that last bit is close to what you want I can work up a bit more of a complete example if that would help but you can learn more by looking through the godocs for [SpecReport](https://pkg.go.dev/github.com/onsi/ginkgo/v2@v2.0.0/types#SpecReport) and [Report](https://pkg.go.dev/github.com/onsi/ginkgo/v2@v2.0.0/types#Report).

**Comment by austince** [comment]
hey @onsi, thanks for the quick and thoughtful response.

For context, I'm spinning up k8s clusters in a `BeforeSuite` and tearing them down in an `AfterSuite`, since they are a bit expensive. Before shutting them down, I'd like to report things like current pod logs, events, etc.

Taking a look at the `ReportEntry` framework in v2, I can easily see how this could be implemented as you describe, thanks for that! One thing I'd like is to write them to a separate place than the JSON/Junit output, which seems like it would be possible with the `AddReportEntry` + rehydration method you described.  As soon as we upgrade to v2, I'll give this a shot and report back :) Thanks again!

**Comment by onsi** [comment]
hey @austince - glad it was helpful.  please ping me if you run into any issues.  I'll just call out the specific thing to be aware of since it's a bit buried in the docs [here](https://pkg.go.dev/github.com/onsi/ginkgo/v2@v2.0.0/types#ReportEntry.GetRawValue) - you'll want to grab `entry.Value.AsJSON` and run _that_ through the json decoder to reconstitute your original object.

**Comment by ezequiel-aguilera-uala** [comment]
Use {command} || (make something)

Example, when tests fail play a loser song of this repo [](https://github.com/ezequielaguilera1993/tocadiscos)


```
GREEN=\033[0;32m
NC=\033[0m # No Color

tests:
	@echo "${GREEN}Running TESTs${NC}"
	$(HOME)/go/bin/ginkgo version
	$(HOME)/go/bin/ginkgo unfocus
	rm -f ./test/coverage.out
	$(HOME)/go/bin/ginkgo -r --progress --fail-fast --randomize-all --randomize-suites --fail-on-pending --trace --coverpkg=github.com/sarasa/... --coverprofile=coverage.out --output-dir=./test || (make playLooserSong)
	go tool cover -html=./test/coverage.out -o ./test/coverage.html

playLooserSong:
	@if [ -z "$$GITHUB_ACTIONS" ]; then \
		go get github.com/ezequielaguilera1993/tocadiscos; \
		mkdir tmp; \
		TMP_FILE="./tmp/playLooserSong.go"; \
		echo "package main;import \"github.com/ezequielaguilera1993/tocadiscos\";func main() {tocadiscos.PlaySong(tocadiscos.LooserSong)}" > $$TMP_FILE; \
		echo "${GREEN}WOW you suck! This is really a bad code.${NC}"; \
		go run $$TMP_FILE > /dev/null; \
		rm -rf tmp; \
		echo "${GREEN}Greetings 👍${NC}"; \
	fi
```
