### ISSUE TITLE
Ginkgo's DSL `Labels` type pollutes user modules when dot-importing github.com/onsi/ginkgo/v2

### ISSUE THREAD

**Issue by TheDiveO** [onsi/ginkgo#876]
What have I been warned of dot imports ... but here we Go 😀: `Labels` seems to be a type that is loved and declared in so many places (I'm afraid that my phrasing still won't be sufficient for a Purlitzer, though). Think of HTTP, containers, ...

With Ginkgo v2 the newly added `Labels` types now will conflict with existing `Labels` types in the user's modules, because of the highly generic type name. For me, this blocks upgrading several of my public and company Go modules as I don't see rationale -- despite my love for Ginkgo -- to change existing code for the sake of a TDD module polluting user module type space.

While this will be another breaking change for v2, can we please move Ginkgo's `Labels` out of the way without having to remove all dot-imports in existing user code? Can we rename it to something like `TestLabels`?

**Comment by onsi** [comment]
Ouch.  The dangers of dot-imports indeed.  Strictly speaking I'd have to release a 3.0 with this change but I can perhaps get away with a 2.0.1 since it's very early days.

Is the issue that you are dot-importing the code under test?  And so don't want to change the actual production code (totally fair)?  Or is the issue that you have a type named `Labels` in your test suites (arguably could be changed as part of the upgrade?)  If it's a production code issue I've generally (arguably, hypocritically) advocated not dot-importing production code under test to avoid the namespace battle.

In any event rather than change to `TestLabels`  I'd sooner find a better long term solution and rip the bandaid off now.  Perhaps something like Decorators.Labels or a new decorators package that can be optionally dot-imported.

**Comment by TheDiveO** [comment]
Ah, good question for clarification: it's not dot-importing the code under test, but dot-importing Ginkgo v2 into the white-box test code. The reason for white box testing is that the testing code needs access to the non-exported functions and methods.

I've not yet committed this upgraded code, but the problem arises in this Go package [https://github.com/TheDiveO/lxkns/tree/master/model](https://github.com/TheDiveO/lxkns/tree/master/model). This package defines [`type Labels map[string]string`](https://github.com/TheDiveO/lxkns/blob/f54f2b1f8b947e28a5fffb18cb2b9fec68e21525/model/container.go#L64) (permalink).

The `package_test.go` inside this package then looks as follows, because it does white box testing (same problem with the other `*_test.go` in this package) it's in package `model` and not `model_test`:

```go
package model

import (
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

func TestNamespaceTypes(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "lxkns/model package")
}
```
 
In consequence, the Go compiler barks (didn't know that Gophers bark until now):

```
# github.com/thediveo/lxkns/model [github.com/thediveo/lxkns/model.test]
model/namespaces_test.go:18:2: Labels redeclared during import "github.com/onsi/ginkgo/v2"
        /home/harald/github/lxkns/model/container.go:64:6: previous declaration
model/package_test.go:20:2: Labels redeclared during import "github.com/onsi/ginkgo/v2"
        /home/harald/github/lxkns/model/container.go:64:6: previous declaration
...
```

Dot-importing Gingko is otherwise fine, as its DSL is very domain-specific, so there's a really low chance in reality to get a conflicting `Define`, `It`, ... in practise. It's just with `Labels`, but even that didn't turn up during the RCs (because on my side I didn't test it during RC when I could have).

If the `Label` would have been only in my test suite then I would have simply renamed that, because that's the most simplest thing to do 😀. But I'm hesitant to rename any normal export, as it is the case here.

**Comment by TheDiveO** [comment]
> Ouch. The dangers of dot-imports indeed. Strictly speaking I'd have to release a 3.0 with this change but I can perhaps get away with a 2.0.1 since it's very early days.

Maybe I should file a feature request against Go modules for handling `.0` release always differently and with greatest care anyway...

> In any event rather than change to `TestLabels` I'd sooner find a better long term solution and rip the bandaid off now. Perhaps something like Decorators.Labels or a new decorators package that can be optionally dot-imported.

Even if it may look slightly counter-intuitive at first sight: what about a `spec` package (instead of `decorator`)? ...as the [type `Labels` comment](https://github.com/onsi/ginkgo/blob/6f8577e204f044110ba6e8bd106917993bcf12e2/decorator_dsl.go#L79) in `decorator_dsl.go` links to the documentation anchor `#spec-labels`. Would be shorter to write than `decorator` and less generic.

**Comment by TheDiveO** [comment]
For the moment, I can work around by importing ginkgo as `g "github.com/onsi/ginkgo/v2"` and then using `g.Describe()`, `g.It()`, et cetera. Not nice, but workable. But `spec.Labels` would be keeping the existing v1 dot-imports and yet make things clear when it comes to `Labels` (and maybe other decorators): they're for the (test) spec, not from the user packages.

**Comment by onsi** [comment]
I went on a run this morning and may have come up with a (relatively elegant? maybe??) solution.  (This happens often enough that I refer to it as run-driven development).

In 2.0 I broke the DSL out into a couple of different files to make it easier for myself to keep things organized within the `github.com/onsi/ginkgo/v2` package.   You can see this on the [master branch](https://github.com/onsi/ginkgo) as `*_dsl.go`.  What if I:

- Keep the default DSL the same (this doesn't help you) - the default `import . "github.com/onsi/ginkgo/v2"` continues to work for everyone
- But then introduce a new set of packages under `github.com/onsi/ginkgo/v2/dsl/*` that break the DSL out more granularly that users can pull in piecemeal.  I think it would naturally organize along the same lines as what's currently in the root package:
    - `import . github.com/onsi/ginkgo/v2/dsl/core` - imports all the core stuff into the global namespace.  This'll have all the main DSL elements and is the only thing most specs will need to import.
    - `import decorators github.com/onsi/ginkgo/v2/dsl/decorators` - would pull in the decorators in a namespaces way, this would solve your problem
    - etc. for `reporting`, `ginkgo_t`, and `table`

Then, for your white box tests (thanks for the context, btw, totally makes sense) you can replace `github.com/onsi/ginkgo` with `github.com/onsi/ginkgo/v2/dsl/core` when you upgrade and Everything Should Just Work™.  Then if you want to get at the decorators or reporting infrastructure you would pull in those piecemeal packages.

This allows me to ship a 2.1 that: (a) doesn't break the major version contract, (b) gives me a more sustainable path to guide folks who hit a namespace collision, and (c) gives consumers of Ginkgo a few more options to control which bits and pieces they want to import without losing the convenience of importing the whole thing.

WDYT?

**Comment by TheDiveO** [comment]
L(V)GTM ... and I'm using a similar hike-driven development model 😁

**Comment by onsi** [comment]
Great!  will work on it and aim to ship 2.1 next week

**Comment by onsi** [comment]
hey @TheDiveO - I just pushed the new `dsl` packages to master.  If you have some time could you give 90868e2501c74f1be47c3da3a6343b73b9cbed60 a try?

I've also updated the [docs](https://onsi.github.io/ginkgo/#alternatives-to-dot-importing-ginkgo) to cover how to use them.

If you're able to take a look that would be great.  I can cut a release after I get a "works for me" from you.

**Comment by TheDiveO** [comment]
That's great! Hopefully I can give it a quick try this evening and then give thumbs up. In any case, many thanks! hooray to sports-driven-design.

**Comment by TheDiveO** [comment]
🎉 importing `v2/dsl/core` perfectly works for me, no more conflicts. Thank you very much!

Please excuse me for not being able to check and report earlier, as I was tied up in some heavy architectural day-time work.

**Comment by onsi** [comment]
no worries at all.  thanks for taking a look and making sure things work!
