### ISSUE TITLE
Is there a script for verify license for v2?

### ISSUE THREAD

**Issue by Thor-wl** [onsi/ginkgo#877]
Hi. I updated my ginkgo to v2.0.0 recenetly. But it loses effect for my verify license sciprt for the v2 will not put license file under root directory of the project directly. The directory struct changes to /vendor/ginkgo/v2/license. I wonder is there some scripts for use? My privious script is https://github.com/volcano-sh/volcano/blob/master/hack/verify-vendor-licenses.sh

**Comment by onsi** [comment]
hey there @Thor-wl - seems like an issue in the script.  Ginkgo's github repo includes an MIT license in the root directory.  You may want to open an issue with the source of that script as other v2 modules may have the same issue.
