### ISSUE TITLE
Timeout on setup nodes in ginkgo v2

### ISSUE THREAD

**Issue by mgoerens** [onsi/ginkgo#882]
I've upgraded my project to ginkgo v2 today.

With ginkgo v1.x, I could add a 60s timeout to `BeforeSuite` (among other setup nodes) like this:
```
var _ = BeforeSuite(func() {
    # PrepareSpec
}, 60)
```

Is there a way to achieve the same behavior in ginkgo v2 ?

**Comment by blgm** [comment]
Hi @mgoerens. My guess (which may be corrected by @onsi later) is that this relates to the removal of async tests, with the recommendation to use async assertions instead: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-async-testing

**Comment by onsi** [comment]
That's right @blgm - @mgoerens please take a look at the section of the migration doc George linked to.  There's also a deeper dive into asyn testing patterns in the documentation [here](https://onsi.github.io/ginkgo/#patterns-for-asynchronous-testing).

If you run into issues let us know and we can help further.  In fact if you can point me at your code (if it's open source) i can make some concrete suggestions on how to migrate things beyond the simple first-pass shared in the migration doc.

**Comment by mgoerens** [comment]
Thanks a lot for your answers. I had another look at the docs.

Of course, the reality is a bit more complex than my very simple code snippet :) I'm using `operator-sdk` (https://github.com/operator-framework/operator-sdk/) to build a go-based Kubernetes Operator. `operator-sdk` scaffolds a base project, including a minimal `suite_test.go`, using ginkgo 1.x, and using the deprecated timeout feature on `BeforeSuite`. Here is an example of a  scaffolded project without any further customization: https://github.com/opdev/synapse-operator/blob/89f06097cffe2f3feb710891118663eed4aa1ed5/controllers/synapse/suite_test.go

Note that this is for integration tests, and it starts a test environment using `envTest`.

I'm not a developer of `operator-sdk`, so I can only guess the logic behind the 60s timeout. Most likely the intention is to make sure that tests setup (the whole `BeforeSuite` node), doesn't take more than 60s. Hence my original question.

The actual line which is likely to hang is probably `cfg, err := testEnv.Start()` so I could add a timeout for this line only if that's easier. Right now I simply fixed the error by removing the timeout altogether.

**Comment by onsi** [comment]
hey @mgoerens will reply more when i'm at my computer.  for now just wanted to let you know that github link 404s.  any chance you have a public repo i can look at?

**Comment by mgoerens** [comment]
Right, forgot this was still private. I set the visibility of the repository to public now, as it should be.

**Comment by onsi** [comment]
Thanks for opening the repo up.  It looks like the original code you've linked to wasn't doing what folks expect.  In Ginkgo V1 the timeout only applies if the function passed to `BeforeSuite` accepts a `Done` channel argument.  The [code in the repo you linked to does not](https://github.com/opdev/synapse-operator/blob/89f06097cffe2f3feb710891118663eed4aa1ed5/controllers/synapse/suite_test.go#L52) - which basically means it was running synchronously and the time out wasn't being enforced.

So, you can just drop the 60 and move on.  In fact, I dug in a bit deeper and it looks like `testEnv.Start()` includes some internal timeouts to guard against things taking too long.  I believe it'll return an error if the timeout elapses.

If you _do_ want to wrap your own timeout around `testEnv.Start()` you can:

```go
var _ = BeforeSuite(func() {
	logf.SetLogger(zap.New(zap.WriteTo(GinkgoWriter), zap.UseDevMode(true)))

	By("bootstrapping test environment")
	testEnv = &envtest.Environment{
		CRDDirectoryPaths:     []string{filepath.Join("..", "..", "config", "crd", "bases")},
		ErrorIfCRDPathMissing: true,
	}

        var cfg *rest.Config
        var err error
        done := make(chan interface{}, 0)
        go func() {
            defer GinkgoRecover()
	    cfg, err:= testEnv.Start()
            close(done)
        }()
        Eventually(done).WithTimeout(time.Minute).Should(BeClosed())
	Expect(err).NotTo(HaveOccurred())
	Expect(cfg).NotTo(BeNil())
       
	err = synapsev1alpha1.AddToScheme(scheme.Scheme)
	Expect(err).NotTo(HaveOccurred())

	//+kubebuilder:scaffold:scheme

	k8sClient, err = client.New(cfg, client.Options{Scheme: scheme.Scheme})
	Expect(err).NotTo(HaveOccurred())
	Expect(k8sClient).NotTo(BeNil())

})
```

**Comment by mgoerens** [comment]
Great infos, thanks a lot ! There's nothing else to add I think :)
