### ISSUE TITLE
skip and only flags

### ISSUE THREAD

**Issue by Lehp** [onsi/ginkgo#884]
One of the most convenient features of mocha was the .only flags which executes only one test and ignores all the others. It would make it way easier to focus on my work. 

I read the documentation and didn't see a way to debug only one test. I hope i didn't miss anything. 

love ur work <3

**Comment by blgm** [comment]
Hi @Lehp. I think what you're looking for is called "focus" in Ginkgo:
https://onsi.github.io/ginkgo/#focused-specs
