### ISSUE TITLE
`ginkgo ... -race` fails on `gexec.Build`

### ISSUE THREAD

**Issue by mamachanko** [onsi/ginkgo#887]
👋  Hi!

I am building my CLI with `gexec.Build` within a `BeforeSuite` container. When I am running my tests with the [recommended flags for CI](https://onsi.github.io/ginkgo/#recommended-continuous-integration-configuration) they fail. If I omit `-race`, they pass. There is, however, no condition that should trigger the race detector.

To demonstrate and reproduce the issue I built [mamachanko/ginkgo-race-fails-to-gexec-build](https://github.com/mamachanko/ginkgo-race-fails-to-gexec-build). Run `make test` and `make test-no-race` to see that one fails and the other passes.

[Here's the `gexec.Build` invocation that fails](https://github.com/mamachanko/ginkgo-race-fails-to-gexec-build/blob/main/ginkgo_race_fails_to_gexec_build_suite_test.go#L19):
```
------------------------------
[BeforeSuite] [FAILED] [0.008 seconds]
[BeforeSuite]
/Users/mbrauer/workspace/ginkgo-race-fails-to-gexec-build/ginkgo_race_fails_to_gexec_build_suite_test.go:17

  Unexpected error:
      <*errors.errorString | 0xc000074d30>: {
          s: "Failed to build github.com/mamachanko/ginkgo-race-fails-to-gexec-build:\n\nError:\nexit status 2\n\nOutput:\n",
      }
      Failed to build github.com/mamachanko/ginkgo-race-fails-to-gexec-build:

      Error:
      exit status 2

      Output:

  occurred
  In [BeforeSuite] at: /Users/mbrauer/workspace/ginkgo-race-fails-to-gexec-build/ginkgo_race_fails_to_gexec_build_suite_test.go:20

  Full Stack Trace
    github.com/mamachanko/ginkgo-race-fails-to-gexec-build_test.glob..func1()
        /Users/mbrauer/workspace/ginkgo-race-fails-to-gexec-build/ginkgo_race_fails_to_gexec_build_suite_test.go:20 +0x10c
------------------------------
```

I am misunderstanding `-race` or `gexec.Build`, or am I doing something fundamentally wrong?

Ty!

**Comment by onsi** [comment]
...strange.  Thanks for the repro repo.  I cloned it and, unfortunately (?), both `make test` and `make test-no-race` pass on my machine.  I'm running on an apple silicon machine and I believe the race detector can have subtle differences based on architecture...

...with that said, Ginkgo and Gomega's CI run with the race detector on on GitHub's linux boxes - so `amd64` and both suites do exactly what your suite is doing without issue.

it seems especially strange that the [output you list](https://github.com/mamachanko/ginkgo-race-fails-to-gexec-build#-tests-fail-with-ginkgo---race) doesn't include any mention of a race being detected.

Are you up for taking Ginkgo out of the equation?

What happens on your box if you get rid of all the Ginkgo test files and, instead, have a single `main_test.go`:

```go
func TestGexecRace(t *testing.T) {
       gexec.Build("github.com/mamachanko/ginkgo-race-fails-to-gexec-build")
       gexec.CleanupBuildArtifacts()
}
```

and run _that_ with `go test -race`?

**Comment by mamachanko** [comment]
Thank you for looking into it @onsi !

I followed your suggestion, got rid of all the Ginkgo test files and ran it like that. [Here's what I see](https://gist.github.com/mamachanko/668eb86107f400c124d549fba6385967#file-output-L53-L173) (scroll up for more contextual info).

Fwiw, when containerized it passes on my machine as well:
```shell
docker run \
  --rm \
  golang:1.17 \
  bash -c 'git clone https://github.com/mamachanko/ginkgo-race-fails-to-gexec-build && cd ginkgo-race-fails-to-gexec-build && make test'
```

**Comment by mamachanko** [comment]
Since I was on `go1.17.5` I upgraded to `go1.17.6` and the failure disappeared, even with the original, untouched repo.

```shell
❯ go version
go version go1.17.6 darwin/amd64

❯ make test
# Recommended flags according to https://onsi.github.io/ginkgo/#recommended-continuous-integration-configuration
go run github.com/onsi/ginkgo/v2/ginkgo \
  -r \
  --procs=1 \
  --compilers=1 \
  --randomize-all \
  --randomize-suites \
  --fail-on-pending \
  --keep-going \
  --cover \
  --coverprofile=cover.profile \
  --race \
  --trace \
  --json-report=report.json
[1642933693] GinkgoRaceFailsToGexecBuild Suite - 1/1 specs • SUCCESS! 788.294907ms PASS
coverage: 0.0% of statements
[1642933693] GinkgoRaceFailsToGexecBuild Suite - 1/1 specs • SUCCESS! 398.368904ms PASS
coverage: 0.0% of statements
composite coverage: [no statements]

Ginkgo ran 2 suites in 3.222305255s
Test Suite Passed
```

🥳

**Comment by onsi** [comment]
🎉 great to see this was an issue fixed in the latest go version
