### ISSUE TITLE
When running against multiple packages, `ginkgo --cover` should generate a composite coverfile and emit a single coverage percentage

### ISSUE THREAD

**Issue by onsi** [onsi/ginkgo#89]

**Comment by robdimsdale** [comment]
I would like to +1 this.

I'm currently using [gover](https://github.com/modocache/gover) to collect various `coverfiles` in preparation for sending to a coverage processor (e.g. coveralls.io) and it would be an easier workflow if ginkgo collected them for me.

**Comment by tve** [comment]
+1 on doing it "right". But I'm not sure there is one right way... I write a lot of high-level functional test and often end up with tests at the top level that really test subpackages. The net effect is that I want coverprofiles to be merged and not just concatenated. The way I do that is my Makefile's cover rule has something like:
```
        @for f in `find . -name \*.coverprofile`; do tail -n +2 $$f >>_total; done
        @echo 'mode: atomic' >total.coverprofile
        @awk -f merge-profiles.awk <_total >>total.coverprofile
```
and the awk script to do the merging is:
```
#! /usr/bin/awk
BEGIN { FS = " " }
NF == 3 {
        k = $1 " " $2;
        if (k in block) block[k] += $3
        else block[k] = $3
}
END {
        for (k in block) {
                print k, block[k]
        }
}
```
I hope this helps...

**Comment by mantzas** [comment]
+1

**Comment by thedodd** [comment]
+1 this would be pretty fantastic!

**Comment by thedodd** [comment]
If someone want's to point out the code which needs focus, I am happy to take a crack at it. Haven't looked at the codebase for this project yet.

**Comment by johanbrandhorst** [comment]
What is the status of this? Seems like it would be a nice feature.

**Comment by AlexeySoshin** [comment]
@onsi I'm thinking of implementing this together with -outputdir, which doesn't work right now, and after PR #355 is merged. WDYT?

**Comment by onsi** [comment]
Yes!!!! Thanks :) - I hope to take a look and merge your PR tomorrow.
