### ISSUE TITLE
Using the dsl packages exclusively ignores command line arguments after --

### ISSUE THREAD

**Issue by jhernand** [onsi/ginkgo#891]
I have noticed that when importing only the `dsl/...` packages the test suite is not considered a `ginkgo` test suite (flag `IsGinkgo` is set to false). A side effect of that is that command line arguments passed after `--` in the command line of the `ginkgo run ...` command are not passed to the test binary. In addition the output is not the expected/pretty one generated by `ginkgo`. I think the reason for this is that the tool makes that decision looking for `ginkgo/v2"` inside the source code, and that fails when only the `dsl/...` packages are imported:

https://github.com/onsi/ginkgo/blob/2b99589d37a830dd7e04a4b28919b2ee39fa8486/ginkgo/internal/test_suite.go#L269-L283

The workaround is easy: import the main package at least in one of the files. But would be nice if that wasn't necessary.

**Comment by onsi** [comment]
omg what a dumb bug, so sorry :(

thanks for reporting it!  i'll fix it and push out 2.1.1 soon.

**Comment by onsi** [comment]
This is now fixed in v2.1.1

**Comment by jhernand** [comment]
Great! Thank you very much @onsi.
