### ISSUE TITLE
Is there a way to timeout individual tests?

### ISSUE THREAD

**Issue by johnSchnake** [onsi/ginkgo#897]
Hi, I work to maintain the [Sonobuoy](https://github.com/vmware-tanzu/sonobuoy) project and the most common use case is testing Kubernetes clusters via the Kubernetes conformance tests.

When a cluster is broken, I'd love to be able to run a handful of tests quickly to try and diagnose the problem. The problem I'm running into is this:

 - Given that I've chosen my tests based on their happy path speed; each test typically finishes in less than 5s, often <1s....
 - Given that there are quite a few tests, ~250 and they run in parallel...
 - Problem: when the cluster is broken the fast tests now typically hit timeout code paths and lead to a 5s test taking 1-5m. Since failures my be related, I may end up with 50 failing tests and so I end up hitting 1-4 hours runtime instead of just a few minutes.

I know there are timeouts for the whole suite, but I would like to avoid that because instead of running 250 tests I will timeout after only hitting a handful of errors instead of getting the coverage I want.

What I would ideally like is a way of saying that if a tests runs for more than 10s, assume it is a failure and move on to the next test. That way I still quickly move through all my tests despite the failures.

I've looked but I can't see that something like this is possible without modifying the tests to have shorter timeout periods manually (which isnt feasible in this case; we aren't modifying the Kubernetes tests themselves for this).

Thanks for any insight or suggestions you can provide.

**Comment by onsi** [comment]
hey @johnSchnake thanks for the detailed explanation of the use-case!  In Ginkgo 1.0 there was a somewhat clunky ability to mark individual nodes (i.e. `It`, `BeforeEach` etc.) as asynchronous and add a per-node timeout.  [I removed this in Ginkgo 2.0 for a number of reasons](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-async-testing) and am encouraing folks to use more Gomega's `Eventually` to thread more granular timeouts through their code.

As it stands right now, I don't think it's possible to do what you want.  I can easily imagine having a test suite that aborts if it detects systemic timeout failures:

```go
var _ = ReportAfterEach(func(report SpecReport) {
    if (report.RunTime > time.Second*10) {
       AbortSuite("Everything is gonna fail...")
    }
})
```

But that isn't what you want.  You want to be able to say "fail individual specs after `X` seconds but keep going".

Your use-case makes a lot of sense though and I'm open to reintroducing spec-timeouts as a new 2.0 decorator that now applies across all the nodes in a spec.  The challenge with the old async behavior (which will resurface should I add such a decorator) is that Ginkgo's use of globals and the fact that one groutine can't kill off another means that a spec that has timed out will continue to run in the background and eventually fail - but that the failure will be registered against whatever spec is currently running.  I can help make users more aware of this with Ginkgo's timeout failure message, but it can make for some confusing test failures if one isn't careful and is ultimately why I removed the async support.

In any event, I'm open to adding this to the 2.x line and can imagine a few options (which can all work together, they aren't mutually exclusive):

- you can run `ginkgo --per-spec-timeout=X` to set a global per-spec timeout - this will override any per-spec decorations.
- you can add a new `FailAfter(time.Duration)` decorator to any `It`, `Describe`, `Context` node to decorate individual specs with a timeout.

Thoughts?

**Comment by johnSchnake** [comment]
Thanks for the thorough response. Let me think on it for a days and see how those options sit. I'm also attending one of the k8s working groups and may be able to bring it up.

**Comment by onsi** [comment]
👍 stepping back - one thing to consider is whether there are changes that can be made to the test suite to make it more robust/responsive when a systemic failure occurs.  or, put differently: "why _does_ it take the test five minutes to fail?  and the whole suite O(hours)?  is that reasonable?  should the timeout be changed or more easily configured? is there a top-level or context-dependent `BeforeEach` guard that is missing that can quickly identify if a time-out failure is likely (eg this entire subsystem is just not responding)?  etc."

i appreciate that with a big 'ol codebase and complex community dynamics it can be hard to address those sorts of issues.  and i'm quite open to brining back spec timeouts in ginkgo.  but these are the questions that come to mind when i consider your use case.

**Comment by johnSchnake** [comment]
I definitely don't think that the async failure causing _other_ tests to fail would be beneficial; I can see why you wanted to get rid of that behavior. Even if it made things faster, if we can't properly identify which failed then we don't really make progress.

As for why things take so long; its a series of hardcoded timeouts that are just too long for this particular use case. For instance, when creating a job, there is a JobTimeout value which defaults to 15m and is not customizable. Another timeout, again not configurable, is `pollTimeout  = 60 * time.Second`. If a test normally takes 5s, a 60s timeout is extremely long.

It may be much more reasonable to simply get k8s to add this as an option to override these timeouts. Upon looking, there may be some ability to override many of these (not sure if all but its worth a shot; I found `NewTimeoutContextWithDefaults`)

The idea of decorating individual tests with the `FailAfter...` would be great if we could shim that in so that _every_ spec has it. But it sounds like you're saying thats not really feasible?

I'm going to try to see what else I can do from within the existing framework and I'll let you know where the problem stands afterwards.

**Comment by onsi** [comment]
> I definitely don't think that the async failure causing other tests to fail would be beneficial; I can see why you wanted to get rid of that behavior. Even if it made things faster, if we can't properly identify which failed then we don't really make progress.

^- agreed.  In your use case are you trying to automate interpretation of the failures?  Or is this for a human to look at output and make a diagnostic decision.  If the latter then such failures, though confusing, might be "good enough" - especially with adequate warning (e.g. I could have failures explicitly say "hey there was a timeout so take a look at the source lines to see where this failure actually originated" - clunky, but potentially better than nothing).

> The idea of decorating individual tests with the `FailAfter...` would be great if we could shim that in so that every spec has it. But it sounds like you're saying thats not really feasible?

Not necessarily - you could still run `ginkgo --per-spec-timeout=X` and I could also imagine having Ginkgo's entry-point `RunSpecs` accept the `FailAfter...` decorator and apply it to all specs in the suite.

> It may be much more reasonable to simply get k8s to add this as an option to override these timeouts. Upon looking, there may be some ability to override many of these (not sure if all but its worth a shot; I found NewTimeoutContextWithDefaults)

This seems reasonable to me too.  If all the async-timeouts are already there then making them adjustable seems like the right tool for the job vs something more blunt like a spec-wide or suite-wide timeout.

>I'm going to try to see what else I can do from within the existing framework and I'll let you know where the problem stands afterwards.

All the best as you try to figure it out.  I'm totally open to adjusting Ginkgo to find ways to suit this use case.  And I'd love, someday, to find a way to get past the single-global-fail-handler problem.  I could imagine allowing some specs to optionally receive their own Fail object (or their own Gomega) so the I can better track where failures originated.  That would enable this use case and generally make async failures more sane... but it would entail rewriting all test suites everywhere to make use of the feature.

**Comment by onsi** [comment]
Closing this out now that interruptible nodes and timeout decorators have been shipped.
