### ISSUE TITLE
Feature Request Validate Swagfile

### ISSUE THREAD

**Issue by Lehp** [onsi/ginkgo#898]
I've written a Function that takes json swagfiles and checks if the types of a json buffer (server response) equals the corresponding type in the swagfile. Idk if someone cares about this I'd be clad to help.

https://pkg.go.dev/github.com/lehp/goswag-validator/validate_json

**Comment by onsi** [comment]
Cool!  If you'd like you can implement this as a [Gomega matcher](https://onsi.github.io/gomega/#adding-your-own-matchers) and i'd be happy to mention it in the [list of community supported marchers](https://github.com/onsi/gomega/wiki)
