### ISSUE TITLE
Question: Is it possible to reference testing.T in the tests?

### ISSUE THREAD

**Issue by adamstep** [onsi/ginkgo#9]
Is it possible to reference `testing.T` in the tests? This is needed by [gomock](http://godoc.org/code.google.com/p/gomock/gomock) to create a new mock controller.

**Comment by librant** [comment]
why not transform the t *tesinging.T, the same as convey()?

**Comment by librant** [comment]
type GinkgoTestReporter struct {}

func (g GinkgoTestReporter) Errorf(format string, args ...interface{}) {
    Fail(fmt.Sprintf(format, args))
}

func (g GinkgoTestReporter) Fatalf(format string, args ...interface{}) {
    Fail(fmt.Sprintf(format, args))
}
[adamstep](https://github.com/adamstep) this should is Fail(fmt.Sprintf(format, args...)), need ...
