### ISSUE TITLE
New decorator for It blocks: Always

### ISSUE THREAD

**Issue by LittleFox94** [onsi/ginkgo#933]
Hi,

we are writing integration tests for API bindings with Ginkgo and Gomega and quite often use Ordered contexts to check CRUD-like operations with these bindings, like this:

```golang
It("creates a VLAN", ...)
It("retrieves the VLAN", ...)
It("eventually sees the VLAN being ready", ...)
...
It("deletes the VLAN", ...)
```

The problem is when one of the tests between "creates a VLAN" and "deletes a VLAN" fails - the VLAN will not be deleted. To work around this, we sometimes have a `BeforeAll` containing a `DeferCleanup` instead of the first `It`; in some other cases we have an `AfterAll` checking if the last `It` ran and cleaning up itself otherwise.

I want to propose a decorator for `It` blocks: `Always`. An `It` marked with `Always` will be run regardless if previous tests failed. It only makes sense in `Ordered` `Contexts` as only those are aborted when a spec fails. In the example given above, it could look like this:

```golang
It("creates a VLAN", ...)
It("retrieves the VLAN", ...)
It("eventually sees the VLAN being ready", ...)
...
It("deletes the VLAN", Always, ...)
```

This would be roughly equivalent to this, but much more elegant code:

```golang
cleanedUp := false
cleanup := func() {
  // do magic to clean up
}

AfterAll(func() {
  if !cleanedUp {
    cleanup()
  }
})

It("deletes the VLAN", func() {
  cleanup()
  cleanedUp = true
})
```

**Comment by onsi** [comment]
hey there sorry for the delayed response.  i've been taking some time off that last few days but will take a look at this and reply in more detail soon.

**Comment by LittleFox94** [comment]
No worries about the delay @onsi :)

in this exact case, creating and tearing down the VLAN is actual part of the test suite, not a prerequisite for them - if it was a prerequisite, a BeforeAll and AfterAll would be correct, yes.

I agree adding more complexity to lifecycle of things is probably not good in the long term. I'm wondering if there is some syntactic sugar possible, doing the `AfterAll(if It didn't run: run code)` - maybe looking like this from the user perspective? I think I'll try to write something like this, as I can easily add and test this outside ginkgo code :)

```go
ItAlways("cleans up the vlan", cleanup)
```

**Comment by onsi** [comment]
hey, sorry I was never able to better engage with this.  if it's still an open issue let me know.  for now I'm going to close this as I try to clean up GInkgo's issue backlog.
