### ISSUE TITLE
How can we use ginkgo in Apple M1?

### ISSUE THREAD

**Issue by zaunist** [onsi/ginkgo#936]
Does v1.x version support on apple m1, I downloaded v1.16.4, but I got stuck in the process of running the test, I downloaded ginkgo through `go install`, I don't know if the version I downloaded this way supports arm64 architecture.

Ginkgo Version 1.16.4

**Comment by blgm** [comment]
I don't have an Apple M1 to try this out. What's the error that you are seeing?

**Comment by zaunist** [comment]
> I don't have an Apple M1 to try this out. What's the error that you are seeing?

Sorry, I checked again, it's not ginkgo error, I would close this issue.
