### ISSUE TITLE
Allow turning on reporter via env variables

### ISSUE THREAD

**Issue by roopakv** [onsi/ginkgo#939]
While we use the ginkgo framework we do not use the Ginkgo CLI. 

in V2 we are forced to use the CLI to support junit reporters. Would be nice to be able to enable reporters without needing to switch to the CLI

**Comment by onsi** [comment]
Hey there,

I generally recommend using the CLI - it enables additional ginkgo functionality that you can't get from `go test` - and will not be adding environment-based configuration.

You can add a [`ReportAfterSuite`](https://onsi.github.io/ginkgo/#reporting-nodes---reportaftersuite) node that calls [`reporters.GenerateJunitReport()`](https://github.com/onsi/ginkgo/blob/master/reporters/junit_report.go#L130) depending on the presence of an environment variable if you want to implement this in your suite yourself.
