### ISSUE TITLE
running tests with --coverpkg=./...  does not give coverage across all packages

### ISSUE THREAD

**Issue by vedil** [onsi/ginkgo#944]
when i run tests like `ginkgo -p -covermode=count --cover  --output-dir=$(TESTDIR)   --coverpkg=./...  $(PKG1)`  would still give coverage only in $(PKG1)

where as if i run `ginkgo -p -covermode=count --cover  --output-dir=$(TESTDIR)   --coverpkg=$(PKG0),$(PKG2)  $(PKG1)`  would still give coverage in $(PKG0),$(PKG1),$(PKG2)

:( to get the list of all packages , output of go list ./... could not be used as it is, got it working using `go list -f='{{.ImportPath}}', ./..` and after piping that to ` echo "$(COVER_PKGS)"|tr -d "[:space:]"` , hope this might save some time for someone.

**Comment by onsi** [comment]
boo.  `ginkgo --coverpkg=X` simply passes `X` straight to `go test --coverpkg=X` - I'd suggest opening and issue over at the go repo to see if there's interest in having `cokerpkg` handle `./...`

(but please let me know if I'm mistaken and Ginkgo is munging `X` somehow)

**Comment by vedil** [comment]
closing this (might be some thing related to my project structure :( )
i tried creating a sample project there the result is as expected/documented
