### ISSUE TITLE
How can I run the test suite indefinitely?

### ISSUE THREAD

**Issue by alexgenco** [onsi/ginkgo#947]
This would allow me to use a ginkgo test suite for e.g. continuously smoke testing an API. It seems like the options are:

- `--repeat=<large int>`
- `--until-it-fails` + hacking assertions to never actually fail
- `FlakeAttempts(<large int>)` + permanently failing test
- wrap `RunSpecs` in a loop (explicitly not allowed)
- wrapper script

I would prefer not to use a wrapper script because I would want to serve a permanent prometheus scrape endpoint while the tests are running to expose metrics.

Is there a known workaround here, or would you be open to adding a `--forever` option, decorator, or something along those lines?

Thanks!

**Comment by alexgenco** [comment]
Thanks @onsi this is an interesting idea spawning a subprocess and parsing its JSON report for metrics. I'll give it a shot and report back if I have any issues.

**Comment by onsi** [comment]
great!  let me know how it goes.  i haven't documented how to read/parse the json format in detail but you should be able to unmarshal ginkgo's generated json file into a `[]types.Report{}` object [defined here](https://github.com/onsi/ginkgo/blob/master/types/types.go)

**Comment by alexgenco** [comment]
Is there a way to write the json report to stdout, rather than to a file? It doesn't seem like `--json-report=-` or `--json-report=/dev/stdout` work. The former seems to be ignored, and the latter fails with

```
  Failed to generate JSON report:
  open /Users/.../dev/stdout: no such file or directory
  In [ReportAfterSuite] at: /Users/.../github.com/onsi/ginkgo/v2@v2.1.3/reporting_dsl.go:121
```

It looks like it's converting it to a relative path

**Comment by onsi** [comment]
nope sorry it spits out to a file and doesn't support stdout.  i could do that for you in the ginkgo cli but the reality is i would write it to a temp file and then read it and pipe it to stdout - this is because the cli does some post processing to combine reports when running multiple suites.

**Comment by alexgenco** [comment]
This worked pretty well! Thanks for the suggestion. I do think it would be a nice convenience to support stdout, but I'm not blocked on that, and i feel like it might conflict with the progress output that's already there.

**Comment by onsi** [comment]
sweet! glad that worked out for you :)
