### ISSUE TITLE
print report before running the AfterEach/JustAfterEach sections

### ISSUE THREAD

**Issue by TomerJLevy** [onsi/ginkgo#952]
Hi, currently I see that the report is being printed after running the `JustAfterEach` and the `AfterEach` sections and before the `AfterSuite` section, is it possible to configure it to print the report before running the `JustAfterEach` and the `AfterEach` sections?

**Comment by onsi** [comment]
hey there @TomerJLevy - that ordering is not configurable.  Can I ask:  what problem are you trying to solve?  It may be that there are alternatives I can point you to.
