### ISSUE TITLE
Pending Specs was not outlined as pending when running ginkgo outline command

### ISSUE THREAD

**Issue by JiaYongfei** [onsi/ginkgo#955]
Spec:
`It("should be skipped too", Pending, func() {})`

Run 
`ginkgo outline --format=json <test_suite>` command

Output:
`{
        "name": "It",
        "text": "should be skipped too",
        "start": 1734,
        "end": 1784,
        "spec": true,
        "focused": false,
        "pending": false,
        "nodes": []
      }`

We can see that the pending field's value is false, which should be true

**Comment by onsi** [comment]
hey thanks for reporting this.  looks like I'll need to add decorator support to `ginkgo outline` - I'll try to work on that soon and publish a new release.

**Comment by Dannyb48** [comment]
@JiaYongfei @onsi I think we can close this one now with the merger of #1113

**Comment by onsi** [comment]
Yes!! Thanks so much @Dannyb48 - this will ship with the next release.
