### ISSUE TITLE
[Question] dump `specSummary` with dry-run in v2

### ISSUE THREAD

**Issue by chendave** [onsi/ginkgo#956]
I am trying to migrate ginkgo from v1 to v2, there were a custom report defined to dump the  `specSummary` with `dryRun` mode,  this is workable in the v1, and it was implemented in `SpecDidComplete`.
```
func (reporter *DetailsReporter) SpecDidComplete(specSummary *types.SpecSummary) {
     // dump the spec summary here.
}
```
The migration guide here: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#migration-strategy-2 suggests to add a `ReportAfterSuite` node and process the `types.Report` in v2 to replace custom report. I tried and found that if it's `dry-run` mode in v2 neither  `ReportAfterSuite("", func(report Report)`  nor `ReportAfterEach(func(report SpecReport)` would got called, so what's the best practice in v2 for me to dump the test spec with `dry-run` mode?

thanks a lot for any input!

**Comment by onsi** [comment]
hey there - this is similar to #935 - i'm going to be adding support for this in v2 soon
