### ISSUE TITLE
Is there a way to get the real-time num of specs like how many specs are running, passed, failed, to-be-running?

### ISSUE THREAD

**Issue by JiaYongfei** [onsi/ginkgo#964]
We'd like to show these kind of info on our platform to indicate the progress. Is there a way to get them?

**Comment by onsi** [comment]
hi @JiaYongfei sorry for the delay.  Please take a look at the [Generating reports programatically](https://onsi.github.io/ginkgo/#generating-reports-programmatically) portion of the documentation.  In particular, you can use [`ReportAfterEach`](https://onsi.github.io/ginkgo/#reporting-nodes---reportaftereach-and-reportbeforeeach)  to track whether a spec has passed/failed.  You could then send this information over to a server somewhere.

There is not currently support for getting the total number of specs that _will_ run.

**Comment by JiaYongfei** [comment]
Thanks. It helps.
