### ISSUE TITLE
Switch off fail on focus

### ISSUE THREAD

**Issue by zostay** [onsi/ginkgo#965]
Sorry if this already exists as a feature and I'm just not finding it: It would be helpful if there were a way to switch off returning a non-zero exit code on failure. I think that is a great default, but sometimes the exit code is helpful just to see if one or more tests in the suite are failing, i.e., when bisecting. If you want to focus on a single test and perform a bisect, this makes it somewhat painful to find what change resulted in the failure.

I thought `--fail-on-pending=false` might do it, but it didn't.  Otherwise, I'm not seeing an option that would, but I'm pretty new to Gingko, so I may have missed it.

**Comment by zostay** [comment]
My current work-around is a shell script like this:

```
#/bin/bash
ginkgo run ./test/pkg | grep '0 Failed'
```

**Comment by onsi** [comment]
You can set an environment variable like so: `GINKGO_EDITOR_INTEGRATION=TRUE`

It's a bit of a [hidden feature](https://github.com/onsi/ginkgo/blob/ce3d3731402b67a8d6dd966480924b7133bb5642/core_dsl.go#L292) but it's supported for editor integrations so don't worry about relying on it.
