### ISSUE TITLE
[Question] How to debug the node hangs when multiple nodes run in parallel

### ISSUE THREAD

**Issue by chendave** [onsi/ginkgo#970]
Hi, 

I am still working on the Ginkgo migration from V1 to V2 for Kubernetes (https://github.com/kubernetes/kubernetes/pull/109111), only one last job is failing and it is saying, 

```Ginkgo timed out waiting for all parallel procs to report back```

This job "pull-kubernetes-e2e-ubuntu-gce-network-policies" intends to run testcases with 15 nodes in parallel. Seems like the job failed with some node hangs, but I cannot find any useful information on where the issue comes from. 

Here is the [log](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109111/pull-kubernetes-e2e-ubuntu-gce-network-policies/1517327142990385152), and the [text log ](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/109111/pull-kubernetes-e2e-ubuntu-gce-network-policies/1517327142990385152/build-log.txt). I cannot get any useful or details information on which node hangs.

The job can pass in V1 and the issue is only found after the migration, can I assume there is no big issue for the testcases itself?

I noticed there is an option "-debug" in V1 which could emit the output to the files, but I cannot find the similar option in V2.

There are ton of testcases running in parallel, debug for the issue like this is super difficult for me.

Any suggestion on how to debug such issue?

**Comment by chendave** [comment]
@onsi , thanks for all the help you have provided, the migration is pretty close now, this is last one big problem as far as I can see now.

**Comment by chendave** [comment]
I saw the error message `Ginkgo timed out waiting for all parallel procs to report back` comes right after the below testcases, 

> • [SLOW TEST] [53.494 seconds]
[sig-network] Netpol NetworkPolicy between server and client should enforce egress policy allowing traffic to a server in a different namespace based on PodSelector and NamespaceSelector [Feature:NetworkPolicy]
test/e2e/network/netpol/network_policy.go:879
------------------------------

Is that meaning this testcase is the culprit? this testcase can pass with Ginkgo v1, what's the difference in v2?

**Comment by chendave** [comment]
the log says all the parallel processes run on the "Ginkgo node 0", this is something need to be optimized (ParallelProcess is not passed in correctly I think) but I don't think this is the root cause.

> I0422 02:58:15.341018   80519 e2e.go:128] Starting e2e run "b028b839-e91f-4cb1-a007-39564d6f2d45" on Ginkgo node 0

**Comment by onsi** [comment]
Hey @chendave - i'll try to find some time to reply and help this morning.

**Comment by onsi** [comment]
hey @chendave 

First to reply to some of your follow-up questions:

> the log says all the parallel processes run on the "Ginkgo node 0", this is something need to be optimized (ParallelProcess is not passed in correctly I think) but I don't think this is the root cause.

correct - I have no reason to believe the tests aren't being parallelized, this looks like a minor issue around passing in `ParallelProcess`.

> Is that meaning this testcase is the culprit? this testcase can pass with Ginkgo v1, what's the difference in v2?

No, it does not.  That test succeeded and finished.

---

When Ginkgo runs tests in parallel it launches multiple test processes and then monitors them.   The error you are seeing can occur if a test exists prematurely.  I'm not seeing anything odd in the logs but a have a few questions to help us make progress together:

1.  Does this happen consistently?  (i.e. every time you try running this set of tests?)
2. Can you try running the suite with `--output-interceptor-mode=none` (see *  below) and tell me if it behaves differently?
3. Can you point me to the source code for this subset of tests?

*Ginkgo does some fancy file descriptor duplication to capture stdout/stderr during a parallel test run.  There are certain situations where tests can launch processes that cause Ginkgo to hang.  That isn't what you're seeing, but I'd like to rule it out and it _is_ a potential difference between 2.0 and 1.0 (in 1.0 the hang could happen intermittently - in 2.0 it is more consistent and easier to deal with.

**Comment by chendave** [comment]
Thanks @onsi for the quick response! 

> Does this happen consistently? (i.e. every time you try running this set of tests?)

yes, the job (pull-kubernetes-e2e-ubuntu-gce-network-policies) never pass after the migration, I am trying to see whether it will fail intermittently on V1 and pushed a testing pr here (https://github.com/kubernetes/kubernetes/pull/109633).

> Can you try running the suite with --output-interceptor-mode=none (see * below) and tell me if it behaves differently?

tried here (https://github.com/kubernetes/kubernetes/pull/109111/commits/21c185f6034494e6e70b15a3361f46c135196ee9), let's see is there any difference.

> Can you point me to the source code for this subset of tests?

here is the filter string, 
`--ginkgo.focus=\[sig-network\]|\[Conformance\]|\[Feature:NetworkPolicy\]|\[Feature:NetworkPolicyEndPort\] --ginkgo.skip=\[Feature:\(Networking-IPv6|Example|Federation|PerformanceDNS|KubeProxyDaemonSetMigration|ProxyTerminatingEndpoints\)\]|DualStack|GCE|Disruptive|Serial|SNAT|LoadBalancer|ESIPP`

overall, there are 482 testcases are required for the job, this can be found from here [logs](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109503/pull-kubernetes-e2e-ubuntu-gce-network-policies/1515881392355938304), the testcases are dispersed in different directory, but most of them could be found from [here ](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/network).

Something I could try in my side,
- remove the "-nodes" parameters, and executes all test in serial, and see is there any difference.
- try to focus on the one specific type of features. e.g. I will try this focus string instead `--ginkgo.focus=[Feature:NetworkPolicy\]|\[Feature:NetworkPolicyEndPort\]`.

btw. I tried to run those testcases on my desktop, Ginkgo hangs as well after some exceptions, I am not sure whether this is related as some prerequisite cannot be satisfied on my desktop, and I haven't found this error string - "Ginkgo timed out waiting for all parallel procs to report back".  The Ginkgo seems never abort.

**Comment by chendave** [comment]
Tried with the option `--output-interceptor-mode=none`, the log shows something helpful,  the [log ](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109111/pull-kubernetes-e2e-ubuntu-gce-network-policies/1518068579122024448) here says there is concurrent map writes when using the deprecated `CurrentGinkgoTestDescription` method.

snap of the stack trace,

> vendor/github.com/onsi/ginkgo/v2/types/deprecation_support.go:106 +0x273 fp=0xc001a03150 sp=0xc001a03048 pc=0x26f4653
  > k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2.CurrentGinkgoTestDescription()
  	vendor/github.com/onsi/ginkgo/v2/deprecated_dsl.go:80 +0x1c5 fp=0xc001a037f0 sp=0xc001a03150 pc=0x29cc565
  k8s.io/kubernetes/test/e2e/framework.LoadConfig.func1()
  	test/e2e/framework/util.go:492 +0x50 fp=0xc001a038f8 sp=0xc001a037f0 pc=0x3a7e850
  k8s.io/kubernetes/test/e2e/framework.LoadConfig()
  	test/e2e/framework/util.go:526 +0x38e fp=0xc001a03a90 sp=0xc001a038f8 pc=0x3a7e7ae
  k8s.io/kubernetes/test/e2e/framework.(*Framework).ExecWithOptions(0xc000eca600, {{0xc00379a460, 0x5, 0x5}, {0xc002f05670, 0xd}, {0x71accaf, 0x1}, {0xc002b84153, 0xb}, ...})
  	test/e2e/framework/exec_util.go:56 +0xda fp=0xc001a03bf0 sp=0xc001a03a90 pc=0x3a6395a
  k8s.io/kubernetes/test/e2e/network/netpol.(*kubeManager).executeRemoteCommand(0x4?, {0xc002f05670?, 0x739b527?}, {0x71accaf?, 0x6387f40?}, {0xc002b84153?, 0x0?}, {0xc00379a460, 0x5, 0x5})
  	test/e2e/network/netpol/kubemanager.go:165 +0xf8 fp=0xc001a03cc8 sp=0xc001a03bf0 pc=0x5ced598
  k8s.io/kubernetes/test/e2e/network/netpol.(*kubeManager).probeConnectivity(0xc000e90690?, 0xc0028861e0)
  	test/e2e/network/netpol/kubemanager.go:155 +0x84c fp=0xc001a03f00 sp=0xc001a03cc8 pc=0x5ced1ec
  k8s.io/kubernetes/test/e2e/network/netpol.probeWorker({0x7a6da20, 0xc000e90600}, 0xc0037277d0?, 0x32a88ca?, 0x1)
  	test/e2e/network/netpol/probe.go:111 +0x2be fp=0xc001a03fa8 sp=0xc001a03f00 pc=0x5d3a1de
  k8s.io/kubernetes/test/e2e/network/netpol.ProbePodToPodConnectivity.func1()
  	test/e2e/network/netpol/probe.go:57 +0x36 fp=0xc001a03fe0 sp=0xc001a03fa8 pc=0x5d39ef6
  runtime.goexit()

I guess the code there could be optimized a little bit?

https://github.com/onsi/ginkgo/blob/master/types/deprecation_support.go#L106

might a lock around the `d.deprecations`?

Anyway, let me try to avoid using the deprecated method, and try it again.

**Comment by chendave** [comment]
the job "pull-kubernetes-e2e-ubuntu-gce-network-policies" eventually passed, thanks @onsi for the hints.

**Comment by onsi** [comment]
aha!  that's a bug in 2.0 then, the concurrent map write was causing at least one of the nodes to exit early which triggered this issue.  having removed `CurrentTestDescription` are things passing?  Do you they pass without `--output-interceptor-mode=none`?

I'll add a lock to the depredation tracker and push out a new version soon.  But if your tests are passing now you should be good!!

**Comment by chendave** [comment]
> having removed CurrentTestDescription are things passing?

yes, remove `CurrentTestDescription` everything is good.

> Do you they pass without --output-interceptor-mode=none

as long as removed the `CurrentTestDescription`, the job will be happy.

**Comment by chendave** [comment]
I don't know what's the magic, but `--output-interceptor-mode=none` do show me lots of useful information. :)

**Comment by chendave** [comment]
thanks again!

**Comment by onsi** [comment]
alright I've added a lock to `DeprecationTracker` and updated Ginkgo's `Ginkgo timed out waiting for all parallel procs to report back` error to also encourage users to try setting `--output-interceptor-mode=none` to get additional debugging information.
