### ISSUE TITLE
Can not access slack channel

### ISSUE THREAD

**Issue by nwaizer** [onsi/ginkgo#979]
Hi,
I try to open the link provided in the Readme https://app.slack.com/client/T029RQSE6/CQQ50BBNW
This leads me to choose my workspace, but does not add the channel.
So how to get in touch with ya?
Niv

**Comment by onsi** [comment]
hey @nwaizer  - not sure what that link isn't working, but you'll want to join the [Gophers slack](https://gophers.slack.com) and then join the #ginkgo channel.

You can also feel free to open an issue.
