### ISSUE TITLE
undefine variable error in types.

### ISSUE THREAD

**Issue by ShrutiBidada-Calm** [onsi/ginkgo#985]
Error message when I try to compile source in to a single binary
```
#10 7.637 # github.com/onsi/ginkgo/v2/types
#10 7.637 /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/code_location.go:30:19: undefined: os.ReadFile
#10 7.637 /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/flags.go:125:23: undefined: io.Discard
#10 7.637 note: module requires Go 1.18
```

**Comment by onsi** [comment]
Which version of go are you using?

**Comment by ShrutiBidada-Calm** [comment]
I tried it with go 1.14, 1.16, 1.18

**Comment by onsi** [comment]
...ok.  I expect this is a go toolchain issue but I can try to help you debug it.  can you share more about your project?  are you using go modules?  what are you trying to compile and how, exactly, are you compiling it?

**Comment by ShrutiBidada-Calm** [comment]
I am trying to build a docker image. 
As a part of image building, my docker file runs a go build
`RUN go build `

The resulting error is as below:
` ERROR [5/5] RUN go build                                                                                                                                                                5.3s
------
 > [5/5] RUN go build:
#10 1.530 # github.com/onsi/ginkgo/v2/types
#10 1.530 /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/code_location.go:30:19: undefined: os.ReadFile
#10 1.530 /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/flags.go:125:23: undefined: io.Discard
#10 1.530 note: module requires Go 1.18`

**Comment by onsi** [comment]
ginkgo requires a supported version of Go.  currently that's 1.17 and 1.18
