### ISSUE TITLE
SynchronizedBeforeSuite but before all suites?

### ISSUE THREAD

**Issue by xv-ethan-v** [onsi/ginkgo#992]
Hi, 
I'm trying to use [testcontainers](https://github.com/testcontainers/testcontainers-go) to set up a database to run my specs against. I've managed to use `SynchronizedBeforeSuite` to  ensure only one instance gets created per suite, but unfortunately I can't figure out a way to reuse that instance across multiple suites. Is there something like `SynchronizedBeforeAllSuites`?

Thanks!

**Comment by onsi** [comment]
hey @xv-ethan-v 

sorry, but there's no built in mechanism for that at this time.  you can put your setup and tear down in separate suites and then orchestrate running them around your test suites manually.  but there isn't anything much more elegant than that.
