### ISSUE TITLE
multiple package with only one suite? 

### ISSUE THREAD

**Issue by lxyhust2018** [onsi/ginkgo#998]
Is this possible?

I may just be mistaken on how I should be structuring my Go, but I have a project that looks like this
module_test/
|------module_a_test.go
|------module_b_test.go
end_to_end_test/
|------scene_a_test.go
|------scene_b_test.go
test_case_suite_test.go
I'd lke to have only one suite that drives any test package.

Is this possible? I've read the docs up and down.but I have no idea about this.

**Comment by onsi** [comment]
hey - sorry for never replying.  this _is_ possible but it will look like this:

module_test/
|------module_a.go
|------module_b.go
end_to_end_test/
|------scene_a.go
|------scene_b.go
test_case_suite_test.go

Both the `module_*.go` and `scene_*.go` files would import Ginkgo and use the DSL to construct tests.  You would then `import  _  end_to_end_test` and `import _ module_test` in `test_case_suite.go` to load them into the suite.

This pattern works.  Though I generally just have two suites and use `ginkgo -r`.
